### ISSUE TITLE
Save As doesn't support all file types

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1566]
DS: 
![ds](https://s3.amazonaws.com/f.cl.ly/items/2l1H0h1h071d0S0m2U14/Image%202015-06-12%20at%207.11.15%20AM.png)

Standard:
![standard](https://s3.amazonaws.com/f.cl.ly/items/1a3j3Z3g3l1f0e1A2v2n/Image%202015-06-12%20at%207.11.48%20AM.png)

**Comment by chadrolfs** [comment]
Closing as Jenkins isolated issue
