### ISSUE TITLE
Selected layer drop targets sometimes lose border radius

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1570]
![border](https://s3.amazonaws.com/f.cl.ly/items/1E422l0q1f3X1T2v2N1B/Screen%20Recording%202015-06-12%20at%2011.18%20AM.gif)

**Comment by iwehrman** [comment]
Not addressed by #1625:
![radius](https://s3.amazonaws.com/f.cl.ly/items/3j3G2K3514341G3f3P1q/Screen%20Recording%202015-06-26%20at%2003.23%20PM.gif)

**Comment by designedbyscience** [comment]
Okay, this partially fixed in that the selected layer should lose radius for the top/bottom (matched to drop above/below), otherwise, how would you tell where the dragged later is supposed to go? However, there is a weird issue that inset causes the top border to have a slightly different color.

**Comment by iwehrman** [comment]
Given your explanation, and given that the layer and drag styling is going to change anyway, I'm just going to close this. Mission accomplished! :us: :us:
