### ISSUE TITLE
zooming with cmd-+/- is slow

### ISSUE THREAD

**Issue by joelrbrandt** [adobe-photoshop/spaces-design#1573]
There's a 500ms delay before zoom happens.

Some of this might be on core, some might be on JS.

@iwehrman wants to look at it! So does @jsbache!

**Comment by thibmaek** [comment]
Any zooming here (running on latest rMBP)

**Comment by iwehrman** [comment]
I think cmd-+/- is slow for a completely different reason than option-scroll. @jfitz-adobe and I are gonna talk about this on Wednesday!

**Comment by iwehrman** [comment]
@jfitz-adobe We're currently playing a `setPanZoom` event to implement all our zooming and centering commands, but I notice that standard PS implements zooming with different events: `zoomIn` and `zoomOut`. When I zoom out, e.g., I see 10 `scroll` events followed by 9 `zoomOut` events:
```
('scroll', {
 "offset": {
  "_obj": "paint",
  "horizontal": -0.51365933507509,
  "vertical": -0.3307906337105351
 },
 "transform": {
  "_obj": "transform",
  "tx": 7.998888888888889,
  "ty": 488.0449852507375,
  "xx": 7.998888888888889,
  "xy": 0,
  "yx": 0,
  "yy": 8.000737463126844
 }
});

(... 9 more)

('zoomOut', {
 "transform": {
  "_obj": "transform",
  "tx": 15.997777777777777,
  "ty": 488.0449852507375,
  "xx": 7.998888888888889,
  "xy": 0,
  "yx": 0,
  "yy": 8.000737463126844
 },
 "zoom": 0.2499128591642953
});

(... 8 more)
```
Unfortunately I don't seem to be able to play these `zoomIn`/`zoomOut` events from Spaces. I wonder if making that work somehow is the way forward here?

**Comment by iwehrman** [comment]
I'll take this up with @jfitz-adobe once he's back, but for now I'm kicking this bug out of S25 because it's blocked anyway.

**Comment by iwehrman** [comment]
@chadrolfs: Can you file a Watson issue for this to get it on @jfitz-adobe's radar? It's a high priority performance issue that is purely in core.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4024485

**Comment by volfied** [comment]
Is this still a problem @iwehrman @joelrbrandt ?

**Comment by iwehrman** [comment]
I no longer think this is a problem, at least compared to standard PS. (Which is all we're tracking, here.) What do you think, @placegraphichere and @davealonzo? FBNC to @placegraphichere.

**Comment by placegraphichere** [comment]
we seem to match standard now. will mark as fixed
