### ISSUE TITLE
Opening a large file (lots of layers) results in lots of registerDroppable and Dialog actions

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1574]
Open VermilionArtboards.psd and watch the console.  Here's a couple:
`Executing action dialog.registerDialog after waiting 5205ms; 8/739`
`Finished action draganddrop.registerDroppable in 50ms with RTT 6422ms; 8/13`

**Comment by designedbyscience** [comment]
1. We can avoid most of the overhead by batch registering items.
2. The impact of this is definitely increased by debug mode (registration is somewhere around 10x slower by a quick test).

**Comment by chadrolfs** [comment]
Switching between open docs becomes horribly painful and REALLY slow.

**Comment by designedbyscience** [comment]
Because you are getting hit twice (register and deregister). Working on it

**Comment by chadrolfs** [comment]
:hurtrealbad:
