### ISSUE TITLE
Dragging layers in layer panel draws layer in upper left of app window

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1577]
https://www.dropbox.com/s/1bdsp32wnz30z6p/LayersDrag.mov?dl=0

**Comment by iwehrman** [comment]
Not addressed by #1625.

**Comment by designedbyscience** [comment]
This should also be fixed by  #1673

**Comment by chadrolfs** [comment]
I can still repro.

**Comment by designedbyscience** [comment]
@chadrolfs I can't reproduce this, is there anything in particular that seems to trigger it?

**Comment by designedbyscience** [comment]
Okay, this is related to the fact that the initial positions (state.startX and state.startY) are only applied when the layer is clicked on. If you select a bunch of layers with shift, you should be able to replicate this

**Comment by chadrolfs** [comment]
Yep, you got it.  If you select more that one layer, you'll see this.

**Comment by iwehrman** [comment]
Addressed by #1700. FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
doh!  Still there.  Try these steps.  
New default doc (AB)
Select Rect tool and drag out 3 shapes (Rect 3 should be at top of AB stack and selected)
Hold down Shift and select Rect 1 (all 3 shape layers selected), then drag down

**Comment by designedbyscience** [comment]
Hmm... I don't see it when I try these steps. @iwehrman do the repro steps work for you?

**Comment by chadrolfs** [comment]
something was off with my environment, i refreshed everything and now CNR
