### ISSUE TITLE
Shapes don't snap to document edge.

### ISSUE THREAD

**Issue by CristianMoisei** [adobe-photoshop/spaces-design#1583]
In the regular version a vector shape or an element you are transforming snaps to the document edge even after having been created.

https://www.dropbox.com/s/vnwp00y0qj95x89/clip.mov?dl=0

**Comment by iwehrman** [comment]
Thanks for the report! This is a known issue that, actually, @volfied is working on right now. Assigning to him so that he can reference this in his PR and close the issue once the fix lands.
