### ISSUE TITLE
Radius for individual corners (rounded corners)

### ISSUE THREAD

**Issue by ChrisChiera** [adobe-photoshop/spaces-design#1584]
While the mode supports settings the same rounded corner to all corners it doesn't support support different values for different corners. It should either have 4 input boxes or follow standard css and support entering either one value (for all 4 corners, or values separated by commas).

**Comment by chadrolfs** [comment]
Feature request - moved to wish list

**Comment by chadrolfs** [comment]
https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist
