### ISSUE TITLE
Auto-nesting: Shapes created outside of artboards won't be nested when they are moved on to artboards

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1587]
The layers panel is not updated till a shape is moved from another artboard or new artboard is created.

Create a new artboard (Artboard 1)
Create a rectangle outside of the Artboard 1.
Move the shape on to the Artboard 1.
Notice that the Rectangle is not auto-nested in the Layers panel.
Create another rectangle on the Artboard 1.
Notice that the Rectangle is also not auto-nested in the Layers panel.

Create another artboard (Artboard 2) in the same doc.
Now the layers panel is updated and has two rectangle under the Artboard 1.

Continue:
Create a rectangle outside of the two artboards.
Move the rectangle on to Artboard 2.
Notice that the rectangle is not auto-nested in the Layers panel.
Move a rectangle from Artboard 1 to Artboard 2.
Now the layers panel is updated and has two rectangle under the Artboard 2.

**Comment by pineapplespatula** [comment]
we get move and movetoArtboard in oposite orders depending on if the shape is outside an artboard to start. Our history model doesn't support this so i'm throwing it over to cory to extend our history model

**Comment by mcilroyc** [comment]
I created a watson bug for this: 4011496  assigned to @isonno

**Comment by mcilroyc** [comment]
I believe this has been addressed both by the above referenced watson bug, and by PR #1696.
