### ISSUE TITLE
2nd swap returns incorrect location

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1589]
create two shapes, select them, swap once, swap again.

Result: 2nd swap results in incorrect locations
https://www.dropbox.com/s/rgru01p7wrp39wd/swap-fail.mov?dl=0

**Comment by chadrolfs** [comment]
happens under the following conditions: layers are inside an AB and one extends beyond AB bounds.

**Comment by volfied** [comment]
Ah, this has nothing to do with artboards. Our swap algorithm does one thing for the first situation, and another thing for the second situationa fter they're swapped, due to size differences in the layers.

I'll look into it, but we never tried to make our swap algorithm symmetric.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Swapping ABs is kinda jacked:
https://www.dropbox.com/s/mjwaf9jh00ee1pc/AB-Swap-bug.mov?dl=0

**Comment by chadrolfs** [comment]
Might be a dupe of #1532

**Comment by volfied** [comment]
I got it! We need to turn off auto expand during swap

**Comment by volfied** [comment]
@chadrolfs the core of this issue (back to back swap not being a no-op) was fixed by #1796. The AB swap issue is #1532 so I vote we close this one or hte other.
