### ISSUE TITLE
Can't select zoom tool

### ISSUE THREAD

**Issue by Lapin** [adobe-photoshop/spaces-design#1598]
When switched to design space mode, can't even select the zoom tool with 'z'. 

*Mac 10.10.2 
*smaller scaled resolution

**Comment by chadrolfs** [comment]
Currently as designed.  Use menu commands or kbsc (cmd/ctrl - +/-)

**Comment by iwehrman** [comment]
We have designs for the future which include a zoom tool, however, @Lapin: can you imagine life without a **tool** for zooming? Note that we're working on making zoom in/out a little smarter (they center on your selected layer), and we'll probably add the zoom level to the UI somewhere. Is a zoom tool a must-have for you?

**Comment by Lapin** [comment]
Hi all,

@iwehrman Yes, I just felt crippled when I couldn't zoom when I first use the design space. I was previously a print designer, and I got this habit from there, which saved my hide a lot. I don't know but most of my friends find my habit nauseous but that's how I work :) 

Also since we're talking about zooming, I love scrubby and animated zoom in PS. To be honest, I also like the Omnigraffle (or sketch) style zooming as well. (zoom tool only works while pressing z button). It'll be delicious if those both merged. (just a friendly feedback)

And yeah, without zoom tool, X-Files wouldn't existed I guess.

**Comment by iwehrman** [comment]
OK, super awesome, feedback noted! I'll talk this over with the rest of the team. If you have any other thoughts about what Design Space is or what it could be in the near future, please either file more issues or hit me at wehrman@adobe.com. Thanks again!

**Comment by Lapin** [comment]
You're welcome @iwehrman :) It felt good getting fast response from Adobe this time. I hope you guys would take the project out from beta as soon as possible. *because I'm getting sick using sketch day by day*

I will send you a separate e-mail as well!

**Comment by volfied** [comment]
Hi @Lapin, 

You can currently zoom by holding down option key and using your mouse wheel / two finger scrolling. It will zoom in/out at the mouse location.

**Comment by placegraphichere** [comment]
@Lapin there is a spring loaded zoom with artboards. What do you think of that? [https://d262ilb51hltx0.cloudfront.net/max/800/1*ElTHZhoIOLkJ06Zo_B55fQ.ogv]

Check out @bradee 's article [https://medium.com/photoshop/photoshop-has-artboards-90232c85324f]
