### ISSUE TITLE
Point Text: Do not move X and Y position of bounding box when the text alignment is changed

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1602]
I know this is a core issue, but I want to know how others think about this. Currently, changing alignment of point text shifts the text position on canvas. I think this is a bad behavior. You have to adjust the position when you change the alignment. X and Y values should not change.

![screen shot 2015-06-17 at 1 42 57 pm](https://cloud.githubusercontent.com/assets/2029597/8218436/cb2548f6-14f7-11e5-98e0-0c522f531f06.png)

![screen shot 2015-06-17 at 1 43 11 pm](https://cloud.githubusercontent.com/assets/2029597/8218439/d3824788-14f7-11e5-8e86-cc3f5d0225eb.png)

![screen shot 2015-06-17 at 1 43 24 pm](https://cloud.githubusercontent.com/assets/2029597/8218444/db0f711a-14f7-11e5-8b0d-9a60e73a8d09.png)

**Comment by chadrolfs** [comment]
@ktaki talk to Seth and figure out if this is something core wants fixed.

**Comment by ktaki** [comment]
Watson bug opened.
https://watsonexp.corp.adobe.com/#bug=4010893

**Comment by ktaki** [comment]
Seth Shaw is on this. Will assess the task to fix this in Core after the company shutdown.

**Comment by iwehrman** [comment]
Awesome! Thanks for finding and pushing on this, @ktaki!

**Comment by ktaki** [comment]
This is not likely fixed for 16.1. XD needs to spec out in details.

**Comment by ktaki** [comment]
Closing this as a pure core issue. I will keep an eye on the progress towards 17.0.
