### ISSUE TITLE
Cannot move layers under vector mask with select tool

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1605]
Group 1 has a vector mask and is inside Group 2. Ellipse 1 layer and Select Me text layer cannot be selected and moved with the super select tool.

![screen shot 2015-06-17 at 3 36 48 pm](https://cloud.githubusercontent.com/assets/2029597/8220374/f5a9f3ec-1506-11e5-95ce-ece8ae7405eb.png)

The test file is posted at:
smb://sjshare/photoshoptestfiles/TestFiles/_Photoshop_Feature_Testing/Playground-Recess/bugs/CannotSelectLayers.psb
Open CannotSelectLayers.psb and select "Group 2"

**Comment by chadrolfs** [comment]
Interesting.  It's the top level group that is preventing the selection.  If you double-click to drill down, you can then select the ellipse/text.  Might be as designed.

**Comment by ktaki** [comment]
Can you move them?

**Comment by chadrolfs** [comment]
Yes.

**Comment by chadrolfs** [comment]
here's what i'm seeing/doing; double-click to drill down then move
https://www.dropbox.com/s/04tv86tbr9w9n5a/dclick-then-move.mov?dl=0

**Comment by ktaki** [comment]
Interesting. I cannot do what you are doing in the video. Trying to move the ellipse will move the Group 2. When Artboard 1 is selected, double clicking the ellipse should not select Group 1 in the first place. Anyway, this is a bug.

**Comment by chadrolfs** [comment]
@ktaki please re-test.  I think we can close this?

**Comment by ktaki** [comment]
No, this is still an issue. You can click on it to select, but cannot drag it to move. @pineapplespatula Let us know your assessment of fixing this bug. Fixable by M3 or possibly deferring to M4?

**Comment by pineapplespatula** [comment]
This is a core issue with the hit test we are using. It returns groups to us despite there not being any visible pixels under the pointer location that is sent to the hit test. Filing a core bug

**Comment by pineapplespatula** [comment]
https://watsonexp.corp.adobe.com/#bug=4077991

**Comment by chadrolfs** [comment]
core bug deferred, moving to M4

**Comment by tomwmcrae** [comment]
Doing the following:
1. Select the ellipse layer (or the text layer) in the layers panel.
2. On the canvas, try to move the selected item.
results in the image being moved. It's as if the parts of the image that are masked out are still selectable from clicking on the canvas.

**Comment by pineapplespatula** [comment]
i may have a fix without relying on core

**Comment by tomwmcrae** [comment]
Note, Jesper has a core-side fix (if JS-side fix doesn't pan out). CL: 1049917

**Comment by ktaki** [comment]
Verified the fix. Looks good.
