### ISSUE TITLE
Selection model should special-case Artboard layers

### ISSUE THREAD

**Issue by timriot** [adobe-photoshop/spaces-design#1607]
Presently, Artboard layers are treated similarly to groups. This results in difficult, if not impossible, selection of elements on the canvas. It should not require a double-click to select an element on an artboard. Single clicks on the interior area of an artboard should fall through to the underlying elements. Artboards should be selectable on the canvas via clicking on the artboard frame only.

**Comment by volfied** [comment]
Fixed by 89d6f545a10e843082fd4a59d82d27aebef59d0b :)

**Comment by chadrolfs** [comment]
Yay!  @timriot in dah house!

**Comment by iwehrman** [comment]
First thing discussed in @chadrolfs' most recent (and first public) sprint review video: https://www.youtube.com/watch?v=B1LjoVFZrtw
