### ISSUE TITLE
Can't get the source work.

### ISSUE THREAD

**Issue by emptykid** [adobe-photoshop/spaces-design#1608]
I downloaded the source code and followed the guide to setup the development enviorment. 
But there are errors occur while loading the space.
and the buttons on the space has no response to any mouse click.
Is there anything I missed?
![snip20150618_7](https://cloud.githubusercontent.com/assets/714414/8228704/7bbff92c-15e3-11e5-8650-fac8298250db.png)

**Comment by volfied** [comment]
Hi @emptykid, our master branch is under constant development, and some of those changes are not compatible with the version of Photoshop we've shipped. Have you tried the steps listed [here](https://github.com/adobe-photoshop/spaces-design/wiki/Design-Space-Development-Setup#source-compatibility-with-photoshop-cc-2015-version-160)?

**Comment by iwehrman** [comment]
In particular, I wonder if you have checked out the right commit with `git checkout ps-16.0`. If you type `git log -1` does it say that you're on commit `01166d280b27e29160bed944d4965f458ccd6c51`?

**Comment by iwehrman** [comment]
@emptykid Please re-open this issue if the above instructions didn't solve your problem. Good luck!

**Comment by iwehrman** [comment]
@emptykid You were right! There are some missing steps in the instructions. I've updated them in the wiki, and here's a link to the diff: https://github.com/adobe-photoshop/spaces-design/wiki/Design-Space-Development-Setup/_compare/58ac0a41d0c4b551e688aa3da194150722aa1251%5E...58ac0a41d0c4b551e688aa3da194150722aa1251 
Hope that helps! Again, please feel free to re-open this issue if you're still having trouble.
