### ISSUE TITLE
Layer selection is slow

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1609]
In the mega-artboards document, selecting layers in the panel takes >300ms in debug mode on a retina MBP. On-canvas targeting takes > 450ms. Yes, some of this overhead is due to the post-condition verification, but I think we can do better. 

This is a tracking bug. At least one related issue may be #1464.

**Comment by mcilroyc** [comment]
@chadrolfs in PR #2657 @iwehrman  mentioned three bugs.  I assigned one (this one) to you.  This was a fairly major change to layer selection (esp. w/ modifiers) and needs a careful eye.

**Comment by chadrolfs** [comment]
Yeah, much better, I'm seeing between 100-200ms on retina.
