### ISSUE TITLE
Moving a layer from an artboard to another in layers panel will cause a separation of bounding box

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1614]
Create two artboards. Add a rectangle to Artboard 1. In layers panel, drag the rectangle to Artboard 2. The bounding box remains in Artboard 1 while the shape is drawn in Artboard 2.

![screen shot 2015-06-18 at 1 12 12 pm](https://cloud.githubusercontent.com/assets/2029597/8241126/58f809e2-15bc-11e5-90ce-bd29c8cdba05.png)

**Comment by chadrolfs** [comment]
regress against PR #1617 once merged.

**Comment by chadrolfs** [comment]
#1617 doesn't fix this.

**Comment by volfied** [comment]
This is related to auto-position, we can get away with calling reset bounds on layers after reorder. If you want to be fancy and optimized, layers will be placed in the same x,y location in relation to the top left of the artboard.

**Comment by pineapplespatula** [comment]
can you provide new steps for this. as it is written i dont understand the bug

**Comment by volfied** [comment]
Re-order of the layer does not update it's bounds, even though auto-position causes it to be moved. 

1 - Create two artboards
2 - Draw a rectangle in the selected artboard
3 - Select the rectangle, and keep track of the X/Y location
4 - Re-order the rectangle to the other artboard through layers panel
5 - Check the bounds again, they're not updated, This breaks our border policies for on canvas transform.

Solution is to call resetBounds on the re-ordered layers.

**Comment by chadrolfs** [comment]
Look at Ian's video in #1690 as well.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
