### ISSUE TITLE
Nudge layer does not auto-nest into Artboard

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1615]
create two AB, create one shape in AB-1, use arrow keys to nudge shape to AB-2.
Result: shape remains in AB-1 although it's coords are with AB-2 bounds

**Comment by chadrolfs** [comment]
task: figure out if we can do this with the current action descriptor.  If not, we need a core watson bug to add this feature to the action descriptor.  CC @bradee - is this what you want to happen?

**Comment by pineapplespatula** [comment]
This is not a core issue. I'm should have a fix for this soon

**Comment by pineapplespatula** [comment]
We will need to do a little work on the Ds side to listen for this call once it is happening

**Comment by pineapplespatula** [comment]
Chad can you log a watson bug?

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4010171

**Comment by pineapplespatula** [comment]
will need to verify rotate, flip and swap once the core bug is fixed

**Comment by chadrolfs** [comment]
Also need to verify transform rotation: two shapes both selected so that they have one transform controls bounding box, one shape is within an AB the other is outside.  Rotate them so that they essentially should swap being in/out of the AB.
![screen shot 2015-07-06 at 2 40 00 pm](https://cloud.githubusercontent.com/assets/8442631/8533847/9fc81856-23ec-11e5-8e6a-4b58e650074e.png)

**Comment by chadrolfs** [comment]
looks like cyan is integrating a fix for this in main today.

**Comment by chadrolfs** [comment]
Sweet, cyan fixed these cases.  Nudge and swap now work!
