### ISSUE TITLE
Swap layers do not auto-nest in Artboards

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1616]
Swap two layers, where 1st layer is in AB-1 and 2nd layer is AB-2
Result: positions are swapped but layers remain in their original ABs

**Comment by ktaki** [comment]
The same applies to Rotate and Flip. Are these operations allowed over multiple artboards?

**Comment by pineapplespatula** [comment]
this is related to issue 1615. and is dependent on the same core bug.

**Comment by pineapplespatula** [comment]
@chadrolfs : after you crate a core bug for this can you mark it here and reassign it to me?

**Comment by chadrolfs** [comment]
#1615 is essentially the same underlying root core bug.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4010171
