### ISSUE TITLE
CMD+ for numeric keyboard

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#1626]
CMD = (or plus) and CMD _ (minus) work, however for number pads, the same should be the case for CMD+ and CMD-. The + option is simply missing. We should add it.

Referenced from Scott Beaty@ahoyscottbeaty https://twitter.com/ahoyscottbeaty/status/611925737688305664

**Comment by volfied** [comment]
This is either a one character fix, or is a core issue. @shaoshing please see if the obvious solution works, if it doesn't let's open a core bug.

**Comment by volfied** [comment]
FBNC to @chadrolfs
