### ISSUE TITLE
Color picker drag jitter

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1627]
I strongly suspect that this started with @designedbyscience's recent drag-and-drop changes:
http://cloud.wehrman.org/3G1y3O442m1T

**Comment by designedbyscience** [comment]
I think this is actually do to historyStates (as I didn't touch that code, and it seems to jump as history state things appear in the console...)

@mcilroyc Could you check if that seems accurate?

**Comment by iwehrman** [comment]
Transferring @mcilroyc to this salt mine.

**Comment by mcilroyc** [comment]
![joe](https://cloud.githubusercontent.com/assets/1168110/8298543/961dfdce-192f-11e5-8d41-f612c802edb0.jpg)

**Comment by mcilroyc** [comment]
History *does* seem to be the culprit.  I turned history tracking off and the jitter goes back to the old mostly-bearable levels.  I'll look further to see what our options are...

**Comment by iwehrman** [comment]
By way of #1773, good enough for me.
