### ISSUE TITLE
Zoom keyboard shortcut should match standard PS

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1628]
It's cmd-= in Design Space and cmd-+ in standard PS. I'm not that we did this for any good reason, though it's possible it had to do with some difficulty with menu shortcuts and shift modifiers. A friendly twitter user brought this to our attention here: https://twitter.com/ahoyscottbeaty/status/611919837250482176

**Comment by volfied** [comment]
Please get in touch with Fitz to work on this issue and either add a secret keyboard shortcut for cmd+ = and display it as cmd++
Related to #1626

**Comment by volfied** [comment]
FBNC to @chadrolfs
