### ISSUE TITLE
Tooltip for Artboard in layers panel needs update

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1633]
Tooltip: Group Layer

**Comment by hamburge** [comment]
@chadrolfs @volfied Looks like this is already fixed in master? Or is it supposed to say "Artboard" instead?

![grouplayer](https://cloud.githubusercontent.com/assets/12618145/8602788/19031890-2629-11e5-9e01-27b930fae0ee.png)

**Comment by volfied** [comment]
Bug is the fact that it says Group Layer, we'd like it to say Artboard for artboards :)

**Comment by volfied** [comment]
@hamburge ^

**Comment by volfied** [comment]
FBNC over to @chadrolfs
