### ISSUE TITLE
Unable to set focus on a AB, group, or layer in layers panel

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1634]
Mostly seen on Win (surface w/mouse) although I have seen it on mac but it's really hard to repro there.
Attempting to select or put focus to a different AB or sub layer/group, in the layers panel, sometimes bounces to the right in the layers panel and doesn't select it. https://www.dropbox.com/s/y0dxywe0zwu70su/capture_Mon_Jun_22_13.30.40.mkv?dl=0

**Comment by chadrolfs** [comment]
related to #1579?

**Comment by iwehrman** [comment]
I've never seen this. Can you try to repro again with @designedbyscience's latest PR? (#1700.) FBNC (I'm optimistic) to @chadrolfs for this purpose.

**Comment by chadrolfs** [comment]
CNR on win and mac boxes.  Want to confirm on SPro before closing but I'm optimistic.
