### ISSUE TITLE
UX needs to follow Fireworks & Sketch

### ISSUE THREAD

**Issue by ylluminate** [adobe-photoshop/spaces-design#1640]
As I tried to explain during beta years ago, one of the user interface options for Photoshop desperately needs to be very closely modeled after Fireworks.  Sketch has been doing something similar in some regards and is being very successful at catering to the Fireworks refuges.

**Comment by chadrolfs** [comment]
Thanks for the feedback.  Closing this and moving it to our wish list.  
https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist
