### ISSUE TITLE
Trying to add inner shadow or changing values for drop shadow causes error

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1644]
Create a rectangle. Add a drop shadow. Set the X to 5.

Action layerEffects.setShadowX failed: Error: Photoshop returned an error when playing command number: 2 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Set” is not currently available.

![screen shot 2015-06-24 at 2 51 37 pm](https://cloud.githubusercontent.com/assets/2029597/8342406/b65664e4-1a80-11e5-85db-92964e46524e.png)

**Comment by chadrolfs** [comment]
```Action layerEffects.setShadowColor failed: Error: Photoshop returned an error when playing command number: 2 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Set” is not currently available.```

**Comment by chadrolfs** [comment]
Doesn't have to be a text layer ^^

**Comment by pineapplespatula** [comment]
I put in a fix into core for drop shadows. but inner shadows are still broken.

**Comment by iwehrman** [comment]
What is/was the problem? Is there some problem with all layer effects?

**Comment by pineapplespatula** [comment]
for drop shadows it seems that there was a problem interpreting angle vs degrees. but yes there is a problem for all layer effects

**Comment by pineapplespatula** [comment]
i'm guessing its somehow related to the performance changes that went in but i dont understand how yet.

**Comment by iwehrman** [comment]
Is there a Watson bug for this?

**Comment by pineapplespatula** [comment]
no, but fitz is looking into it

**Comment by volfied** [comment]
Got a fix in playground-dev CL 1028969

**Comment by volfied** [comment]
Jenkins #377 should have this fixed.
