### ISSUE TITLE
Editing the fill value rgb(x,x,x) does not change the color

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1645]
Create a shape. Edit the fill rgb(x,x,x). No change on canvas. No error reported in console.

**Comment by iwehrman** [comment]
@pineapplespatula Have you looked into this yet? I know we talked about something related a few days ago. I might take this off your plate if you haven't already fixed it in a branch.

**Comment by chadrolfs** [comment]
reassign to @iwehrman if still a bug.  related to or dupe of #1754

**Comment by ktaki** [comment]
This is no longer reproducible.
