### ISSUE TITLE
Instrument all external links with the Headlights API

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1648]
In particular, we failed to do this for the first-launch links to helpx, forums and Twitter.

**Comment by volfied** [comment]
@DivyaPrabhakar Can you take care of this at some point? We have example uses of Headlights scattered across the app, so please find a fitting category/subcategory/event-name for each link.

**Comment by DivyaPrabhakar** [comment]
@volfied Sure, will do

**Comment by chadrolfs** [comment]
M3 if time, if not, boot to M4

**Comment by DivyaPrabhakar** [comment]
@chadrolfs This can be M3

**Comment by iwehrman** [comment]
Fixed by #3038.
