### ISSUE TITLE
Text Transform: Type layers don't report their actual bounding boxes, unable to rotate

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#1650]
If a type layer is created by dragging a rectangle, we still only get the bounds of the text itself, but transform controls show over the entire bounding box.

**Comment by chadrolfs** [comment]
does this need a watson bug?

**Comment by volfied** [comment]
I'm fixing it.

**Comment by volfied** [comment]
CL 1028819 , will be playground-dev-mac#370.

**Comment by volfied** [comment]
Also requires #1652

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Maybe they do but there are still problems.  Here are results on Win (hiDPI) and 2nd rotation on mac fails.  https://www.dropbox.com/s/d2qhymeulqscm56/capture_Sat_Jun_27_19.02.32.mkv?dl=0

**Comment by chadrolfs** [comment]
Looks like there's a conflict with mr. quee.  repro case may include, rotate, move, then rotate again (fail).

**Comment by chadrolfs** [comment]
fixed by #1697

**Comment by chadrolfs** [comment]
better but still not totally fixed.  Still get into cases where it fails, like this:
![screen shot 2015-07-10 at 2 32 22 pm](https://cloud.githubusercontent.com/assets/8442631/8629455/6f0fb6de-2710-11e5-8bd6-54a104de9ca3.png)

**Comment by chadrolfs** [comment]
This is harder to hit now, lowering priority.  It also seems that switching to standard and back corrects this if you get in to this state.

**Comment by chadrolfs** [comment]
This has gotten worse and not isolated to just text now.  seems like subsequent attempts after initial rotation/scale now drop selection and fail.

**Comment by iwehrman** [comment]
Adding this to the S26 milestone, since this seems like something we should try to address sooner rather than later.

**Comment by volfied** [comment]
@chadrolfs now that latest fixes are in. Can you review this bug? Please make sure you're on a release build as postconditions on layers.select hampers the policy reset.

**Comment by chadrolfs** [comment]
Still fails after a few rotations.
https://www.dropbox.com/s/8c6ub6xp4tm8nfr/TextBoxRotateFail.mov?dl=0

**Comment by volfied** [comment]
This happens due to superselect installing it's policies AFTER border policies. The fix will be either merging the two policies, or figuring out why that's happening and fixing it.

**Comment by ktaki** [comment]
Since text layer scaling is now enabled, this issue also causes unable to grab the handles for scaling text vertically, i.e., the handles located at the center of the top and bottom border. Also, the handles at the four corners cannot be grabbed.

**Comment by chadrolfs** [comment]
@ktaki does it perform better with barkin's transform branch ^^ PR #1778?

**Comment by ktaki** [comment]
No, I still see the vertical calling issue. The handles are not there when clicked.

**Comment by volfied** [comment]
@ktaki can you please provide a video of the problem?

**Comment by ktaki** [comment]
Here is the video.
https://photoshop.slack.com/files/ktaki/F080A753M/texttransform.mov

**Comment by volfied** [comment]
Hmm, seems like you need to have a type layer without defined bounds (create by single clicking).

This is identical to core behavior, and I don't see any transform bugs related to Design Space.

For those reasons, I suggest this bug "fixed" and if we really want to track the non-defined area type layer transforms in Photoshop in a bug, opening a bug in Watson.

**Comment by volfied** [comment]
See how the resize area flashes big when you drag top/bottom handles? Rotation doesn't "work" after that, because that's the actual area of the type layer, which PS never reports to us.

There is nothing I can do for this issue on our side. At this point, this issue is fixed, and the non-defined area type layer sizing issue should be tracked in Watson, not blocking our transform progress.

**Comment by ktaki** [comment]
Yes, I see what is happening with the point text bounding box and transformation bounding box. The box grows vertically when you click on a handle and you miss the handle. I can open a watson bug for that. How about the box text in which you are trying to fix the issue in above PRs? I still have difficulties rotating the text box. See the video.
https://photoshop.slack.com/files/ktaki/F080BHTPE/boxtexttransform.mov

**Comment by volfied** [comment]
It's all on Photoshop side. I'm not sure why despite PS telling me it's a rotate cursor, and it's in the rotate area, it decides to resize layers. It can be part of the other bug if you like. As far as policies and Design Space's propagation of transforms to PS, I see no problems.

**Comment by ktaki** [comment]
Can you make the area where rotation icon appears wider a bit? That should prevent clicking near the border line which separates resize icon and rotate icon. I think current area is too narrow which makes user to click too close to the border and as a result, the icon become resize icon.
https://photoshop.slack.com/files/ktaki/F080D7Y3S/criticalarea.mov

**Comment by ktaki** [comment]
As for the point text, the text bounding box and transformation bounding box are different. As soon as you try to rotate or resize the text, you will see the transformation bounding box. With the text layer selected, you usually do not want to see the transformation bounding box. It is only needed when user tries to transform the text. How do you want to display the transformation bounding box?

**Comment by ktaki** [comment]
With standard Ps, as soon as user clicks one of the handles in the text bounding box, the bounding box will change to display the transformation bounding box. (Goes into text transformation mode automatically.) Then user can grab a handle. Can this be done in DS? Do we still need a Core change?

**Comment by volfied** [comment]
@ktaki Transform area/handles are completely controlled by Photoshop at this point. We only define the areas that mouse clicks go through to Photoshop. At this point, to not block the transform card, and this issue (which is about clicks not going correctly to Photoshop), I think we should close this card and tracking an issue in Watson with the PS engineer responsible for type transformation.

For your last comment: yeah, that is a PS side effect too. Only difference between PS and DS is, in DS, we apply the transform as soon as you let go of the mouse (this shouldn't change), and in PS, you stay in the transform modal state, which lets the user edit the type size with the correct handles.

We either need PS to send us correct bounds of layer to begin with, or act correctly when user clicks one of the handles.

**Comment by ktaki** [comment]
@volfied You said, "We only define the areas that mouse clicks go through to Photoshop." I ask if this could be wider for rotation. That will make the text rotation easier.

For the point text, you do not want to have the transformation bounding box when you are moving text layers around. Ps sends DS correct transformation bounding box when user clicks one of the handles. We just do not have a way to grab the new handles show up since releasing a mouse button makes the handles go away. What could be a solution here? Press option key to display transformation bounding box, maybe?

**Comment by volfied** [comment]
@ktaki, no it can not. That's being set in Photoshop. As you see, even in Photoshop, the area is smaller until you click and it goes into modal state. At that point we can't make any changes to our policy. Fix would be for PS to tell us the actual area of a point text layer to begin with, and not change it when a transform starts. Me widening the area would just cause a move to happen because the rotate area is small to start with.

I repeat, we do not get a bounding box from Photoshop during transformation. That resize handles etc. you see (which we call quadshape) is drawn and controlled by Photoshop. We just let mouse clicks go through.

There is nothing we can do on our side to get the bigger bounding box. Solution is to open a Watson bug and fix it in Photoshop.

**Comment by ktaki** [comment]
Watson bug: https://watsonexp.corp.adobe.com/#bug=4025367

**Comment by ktaki** [comment]
John F handed this bug over to Barkin.

**Comment by ktaki** [comment]
The core bug has been fixed by John Peterson.  Now text transformation reasonably works.
