### ISSUE TITLE
Test failure: setKeyboardPropagationMode

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1655]
Tests 2 and 6 of the `setKeyboardPropagationMode() get/set` in low-level-tests are failing on the latest Jenkins build (PlaygroundDev Mac 371). The failure is reliable.

**Comment by tiburbage** [comment]
The current state of low-level-test.js in git playground-adapter matches the current playground-dev Perforce state, and those tests pass in a current P4 playground-dev context. I note that the state of low-level-test.js in spaces-design on github has not been updated to the current state in playground-adapter. The other possible source of mis-match is SpacesExtension.js, relating I'm sure to jfitz' P4 CL1028094 06/22, which renamed ALPHA_PROPAGATE_WITH_ADVISE to ALPHA_PROPAGATE_WITH_NOTIFY, and low-level-test of course had to be updated for that.

Do I need to separately push low-level-test.js updates to git spaces-design? And I mean't to ask that question per SpacesExtension.js: when that changes, do I just push changes independently to spaces-design and playground-adapter, or is there a preferred way to sync them up?

**Comment by iwehrman** [comment]
The spaces-design does not hold low-level-tests, only spaces-adapter. We just file all bugs in the spaces-design repo. I'm still seeing the same two failures, as well as a failure of test 7 in the "acquire / release / isActive function" suite. Can you try reproducing from Design Space using `Help > Run Tests...`?

**Comment by iwehrman** [comment]
That's with adapter version 1.0.25, by the way.

**Comment by tiburbage** [comment]
This was a test case issue. Fixed long ago.
