### ISSUE TITLE
Enter to dive into type layers does not work

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#1659]
When we dive into layers using the keyboard, we synthesize a click event in the middle of the bounds. Now that type layer bounds are defined by the sheet reference rectangle (what the user dragged when creating layer), sending a click to the center of the layer causes a new type layer to be created instead of going into edit mode of the current layer.

This may require a core change, @pineapplespatula, did we get an API to go into type edit mode?

**Comment by iwehrman** [comment]
Fixed by #1661.

**Comment by pineapplespatula** [comment]
we do have an api. In my modaltext branch it is   UI.startEditWithCurrentModalTool(function (err))
