### ISSUE TITLE
First app focused click is treated as a double-click

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1677]
Launch DS, go to/set focus to any other app (Chrome) but have DS app window still visible.  Click on either empty canvas area or DS title bar.
Result: empty canvas single click acts like double-click resulting in open file dialog
DS title bar single click acts as double-click by maximizing app window.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4019697

**Comment by iwehrman** [comment]
FBNC to @chadrolfs as of CL 1032252 in PG-Dev-Win 398.
