### ISSUE TITLE
Double-click multi-line text fails to enter edit mode most of the time

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1679]
create multiple lines of text, select Super Select tool and double-click on Type layer to enter edit mode.

Result: depending on where you click, it fails to enter edit mode most of the time.
https://www.dropbox.com/s/t3twu1jb1cyh22z/dclick-editText.mov?dl=0

**Comment by iwehrman** [comment]
@pineapplespatula: This might be related to @volfied's rectangle keyboard policy stuff for the transform controls. But, it might not. :mag:
