### ISSUE TITLE
Repeated move of shape or layer results in drop selection, no move, or marquee

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1686]
https://www.dropbox.com/s/hcawortqk2fsp2m/move-drops-performance.mov?dl=0

**Comment by chadrolfs** [comment]
It's really bad on Windows.  I was trying to repro the snap-back bug for Seetha and ran into this.  :(

**Comment by iwehrman** [comment]
I saw this too when talking with @shaoshing. Assigning to @volfied.

**Comment by chadrolfs** [comment]
addressed by #1697
