### ISSUE TITLE
dragging an artboard to top in layers panel results in Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1687]
create new default doc, 
select Rect tool and draw a shape outside AB,
in layers panel drag AB above Rectangle 1

Result: `Uncaught TypeError: undefined is not a function`

**Comment by iwehrman** [comment]
I pushed a tiny fix on master in 940d2766bf881cdc873496003e846fb1314d28bb for this typo too. FBNC to @chadrolfs.
