### ISSUE TITLE
Auto-nested artboards move on canvas and are not selectable or draggable

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1690]
Video: http://cloud.wehrman.org/0D1M0y3z3A1l

When a layer that is outside of an artboard is dragged into the artboard from the layers panel, the layer is automatically repositioned on a canvas. Unfortunately Design Space doesn't update its bounds as a result, and so the layer can't be selected, dragged, etc.

**Comment by volfied** [comment]
Ideally: Reorder action descriptor response should indicate whether a layer's position is changed or not on reorder.

Realistically, we'll need to update bounds of the reordered layer IFF it's being moved into an artboard

**Comment by joelrbrandt** [comment]
Possible dupe of #1614

**Comment by iwehrman** [comment]
Fixed by #1790 and #1792.
