### ISSUE TITLE
Selecting another tool from Type edit mode fails to commit the text

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1691]
new doc, select Type tool, click on canvas and enter text, while still in edit mode, click on another tool (Select).

Result: text is not committed and you lose it.

**Comment by iwehrman** [comment]
Low priority, I think.

**Comment by ktaki** [comment]
This is a data loss and very annoying while testing text layer functionality. Please allow me to set it to Med Pri.

**Comment by chadrolfs** [comment]
:+1:

**Comment by ktaki** [comment]
Now addition of super sampler, this should be set to high priority. It is natural trying to set the text color in text editing mode. Even though changing a part of text color with sampler tool may not be possible in the current implementation, at least the text edited should remain.
