### ISSUE TITLE
Moving a layer in the layers panel to be inside an AB moves the position of the layer

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1693]
new default doc, 
select rect tool and draw a shape outside the AB bounds (it will be above the AB in the layers panel), 
in the layers panel drag the Rectangle 1 layer below the AB

Result: the layer position moves to be half inside the AB

**Comment by iwehrman** [comment]
Dupe of #1690?

**Comment by chadrolfs** [comment]
Maybe.  I think there are 2 bugs: 1. that the shape moves and 2. that the bounds get separated.  Resolving the 1st issue should fix the 2nd.

**Comment by volfied** [comment]
Definitely a dupe, 1. is as designed, we have Auto Position enabled in Photoshop.
