### ISSUE TITLE
Unable to drag a layer below bottom empty AB without it nesting

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1695]
new default doc, 
select rect tool and draw a shape outside the AB bounds (it will be above the AB in the layers panel), 
in the layers panel drag the Rectangle 1 layer below the AB without having it nest into the AB

Result: no matter how far down you drag, it always nests into the AB

**Comment by iwehrman** [comment]
I think this happens for any group, not just artboards. So, removing that label.

**Comment by chadrolfs** [comment]
Mostly fixed.  If you follow the steps above, it works.  If you first drag it into the AB and then try to drag it out and below, it takes several attempts before you're successful.
