### ISSUE TITLE
Use Document.elementsFromPoint for drag-and-drop hit testing once available

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1698]
Once we upgrade to at least Chromium 45, we should use the new [Document.elementsFromPoint](http://dev.w3.org/csswg/cssom-view/#dom-document-elementsfrompoint) API to implement hit testing in our drag-and-drop code. Currently we have to repeatedly call `getBoundingClientRect` on each droppable node in the zone to find the droppable node under the cursor, which is a little crazy. Instead we should call this once and walk the sequence of elements to find one that is droppable.

(Note that [Document.elementFromPoint](https://developer.mozilla.org/en-US/docs/Web/API/Document/elementFromPoint) is available in Chromium 39, but it isn't useful because the _drag target_ is always the top-most node under the cursor.)

**Comment by iwehrman** [comment]
Related to #1674.

**Comment by iwehrman** [comment]
@shaoshing: this API is available in the version of CEF that is embedded in the latest Spaces plugin that @dtristram is working on. You might want to try it out! I'm assigning this issue to you so that you can decide whether to a) use this new API, or b) not, because it's not useful, in which case you should just close this issue.

**Comment by shaoshing** [comment]
@iwehrman in the latest dnd code, we are getting the element from the mouse move event `event.target`, which works the same as `Document.elementFromPoint` but is faster as the result is already there in the event.
