### ISSUE TITLE
Fit to Window should not use "infinite canvas" artboard bounds

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1709]
1. Create a new artboard-preset document
2. Move the artboard down and to the right.
3. View > Fit to Window

Result: find the artboard!

The problem is that we're using the document bounds, but... we shouldn't be. We probably need to compute our own bounds as the union of all top-level layers, and the centering code should use those bounds instead. These virtual bounds should be a derived property of the layer structure or document model.

**Comment by shaoshing** [comment]
@iwehrman  The centering position is correct and the art board does centered. However, if you move the art board fast with the track pad, it will be still in the "moving" state after centered, and this cause the shifting problem. I confirmed standard PS has the same problem, so this is a core bug. Shall I report in watson?

![offset-centering](https://cloud.githubusercontent.com/assets/118264/9066544/3633aa24-3a8d-11e5-8d95-0e05be98102c.gif)

**Comment by volfied** [comment]
This is also fixed by #2339

**Comment by iwehrman** [comment]
Fixed either by #2339 or #1999.
