### ISSUE TITLE
Allow post condition validation to be turned off temporarily while in debug mode

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#1711]
Post condition validation is great.  It catches bugs.  But in some cases when tracking down performance issues, it would be nice to be able to selectively turn off PCV without ditching debug mode entirely.

**Comment by volfied** [comment]
I thought this was a PR and I got so excited...

**Comment by volfied** [comment]
Closing as this is now implemented, and a dev only feature.
