### ISSUE TITLE
Dragging shapes quickly back and forth, you can hit a modal dialog error: Could not use Move tool...

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1712]
![couldnotusemove-modaldialog](https://cloud.githubusercontent.com/assets/8442631/8609006/7dddf632-2655-11e5-92f6-cfa6500458ed.PNG)

**Comment by iwehrman** [comment]
@volfied: Sometimes I wonder if we should just allow all clicks to pass right through to the PS canvas with super select and abandon the parent group overlays.
