### ISSUE TITLE
No document state ought to display handy tips / tricks like the Atom editor

### ISSUE THREAD

**Issue by timriot** [adobe-photoshop/spaces-design#1714]

**Comment by timriot** [comment]
Apologies if this is a dupe.

**Comment by iwehrman** [comment]
Good idea. Another one we've kicked around is to have @hamburge's [in-progress Super Search :tm: feature](http://cloud.wehrman.org/1u1I2j241I22) up-and-at-'em in the no-doc state.

**Comment by iwehrman** [comment]
In case you don't have Atom installed:
![atom](https://s3.amazonaws.com/f.cl.ly/items/0d0K3a0Y432r2p2m1v0i/Image%202015-07-09%20at%205.21.18%20PM.png)

**Comment by timriot** [comment]
@iwehrman, while @hamburge's work is hecka cool, in the context of no-doc, the ambient tip / education approach feels more proactively helpful. Super search seems useful when one is looking for a particular something, but not so much at providing serendipitous discovery.

**Comment by iwehrman** [comment]
Indeed, an empty search bar does not obviously lead the user in a helpful direction. Point taken!

**Comment by chadrolfs** [comment]
_"serendipitous discovery"_  I miss you @timriot

**Comment by chadrolfs** [comment]
Moved to [Wishlist](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist)
