### ISSUE TITLE
Super Search should be positioned higher in the window

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1715]
Maybe at 25% or 33% instead of 50%?
![search](https://s3.amazonaws.com/f.cl.ly/items/1k0A440I2I3C3w2P0G2L/Image%202015-07-09%20at%205.36.55%20PM.png)

**Comment by placegraphichere** [comment]
30% seems about average for others

**Comment by iwehrman** [comment]
Lookin' good.
