### ISSUE TITLE
Sketch Importing/Integration

### ISSUE THREAD

**Issue by tomthorley** [adobe-photoshop/spaces-design#1717]
Hey Adobe! 

Updated my CC yesterday and started playing with design space. I am a long time Adobe user, and whilst I still subscribe to CC for work and freelance I only really use Illustrator now. Late last year I converted to sketch because the primary focus of my role is App UI design and Sketch streamlined the process for me.

Now, you know that! And thats why you've introduced Design Space (which is looking pretty awesome by the way). I think you have a really good shot at pulling back Sketch Converts who are traditional Adobe users (like me) with this new bit of kit.

I don't have any data to back this up, but I would guess Photoshop usage has declined slightly with the rise of Sketch 3.0 and I would also guess Design Space will help to reverse that!

So having said all of that: You need to build in sketch integration! I've re-designed, from the ground up, over the last several months the entire iOS & Android application for my employer. Every single screen, meticulously and lovingly hand-crafted in Sketch 3.0. I really want to get my hands dirty in Design Space, but it isn't really a viable option to re-create every screen in Photoshop again.

Build in a feature that allows me to import my Sketch 3.0 file into Photoshop and carry on seamlessly working with it in PS Design Space, and you have me back, and probably a lot more Sketch converts. 

Regards,
Tom

**Comment by chadrolfs** [comment]
Hey @tomthorley, thank you so much for your feedback and request.  Really value and appreciate it!  While this isn't technically a bug/issue, I am going to close this and move it to our [Wishlist](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist).  Follow and submit other feedback, ideas, and feature request via Twitter: @psdesign. We'll be posting our progress as we go (sprint videos) for new functionality and features we implement.  You can also join the prerelease to get access to these sprint builds (details coming via twitter).  If you run into any bugs please submit an issue like you did here.  Thanks again!
