### ISSUE TITLE
Layer Search: selecting text in field can get jumbled

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1720]
![screen shot 2015-07-10 at 2 14 34 pm](https://cloud.githubusercontent.com/assets/8442631/8629161/cb01eca8-270d-11e5-9443-ad82680fb63c.png)

**Comment by chadrolfs** [comment]
check with @iwehrman or @volfied 
we had this problem before in other UI fields and I think one of them fixed it.

**Comment by iwehrman** [comment]
Or @designedbyscience. I seem to recall that it had something to do with setting a background color on the text input versus it being transparent.
