### ISSUE TITLE
Attempting to rotate group with locked leaf has is inconsistent mac/win

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1721]
on mac, the group remains selected when you attempt to rotate
on win, the selection drops when you attempt to rotate

Not sure which is correct or if it is even crucial that the behavior be the same per both platforms.

**Comment by chadrolfs** [comment]
@designedbyscience please decide which one is correct and then assign to @volfied.  Thanks.

**Comment by designedbyscience** [comment]
Oh, the selection should be maintained

**Comment by volfied** [comment]
Behavior is identical now. @chadrolfs I think my recent transform fixes helped fix the "drop selection on attempt" so in both cases, you can't rotate a group with a locked child.
