### ISSUE TITLE
After the Duplicate command is called we get an innocuous warning from history.js

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#1722]
`history.js:267 Photoshop history status matches ours, but the documents differ. Object`

this is because we call select after the history state is set. However since our history operations ignore selection this is not an user facing issue.

**Comment by iwehrman** [comment]
It seems like there should just be no warning when the historical document is "equal enough" (e.g., equivalent modulo layer selection).

**Comment by mcilroyc** [comment]
I think this is no longer an issue.  I am going to open a separate bug for a duplicate group bug I think I found.

**Comment by mcilroyc** [comment]
FBNC to @ktaki  - this has some testing overlap with another bug #3515 that I just created.

**Comment by ktaki** [comment]
Thank @mcilroyc for looking into this and creating a separate issue. I am closing this one.
