### ISSUE TITLE
Border policies reset on every command key press

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1733]
I'm not sure if this is expected or excessive, but @volfied wants to find out. Here's the call stack:
![border](https://s3.amazonaws.com/f.cl.ly/items/0W2Y3U1W3X2d0c2W1x0s/Image%202015-07-14%20at%202.49.25%20PM.png)

**Comment by volfied** [comment]
This will be fixed in my upcoming PR #1744
