### ISSUE TITLE
Layer Search: Background layer filter does not work

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1737]
open a file containing a background layer. cmd/ctrl + f, select Background layer for filter

Result: Background (layer) does not appear in the filter list
If you select Pixel layer, it shows up there.

**Comment by hamburge** [comment]
@chadrolfs @placegraphichere Do you think the fix for this should be not offering to filter by background layers (and just have them be considered pixel layers) or to have a background layer filter that actually lists the background layers?

**Comment by chadrolfs** [comment]
I would lean towards not having a filter for background layers.  You can only have one per document anyway, users know where it is (always at the bottom) and technically it is a pixel layer.

**Comment by iwehrman** [comment]
Yes, I would say just include it among the pixel layers.
