### ISSUE TITLE
Clobbering Shadow color fails with mixed selection

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1739]
create Shape1 with a default Drop and Inner Shadow
create Shape2 with no shadows
select them both
click on the color picker for one of the shadows (mixed) and set a color

Result:
`Action layerEffects.setShadowColor failed: TypeError: Cannot read property '1' of undefined`
`Uncaught TypeError: Cannot read property 'update' of undefined`
`Uncaught TypeError: Cannot read property '1' of undefined`
`Action shortcuts.removeShortcut failed: Error: Shortcut does not exist: colorpicker-shadow-dropShadow-027`

**Comment by chadrolfs** [comment]
Here is a visual of my steps: https://www.dropbox.com/s/unx3kcaxoujdrcn/LS-Clobber.mov?dl=0

**Comment by chadrolfs** [comment]
I initially wasn't able to repro on Win but looks like a timing issue and possibly the color picker being partially covered by the layers panel.

`Action dialog.openDialog failed: TypeError: Cannot read property 'getBoundingClientRect' of null`

**Comment by chadrolfs** [comment]
when you do successfully open the color picker without error, clicking to set the shadow as red will have the target jump to black leaving both shapes with a shadow (one red and one black).

**Comment by chadrolfs** [comment]
![screen shot 2015-07-16 at 2 56 46 pm](https://cloud.githubusercontent.com/assets/8442631/8736119/b050fc98-2bca-11e5-9706-4bf56df5f475.png)
![screen shot 2015-07-16 at 2 57 20 pm](https://cloud.githubusercontent.com/assets/8442631/8736120/b05196d0-2bca-11e5-91ce-7538ae789654.png)

**Comment by shaoshing** [comment]
Thank you @chadrolfs

**Comment by shaoshing** [comment]
Hey @chadrolfs , this kind of operations is disabled in PR #1759 so the issue no long exits. :)

**Comment by chadrolfs** [comment]
I will be happy to close this once that PR gets merged.  :grinning:

**Comment by shaoshing** [comment]
PR #1759 is merged, please try again @chadrolfs
