### ISSUE TITLE
Active vector shape drawn in Standard UI gets its fill color reset to dflt gray on switch to DS

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#1749]
1 - Start PS in standard, or switch to it
2 - File > New
3 - Create a vector shape e.g. Rectangle
4 - Set the fill color in the tool panel to e.g. red
5 - Without changing the active tool, switch to DS
The fill color of the shape has changed to rgb(157, 157, 157) gray.

This is not reproducible using CC 2015 GM.

**Comment by iwehrman** [comment]
I could swear I filed this bug previously, but I can't find it. @pineapplespatula or @mcilroyc: does this sound familiar?

**Comment by mcilroyc** [comment]
def sounds familiar.  these?:
https://github.com/adobe-photoshop/spaces-design-archive/issues/1564
https://github.com/adobe-photoshop/spaces-design-archive/issues/1505

**Comment by pineapplespatula** [comment]
I'm having trouble reproing this. Chad are these steps still good in master?

**Comment by chadrolfs** [comment]
I CNR as well.  @tiburbage can you still repro this?  If not, please close.  Thanks!

**Comment by tiburbage** [comment]
I can't reproduce this anymore. It was an early problem.
