### ISSUE TITLE
Expanding groups expands before selecting resulting in UI selection jump

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1758]
https://www.dropbox.com/s/zl4fv10fuyixpmj/expandB4select.mov?dl=0

**Comment by iwehrman** [comment]
It bothers me that expanding results in changing the selection, but that's how PS does it. @designedbyscience @placegraphichere do you think we should adopt the same convention? If so, I guess we'll have to block rendering the new selection until the the expansion is complete.

**Comment by chadrolfs** [comment]
Love the fix.
