### ISSUE TITLE
Sibling hover overlay is incorrect before mousemove

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1760]
Here's a demonstration: http://cloud.wehrman.org/3K3G2K2v0w2s

To repro:

1. Create a group with two child shape layers, which mostly overlap. Select the group.
2. Double-click on top of the region of intersection of the two child layers. The top layer is correctly selected, but the overlay is for the bottom layer. This corrects itself on mousemove.

May be related to #1734.

**Comment by volfied** [comment]
It's not related to #1734, but it's a bug nonetheless

**Comment by iwehrman** [comment]
Fixed by #1765.
