### ISSUE TITLE
Double-click group on open pixel area does nothing

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#1766]
- Create a group with empty pixel area between objects. 
- Double click the group in one of those open areas. 
- Nothing happens.

Expected: I would think I would be "entering" the group if it still maintains that I am selecting that group on double click. Having no response feels off.

![double-click-empty-area-in-group](https://cloud.githubusercontent.com/assets/3229167/8780904/b151f296-2ed1-11e5-8e85-ac8677dc0ecf.gif)

**Comment by volfied** [comment]
If it enters the group, which layer do we select?

Another option is to deselect all.

**Comment by placegraphichere** [comment]
enter group, select none?

**Comment by volfied** [comment]
so leave the selection as is, which is current behavior?

**Comment by volfied** [comment]
I don't think this is a bug. We don't have a concept of "entering" a group. Being in a group means having one or more of it's children selected. Double clicking an empty area in a group should be a no-op, as user is diving into nothing.

**Comment by chadrolfs** [comment]
It should deselect all.

**Comment by placegraphichere** [comment]
agree with @chadrolfs. It should deselect. Ai and Sketch have slightly different experiences with this, but both deselect. Double click the empty area in Sketch will deselect and attempt to select what is behind the group (deselects if nothing is there). In Ai, their selection model is more accurate, and a single click will select whatever is behind (or deselect if nothing is there).

**Comment by chadrolfs** [comment]
fix for M3 if time permits and fix is low risk

**Comment by iwehrman** [comment]
The current behavior is not flagrantly broken, and I do not think this is a low-risk change, so I'm deferring to M4.

**Comment by mcilroyc** [comment]
Fixed by recent PR.  Seems like it works as was decided by the above discussion.   FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
Looks good on mac, checking win...

**Comment by chadrolfs** [comment]
:tada:
