### ISSUE TITLE
Layers highlight over the resize/rotate areas, they shouldn't.

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#1767]
Fitz is looking into this, this is here to keep track.

We still get highlights on our resize/rotate areas, and clicking them doesn't really select the highlighted layer.

We should not be getting external adapter mouse move events if the area we're on is on ALWAYS_PROPAGATE.

**Comment by volfied** [comment]
After discussing this with Fitz, I realized that mouse down policy areas should not affect mouse move events. So we're going to check for policy areas on our end to make sure our mouse moves are not over an ALWAYS_PROPAGATE area. This simplifies the API.

**Comment by iwehrman** [comment]
LGTM!

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify. Thanks!
