### ISSUE TITLE
Mixed state is inconsistent

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1776]
![screen shot 2015-07-21 at 9 39 41 am](https://cloud.githubusercontent.com/assets/8442631/8806570/20f99c24-2f8c-11e5-9d81-bfccb8d046c6.png)

**Comment by chadrolfs** [comment]
Fill mixed state is black, others are lined

**Comment by volfied** [comment]
FBNC to Chad
