### ISSUE TITLE
Initial click into field does not select all

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1780]
new doc, drag out a shape, click in color fill input field.
Result: only contents to the left of the mouse click are selected

**Comment by iwehrman** [comment]
@DivyaPrabhakar Once you get your Windows VM running, would you try to reproduce this?

**Comment by iwehrman** [comment]
CNR for me on Windows pgdev.715. Back to @chadrolfs.

**Comment by chadrolfs** [comment]
Yeah, this looks like it's no longer an issue with the updated UI

**Comment by chadrolfs** [comment]
I was actually able to repro this.  If you click in the field and slightly move your mouse at the same time, you'll get into this state.  low pri, not M3.
http://cl.ly/image/2F2w361Q0t0P

**Comment by ktaki** [comment]
@chadrolfs: I think this one can be closed. The functionality is working fine. A sight dragging causes the selection to be changed, but that is how user wants when s/he wants to select a part of string. It could be a sensitivity issue, but I do not think it's worth the effort to adjust this.

**Comment by chadrolfs** [comment]
agreed, thanks
