### ISSUE TITLE
Mousedown events are duplicated: clicks get preceded by Tooltips actions (2 clicks needed)

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1781]
ui:diableTooltips and ui:enableTooltips are executed with the first click on a group icon in the layers panel. Then, the second click does layers:setGroupExpansion. This is Windows only issue.

**Comment by iwehrman** [comment]
I can't seem to reproduce this. Note that currently groups are only expanded/collapsed when the group _icon_ is clicked. Or maybe I'm doing it wrong? Back to @ktaki for more info.

**Comment by ktaki** [comment]
With a group already selected in the layers panel, one click on the group icon executes:

> Enqueuing action ui.disableTooltips; 0/0
> fluxcontroller.js:394 
> Executing action ui.disableTooltips after waiting 0ms; 1/0
> fluxcontroller.js:404 
> Finished action ui.disableTooltips in 80ms with RTT 80ms; 1/0
> fluxcontroller.js:373 
> Enqueuing action ui.enableTooltips; 0/0
> fluxcontroller.js:394 
> Executing action ui.enableTooltips after waiting 0ms; 1/0
> fluxcontroller.js:404 
> Finished action ui.enableTooltips in 70ms with RTT 70ms; 1/0
> fluxcontroller.js:373 

Another click executes:

> Enqueuing action layers.setGroupExpansion; 0/0
> fluxcontroller.js:394 
> Executing action layers.setGroupExpansion after waiting 0ms; 1/0
> fluxcontroller.js:404 
> Finished action layers.setGroupExpansion in 115ms with RTT 115ms; 1/0

The above two sections will be repeated for each expand/collapse actions.

**Comment by iwehrman** [comment]
OK, I think I've seen it. I think the problem is that mousedown events are somehow being duplicated. It doesn't happen every time. It also doesn't seem specific the layers panel, but that's one place where two mousedowns (without a mouseup in between) causing the drag to begin but not end. Also, I keep trying to drag the entire PS window around and having that turn into a double-click-to-maximize-window operation. I think there might be something wrong in the adapter on windows with click events. @volfied or @pineapplespatula: can you please try to repro this? CC: @jfitz-adobe

**Comment by iwehrman** [comment]
May be related to #1677 and https://watsonexp.corp.adobe.com//#bug=4019697. CC @chadrolfs.

**Comment by iwehrman** [comment]
@ktaki: I now believe this is a dupe of #1677. Can you repro this without having to click in the unfocused app window? I can repro the problem every time when I do that.

**Comment by iwehrman** [comment]
Back to @ktaki to either close as a dupe or clarify. I also increased the priority and severity of the associated Watson issue.

**Comment by chadrolfs** [comment]
just ran into this on Win trying to create a shape via pen, wondering if its another result of this bug:
`Action layers.addLayers failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: 24946 Photoshop message: error: 24946 message: base element not found`

**Comment by ktaki** [comment]
Well, I am not sure if this is a dupe of 1677, but certainly it is possible. I added my comment in the watson bug report and will wait John F's investigation.

**Comment by iwehrman** [comment]
FBNC to @ktaki as of CL 1032252 in PG-Dev-Win 398. Let me know if you can still repro after @jfitz-adobe's fix.

**Comment by ktaki** [comment]
I see the issue 1677 has been fixed, but this issue 1781 is not. After click on anywhere on the panels including tool bar, subsequent click on the Ps menu bar expands the Ps window to max. Sent a message to John for further investigation.

**Comment by jfitz-adobe** [comment]
After applying CL 1032252, the "2 clicks until Group Expands" issue appears to reside in the JS code. I can see each click being delivered to JS layer from the Adapter:

     mouseClick(isMouseUp=false, mod=0x00000010)
     mouseClick(isMouseUp=true, mod=0x00000010)

But it takes yet another click to expand the group:

     mouseClick(isMouseUp=false, mod=0x00000010)
     mouseClick(isMouseUp=true, mod=0x00000010)

When I observe the HTML console under TomB's blackbox-tests.js I can see the following output:

1st click
=======
mouseClick(isMouseUp=false, mod=0x00000010)
mouseClick(isMouseUp=true, mod=0x00000010)

blackbox-tests.js:591 HTML MouseEvent: type=mousedown; which=LEFT(1); detail (cnt)=1; ctrlKey=false; shiftKey=false; altKey=false; metaKey=false; clientX=662; clientY=275; screenX=1788; screenY=699; target=[object HTMLParagraphElement]; view=[object Window]
blackbox-tests.js:591 HTML MouseEvent: type=mouseup; which=LEFT(1); detail (cnt)=1; ctrlKey=false; shiftKey=false; altKey=false; metaKey=false; clientX=662; clientY=275; screenX=1788; screenY=699; target=[object HTMLParagraphElement]; view=[object Window]
blackbox-tests.js:591 HTML MouseEvent: type=click; which=LEFT(1); detail (cnt)=1; ctrlKey=false; shiftKey=false; altKey=false; metaKey=false; clientX=662; clientY=275; screenX=1788; screenY=699; target=[object HTMLParagraphElement]; view=[object Window]

2nd click
=======
mouseClick(isMouseUp=false, mod=0x00000010)
mouseClick(isMouseUp=true, mod=0x00000010)

blackbox-tests.js:591 HTML MouseEvent: type=mousedown; which=LEFT(1); detail (cnt)=1; ctrlKey=false; shiftKey=false; altKey=false; metaKey=false; clientX=367; clientY=305; screenX=1493; screenY=729; target=[object HTMLElement]; view=[object Window]
blackbox-tests.js:591 HTML MouseEvent: type=mouseup; which=LEFT(1); detail (cnt)=1; ctrlKey=false; shiftKey=false; altKey=false; metaKey=false; clientX=367; clientY=305; screenX=1493; screenY=729; target=[object HTMLElement]; view=[object Window]
blackbox-tests.js:591 HTML MouseEvent: type=click; which=LEFT(1); detail (cnt)=1; ctrlKey=false; shiftKey=false; altKey=false; metaKey=false; clientX=367; clientY=305; screenX=1493; screenY=729; target=[object HTMLElement]; view=[object Window]

This appears to demonstrate correct behavior on the C++/adapter side.

**Comment by ktaki** [comment]
Back to Ian.

**Comment by iwehrman** [comment]
Unfortunately I can't reproduce this. @ktaki: are you still able to repro the problem you described as: 

1. Click once on the toolbar
2. Click once on the title bar, and observe window maximization?

**Comment by ktaki** [comment]
That bug, single click become double click (i.e., window maximization), was fixed. The original issue of taking double click to expand/collapse is still not fixed. Again, this is on Windows only.

**Comment by ktaki** [comment]
@chadrolfs Can you try reproduce this on your Windows machine?

**Comment by chadrolfs** [comment]
Yes, I can repro.  Open a doc with expanded layer groups, then reload DS, click on a group to collapse
``` Enqueuing action ui.disableTooltips; 0/0
fluxcontroller.js:538 Executing action ui.disableTooltips after waiting 1ms; 1/0
fluxcontroller.js:517 Enqueuing action ui.enableTooltips; 1/0
fluxcontroller.js:548 Finished action ui.disableTooltips in 94ms with RTT 95ms; 1/1
fluxcontroller.js:538 Executing action ui.enableTooltips after waiting 43ms; 1/0
fluxcontroller.js:548 Finished action ui.enableTooltips in 32ms with RTT 75ms; 1/0```

then click the group again
```fluxcontroller.js:517 Enqueuing action layers.setGroupExpansion; 0/0
fluxcontroller.js:538 Executing action layers.setGroupExpansion after waiting 0ms; 1/0
fluxcontroller.js:548 Finished action layers.setGroupExpansion in 76ms with RTT 76ms; 1/0```

**Comment by chadrolfs** [comment]
I repro'd this on mac too - where it takes 2 clicks due to blocking Tooltips actions

**Comment by chadrolfs** [comment]
bumping this to High Pri.  This is getting in the way of several things (unlocking layers, setting visibility, etc)

**Comment by iwehrman** [comment]
I can't repro this at all on Mac. On win I see something weird: clicks in the layers panel seem to trigger the `superselect.marqueeSelect` action. That makes me think something is weird with our policies. @volfied, can you repro that on your Windows machine?

**Comment by chadrolfs** [comment]
I can still repro on Windows; enable/disableTooltips is the cause

**Comment by iwehrman** [comment]
If that is the case, then this is a core issue.

**Comment by iwehrman** [comment]
Two useful facts: 

1. We only call disableTooltips after a mousedown + a mousemove (i.e., a "drag"). If clicking is causing a mousemove between the mousedown and mouseup then that's a plugin bug.
2. Tooltips should be transparent to click events. If the presence (or lackthereof?) is causing clicks to be dropped then that's a plugin bug.

I suggest filing a new Watson issue for @jfitz-adobe.

**Comment by chadrolfs** [comment]
See my comment above from Aug 10.  When click fails to select layer, that's what the console show.  When click is successful, those actions don't happen.

**Comment by volfied** [comment]
Unassigning myself since I will not be able to get to this bug before Oct, and I don't want it to rot in my pile. Up for grabs!

**Comment by iwehrman** [comment]
@chadrolfs @tiburbage: is there a new Watson bug associated with this?

**Comment by chadrolfs** [comment]
I thought there was but I can't find anything

**Comment by iwehrman** [comment]
I feel like @tiburbage knows something about this... Can you ask him about it in the standup today?

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4071529

**Comment by chadrolfs** [comment]
Comments from Jesper's checkin (builds ≥ 747 mac, 728 win):

I have marked the bug as fixed (with CL: 1047198), but notice 
Javascript is wrong. mouse down at location X followed by mouse move at location X is *not* a drag operation. Your interaction only becomes a drag when your mouse move differs from the start position. Depending on the interaction you may have a "quick drag box" (means drag immediately) or a hit/drag drag box "typically 5 by 5". The latter is used for situations where a mouse down can result in a click or a drag. The quick drag box must be at least 1x1 unit.

OS'es (especially Windows) use synthesized mouse moves for a numebr of cases.
In this case it appears that the tooltip control generates a mouse move if you delete the tooltip becore deactivation the tooltip handler. By reversing I can remove the extra mouse move (hopefully) but the current js implementation is still fragile.
Also notice that resetCursor is implemented by the adapter synthesizing a mouse move event.

Therefore (again) a drag operation must constitute of:
- mouse down in some location
- mouse move to some other location

Jesper

**Comment by chadrolfs** [comment]
I just realized that the layer panel is a target where we have either a click or a drag interaction (so we have ambiguity when we get a mouse down):
click/control-hit selects the layer
drag moves the layer

Owl uses drag boxes to distinguish between click and drag (example is panel tabs, to tabgroup wells).
- When you interact with the UI using a mouse, then our drag box is 5 by 5 units. So you have to click and move 5 units to initiate the drag
- When you interact with the UI using a stylus, then our drag box is 15 by 15 units. Anything less caused intentional drags for stylus (which are less precise)

So for the layer panel, I suggest that JS adopts drag boxes to distinguish between click and drag.

Jesper

**Comment by chadrolfs** [comment]
My fix only addresses Windows.
There is some chance that John's "don't send infinite mouse events fix" solves things on OSX, but as mentioned, javascript needs to update their drag interaction detection logic.
Jesper

**Comment by mcilroyc** [comment]
Assigning this to @chadrolfs as FBNC.  I have not personally tried this on windows, but it sounds like you did some pre-checking of it already.

**Comment by chadrolfs** [comment]
YES!!! This looks fixed to me on both Mac/Win.  Over to @ktaki to also verify and have the honor of closing!

**Comment by ktaki** [comment]
Wow, works great!!

**Comment by chadrolfs** [comment]
Miracles do happen!  Closing this made my day.  :tada: :fireworks:

**Comment by tiburbage** [comment]
Closed Watson side as well, based on testing with pgdev.774 (Mac) and pgdev.755 (Win) (playground-dev/...@1048199) and spaces-design master.
