### ISSUE TITLE
Type: unable to move via transform panel fields

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1794]
create type layer and try to change X, Y
Result: you can't

Also, since we reverted to classic transform controls, should we also allow W and H to change?

**Comment by volfied** [comment]
@iwehrman need your opinion on this, in regards to unlocking W/H for type layers

**Comment by volfied** [comment]
You can assign it to me once a decision is made.

**Comment by iwehrman** [comment]
Whoops, Github auto-closed this. FBNC to @chadrolfs.

**Comment by iwehrman** [comment]
We'll need a card for it, but yes we should unlock the W/H controls. We'll also need to fix the action descriptors for use with the "implied" font sizes.

**Comment by iwehrman** [comment]
https://trello.com/c/o5nH9ksM/527-allow-type-layer-transformations
