### ISSUE TITLE
First instance of creating a Type layer results in Typeface: missing

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1797]
https://www.dropbox.com/s/qt9vlc9vbxewgip/Font-Missing.mov?dl=0

**Comment by iwehrman** [comment]
I suspect that this is fixed by #1803.

**Comment by volfied** [comment]
@chadrolfs since #1803 is merged, can you re-confirm?

**Comment by chadrolfs** [comment]
Weeeeelllll, it still flashes for a split second.  https://www.dropbox.com/s/6a8ryol0uqszb98/Type-missing-flash.mov?dl=0

**Comment by iwehrman** [comment]
That's a different issue, I think.

**Comment by iwehrman** [comment]
It also happens exactly one time.

**Comment by mcilroyc** [comment]
the new fix is in
