### ISSUE TITLE
Expand last collapsed panel didn't work correctly 

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#1800]
Here's how to reproduce the issue:

1 double click to collapse STYLE and LAYERS panels
2 double click to expand the LAYER panel
3 STYLE panel got expanded.

Expected:

should expand LAYER panel

![layer-toggle](https://cloud.githubusercontent.com/assets/118264/8839946/d42c027e-308f-11e5-836b-8d3fe778fcdf.gif)

**Comment by chadrolfs** [comment]
With new UI, this may not be an issue anymore.

**Comment by shaoshing** [comment]
credit to @designedbyscience ! one small problem: the layers panel is not fully collapsed (you can still see the white line). 
![screen shot 2015-07-28 at 2 49 36 pm](https://cloud.githubusercontent.com/assets/118264/8944954/62bbf542-3538-11e5-97e2-87a39643d0dd.png)

**Comment by designedbyscience** [comment]
Yep, solution incoming with layer panel style updates

**Comment by chadrolfs** [comment]
How should this work with new UI and additional panels (CC Lib & Export)?

**Comment by placegraphichere** [comment]
This issue is out of date with the new UI work by @designedbyscience, closing
