### ISSUE TITLE
window stays in EDIT mode after close the last document

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#1801]
The window should immediately show recent files and templates after close the last document. 

![close-document](https://cloud.githubusercontent.com/assets/118264/8840057/1e7ae3c6-3091-11e5-9715-158f0361d7ab.gif)

**Comment by chadrolfs** [comment]
Looks similar to #1475

**Comment by shaoshing** [comment]
issue is resolved with the new UI.
