### ISSUE TITLE
Simplify layer-kind checks

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#1802]
We should add a helper function to Layer model for checking layer kind. This will avoid [redundant code](https://github.com/adobe-photoshop/spaces-design/search?utf8=%E2%9C%93&q=layerKinds) like `layer.kind !== layer.layerKinds.GROUPEND`. Instead, it may be improved by using `layer.is("GROUPEND")`

**Comment by iwehrman** [comment]
I support both of these (in principle, at least), but I suggest slicing off one the two into a separate issue since they're completely independent.

**Comment by iwehrman** [comment]
I factored out this unrelated request into #1935:

> It is unlikely to have multiple strokes and fills in the Layer model, so its `fills` and `strokes`
> properties should not be List type.

**Comment by shaoshing** [comment]
Fixed by #3273
