### ISSUE TITLE
Menu command results should use platform symbols for keyboard shortcuts

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1804]
![shortcuts](https://s3.amazonaws.com/f.cl.ly/items/2e440N4005063A0j0e2Z/Image%202015-07-23%20at%206.53.11%20AM.png)

This should use ⌘ instead of Cmd, ^ for Ctrl, etc. The correct symbols may be different on Mac and Windows.

**Comment by iwehrman** [comment]
Also, there shouldn't be a + separating the terms because then you get things like this:
![++](https://s3.amazonaws.com/f.cl.ly/items/0P0k09472Q1G1i0L3B1c/Image%202015-07-23%20at%207.09.24%20AM.png)

Instead, just follow the platform menu conventions: 
![--](https://s3.amazonaws.com/f.cl.ly/items/2h1W232Q1R1L0Q221s3k/Image%202015-07-23%20at%207.10.35%20AM.png)

**Comment by volfied** [comment]
@iwehrman please confirm the fix.

**Comment by iwehrman** [comment]
Partially addressed, but a) the shortcuts should be right-justified somehow, and b) they shouldn't be wrapped in parentheses because that makes them harder to parse. Back to @hamburge!

**Comment by iwehrman** [comment]
Actually, I guess I will relent on this and complain elsewhere about the styling. The shortcuts are indeed using the correct symbols. YOU WIN!
