### ISSUE TITLE
Baseline of proposed search completion is shifted

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1807]
![baseline](https://s3.amazonaws.com/f.cl.ly/items/2I1q0o0t2u2e41153c45/Image%202015-07-23%20at%207.12.56%20AM.png)

Notice that "Others" sits below "Hide".

**Comment by volfied** [comment]
FBNC to Ian

**Comment by iwehrman** [comment]
Sure enough.
