### ISSUE TITLE
Can't drag shape from rotation pivot

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1809]
1. Create a shape and select it.
2. Attempt to drag the shape starting from the rotation pivot (i.e., the crosshair in the center)

Result: no drag.

I believe this is a core bug. Assigning to @volfied to either file a Watson issue or fix it himself.

**Comment by chadrolfs** [comment]
Sometimes you can move the rotation anchor but then is just goes back to center.  Are we going to do anything with it or provide the same functionality/use as in standard PS?  If not, can we just hide it - may be difficult since it's part of PS transform controls.

**Comment by volfied** [comment]
CL 1032341

**Comment by iwehrman** [comment]
I guess we're just going to kill it for now.

**Comment by iwehrman** [comment]
Fixed by @volfied.
