### ISSUE TITLE
Difficult to select underlying layer when zoomed out

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1810]
rotate and scale of top layer blocks selection of underlying layer
https://www.dropbox.com/s/x0tum2qthx615tv/Selectionally-Challenged.mov?dl=0

**Comment by volfied** [comment]
This and #1767 should have a fight. Since they're exact opposites of each other :)

My plan is to only highlight when cmd key is held down, other times those areas are reserved for rotate.

**Comment by volfied** [comment]
@chadrolfs I don't think this is a bug. User shouldn't expect to select a layer underneath the resize/rotate area while zoomed out. They can always hold down cmd to highlight and then the select will actually work. #2281 addresses the highlight issue.
