### ISSUE TITLE
Always show up to ~10 results

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1816]
The total number of visible results should be ~10, and if all the valid results are from the same category then sobeit. 
![5](https://s3.amazonaws.com/f.cl.ly/items/1i030J3d2e1n3G0V1801/Image%202015-07-23%20at%202.42.43%20PM.png)

**Comment by volfied** [comment]
FBNC to Ian

**Comment by iwehrman** [comment]
Sure enough.
