### ISSUE TITLE
Unrecoverable error by dragging artboard and an empty layer in layers panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1819]
Create a new artboard doc. Select the artboard and Layer 1 (empty) at the same time in the layers panel. Drag them downward and release the mouse.

A series of errors are reported in console and finally unrecoverable error will result.

Uncaught Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Move” is not currently available.
fluxcontroller.js:396 Executing action transform.beforeStartup after waiting 1ms; 7/4

Action documents.beforeStartup failed: Error: Failed to deregister dialog: datalist-blendmodes-main-1493 does not exist.

Action documents.beforeStartup failed: TypeError: Cannot read property '_currentElement' of null

Unrecoverable error: TypeError: Cannot read property '_currentElement' of null
    at Object.ReactReconciler.unmountComponent

**Comment by ktaki** [comment]
Empty layer issue has been reported as https://github.com/adobe-photoshop/spaces-design/issues/1458.

**Comment by iwehrman** [comment]
There are two different bugs here: one that's causing the error in the first place, and one that's causing reset to fail. I introduced the latter one in #1803. CC @mcilroyc

**Comment by mcilroyc** [comment]
This has been addressed in both master AND release branches, please validate both @ktaki

**Comment by ktaki** [comment]
Verified the fix.
