### ISSUE TITLE
The first doc opened after switching to DS not centered

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1830]
Switch to DS and open a new doc. The doc is not centered in the open canvas area and often partially behind the property panel. The second doc shifts a bit, but  still not centered. The third doc on, they are centered correctly.

**Comment by iwehrman** [comment]
Possibly related to #1812 and/or #1709.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
