### ISSUE TITLE
Templates "Android 1080p" and "Microsoft Surface Pro" are invalid

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1835]
"Microsoft Surface Pro" is not available in Default New Doc Size.txt. "Android 1080p" exists in the file, but failing for some reason.

Action documents.createNew failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25923 Photoshop message: error: -25923 message: The parameters for command “Make” are not currently valid.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
Verified the fix but assigning to @ktaki since he originally reported it.

**Comment by ktaki** [comment]
Verified the fix.
