### ISSUE TITLE
Invalid new doc template will append the template names to New From Template menu

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1836]
With no doc opened, click on either "Android 1080p" or "Microsoft Surface Pro" in the TEMPLATES panel. They are currently invalid templates as reported in https://github.com/adobe-photoshop/spaces-design/issues/1835. This should fail.

Check File -> New From Template. 
RESULT: The menu contents were doubled.

**Comment by pineapplespatula** [comment]
since i fixed the two broken templates i cannot reproduce this anymore. I'm not sure if it is worth breaking in order to fix this other bug.

**Comment by ktaki** [comment]
Since current template implementation in Ps is fragile, we should fix this bug. Modifying one of the template names in Default New Doc.txt will break the template. Let me know if you cannot repro.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
