### ISSUE TITLE
Errors selecting layers in Vermilion

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1846]
Open it, zoom into Desktop Large, start selecting layers (targeting via cmd/ctrl modifier), delete a couple, select some more.

Result: errors

**Comment by chadrolfs** [comment]
![screen shot 2015-07-27 at 3 16 25 pm](https://cloud.githubusercontent.com/assets/8442631/8919360/9b1e0224-3473-11e5-9aeb-625f05488cda.png)
![screen shot 2015-07-27 at 3 22 46 pm](https://cloud.githubusercontent.com/assets/8442631/8919361/9b2ff060-3473-11e5-845f-72825d0a9aa5.png)

**Comment by volfied** [comment]
This is `_removeArtboardIDs` function in superselect.js

Maybe due to layer deletion, we're not updating our models correctly and a layer that's been deleted is still showing up in an async call?

Safest bet is to just test for layer existence.

**Comment by iwehrman** [comment]
In the PR, @volfied says:
> This, by the way, is just a band-aid. The real problem here is, our models are not up to date with
> Photoshop, which means we're forgetting a lock in the click action.
> 
> On master, the fix should be for the locks and making sure that hitTest does not return back a layer 
> ID that's not in our model.

**Comment by chadrolfs** [comment]
I just hit this (CC Lib enabled):
cmd+n
select a library
click the (+) to add the asset to the canvas, hit enter to place
click on canvas to select/move cc-linked layer
Result: `Action superselect.click failed: TypeError: Cannot read property 'isArtboard' of null`

Let me know if I should write this up separately.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
