### ISSUE TITLE
History state with modal text tool is broken

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#1848]
Step backwards is not allowed during the modal tool. and currently we have update color modify our history state, but it does not match PS behavior during the modal type tool. it only matches when we are not in the modal state.

**Comment by iwehrman** [comment]
We should disable undo/redo when in a modal tool state.

**Comment by iwehrman** [comment]
And probably a whole bunch of other commands.

**Comment by pineapplespatula** [comment]
there is a  watson bug related to this 4028040

**Comment by mcilroyc** [comment]
I'm stealing this so I can try out a fix that @jsbache recommended, and which I've initially had success with.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs, but please read the caveats described in #2270. Short version: full-blown undo/redo in the modal type state is impossible in PS. We should now be doing what standard does, which is to support a single, combined, single-step undo/redo command.
