### ISSUE TITLE
To reduce mouse travel, always show panel well or add option to pin

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1853]
![screen shot 2015-07-28 at 2 44 19 pm](https://cloud.githubusercontent.com/assets/8442631/8944684/d8966d12-3536-11e5-8d4c-e33e7c609bb0.png)

It's easier to toggle/expand/collapse panel visibility if the well is always there and also more discoverable than the triangles

**Comment by designedbyscience** [comment]
I think we're gonna have it here all the time

**Comment by placegraphichere** [comment]
I think we're gonna do this for other reasons, but yes, agreed

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
