### ISSUE TITLE
Modal text navigation executes a set of flux actions

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#1857]
There are a variety of user actions that, while in a modal text edit state, cause a set of flux actions (~6) to be (seemingly) needlessly executed.  Examples: Navigating with mouse, arrow keys, or backspace.

http://cl.ly/240D3v3e2T1s

**Comment by pineapplespatula** [comment]
We do need some actions in order to update our text model depending on the state of the modal tool, we can reduce the 6 actions to 1, but that is a design choice that i don think is too important.

**Comment by DivyaPrabhakar** [comment]
giving to Divya to refactor

**Comment by iwehrman** [comment]
@mcilroyc One throttled action is now executed every time the cursor/selection context changes. Without significantly changing the architecture of modal type, this is the best we can do.
