### ISSUE TITLE
Using the color text input while in modal text edit state, can't get back to edit text

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#1858]
- create a text layer (or enter an existing text layer, in edit mode)
- type some characters
- click in to the color text input box, type "red" to change the color to red
- try to continue editing the text layer... it doesn't seem possible

**Comment by pineapplespatula** [comment]
hit enter again to blur the input.

**Comment by pineapplespatula** [comment]
i dont think this is a bug, unless we want to revisit how we commit and blur inputs

**Comment by mcilroyc** [comment]
fwiw, (since I created this bug), I see that hitting enter twice does what I need it to do.  I think it is clunky, but at least it works... so I retract my assertion that it is "impossible".  I'll defer to the experts about how to proceed.

**Comment by pineapplespatula** [comment]
@placegraphichere care to comment?

**Comment by iwehrman** [comment]
Clicking in the canvas should blur to the HTML input. We probably need some core support for this. Over to @pineapplespatula to file the appropriate Watson bug.

**Comment by pineapplespatula** [comment]
created watson bug 4034882

**Comment by iwehrman** [comment]
@jfitz-adobe is going to blur the CEF window automagically when clicking back in the PS canvas.

**Comment by chadrolfs** [comment]
Seems to work as expected on Mac.  Windows is terribly broken #2252
