### ISSUE TITLE
CC Lib: importing asset does not update layers panel

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1859]
new doc, load a library and add an asset to canvas by clicking on (+), hit Enter to place

Result: layers panel is not updated 
Expect: layer panel to update reflecting newly added asset (and it should be focused/selected)

If you attempt to move the artboard, you get 
`Action layers.getLayerOrder failed: Error: Too many layers in layer index`

**Comment by shaoshing** [comment]
The + button is working but it is placing at the top left corner. I can make it to place at the center of the view port, but I am wondering with the drag-n-drop, do we really need the click-n-add function? It is not as natural as drag-n-drop, and is not more efficient either (you can not batch add given that you have to quit the transform mode first). @volfied @chadrolfs  what do you think?

**Comment by volfied** [comment]
Let's definitely get @davealonzo's input, but as far as the designs show, there is no click to apply for Graphic assets, it should be drag&drop.

**Comment by chadrolfs** [comment]
Agreed with @volfied that we can probably do away with the (+) and just do drag&drop but the final call is @davealonzo's

**Comment by shaoshing** [comment]
With the implementation of drag and drop graphic asset, I believe we can safely close this one. Any further discussion on whether to support mouse click event will be in a separate issue.
