### ISSUE TITLE
CC Lib: adding a vector smart object imports into library incorrectly

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1860]
open a file that has an embedded vector smart object layer (basically an illustrator file) and select it
click the Add Graphic icon at the bottom of the Lib panel

Result: layer is added to library but it has no icon.  Switching to standard PS reveals that it was created as PS instead of AI.

Attempting to add it to a doc in DS results in:
`Action libraries.createLayerFromElement failed: Error: unknown exception type
    at eval (eval at undefined, <anonymous>:1:5)
    at eval (native)`

**Comment by chadrolfs** [comment]
![screen shot 2015-07-29 at 11 49 40 am](https://cloud.githubusercontent.com/assets/8442631/8966691/8d0d7e74-35e7-11e5-907f-e90d8c7e4b83.png)

**Comment by shaoshing** [comment]
@volfied could you check this out?

**Comment by volfied** [comment]
We no longer see the error, but I will fix the Ai/PS source issue.

**Comment by chadrolfs** [comment]
@volfied @shaoshing Here's the error I get now:
``` Action libraries.createElementFromSelectedLayer failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -1715 Photoshop message: error: -1715 message: Could not create a library graphic because of a program error.
    at eval (eval at undefined, <anonymous>:1:5)
    at eval (native)
From previous event:
    at Descriptor.batchPlay (file:///Users/crolfs/Documents/git-repos/spaces-design/bower_components/spaces-adapter/src/ps/descriptor.js:373:14)
    at Descriptor.batchPlayObjects (file:///Users/crolfs/Documents/git-repos/spaces-design/bower_components/spaces-adapter/src/ps/descriptor.js:418:21)
    at Descriptor.playObject (file:///Users/crolfs/Documents/git-repos/spaces-design/bower_components/spaces-adapter/src/ps/descriptor.js:352:21)
    at Object.<anonymous> (file:///Users/crolfs/Documents/git-repos/spaces-design/src/js/actions/libraries.js:156:35)```

**Comment by chadrolfs** [comment]
hmmm, CNR now - PS may have been in a bad state after a previous crash.

**Comment by chadrolfs** [comment]
Looks like it may be the first time you attempt to add it that you get that error.  Just repro'd again.

**Comment by shaoshing** [comment]
@chadrolfs , I am unable to reproduce this `Result: layer is added to library but it has no icon. Switching to standard PS reveals that it was created as PS instead of AI`.  Could you check again and post your steps if you still see it (it would be even better if you can share me your file that `has an embedded vector smart object layer`). Thank you

**Comment by chadrolfs** [comment]
I can still repro.  let me know if you need a file.  Here are my steps:
cmd + n
file > place embedded... (choose an illustrator file .ai) 
press Enter to place - note it places it on top of but not nested in AB
make sure that layer has focus in the layers panel and press the Add Graphic icon at the bottom of the Libraries panel.  

That should give you the error above and no asset will be added to the library.

**Comment by shaoshing** [comment]
Hi @chadrolfs , I fixed a bug that is potentially related to your issue. Could you test again and let me know if the issue still exists? Thank you.

**Comment by chadrolfs** [comment]
Yeah, looks fixed to me.  CNR on both mac/win.  Thanks!
