### ISSUE TITLE
CC Lib: loading a library after creating a Type layer result in errors

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1863]
new doc
select Type tool and create a type layer (hit numpad Enter or Esc to commit)
Libraries drop down initially has no library loaded, click to expand list and load a library 
(I loaded one that contains a single layer style effect: inner and drop shadow)

Result: `Uncaught TypeError: Cannot read property 'first' of undefined`
`Action libraries.selectLibrary failed: TypeError: Cannot read property 'first' of undefined`

**Comment by shaoshing** [comment]
This is related to the change of text#characterStyles to text#characterStyle (introduced from merge e42705db5185780f4a051cb9833a098e8a69606a) Fix is on the way.
