### ISSUE TITLE
Type: Empty text layer is created

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1875]
Select type tool. Click on canvas. Hit Esc. 
RESULT: Empty text layer is created.
EXPECTED: No text layer is created regardless of Esc key setting (commit or cancel).

**Comment by ktaki** [comment]
Subsequent click on the empty text layer will result in error:
 Action layers.select failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Select” is not currently available.

**Comment by chadrolfs** [comment]
or if you attempt to delete it:
```Action layers.deleteSelected failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Delete” is not currently available.```

**Comment by chadrolfs** [comment]
if you reset design space, the empty layer is then gone.

Type tool, click on canvas, ESC to commit, Help > Reset Design Space
Result: no empty text layer

**Comment by ktaki** [comment]
Yes. This is because no empty text layer can be created in standard Ps. In DS, it looks like an empty layer was created, but actually not.

**Comment by pineapplespatula** [comment]
I'll need to talk to @isonno  about this one

**Comment by iwehrman** [comment]
A Watson issue is needed for this.

**Comment by iwehrman** [comment]
With @pineapplespatula's recent `deletedTextLayer` event, this is now FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
