### ISSUE TITLE
Focus is lost when tabbing out of a datalist

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1877]
select a text layer, enter X (transform field), tab (repeat)
or set focus in Letter and Shift + tab (repeat)

Result: focus drops after blend mode or Weight if you are reverse tabbing

(also happens in edit mode)

**Comment by pineapplespatula** [comment]
this may be a good candidate for @DivyaPrabhakar,

**Comment by iwehrman** [comment]
This has nothing to do with type. I suspect that one of @hamburge's PRs broke this. @chadrolfs: if you have time, can you `git bisect` this failure?

**Comment by chadrolfs** [comment]
92856812c5c0b72c2294ac29e7f228164466b35e is the first bad commit
commit 92856812c5c0b72c2294ac29e7f228164466b35e
Author: Jeffrey Cohen <jecohen@adobe.com>
Date:   Tue May 12 11:04:27 2015 -0700

    Allow text tool to work in modal state

**Comment by pineapplespatula** [comment]
it looks like its related to my addition or _releaseFocus which it seems too heavy handedly gives keyboard focus back to PS so that we can be back in the modal editing state. We may need to work with @jfitz-adobe  on this one to figure out what to do about keyboard focus, or is there a way we can only call this when we exit via enter and not via tab ?

**Comment by pineapplespatula** [comment]
or @iwehrman is there a way we can only call this when we exit via enter and not via tab ?

**Comment by volfied** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
Not fixed.  Gets stuck on Typeface.

**Comment by iwehrman** [comment]
You have to hit tab twice currently; the second time opens the select menu.

**Comment by chadrolfs** [comment]
That wasn't what I was seeing in previous build but with current sources, this looks fixed so closing this.
