### ISSUE TITLE
Type: Initial type settings shown as "mixed" when creating new text layer

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1880]
Instead of saying "mixed" for all the type settings, show current font settings that are either default or inherited from the previous creation of a text layer.

**Comment by chadrolfs** [comment]
what's interesting is if you click, type and then delete one char, then typeface and settings populate correctly.

**Comment by pineapplespatula** [comment]
@this needs some more communication with core, I'll chat with @isonno about some of our type issues.

**Comment by iwehrman** [comment]
The problem seems to be that the text descriptor simply has the wrong information in it right after creating the text layer.

**Comment by iwehrman** [comment]
https://watsonexp.corp.adobe.com/#bug=4038142

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Now the font name is not "mixed" but it always stay with default font and attributes, "Myriad Pro", "Regular", black, rgb(0,0,0), Size 16, etc., regardless of previous setting used to create a text layer.

**Comment by iwehrman** [comment]
I spent some time understanding this yesterday. It's a race condition that starts with the fact that even after we get a valid `updatedTextProperties` event with the correctly color, the `textKey` property of the layer descriptor has invalid style information. I have a workaround in mind though...

**Comment by volfied** [comment]
Over to @ktaki to verify.

**Comment by ktaki** [comment]
Verified the fix.
