### ISSUE TITLE
Text Edit: color picker does not update to reflect color of selected text

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1881]
select some characters of a text layer, open color picker and select a red, select some other characters that are black

Result: color picker remains unchanged (red)

**Comment by pineapplespatula** [comment]
this might be a good one for @DivyaPrabhakar

**Comment by iwehrman** [comment]
https://watsonexp.corp.adobe.com/#bug=4038142

**Comment by chadrolfs** [comment]
As soon as I try to initially set the text color, it blows up on me:
`Action type.setColor failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Select” is not currently available.`

new doc
hit T for type tool
click on canvas and start typing creating mulitple lines (type, enter, type, enter)
hit Esc to commit the text
hit V for select tool
double-click on type and select one line
click on the Type Color picker and set it to a red
BOOM

**Comment by iwehrman** [comment]
This is the recent change which is causing this bug:
https://github.com/adobe-photoshop/spaces-design/commit/4ae20a279e2416926bc9cd9cdafc39b767a05795#diff-66fb006bb46f8f716c009f317aded016R268

**Comment by iwehrman** [comment]
@volfied @shaoshing @mcilroyc: Let us discuss this in ye olde parking lot tomorrow morning.

**Comment by mcilroyc** [comment]
FBNC @chadrolfs
