### ISSUE TITLE
Text Edit: Alignment changes does not work in text edit mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1882]
Click Align icons in text editing mode. No changes shown on canvas.

**Comment by pineapplespatula** [comment]
The modification that allows us to handle modal commands doesn't seem to support paragraph styles. 
@chadrolfs  would you be able to log a watson bug about it?

**Comment by chadrolfs** [comment]
@ktaki originally logged this so I'll let him do the honors.

**Comment by ktaki** [comment]
Here it is. https://watsonexp.corp.adobe.com//#bug=4032644

**Comment by iwehrman** [comment]
@pineapplespatula There's a typo in the `alignAssigned` event property name:
![image](https://cloud.githubusercontent.com/assets/1075154/9296258/423dae46-443d-11e5-8515-d009dd9dedab.png)

Also 1) what is the point of these `Assigned` property names? I can't figure out how to get in a state in which they are meaningful. 

Also 2) why can't the event just _omit_ the relevant property names if they aren't specified in the event?

In any case, some JS-side change relevant to this are FIP by me, but we should still talk about potential changes to the event interface.

**Comment by pineapplespatula** [comment]
they were a cross over from the way that PS represents its character style model, but you are right that it makes more sense in a javascript world to just omit them from the descriptor. I'll look into making the core changes needed for that.

**Comment by iwehrman** [comment]
Can you give instructions for how to reproduce an event with, say, `sizeAssigned === false`?

**Comment by pineapplespatula** [comment]
not anymore, because i took out assigned keys in the descriptors. 
but you would have done it by making a text layer with two characters, changing on the of the characters sizes and then selecting both characters

**Comment by iwehrman** [comment]
So now it just omits `size`?

**Comment by pineapplespatula** [comment]
yes

**Comment by iwehrman** [comment]
As of CL 1038558, the alignment commands seem to work, although the changes don't take effect on the canvas until after the modal state is committed. @jsbache to address!

**Comment by mcilroyc** [comment]
The latest PR 2276 should address this issue.  FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
