### ISSUE TITLE
Text Edit: Align icons should be highlighted to indicate current setting

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1883]

**Comment by DivyaPrabhakar** [comment]
@pineapplespatula said that this might be a good bug to get lost in for a while

**Comment by ktaki** [comment]
Do we have a label "get lost"? It surely will become very popular. :-)

**Comment by placegraphichere** [comment]
#2d86de is the color you're looking for a highlight state

**Comment by ktaki** [comment]
Verified the fix.
