### ISSUE TITLE
Text Edit: Glyph size in Set Text Color square is too small

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1884]
Currently the character in the Set Text Color resizes depending on the font size setting. Is this necessary? It often is too small for the size of the square. Could it be fixed size about 40 pt?

**Comment by chadrolfs** [comment]
@designedbyscience not sure if this is you or @placegraphichere

**Comment by designedbyscience** [comment]
This will be changed by the new panel design I believe

**Comment by chadrolfs** [comment]
Looks like this is fixed now.

**Comment by ktaki** [comment]
Yes, with UI refinement, the issue has been resolved.
