### ISSUE TITLE
Opacity field in style panel is truncated if "mixed"

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1885]
![screen shot 2015-07-31 at 11 14 14 am](https://cloud.githubusercontent.com/assets/2029597/9014204/b92e25a0-3775-11e5-8706-0eaa2fec0a52.png)

**Comment by designedbyscience** [comment]
Also, fixed in my Mixed states PR

**Comment by ktaki** [comment]
Verified the fix.
