### ISSUE TITLE
Can't search unless a document is open

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1888]
I want to use the search bar to open recent files!

**Comment by placegraphichere** [comment]
When there are no open docs, I might suggest the default view once you click into the app search would be recent files, instead of filters. Auto fill for filters would still work of course

**Comment by iwehrman** [comment]
Fixed by #1900.

**Comment by chadrolfs** [comment]
can't search in zero doc state

**Comment by volfied** [comment]
@chadrolfs please confirm the fix.
