### ISSUE TITLE
Recalculate tab size on panel expand/collapse

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#1890]
In case we need to go from small/large tabs

**Comment by chadrolfs** [comment]
@designedbyscience did #1904 address this or is this still an open issue that needs to be fixed for M3?

**Comment by designedbyscience** [comment]
@shaoshing is fixing this one, open PR #2883 for it that I am reviewing

**Comment by designedbyscience** [comment]
Fixed by #2883
