### ISSUE TITLE
transform.flip, align and distribute should have an underscore prefix

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1895]
... because they're private. They should also be moved to the top of the file for consistency and readability.

**Comment by iwehrman** [comment]
Also, `transform.flip`. CC @mcilroyc.

**Comment by volfied** [comment]
#1921 will fix this.

**Comment by iwehrman** [comment]
@DivyaPrabhakar will finish painting the back of this fence.

**Comment by iwehrman** [comment]
Also `transform.nudgeLayers`.

**Comment by pineapplespatula** [comment]
@iwehrman  you wrote it, so you get to close it. 
congrats

**Comment by iwehrman** [comment]
Challenge accepted.
