### ISSUE TITLE
After touch gesture, standard PS context menus and behaviors are available

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1902]
(on a Surface) draw out some shapes (rect tool)
invoke a gesture (2 finger swipe or 3 finger drag for history)
single click or right click with Rect tool 

Results: pops up the create a new rect dialog with dimensions and right click reveals full context menu with things like extrude to 3D

**Comment by chadrolfs** [comment]
https://www.dropbox.com/s/30eo5r98i88nw53/Rect-on-Surface-rightclick.png?dl=0
https://www.dropbox.com/s/8zzpvpk2tljrixo/Rect-on-Surface-singleclick.png?dl=0

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4037340

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4037340 closed/fixed
playground/...@1042114 (09/12)
