### ISSUE TITLE
Clicking on an artboard dirties the document

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#1903]
1) open any psd file
2) click on the art board
3) file tab shows changed state

![unsaved-status](https://cloud.githubusercontent.com/assets/118264/9066720/0fd60d1c-3a8e-11e5-9d84-4ecfeddf9c12.gif)

**Comment by iwehrman** [comment]
@DivyaPrabhakar this might be another good one to investigate. The fix may or may not be obvious.

**Comment by iwehrman** [comment]
This seems to be a core bug. [Watson 4071097](https://watsonexp.corp.adobe.com/#bug=4071097).

**Comment by mcilroyc** [comment]
FBNC.  asking @chadrolfs to take a look.  The PR was non-trivial, so we'd be interested to find cases where an actual "dirtying" user action was not reported as such (but showing the doc as dirty).

**Comment by chadrolfs** [comment]
related watson bug is closed/fixed

**Comment by chadrolfs** [comment]
related to #2959 but this is fixed, closing.
