### ISSUE TITLE
Search: Unable to Paste after Cut

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1907]
ctrl + f to bring up Search
click in field and enter some text, "design"
select the text and hit ctrl + x to cut
hit ctrl + v to paste

Result: nothing pasted

**Comment by volfied** [comment]
Passing to @iwehrman as he graciously accepted my plea for help.

During edit.cut, `window.document.activeElement` is `<body>`, and it seems like we're not using our own code at all... Cut "deletes" the highlighted text before my debugger hits edit.cut action.

Thanks Ian!

**Comment by volfied** [comment]
I can't repro this anymore, altho we get the double paste (#1906)
