### ISSUE TITLE
CC Lib: Library should sticky. Open or new doc results in no library loaded.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1909]
Once the app is open and a library is loaded it should remain sticky if you open or create new docs.  This is how standard PS behaves

**Comment by shaoshing** [comment]
It is implemented in the new UI, so I will close this one for now.

**Comment by chadrolfs** [comment]
I'll verify

**Comment by chadrolfs** [comment]
This is not fixed.  It defaults to the first library.  Whatever library I load, it should remain on that library until I change it.  If I load the 3rd library down in my list and create a new doc, it goes to the 1st library in the list.

**Comment by chadrolfs** [comment]
Sorry if I wasn't clear about this.  What should happen here is the same behavior as standard PS.  The libraries shouldn't be sticky per document but sticky as in whatever library you have loaded, it should remain on that library across the whole session and re-launch.  Make sense?  It should never change unless the user changes it.

**Comment by chadrolfs** [comment]
doh, sorry I was one `git pull` behind

**Comment by shaoshing** [comment]
Thanks for verifying.
