### ISSUE TITLE
Crash starting Ps in DS mode with Spectrum build

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1916]
Tested with Jenkins main build (cl#1034440) on Mac.
Switching to DS works fine. However, starting with DS mode will crash Ps.

Start Ps with preferences cleared.
Switch to DS.
Quit Ps.
Start Ps.

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000

VM Regions Near 0:
--> 
    __TEXT                 0000000109e6c000-000000010f62f000 [ 87.8M] r-x/rwx SM=COW  /Users/USER/*/Adobe Photoshop CC 2015.app/Contents/MacOS/Adobe Photoshop CC 2015

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   com.adobe.Photoshop           	0x000000010ac73960 UStyles::BrightnessChanged() + 48
1   com.adobe.Photoshop           	0x000000010a83930d ForEachModule(boost::function<void (CModule*)> const&) + 333
2   com.adobe.Photoshop           	0x000000010a83a511 NotifyModulesOfBrightnessChange() + 33
3   com.adobe.Photoshop           	0x000000010a9da051 TPreferences::SetBrightnessLevel(PanelBrightness, bool) + 97
4   com.adobe.Photoshop           	0x000000010bdc569f ExternalUI::ShowHide(bool) + 1103
5   com.adobe.Photoshop           	0x000000010bdc51dc ExternalUI::Initialize() + 124
6   com.adobe.Photoshop           	0x000000010a837ded InitModules() + 765
7   com.adobe.Photoshop           	0x000000010a91e060 TPhotoshopApplication::IPhotoshopApplication() + 64
8   com.adobe.Photoshop           	0x000000010a1f9fd5 psmain(int, char**) + 645
9   com.adobe.Photoshop           	0x000000010a1fa649 main + 9
10  libdyld.dylib                 	0x00007fff841595c9 start + 1

**Comment by ktaki** [comment]
Also crashes on Windows. No crash with the builds before the Spectrum integration.

**Comment by ktaki** [comment]
John F is looking into it.

**Comment by chadrolfs** [comment]
@ktaki is there a watson issue logged for this or are we just tracking it here?

**Comment by ktaki** [comment]
Here it is.
https://watsonexp.corp.adobe.com/#bug=4032088
Just reproduced this issue with John F. He will fix this shortly.
