### ISSUE TITLE
Help > Reset DS defaults to Type tool and then errors selecting another tool

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1923]
```Action tools.select failed: TypeError: Cannot read property 'layers' of null
    at Object.deselectHandler (file:///Users/crolfs/playground-repos/spaces-design/src/js/tools/type.js:147:41)
    at Object.<anonymous> (file:///Users/crolfs/playground-repos/spaces-design/src/js/actions/tools.js:184:52)```

**Comment by volfied** [comment]
Also, can you please explain here why type tool deselect handler is calling reset layers? Tool switch is a common thing and we shouldn't be blocking with expensive operations.

**Comment by pineapplespatula** [comment]
On exiting the type tool, if the current character style has been changed to match a selection made in the modal state, we need to reset it to the baseline character style from PS.

**Comment by volfied** [comment]
Aren't all the other listeners you have handling that case?

**Comment by pineapplespatula** [comment]
no
