### ISSUE TITLE
Layers created outside Artboard nest incorrectly when dragged in/out of AB on canvas

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1937]
new doc
create a new Rect or Type layer outside AB bounds
switch to Select and drag layer into AB, then out
compare canvas to layers panel

Result: Layer is visible outside AB bounds but is still represented as inside AB in layers panel

**Comment by chadrolfs** [comment]
This also happens when you drag CC Lib assets into/out of ABs

**Comment by iwehrman** [comment]
May only happen with point text layers?

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4034965

**Comment by volfied** [comment]
Please re-test with the latest Jenkins build (mac #646)
