### ISSUE TITLE
Show/Hide Guides has wrong shortcut, conflicts with Group (cmd/ctrl + g)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1938]

**Comment by iwehrman** [comment]
What should the correct shortcuts be? CC @placegraphichere @designedbyscience

**Comment by chadrolfs** [comment]
it was cmd/ctrl + ;
why did it change?

**Comment by iwehrman** [comment]
It's possible that I screwed it up in #1926.

**Comment by chadrolfs** [comment]
6a20b769818918de6976525279c024088434a204 is the first bad commit
commit 6a20b769818918de6976525279c024088434a204
Author: Ian Wehrman <wehrman@adobe.com>
Date:   Wed Aug 5 14:40:08 2015 -0700

    Localize menu and global keyboard shortcuts. Also factor out menu strings into their own file.

**Comment by iwehrman** [comment]
I changed my mind. @DivyaPrabhakar should fix this.

**Comment by DivyaPrabhakar** [comment]
https://github.com/adobe-photoshop/spaces-design/pull/2109
