### ISSUE TITLE
LESS Variable Refactoring

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#1946]
Right now, we use `@warm-black` and such throughout the code rather than a variable named for the context (such as `@label-primary-color` in my new layers work). We should be replace non-context variables outside of colors.less.

**Comment by iwehrman** [comment]
I believe that @placegraphichere has done this with his theming work, and it's amazing. If I'm missing something, please re-open!

**Comment by placegraphichere** [comment]
@designedbyscience is right, we should leave this open. It should be more of a non-context name. So it will not be theme specific. I think I missed this one in the work I did.

**Comment by iwehrman** [comment]
master is open for pull requests!

**Comment by placegraphichere** [comment]
I should add, we need this applied to `@warm-grey`. That's the one I missed.

**Comment by iwehrman** [comment]
Fixed by #3171.
