### ISSUE TITLE
Multiple history states are recorded for pasting a style

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1947]
Undo reveals middle states that show inconsistency between actual canvas drawing and the state of the style panel. Either removing this inconsistency (i.e., update the style panel when Undo'ed) or record just one history state so that one undo takes care of going back to the original state.

New copy/paste style commands are great!

**Comment by volfied** [comment]
Thanks for tracking this, @iwehrman and I have some crazy ideas to implement to fix it, which is lower priority currently than the Sampler HUD feature. I will get to fixing this after the HUD is complete.

**Comment by volfied** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Undo is successful, but subsequent apply of a style causes error.

Create a shape layer
Apply a style, say, a drop shadow from  the libraries panel
Undo
Apply the same style again from the libraries panel

![screen shot 2015-08-27 at 2 41 07 pm](https://cloud.githubusercontent.com/assets/2029597/9533878/bcb1a1e8-4cc9-11e5-866e-5ff6e85efade.png)

**Comment by volfied** [comment]
libraries.applyLayerStyle does not create any history state in our world, so undo removes the layer from our model. Looking into it.

**Comment by volfied** [comment]
@ktaki Now i'm extremely confused by this bug. Is this a libraries style apply bug, or paste layer style?

Can you please open new bugs for new issues instead of recycling old issues? If the paste layer style issue, which this bug title and description states is fixed, then it should be closed.

**Comment by ktaki** [comment]
Oops. Sorry.

**Comment by ktaki** [comment]
Verified the fix.
