### ISSUE TITLE
Unable to reset canvas after 2-finger rotate canvas

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1952]
https://www.dropbox.com/s/gxenftbunjkyzr8/Surface-Rotate.mkv?dl=0

workaround: switch to standard PS and hit Esc

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4037331

**Comment by tiburbage** [comment]
Not sure if it wasn't working at the time, but a double tap will reset the transformation (reset rotation, do a zoom to fit). This is working. However, note we have some bad stuff going on in DS after using touch gesture transformations, logged a couple of Watson bugs in this area...
