### ISSUE TITLE
Clean up Toggle Overlay dispatches

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#1960]
These calls were mainly to help with on canvas transform guides... However, with cloaking and on canvas transform being driven by Photoshop, a lot of these dispatches can be cleaned up.

**Comment by iwehrman** [comment]
For example, these calls in `selectNext` and `selectPrevious` should be pushed into `selectDocument`: https://github.com/adobe-photoshop/spaces-design/blob/915d5540fab46e6635400baf5e470a5a83b9705e/src/js/actions/documents.js#L580-L582

**Comment by iwehrman** [comment]
Maybe what we want is a utility which takes an action, or an array of play objects, and executes them after disabling the overlay, and then reenables the overlay afterward?
