### ISSUE TITLE
CC Lib: dragging asset with Opt/Alt key auto-nests into AB attempting to place outside AB

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1967]
create a new default doc (AB),
zoom out 
load a library that contains an asset with multiple layers
hold down opt/alt and drag asset from CC Lib to area of canvas outside AB bounds

Result: asset auto-nests into AB.

**Comment by shaoshing** [comment]
This appears to be a bug in standard PS: you cannot expand a graphic outside of a art board unless there is already layers outside. Please see the image below for demonstration. 

![libraries-nested](https://cloud.githubusercontent.com/assets/118264/9202727/1c1c799c-4008-11e5-947d-f1294824c755.gif)


@volfied / @chadrolfs I am wondering if this look familiar to you, and do you have any suggestions?

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4048115

**Comment by chadrolfs** [comment]
verified fix in cyan build, waiting for main integration to verify and close
