### ISSUE TITLE
Dark titlebar makes window drag zone hard to find

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1976]
With the recent change to a dark titlebar, the application UI is no longer distinguishable from the titlebar. I think this _looks_ great, personally, but it makes moving the window harder because it's no longer clear exactly where the draggable region is:
![dark](https://s3.amazonaws.com/f.cl.ly/items/1p1s3l0W1y0Q1N3A1b0w/Image%202015-08-10%20at%205.37.24%20PM.png)
For comparison, the standard UI addresses this by adding a hairline black rule at the top of the application UI. An alternative UX solution would be to allow the entire document header to be a window drag zone, but I don't think we can accomplish that without resorting to some new native API.

**Comment by placegraphichere** [comment]
OMG when did we get the title bar done? I am so excited about this! We could add a small hairline to the top of the doc bar and toolbar. But really, I don't think it's much of a problem.

**Comment by chadrolfs** [comment]
if the app does not have focus, it is distinguished.
![screen shot 2015-08-11 at 8 12 05 am](https://cloud.githubusercontent.com/assets/8442631/9201214/b09f4412-4000-11e5-96fd-a31f5040c980.png)

**Comment by iwehrman** [comment]
For whatever reason, the titlebar color has changed, so this is no longer an issue.
