### ISSUE TITLE
CC Lib: unable to apply Fill/Stroke color or Layer Styles

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1983]
new doc, drag out a rect
load a library that has fill and stroke colors and layer styles

mouse over cc lib assets (Click to apply): click 
Result: nothing is applied

Drag and drop doesn't work, double-click doesn't work

**Comment by shaoshing** [comment]
Hi @chadrolfs , this is implemented and merged into master. note that you have to click on the preview to apply an asset.
