### ISSUE TITLE
CC Lib: Library name field left with bogus name 

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1989]
Enter gibberish in the library field. Hit enter key twice. The name remains with current lib contents.
EXPECTED: Since search failed, the name returns to the current library name.
![screen shot 2015-08-11 at 2 21 53 pm](https://cloud.githubusercontent.com/assets/2029597/9211037/5e48d10e-4034-11e5-9eb5-31e99621980f.png)

**Comment by chadrolfs** [comment]
When I try to do this, I get:
`Uncaught TypeError: Cannot read property 'id' of undefined`

**Comment by ktaki** [comment]
Verified the fix.
