### ISSUE TITLE
CC Library: Cloud Linked layers have the same icon as Linked Smart Objects

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#1990]

**Comment by placegraphichere** [comment]
we have icons for these.  
ico-layer-5-linked.svg
ico-layer-cloud-linked.svg

They have been added to the icon branch sewalker/icons_end_the_blur

**Comment by designedbyscience** [comment]
The code to check the properties for this is coming in @volfied's style PR

**Comment by chadrolfs** [comment]
@DivyaPrabhakar wants to fix this. @designedbyscience let her know when it's in master.

**Comment by designedbyscience** [comment]
Okay

**Comment by volfied** [comment]
Grabbing this since I'm fixing it for all linked smart objects with broken links as well
