### ISSUE TITLE
CC Lib: Edit asset: Document name for a smart object is not shown immediately after the creation

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#1996]
Place a graphic from CC Lib. 

![screen shot 2015-08-11 at 3 45 13 pm](https://cloud.githubusercontent.com/assets/2029597/9212692/1429b3fc-4040-11e5-8b48-3b618139bfa4.png)

Double click it to convert to smart object. A doc opens but no tab with the doc name is shown. Panels are not updated.

![screen shot 2015-08-11 at 3 37 49 pm](https://cloud.githubusercontent.com/assets/2029597/9212598/40623b66-403f-11e5-8a5b-fd4d6bc4ed97.png)

After changing a tool on the toolbar, the doc name shows up. Panels are updated.

![screen shot 2015-08-11 at 3 38 25 pm](https://cloud.githubusercontent.com/assets/2029597/9212614/5e8d2b28-403f-11e5-9b2d-f2b1b7296bc4.png)

**Comment by chadrolfs** [comment]
Here were my steps:
new doc, drag a Lib asset onto canvas and then hit Enter or double-click it

Result: CLSO opens but layers panel and doc tabs doesn't update
close (cmd/ctrl + w)
`Action documents.close failed: Error: Next selected document ID should be null iff there are no open documents`

**Comment by shaoshing** [comment]
there seems to be a lag between the [placedLayerEditContents ](https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/superselect.js#L302) and  [documentLib.referenceBy.current](https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/documents.js#L301) when editing smart object imported from CC Libraries. After the `placedLayerEditContents`, the `documentLib.referenceBy.current` is still returning the source document, but if I add a `delay(200)` [here](https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/superselect.js#L310), it will return the editing document correctly. 

@volfied is this suppose to be a core issue? or do we have a way to ensure the new document is fully loaded before `updateDocument`? The complete workaround is push at https://github.com/adobe-photoshop/spaces-design/commit/70365c4c93bd7b06fe59200910713be6a44370ea#diff-1bd8d606e837ab0e4ebf7c4eb81890aaL309

**Comment by iwehrman** [comment]
@shaoshing @volfied: can you please narrow down the issue and file a high-severity Watson bug for this?

**Comment by volfied** [comment]
Seems to be fixed with latest changes Shaoshing made, please confirm @ktaki

**Comment by ktaki** [comment]
Verified the fix.
