### ISSUE TITLE
New artboard document repositions itself

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#1999]
New documents should not require repositioning. They should be positioned correctly by default. This should happen automatically as a result of the `setOverlayOffsets` calls. If the new document is not being  positioned correctly on creation, then either a) the bounds we're giving to `setOverlayOffsets` is incorrect, b) we are somehow re-positioning the artboard differently after creation; or c) there is a bug in Photoshop.

![jump](https://s3.amazonaws.com/f.cl.ly/items/0l2i2h2d0E1S3u1G3213/Screen%20Recording%202015-08-11%20at%2004.52%20PM.gif)

**Comment by ktaki** [comment]
Could we improve the behavior of the first doc opened  (#2043) ?

**Comment by zoranagee** [comment]
This is really jarring when you are going back and forth - check it out.
![documentzoom](https://cloud.githubusercontent.com/assets/7904855/9591542/e6f45c28-4ff0-11e5-9fa0-e0e0fd10e701.gif)

**Comment by zoranagee** [comment]
We need to fix this one for the MAX keynote.

**Comment by iwehrman** [comment]
The tricky thing here is that when you switch to standard PS, it moves the document into the center of the window. So we almost certainly want to do _some_ kind of repositioning when entering Design Space because the center of the window is probably not the best placement for Design Space. My current best guess is that we just want to _center_ all the already-open documents when they're first activated in Design Space. In particular, we should not be changing the zoom level at all, and we certainly should not be doing any repositioning of documents opened from within Design Space because we've already made it possible for PS to position new documents correctly when Design Space is active.

**Comment by iwehrman** [comment]
Offline, @placegraphichere has suggested that, in fact, we do not want to even just center documents that were already open when switching to Design Space. I guess the thought is that having them off-center is better than the alternative of panning the canvas to a possibly distant position. So, OK!
