### ISSUE TITLE
Touch gesture undo does not update layers panel 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2004]
new doc, drag out several shape layers
perform touch gesture: slide 3 fingers on surface to left to undo until one or no shapes show on canvas.

Result: layer panel doesn't update/show results of undo

**Comment by mcilroyc** [comment]
Created a core request to provide better event info when an out-of-bands undo occurs.  https://trello.com/c/PTpVWcx5

**Comment by chadrolfs** [comment]
self-assigning to re-check since more touch stuff has come in from main and cory asked me to.  :)

**Comment by chadrolfs** [comment]
Confirmed, layers panel does not update on undo/redo surface gestures (2- or 3- finger).

**Comment by iwehrman** [comment]
When I slide three fingers to the left, the canvas disappears and I never see the touch UI... Windows pgdev.715.

**Comment by mcilroyc** [comment]
Hey @chadrolfs I warned you I'd come-a-askin bout this.  I think you agreed to help.  Can you please run the first (all-events) snippet in dev tools listed on [this wiki page](https://github.com/adobe-photoshop/spaces-design/wiki/DevTools-Snippets), and then send the output when you swipe-to-undo on a touch device?  I'm looking to see what events PS throws at us.

**Comment by chadrolfs** [comment]
yessir

**Comment by chadrolfs** [comment]
![screenshot_fri_oct_09_16 18 42](https://cloud.githubusercontent.com/assets/8442631/10407553/b0ac7dce-6ea1-11e5-8059-45190f0a891b.png)
![Uploading screenshot_Fri_Oct_09_16.19.31.png…]()

**Comment by iwehrman** [comment]
FBNC to @chadrolfs. I tested 3-finger-drag and 2-finger-swipe with success. Note that it ONLY works if the gestures happen on the PS canvas and not on the HTML UI.

**Comment by chadrolfs** [comment]
ahhhh snap, it's merged now!  It's on!  Cool!
