### ISSUE TITLE
Editing a Cloud Linked Smart Object doesn't update our models (layers, tabs)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2005]
new doc, drag a Lib asset onto canvas and then hit Enter or double-click it

Result: CLSO opens but layers panel and doc tabs doesn't update
close (cmd/ctrl + w)
`Action documents.close failed: Error: Next selected document ID should be null iff there are no open documents`

**Comment by chadrolfs** [comment]
re-assign to as needed

**Comment by volfied** [comment]
@shaoshing let me know if you get stuck on this one when you work on it.

**Comment by chadrolfs** [comment]
dupe of #1996
