### ISSUE TITLE
Stuck in multiple text editing modal states

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2009]
With type tool selected, selecting a text layer in the layers panel immediately goes into modal text editing mode. With this mode, clicking on another text layer in the layers panel seems to go into another level of modal state. Eventually, the UI freezes. Repeating Esc keys can escape from the editing mode, but bad things may happen in the process.

Steps.  
Create two text layers
Select type tool
1. Select one of them in the layers panel.
2. Select another text layer in the layers panel.
Repeat 1 and 2.
Eventually UI freezes. Use Esc key a few times to recover the state. This might cause some errors.

**Comment by chadrolfs** [comment]
related to or dupe of #1969?

**Comment by iwehrman** [comment]
I agree that this is a high priority bug. It's distinct from #1969. One of the problems is that we get a "createdTextLayer" event when we click with the text tool, but then if the modal tool state is ended without committing the text we never get a corresponding "delete" event. (And I'm not aware of any other way to detect this.) The other problem is that, when the type tool is selected, we seem to be entering the type modal tool state automatically when selecting the layer, which is unexpected and broken.

@pineapplespatula: Any idea about either one of these issues? They both seem like core bugs to me. Let me know if you think I should file issues about either one.

**Comment by ktaki** [comment]
Verified the fix.
