### ISSUE TITLE
CC Lib: dragging layer/group to Lib panel takes a long time to generate thumbnail

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2011]
drag a layer or group from the Layers panel into the Libraries panel

Result: It takes a long time for the asset thumbnail to show.

**Comment by chadrolfs** [comment]
Now I'm seeing that sometimes it doesn't generate a thumbnail at all.

**Comment by chadrolfs** [comment]
haven't been able to repro the thumbnail not ever generating today but man is it slow.

**Comment by chadrolfs** [comment]
for bug scrub discussion: should this block the card from being done?

**Comment by shaoshing** [comment]
Hey Chad, I put this issue in the "Asynchronous" card, and we should move on with the drag-n-drop card.  My test indicates the asset is soon ready for use once imported, but the process of getting the preview image is slow. We can improve this by using the local preview image instead.

**Comment by chadrolfs** [comment]
Got it, thanks.  Moved the card to done.

**Comment by chadrolfs** [comment]
very nice!
