### ISSUE TITLE
truncated file path of exported layer with long name in libraryAdapter#exportLayer 

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2015]
Maybe a core bug, but when you export a layer with long name, the result contains truncated file path.

#### Truncated
<img width="645" alt="screen shot 2015-08-12 at 12 58 36 pm" src="https://cloud.githubusercontent.com/assets/118264/9238979/1bf999c2-410c-11e5-9a0c-657c8a550f0b.png">

#### Normal
<img width="631" alt="screen shot 2015-08-12 at 1 03 49 pm" src="https://cloud.githubusercontent.com/assets/118264/9238984/247fe48e-410c-11e5-8481-86979315974a.png">

cause #2001 but has way to work around.

**Comment by volfied** [comment]
This seems like a core bug. Look at the file name closely in `saveData.in._path`, it repeats itself (`...11755ff`/`ac69f...`) I'll confirm, workaround is fine for now.
