### ISSUE TITLE
UI color should match title bar color

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2019]
![image](https://cloud.githubusercontent.com/assets/1075154/9258618/605fe634-41b1-11e5-8ed2-fc5fcb86b97c.png)

There should also be a hairline that separates the UI from the title bar to make it clear where the draggable region is.

**Comment by chadrolfs** [comment]
Fixed in #2115?

**Comment by iwehrman** [comment]
Possibly, though it may be complicated somewhat by #2068.

**Comment by iwehrman** [comment]
Current state of affairs:
![](https://s3.amazonaws.com/f.cl.ly/items/1s292E1a2q183g0y2q47/Image%202015-08-22%20at%2010.41.13%20AM.png)

**Comment by chadrolfs** [comment]
This looks fixed to me.  @iwehrman close if you agree.
