### ISSUE TITLE
Most icons blink when a document is opened/closed

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2020]
Notably, not the toolbar icons:
![blink](https://s3.amazonaws.com/f.cl.ly/items/1v1C3Z3t1F0e0z2A300h/Screen%20Recording%202015-08-13%20at%2011.54%20AM.gif)

**Comment by designedbyscience** [comment]
So, that's the same toolbar but different everything else (they are blinking because we are creating new versions of all of them)

**Comment by chadrolfs** [comment]
Agree with @designedbyscience.  Only icons associated with new attributes blink.  Tab icons and tab titles don't blink.  And closing doesn't blink.  It's definitely better than it was.  @iwehrman do you think this issue is still medium priority based on current behavior?

**Comment by chadrolfs** [comment]
reviewed - not M3

**Comment by iwehrman** [comment]
Yeah, this is a real bummer, but I think we're out of ideas anyway. Off to M4land!

**Comment by chadrolfs** [comment]
I'm still seeing this occur every so often now (not every time) if I repeatedly do cmd/ctrl + n.

**Comment by chadrolfs** [comment]
almost totally gone though

**Comment by iwehrman** [comment]
Still happens every time for me!

**Comment by iwehrman** [comment]
Fixed by #3611!
