### ISSUE TITLE
Libraries datalist is styled differently from other datalists

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2023]
![image](https://cloud.githubusercontent.com/assets/1075154/9258895/e32fdf64-41b2-11e5-8f83-4f01dd2ec550.png)

![image](https://cloud.githubusercontent.com/assets/1075154/9258904/f08e7260-41b2-11e5-81bd-f5af52edebc6.png)

![image](https://cloud.githubusercontent.com/assets/1075154/9258918/fdec4f68-41b2-11e5-8a6b-e81b8dd72b71.png)

**Comment by designedbyscience** [comment]
Hey, @placegraphichere, are we moving all of them to the white on black?

**Comment by placegraphichere** [comment]
we should be somewhere in this realm
![spectrum_components_dark_v1](https://cloud.githubusercontent.com/assets/3229167/9264027/f9e2244e-41e7-11e5-8e46-6ed343ef2cab.png)
:

**Comment by chadrolfs** [comment]
please check with @davealonzo and @placegraphichere

**Comment by iwehrman** [comment]
This will be addressed by #2115.

**Comment by iwehrman** [comment]
Fixed by #2115.
