### ISSUE TITLE
Zoom increments do not seem correct

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2026]
- open doc
- auto zoom/position occurs
- zoom in and out
- increments seem off, hard to know if 100% can be achieved (my doc would only allow me to be  127.01%)

expected zoom increments:
5, 6.25, 8.33, 12.5, 16.67, 25, 33.333, 50, 66.67, 100, 200, 300, 400, 500, 600, 700, 800, 1200, 1600, 3200

**Comment by iwehrman** [comment]
FBNC to @pineapplespatula. Please verify the fix and close this bug if you're satisfied.

**Comment by pineapplespatula** [comment]
i assume you meant @placegraphichere

**Comment by placegraphichere** [comment]
looks to be fixed in master
