### ISSUE TITLE
Panels blink when scrolling or zooming a document

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2029]
https://www.dropbox.com/s/mqm4n09hm108ymj/PanelBlink.mov?dl=0

**Comment by iwehrman** [comment]
I smell an overlay offsets bug!

**Comment by designedbyscience** [comment]
@chadrolfs Anything particular to replicate this (not seeing it with a few different variations on opening/making new doc/refreshing DS)?

**Comment by chadrolfs** [comment]
grab the latest jenkins build (pgdev 454), launch into DS (optional: connect to master), cmd/ctrl + n, use mousewheel to scroll doc.

**Comment by chadrolfs** [comment]
once you toggle a panel, it stops.

**Comment by iwehrman** [comment]
#2045 attempted to fix this, but did not do so completely.

**Comment by designedbyscience** [comment]
Addressing again by #2046, ready for checking
