### ISSUE TITLE
UI: panels are too wide now (sprint 28)

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2038]
With 2 open seem to take up a lot of space (more than in previous builds)

**Comment by iwehrman** [comment]
@zoranagee Can you be more specific? Do you think the individual columns are too wide? Or are you unhappy with the two-column UI?

**Comment by zoranagee** [comment]
individually each column is too wide - takes up too much space. What are we planning on showing for default? 1 column?

**Comment by iwehrman** [comment]
I believe the plan is to show both by default.

**Comment by zoranagee** [comment]
Then we really need to rethink the width. On my MBP the UI takes up almost half of my screen.

Z.

**Comment by iwehrman** [comment]
We tried to strike a balance between making full use of huge screens and making it possible to work on a small screen by hiding some columns. I suggest, for this use case, collapsing the layers panel and working that way. If you're not happy with that, we should probably discuss this at the weekly design review meeting.

**Comment by zoranagee** [comment]
I want to hear what customers think.

**Comment by iwehrman** [comment]
The design review meetings are where we have discussed the results of those conversations. I'm sure we can tweak the width of the individual columns, but I gather your reaction is primarily about the the screen space used with two columns open. I'm sure @placegraphichere would be happy to discuss the feedback from the user group about that issue specifically.

**Comment by designedbyscience** [comment]
Minor points to consider:

We can adjust the overall size of the UI with CSS and make it smaller on higher pixel density screens (very easy).
We can also adjust the width of columns depending on screen size (less easy but a quick pass says not too bad).

**Comment by chadrolfs** [comment]
drive to resolution and close this sucker!

**Comment by designedbyscience** [comment]
I believe this is going to be discussed during the design review on Friday

**Comment by DivyaPrabhakar** [comment]
This was discussed at the review, the consensus was that we are going to wait for our CSS to be cleaned up and more stable so that changing the width is simply the change of a number. The CSS will continue to improve but meanwhile, we need to get user feedback about how they feel about the widths and then depending on that we will use media queries and adjust the width accordingly. @placegraphichere Can you confirm this is in fact the final decision?

**Comment by DivyaPrabhakar** [comment]
Assigning this to @placegraphichere for now because he is making most of the styling changes and knows best about user feedback regarding the width of the panels.

**Comment by zoranagee** [comment]
I would also be content with a modifier that allows me to swap between Layers or Style in the single-column panel. For example, if you have Layers only showing and you OPT or CMD click on Effects button, it will swap out Layers with the Effects panel - keeping 1-column view without have to to stack and unstack. Also keeps my canvas area free and open.

**Comment by chadrolfs** [comment]
I think this was partially addressed via the new Single Column Mode and if/when #2235 gets resolved.  I think we may be able to close this.  Any objections?  @zoranagee @iwehrman @placegraphichere @designedbyscience
