### ISSUE TITLE
CC Lib: libraries don't load/connect on Windows

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2040]
launch sprint 28 windows build (pgdev-456)
switch into DS if not already or switch back and forth between standard PS and DS

Result: libraries don't load

Workaround: if you connect to github master, they do.

**Comment by iwehrman** [comment]
If this works on master, then is it really a bug?

**Comment by shaoshing** [comment]
the latest build (pgdev-544) seems to be working without switching to github master.

**Comment by volfied** [comment]
I'll take a look to see if compiled code is being bad requiring this library.

**Comment by volfied** [comment]
Running a compiled build, things work fine on Windows with latest Jenkins.
