### ISSUE TITLE
CC Lib: first asset dragged onto canvas shows thumbnail until placed.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2041]
https://www.dropbox.com/s/mecv7t9s1vxv154/CCLib-1stAsset.mov?dl=0

**Comment by chadrolfs** [comment]
#1874 would resolve this

**Comment by shaoshing** [comment]
This is the same issue for search dialog when placing a graphic asset.

**Comment by shaoshing** [comment]
This should have fixed by Barkin. @chadrolfs can you verify?

**Comment by chadrolfs** [comment]
Yep, fixed, yay!
