### ISSUE TITLE
Items with vector masks are unable to be transformed. 

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#2048]
On layers with vector masks. Layer descriptors list their bounds as that of the vector mask instead of the layer itself, which stops us from being able to transform properly. 
![tranformvectormasklayer](https://cloud.githubusercontent.com/assets/1008531/9280002/3bf12794-4270-11e5-8a14-9dc85c5c2fc1.gif)

**Comment by pineapplespatula** [comment]
watson bug 4047426

**Comment by pineapplespatula** [comment]
fixed in jecohen/vectorMaskAdd branch

**Comment by ktaki** [comment]
Verified the fix.
