### ISSUE TITLE
Search Bar Icon is wrong color

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#2051]
It is black. It should not be black.
![untitled-1___51_9___rectangle_1__rgb_8____](https://cloud.githubusercontent.com/assets/22372/9282078/de1fc2ec-4297-11e5-8ba6-6dec0a160041.png)

**Comment by designedbyscience** [comment]
I think this is fixed in incoming PR...

**Comment by iwehrman** [comment]
Fixed in #2049. FBNC to @designedbyscience.

**Comment by designedbyscience** [comment]
Hey, we're back to white
