### ISSUE TITLE
Tool icon missing in vector edit mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2055]
drag out a rect
double-click rect on canvas with the select tool
start editing the anchor points

Result: there is no tool icon where the select tool icon use to be.

**Comment by designedbyscience** [comment]
ICONSSSSS (@placegraphichere has one already)

**Comment by placegraphichere** [comment]
see #2140

**Comment by designedbyscience** [comment]
I checked, we have icon now

**Comment by chadrolfs** [comment]
man, don't be closing my bugs!
