### ISSUE TITLE
Opt-Drag layer to adjacent artboard causes strange results Update: Opt+SHIFT+drag is the cause

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2062]
![opt-drag-to-artboard-positioning](https://cloud.githubusercontent.com/assets/3229167/9286496/928a697c-42ba-11e5-8049-4f4db2dbf009.gif)

animated GIF, click on it

**Comment by iwehrman** [comment]
This seems like a core bug with smart guides and artboard canvas auto-resizing. Over to @chadrolfs to file in Watson. Maybe assign internally to @timothynoel for triage?

**Comment by chadrolfs** [comment]
I'm having a hard time repro'ing this.  @placegraphichere is this easy for you to repro every time?

**Comment by placegraphichere** [comment]
Try adding OPT+SHIFT+drag. that seems to do it. The SHIFT seems key to repro

**Comment by chadrolfs** [comment]
Ok, was able to repro with that - thanks!

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4038192
