### ISSUE TITLE
Disable command-drag mode in shape and pen tools

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2067]
With the rectangle, ellipse or pen tool active, holding down the command key changes the cursor to a black arrow and makes it possible to draw a marquee on the canvas which doesn't do anything. This isn't harmful AFAICT, but it definitely presents a confusing experience to the user.

**Comment by volfied** [comment]
Opened a trello card, will bring this up to Jesper.

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4046461

**Comment by chadrolfs** [comment]
Watson bug is closed/fixed and I verified this on our end as well.
