### ISSUE TITLE
Missing type justify-all icon

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2072]
It's in the DOM, but the icon isn't showing up: 
![image](https://cloud.githubusercontent.com/assets/1075154/9296093/d398e770-4438-11e5-8e8f-438587bb2607.png)

**Comment by iwehrman** [comment]
It looks like the SVG file itself is broken. Over @placegraphichere.

**Comment by volfied** [comment]
FBNC to @iwehrman

**Comment by iwehrman** [comment]
Fixed by #2086.
