### ISSUE TITLE
If fill is not visible, alpha of stroke appears to be 100% on canvas

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2077]
Could be the same root cause as #2076, but reporting this anyway.
Draw a rectangle. Add a stroke and set the alpha to be 20%.
Click on Toggle Fill icon to make the fill invisible.
RESULT: Stroke will be drawn as the alpha value 100% on canvas.

**Comment by volfied** [comment]
Dupe of https://github.com/adobe-photoshop/spaces-design/issues/526
