### ISSUE TITLE
Icons for Delete and Toggle Drop/Inner Shadow are not visible or incorrect

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2079]
Only delete icons are visible

**Comment by chadrolfs** [comment]
I actually think it's the delete icons that are not showing but the tooltips depending on where the mouse is can be confusing.   I think the toggle icons might be wrong for all the styles (fill, stroke and shadows) and the delete icons for shadows are missing.

**Comment by iwehrman** [comment]
![image](https://cloud.githubusercontent.com/assets/1075154/9425199/480c8b66-48bc-11e5-8a6b-07eae3b3b5fe.png)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
