### ISSUE TITLE
Sampler tool makes fill visibility off and doesn't sample fill/stroke

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2082]
Create Rectangle 1 and Rectangle 2.
Change the fill color of Rectangle 2 to red.
Switch to Sampler tool. With Rectangle 2 still selected, click on Rectangle 1.
RESULT: The visibility of Rectangle 2 fill turns off

**Comment by chadrolfs** [comment]
turns visibility off and also doesn't sample fill or stroke.  Shift + click to sample effects still works tho.

**Comment by volfied** [comment]
Fixed in master, since it was such a minor change.

**Comment by chadrolfs** [comment]
stroke still not sampled tho

**Comment by volfied** [comment]
That is currently by design, which I understand feels limited. Primary color sampling applies to the fill of the layer.

**Comment by chadrolfs** [comment]
hmmm, ok, so will there be no way to sample stroke other than copy/paste style?  Are we not gonna fix that?  Seems like a bug and I think users will agree.

**Comment by ktaki** [comment]
Verified the fix.
