### ISSUE TITLE
Effects: Outer (drop) shadow set to white does not show

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2087]
- create shape layer overlaid on a dark background layer
- add an outer shadow to the shape layer
- change the color of the outer shadow to white
- nothing shows

expected: outer shadow should be white. 

Is there a blend mode on the outer shadow?

**Comment by volfied** [comment]
Yeah, blend mode is multiply by default, which multiplies to nothing in this situation.

**Comment by volfied** [comment]
What's the expected blend mode for drop shadows?

**Comment by chadrolfs** [comment]
standard PS default for drop shadow blend mode is multiply

**Comment by chadrolfs** [comment]
I'm a bit confused by this bug.  There is Outer Glow and Drop Shadow, but not Outer Shadow.

**Comment by placegraphichere** [comment]
outer glow has no directional component, but has added "noise". Outer glow and shadow are very similar. 

The point of this issue is simply that we are using multiply as the default blend mode that makes some colors impossible to use. If we do not offer the ability to change blend modes, I'd rather we use a Normal blend mode and rely on opacity to soften the amount of shadow. This way more colors are available to users, and confusion I came across would not occur.

**Comment by volfied** [comment]
Let's bring this up tomorrow at stand up and go from there. @placegraphichere do you see a good way to stick a blend mode popup in the drop shadow detail UI?

**Comment by placegraphichere** [comment]
fixed with #2104. Closing
