### ISSUE TITLE
Create New Artboard fails

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2090]
Create a New... Default Photoshop Size document
Add several shapes to it 
select all layers
Layer > Create New Artboard

Result: `Action layers.createArtboard failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Make” is not currently available.`

**Comment by chadrolfs** [comment]
If I open up an existing doc that doesn't contain an artboard but has a bunch of layer types and group, select all and Layer > Create New Artboard, I get:
`Action layers.createArtboard failed: Error: Too many layers in layer index`

**Comment by iwehrman** [comment]
I don't think that #2063 actually addresses this. At least, if it does, I have no idea why. It's probably just that #2063 isn't rebased against master.

**Comment by iwehrman** [comment]
At least one problem here is that the artboard "make" command fails when a background layer is selected.

**Comment by iwehrman** [comment]
@chadrolfs I can only reproduce this failure with a background layer, but not with an artboard layer selected. Can you confirm? Or narrow down that particular failure for me further?

**Comment by iwehrman** [comment]
The output of PS has changed in the last few days when creating an artboard. Working with @jsbache on this currently...

**Comment by iwehrman** [comment]
Or, perhaps, the output from PS is just different depending on whether or not this is the first artboard created. It seems "wrong" (or is at least unexpectedly different) when creating the first artboard from either a transparent document or a document with a background.

**Comment by mcilroyc** [comment]
The way I understand it, this bug should be back to FBNC

**Comment by chadrolfs** [comment]
Background issue may be resolved but I just hit this issue again:
`Action layers.createArtboard failed: Error: Too many layers in layer index`

**Comment by chadrolfs** [comment]
here's the easy repro:
new default doc
drag out one rects in the AB
Layer > Create New Artboard

(this is with the staging jenkins build 1462 that has new AB changes from main + current master @ 348d96e)

**Comment by iwehrman** [comment]
I can't repro on either staging or dev, so I'm sending this back to @chadrolfs.
