### ISSUE TITLE
Text Layer name not restored after undo+redo

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2092]
1. Create a point-text layer by clicking on the canvas with the text tool
1. Type JELLO
1. Hit ESC
1. Note in the Layer Panel that the layer name becomes JELLO
1. Undo
1. Redo
1 Note the Layer Panel shows a default layer name, not JELLO
1. Help > Update Current Document ; see that it now reflects JELLO

**Comment by mcilroyc** [comment]
Heads up @pineapplespatula and @iwehrman in case there is overlap with your bugs ... but I will otherwise assign this to myself.  My hunch is that we are updating the document out of band (after the history state has been captured)

**Comment by volfied** [comment]
I think @DivyaPrabhakar should look at this bug and learn about the wonderful world of `shouldComponentUpdate`, my 2Çents

**Comment by volfied** [comment]
I retract my statement, this might be something far more sinister

**Comment by iwehrman** [comment]
@DivyaPrabhakar should not look directly into this bug :sunglasses:

**Comment by iwehrman** [comment]
Even though @mcilroyc filed this, I'd like to assign it back to @chadrolfs to close. Seems likely that he'll hit another few bugs in this area when verifying :grimacing:
