### ISSUE TITLE
Text transformation by changing H does not update font size

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2093]
With a text layer selected, change H value in the property panel. Font size is not updated till the layer goes to editing mode next time. The font size should be updated immediately.

**Comment by iwehrman** [comment]
Note to self: when fixing this, remove `transform.setBounds`, which is now dead code.

**Comment by iwehrman** [comment]
Indeed, I missed this case in my recent PR. But I made a branch with the additional change, and then discovered that Photoshop is _also_ not sending us the right "impliedFontSize" after we play the "transform" action descriptor. So this is now blocked on a Photoshop core bug, and requires a Watson issue. And I'm probably the best person to do that, so leaving this assigned to me.

**Comment by mcilroyc** [comment]
FBNC, back to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
