### ISSUE TITLE
Graphics corruption on Windows 10

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2099]
A [forum user reported](https://forums.adobe.com/message/7875933#7875933) graphics corruption in Design Space on Windows 10:
![image](https://cloud.githubusercontent.com/assets/1075154/9360612/fe0b4d62-464b-11e5-9fa8-45a141ecda7e.png)

**Comment by iwehrman** [comment]
Do we need a Watson bug for this? Or should we just close it?

**Comment by chadrolfs** [comment]
Without a repro case, I'm closing.  Could be a multitude of possible causes that may have nothing to do with us.
