### ISSUE TITLE
Modal warning dialog when editing locked type layers

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2101]
1. Create a type layer.
2. Lock the type layer.
3. Try to edit the type layer with the type tool.

![image](https://cloud.githubusercontent.com/assets/1075154/9364123/97ecfca6-465f-11e5-8e47-9280585df3d5.png)

**Comment by volfied** [comment]
PGDV.633 (Mac) or later will have this fixed.

**Comment by iwehrman** [comment]
Fixed by @volfied.
