### ISSUE TITLE
SuperSelect: AB: Selecting in the empty canvas will select images (not visible) over the actual canvas (no AB)

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2113]
Have a couple of AB with images that extend beyond the AB size. Click out in the white space - the hierarchy selects the image (not visible) over nothing. This differs from the way PS handles targeting. Where selecting the white space always selects outside the AB (the canvas) and not the actual hidden image.

**Comment by iwehrman** [comment]
@volfied This sounds like a core Photoshop bug with hit testing and artboards?

**Comment by zoranagee** [comment]
PS works as I would expect.

**Comment by iwehrman** [comment]
Presumably PS does not use the same hit test routine that Design Space uses.

**Comment by volfied** [comment]
This is on us, PS hitLayerTest is returning empty. The obvious fix will break couple other interactions, so let me sit on this a bit.

**Comment by volfied** [comment]
Back in April, to allow selecting layers BEHIND the canvas (remember before artboards, we had a canvas?), I started not being restrictive with the PS hitTest.. it causes problems like this one. I'll fix it.

**Comment by volfied** [comment]
@chadrolfs Similar to #2112, if a layer is extending over the edges of an artboard, and is invisible in that location, clicking it should no longer select it outside the artboard.

**Comment by zoranagee** [comment]
I still see this in Sprint 29. - when doing marquee drag it highlights a bunch of hidden (not in the eyeball sense - in the clipped to other AB sense)

Here I'm marquee dragging the 5 squares and bounding boxes from all the other layers in AB to the left show up.
<img width="1440" alt="screen shot 2015-08-27 at 9 46 03 am" src="https://cloud.githubusercontent.com/assets/7904855/9526828/700dae96-4ca0-11e5-9107-cfe359b104bb.png">

**Comment by chadrolfs** [comment]
@zoranagee ^^ that isn't this bug.  That is specific to marquee select and it may be as designed.

**Comment by volfied** [comment]
It is as designed right now. However, we should track in a separate issue to change the design so marquee select doesn't affect layers in an artboard unless the marquee is intersecting with the artboard.
