### ISSUE TITLE
manifest.json being pushed to Perforce in 'www' is out-of-sync with spaces-design source

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2114]
//photoshop/workarea/playground-dev/plugins/playground/www/manifest.json
{
    "start_url": "./src/index.html",
    "name": "Adobe Project Recess",
    "short_name": "Recess"
}

//photoshop/workarea/playground-dev/plugins/playground/www-dev/manifest.json
and current github spaces-design/
{
    "start_url": "./src/index.html",
    "name": "Adobe Photoshop Design Space",
    "short_name": "Design Space"
}

**Comment by chadrolfs** [comment]
should be update with latest push to P4 team sandbox, CL 1037970

**Comment by iwehrman** [comment]
I don't think @tiburbage monitors Github issues assigned to him, so I verified the fix with a recent Jenkins build and am closing this bug.

**Comment by chadrolfs** [comment]
Thank you!
