### ISSUE TITLE
Artboards: plus galore (+) 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2119]
![screen shot 2015-08-19 at 3 59 05 pm](https://cloud.githubusercontent.com/assets/8442631/9371160/4115811a-468b-11e5-9b18-b0458fd6221c.png)

**Comment by chadrolfs** [comment]
It appears you get into this state when interacting with artboards setting to have auto-nesting per layer.

**Comment by iwehrman** [comment]
I can't figure out how to repro. I've tried disabling auto nesting on individual layers and on artboards. Any hints?

**Comment by volfied** [comment]
I'm getting close...

**Comment by volfied** [comment]
Easiest way to repro is to click on a guide intersecting with an artboard border. Basically, anywhere where we send clicks straight down to Photoshop.

**Comment by volfied** [comment]
Will be fixed by playground-dev-mac#495
