### ISSUE TITLE
Artboard coordinates get wacked when interacting with AB set to not auto-nest (per AB layer setting)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2120]
![screen shot 2015-08-19 at 4 10 07 pm](https://cloud.githubusercontent.com/assets/8442631/9371304/9de9d52a-468c-11e5-88c7-a923f0815f9c.png)

**Comment by iwehrman** [comment]
That is wack.

**Comment by volfied** [comment]
The amount of information on this issue is wack. Can you elaborate/add some steps?

**Comment by chadrolfs** [comment]
CNR.  I'll reopen if I run into this again with better steps.
