### ISSUE TITLE
No way to remove layer effects applied from CC Lib within DS

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2121]
Examples: Color overlay, Gradient overlay.

**Comment by chadrolfs** [comment]
The workarounds are:
1. switch to classic PS and remove them there
2. apply a different CC Library effect that doesn't have those (effectively over writing and removing them)

**Comment by ktaki** [comment]
Good suggestion @chadrolfs !

**Comment by placegraphichere** [comment]
I think we should show a placeholder item, without options that is labeled with the effect name. Bonus points if we allow users to delete them. This is similar to unsupported brushes in libraries. We should not change anything, instead simply acknowledge the item for the user

**Comment by chadrolfs** [comment]
Feature work required ^^

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Is it difficult to add visibility icon next to trash can? People do not want to delete but just want to hide sometimes to see the changes in appearance. @placegraphichere How do you think?

**Comment by iwehrman** [comment]
@ktaki There is now a visibility icon next to unsupported layer effects. FBNC 2 U!

**Comment by ktaki** [comment]
Looks great!
