### ISSUE TITLE
Creating a new subsequent document after guides yields policy errors

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2129]
cmd/ctrl + n, drag out a guide, cmd/ctrl + n

Result: `Action documents.createNew failed: Error: Unknown policy ID: 21`

**Comment by chadrolfs** [comment]
![screen shot 2015-08-20 at 9 16 56 am](https://cloud.githubusercontent.com/assets/8442631/9388764/61129ae8-471c-11e5-9053-6b31c35a0310.png)

**Comment by chadrolfs** [comment]
@mcilroyc check this out!

**Comment by mcilroyc** [comment]
thanks for the note @volfied - i just fixed the export onReset bug in a separate branch.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
