### ISSUE TITLE
Dragging mouse from outside edge blinks the create guide area

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2130]
http://cl.ly/1h1V0q2F0c3p

**Comment by iwehrman** [comment]
I strongly disagree that this is a low priority bug. This really makes the UI feel bad.

**Comment by volfied** [comment]
This is hairy... externalMouseMove isn't always sending us the correct coordinates. I'll work with Fitz to figure out why.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs. Nice work, @volfied.

**Comment by chadrolfs** [comment]
Looks fixed on Mac but not on Win

**Comment by volfied** [comment]
@chadrolfs #2288 will fix this, however, during testing, please keep in mind that guide creation is still not working correctly on Windows, so please test this bug/fix only for edge blinking.
