### ISSUE TITLE
SuperSelect: CMD+click always selects the layer that is the highest in the hierarchy

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2132]
Here's another one where we could be a little smarter. I'm trying to select "ACTIVITIES" with CMD+click. I only can select Mt. Hood (which is 'hidden' at this location) since it's higher in the layer stack. 

Mt. Hood is not hidden as in layer visibility - just that it is behind Activities or masked by everything else above it.

Photoshop correctly targets the type layer as I would expect DS to be able to select as well.

When we integrate masking, this could introduce some unexpected behaviour too (i.e. selected the masked out layer instead of the one that is actually visible)
<img width="470" alt="ss_cmdtarget" src="https://cloud.githubusercontent.com/assets/7904855/9390202/811ee906-4724-11e5-9506-6522496c0d12.png">

**Comment by chadrolfs** [comment]
Will be fixed by the fix for #2112

**Comment by volfied** [comment]
This image has a clipping mask, which we are currently not supporting. Closing this bug.
