### ISSUE TITLE
Sampler HUD failed on multi-text-runs

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2137]
create a multi-run text layer (contains 2 different Typefaces)
select the sampler tool
mouse over type layer and hit Space

Result: `Action sampler.showHUD failed: Error: The font for layer is not available!`

**Comment by chadrolfs** [comment]
![screen shot 2015-08-20 at 12 10 05 pm](https://cloud.githubusercontent.com/assets/8442631/9393107/0c0b4d06-4735-11e5-8b9c-604080ac720b.png)

**Comment by volfied** [comment]
This is not the multitext, but the fact that font is not being found in the postScript map.

Stupid question: Are you using a missing font?

**Comment by chadrolfs** [comment]
I'm not but I am using the staging build instead of dev 1462

**Comment by chadrolfs** [comment]
here are my exact steps:
cmd+n
hit the T key 
click in AB and type "abaasdfasdfasdfasdf" (default font)
(while still in edit mode) select a series of characters in the middle "abaa*sdfas*dfasdfasdf" and set it to Helvetica Neue Bold Italic
hit Enter (on Num Pad) to commit text
hit I for Sampler
mouse over Type layer on canvas and hit Space

**Comment by iwehrman** [comment]
FBNC to @chadrolfs. See #2175 for future work.
