### ISSUE TITLE
Clicks in the ExportAll dialog can grab an underlying guide

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2138]
This is also possible in the Design Space Intro screen.  This is only particularly troubling when the guide happens to be below a checkbox.

**Comment by iwehrman** [comment]
The dialog infrastructure should ensure that the pointer propagation policy is NEVER_PROPAGATE while a modal dialog is open.

**Comment by mcilroyc** [comment]
Note this happens as well in the style panel, if you can find an otherwise non-clickable area. 

also dragging @volfied in to this - he had a concern with ian's never-propagate suggestion.

**Comment by volfied** [comment]
Actually, I rescind my concern. It should be safe to add a NEVER_PROPAGATE policy on top when dialogs are open, as it will z-order override the other area policies.

Policy overlay won't visualize it though, I use it only for area policies.

**Comment by mcilroyc** [comment]
booya
