### ISSUE TITLE
Unable to move guides attached to Artboards

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2144]
in classic PS, have a doc with an Artboard
with the AB targeted (focused in layers panel)
(with Rulers shown) drag out a couple guides into the AB
Switch to DS and try to move the guides

Note: you can only see the guides if the AB has focus

**Comment by volfied** [comment]
Will be fixed by #2158

**Comment by ktaki** [comment]
This is still be the case with merged PR #2158.
Create a new artboard. Drag a guild on to the artboard.
Deselect artboard.
Select artboard.
The guide cannot be moved.

**Comment by volfied** [comment]
I can not repro, @ktaki. Can you provide video with the latest build of full steps please?

**Comment by chadrolfs** [comment]
Here are the breakage scenarios:

Open a doc that has doc guides and one AB with guides attached to it.
- if you move the guides in the AB first, you will not be able move the doc guides
- if you move the doc guides first, you won't be able to move the AB guides
- if you move the actual AB before you touch either type of guide, you end up not being able to move any.

**Comment by volfied** [comment]
Oops, I forgot to remove the reverse call, so index i in n guides was ending up editing n-i th guide

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
