### ISSUE TITLE
Very slow "nudge" transform needs to be investigated

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2150]
Not sure if we intend to support arrow keys nudge action for layers/artboards, but our response when you do this is very slow. Naturally, this is most noticeable for heavy artboards or layer groups.

1 - Open VermilionArtboards.psd in standard ui
2 - With the Move Tool (or Artboard Tool) enabled, select one of the Artboards
3 - Press any of the "arrow" keys to nudge the content around. It works very quickly.
4 - Switch to Design Space
5 - Repeat the nudge. I'm seeing 20-30 sec wait times to complete.

Since we seem to be able to drag the same content around will low latency, hoping a more efficient update code path can be applied to nudging.

**Comment by iwehrman** [comment]
Each instance of `transform.nudgeLayers` takes ~100ms in a debug build in Vermilion for me. Are you seeing the problem when you hold an arrow key down?

**Comment by iwehrman** [comment]
CC @volfied because I'm pretty sure we discussed this at some point. I suspect the problem is with how we're throttling this command. I also suspect that the fix is not terribly obvious with our infrastructure. What we really need is something like a nudge tracker...

**Comment by tiburbage** [comment]
When you say "hold an arrow key down", do you mean as opposed to a single tap? I'm just giving it a single keydown/up, but I think it gets worse if I hold it down. The processing time I cited is on Windows. On my MacBook Pro, it is faster but still a long spin.

**Comment by tiburbage** [comment]
Logged in Watson: https://watsonexp.corp.adobe.com/#bug=4045560
Jesper thinks we need to provide access to a faster transform method.

**Comment by jsbache** [comment]
yes: DS seems to be using transform and we need to provide access to "nudgeLayers" from the move tool implementation

**Comment by jsbache** [comment]
CL: 1039134 add a nudgeSelectedLayers command to the document element. This can be used to move layers similar to what happens when the user press the arrow key in standard.
See http://sol.corp.adobe.com/Photoshop/PlaygroundActionDescriptor#Nudging_selected_layers
Sample:
var reference = {_ref: "document", _enum: "ordinal", _value: "targetEnum"}
var desc = {"null":reference, "offset":{"vertical":10, "horizontal":0}}
_playground.ps.descriptor.play("nudgeSelectedLayers", desc, {}, callback)

**Comment by jsbache** [comment]
Required support in Photoshop is available via eventMove and eventCopy.
Although multiple layers may be active you need an action reference with a layer. I recommend using the targetEnum value for the layer/

**Comment by iwehrman** [comment]
Passing this to @volfied.

**Comment by tiburbage** [comment]
This does appear to be fixed looking at staging builds e.g. playground/...@1043692, with
HTML update for MAX (Sprint 31.1), Artboard Guides fix, release @ 8b64b0ad8779db8b1b958fc6d7d14a155e7daaab
