### ISSUE TITLE
Export panel should not grow in height when adding assets

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2152]
This makes the + click target hard to hit multiple times in a row. The panel also seems to have no max height, which I think is wrong.

**Comment by iwehrman** [comment]
More concretely, the panel should not shrink when deleting assets. I might reasonably want to click the trashcan a few times to delete a bunch of assets, but I can't do that easily when the list moves around as I delete assets.

(This is the same reason that chrome tabs hold still as you close them for a few seconds before resizing themselves. If you've never noticed that before, you should try it! It's great.)

**Comment by iwehrman** [comment]
Also, I think this panel should have a relatively modest fixed height. When expanded, it ought to have height enough to see ~5 assets, and never grow taller than that. If you wanna make 100 different assets for one layer, the scrollbar will do ya just fine.

**Comment by iwehrman** [comment]
CC @placegraphichere to slap down my armchair design tendencies.

**Comment by designedbyscience** [comment]
I agree with your observations... Since it is not difficult to add max-heights, I wanted to have a version to point to where we just let them resize without restriction. The other experiments in this vein would be 1) All panels have a max (or possibly fixed) height 2) Let my people scroll (the entire column)

**Comment by iwehrman** [comment]
I think for M3 we should do something closer to 1 than 2. CC @placegraphichere for a second opinion.

**Comment by DivyaPrabhakar** [comment]
Assigning to @designedbyscience for now because he said we need to have a larger discussion about these panels

**Comment by placegraphichere** [comment]
#2544  addresses a portion of this issue. But will not fix all cases.
