### ISSUE TITLE
Zoom: Toggle stroke visibility results in zoom level reverting to default

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2160]
Zoom in
Create a shape
Add a stroke
toggle stroke visibility
zoom reverts to default

**Comment by volfied** [comment]
I can not repro this.

**Comment by iwehrman** [comment]
I also cannot repro this. @zoranagee, if you see this again please re-open!

**Comment by zoranagee** [comment]
Just sent a video to Barkin and Ian - I'll reopen if they can repro (or if I can repro again in Sprint 28)

**Comment by iwehrman** [comment]
Back over to @chadrolfs to try to repro. (I'll forward you the video.)

**Comment by chadrolfs** [comment]
Fixed in current builds
