### ISSUE TITLE
No Generator, No DS

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2165]
DS should still work without generator plug-in working. (DS in today's mainline, PG staging, and PG-dev builds are all dead with master branch on Windows because Generator is not working.) 

GET file:///C:/Users/ktaki/Documents/GitHub/playground/spaces-design/bower_components/generator-connection/main.js net::ERR_FILE_NOT_FOUND
require.js:165 Uncaught Error: Script error for: generator-connection/main

**Comment by mcilroyc** [comment]
My hunch is that this may be unrelated to Generator not working.  @chadrolfs could it be that bower install was not run before pushing the HTML?  (maybe that's not even possible).  It looks like a missing dependency on generator-connection, which is a dep on the design-space side (not the generator plugin side)

**Comment by ktaki** [comment]
Sorry. You are right. User error. Closing.
