### ISSUE TITLE
Hard to grab transformation handles in skew or distort mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2168]
With a shape layer press Cmd (mac) or Ctrl (win) to be in skew/distort mode. Drag transformation handles. The first time works, but subsequent tries may or may not work. This is because as soon as mouse is released, the bounding box is redrawn to be a rectangle in DS while the transformation mode continues in Ps and the transformation bounding box returned from Ps may be different.

**Comment by chadrolfs** [comment]
Using modifier while transform dragging.

**Comment by mcilroyc** [comment]
FBNC to @ktaki   -- this passed my cursory test, but admittedly I may not be attuned to some of the nuances.

**Comment by ktaki** [comment]
It works better than before, transformation handles are now not easy to miss. However, true free transformation which standard Ps offers with modal state cannot be achieved here. Once you release the mouse button, the bounding box and handles will reset to be a rectangle. This prevent users from adjusting details of the transformation. I accept this as a limitation of current design, but will open a separate issue for this hoping to be improved in the future.
