### ISSUE TITLE
Zoom out after creating a new doc shifts to the right under panels

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2169]
https://www.dropbox.com/s/6wmo0kui308kwch/ZoomOut.mov?dl=0

**Comment by placegraphichere** [comment]
Additional 
- Center a document artboard
- select none
- zoom out
-  artboard will shift up and to the right oddly

https://www.dropbox.com/s/hkemdvftzffapgn/zoom-out-centers-things-strangely.mov?dl=0

**Comment by chadrolfs** [comment]
It's really bad on Windows.  It zooms out to the right and then pops back to center.  I'll try to post a video

**Comment by iwehrman** [comment]
FBNC to @chadrolfs!!!!!!

**Comment by chadrolfs** [comment]
Fixed on Mac.  Still looks weird on Win.

https://www.dropbox.com/s/0svfs7hheqgwh1i/capture_Tue_Sep_08_07.41.24.mkv?dl=0

**Comment by mcilroyc** [comment]
take two, @chadrolfs
