### ISSUE TITLE
Guides: unable to move guided that are created under edge highlight

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2170]
new doc
mouse over work area edge to reveal blue highlight and click
pan doc so that guide is not under edge and try to move

Result: won't move

**Comment by volfied** [comment]
Can you try to repro this with policy frames shown in a non-compiled build? It feels like a timing issue where policies are having a hard time catching up.

**Comment by volfied** [comment]
That's the only time I can repro this, but I want to make sure I got the steps right.

**Comment by chadrolfs** [comment]
I can repro this with current resources (dev 522 and master @ ffa24f9c7c730c0a4dd74c14f378fbfcbf57c7c9)

**Comment by chadrolfs** [comment]
still broken

**Comment by chadrolfs** [comment]
https://www.dropbox.com/s/quxeztd3tl4m5cz/guide-underHiLite_noDrag.mov?dl=0

**Comment by volfied** [comment]
The newer issue is due to us calling descriptors to create the guide, and then not moving it, so we don't receive a notification for it. It's fixed on core side: CL 1038728

Will be available Jenkins Dev Mac - #530

**Comment by chadrolfs** [comment]
This is still failing on Windows.

**Comment by volfied** [comment]
Fitz and I looked into it, and we found a bug in Windows side that's causing this bug. He's looking into it.

**Comment by volfied** [comment]
@chadrolfs With latest Jenkins, @jfitz-adobe fixed this, please confirm.
