### ISSUE TITLE
Double clicking guides will display preferences

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2172]
Shouldn't it be suppressed?

**Comment by volfied** [comment]
Will be fixed in Jenkins pg-dev-mac#507

**Comment by ktaki** [comment]
It has been suppressed for horizontal guides, but double clicking vertical guides still show prefs.

**Comment by volfied** [comment]
Oops, turns out horizontal and vertical guide move tools are separate. Sorry!

Should be fixed in the newer Jenkins build.

**Comment by chadrolfs** [comment]
Looks like jenkins dev builds 508 and later.

**Comment by ktaki** [comment]
Thanks Chad. Verified the fix.
