### ISSUE TITLE
CC Libraries connection failure

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2173]
On my machine this morning, the connection failures are repeatable and don't seem to be resolved by restarting the Creative Cloud app. It could be due to this:
![image](https://cloud.githubusercontent.com/assets/1075154/9424438/8a353850-48a1-11e5-9ecc-6696a0a74ae5.png)

It's expecting an object with a `port`, but instead it's just getting a string. I'm using the 20150821.play.1473 staging build.

Related: it seems like if the connection fails at startup, there should be a warning message. It also seems like maybe the "Sync" button ought to be repurposed as a "Connect to CC Libraries" button when we fail to connect? (Though in this case, that obviously would not have helped.)

**Comment by volfied** [comment]
This one's on me, during integration, I mistakenly removed this line from the C++ function getting the descriptor. I've re-added it in staging, so it should be good to go after CL 1037750

**Comment by iwehrman** [comment]
Fixed by @volfied.
