### ISSUE TITLE
Single click on the edge of an Artboard causes add artboard overlay to blink

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2185]

**Comment by volfied** [comment]
We get a `toolModalStateChanged` notification as soon as you click on the edge (which is driven by Photoshop), and start dragging the artboard. And that is our only chance to turn off add buttons. 

User is consciously entering a modal state of dragging artboards, I think it's acceptable to turn off the add artboard overlay at that point, and if they decide not to, bring it back up again.
