### ISSUE TITLE
menu.psd open completely black in DS

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2188]
1. in PS standard open menu.psd (located in my Transfer on sjshare under "DesignSpace")
2 - jump to DS

RESULT: file opens black (even after jumping back to PS standard). If you open the file directly from DS, it opens fine

* This file could've been created with prerelease version but if I re-save in current sprint, I still see the problem.

animated gif of issue
![black](https://cloud.githubusercontent.com/assets/7904855/9452369/b35449f6-4a68-11e5-85ea-0286c57fd6e3.gif)

**Comment by zoranagee** [comment]
Ugh - missed the screenshot of this in DS; now I can't repro. Can anyone else?

**Comment by ktaki** [comment]
CNR with the latest pgDev and master.
