### ISSUE TITLE
Transforming a shape so that it ends up outside AB results in uncaught errors

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2189]
AB doc, drag out a rect shape, move the shape so that it extends mostly outside AB (but a part remains inside so it remains nested).  Click and drag an edge handle so that it snaps to the outside edge of the AB (putting the shape outside AB), click that same handle again and drag further away from AB edge.

Result:
`Uncaught TypeError: Cannot read property 'left' of null`

**Comment by volfied** [comment]
@chadrolfs This was due to my intersection related superselect changes, and I added safety checks across my PRs to make sure these errors don't happen. I can't repro this anymore and it should be fixed. Please confirm.
