### ISSUE TITLE
Shortcuts that are essential for Designers

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2190]
Useful Designer-focused layer shortcuts to have in DS:

Would be weird to not have:
- TAB for renaming layers
- CMD click layer expand to collapse/expand top level group (AB)
- OPT click layer expand to collapse/expand everything (all groups and AB)
- CMD + J to duplicate layers via copy
- OPT + drag layer or group to duplicate
- CMD + , for layer visbility

Next level:
- Shift + or - to change and scroll the blend modes
- Use the numeric keys on the keyboard to change the opacity of a layer. Tapping one number assigns the percentage of the tapped number (1 = 10%, 2= 20% etc. and 0 = 100%). Tapping two numbers quickly will give you that exact amount (5 + 4 = 54%). In Photoshop CS6, tapping 0 + 0 quickly will set the Layer’s opacity to 0 (zero). This works with either a single layer or multiple layers selected

Targeting Layers via the Keyboard
- Option (Mac) / Alt (Win) + “[“ or “]” targets the layer above or below the currently targeted layer
- Option (Mac) / Alt (Win) +Shift + “] “or + “[“ adds the next layer up or down to the targeted layer(s) (note when you get to the top or bottom of the layer stack, Photoshop will “wrap around” to continue adding/subtracting layers)

For Masks when we get them:
- Option (Mac) / Alt (Win) -drag a layer or vector mask thumbnail in the Layers panel to create a copy of the mask

**Comment by zoranagee** [comment]
Would love to hear what @placegraphichere thinks of these - a lot of these we added specifically as TOP Designer requests

**Comment by placegraphichere** [comment]
These all sound correct, although I would place above these the ability to move a selected layer up and down the tree with CMD+[ and CMD+]. With the ability to send the item to the top of the parent group with CMD+SHIFT+[ and CMD+SHIFT+]. There is already a trello card for this.

**Comment by davealonzo** [comment]
Also, toggle shortcuts for locking/unlocking and hiding/showing layers:
CMD+/ (lock/unlock layers)
CMD+, (hide/show layers)

Here's a Trello card I added a few weeks ago that captures these as well as the arrange related ones that Seth mentions above. https://trello.com/c/iRojbdFB

**Comment by DivyaPrabhakar** [comment]
Assigned this to myself because I will be working on #2183 and can work on making sure all the shortcuts are done too. Any objections let me know.

**Comment by iwehrman** [comment]
This is a great list, but a bug it ain't. Each of these feature requests (at least the ones that aren't already implemented) need to be prioritized relative to other work. This is purely a product management task, so I'm assigning this back to @zoranagee. Please head to the Trello board, make cards for the features that aren't already implemented, and prioritize them along with all the other work we've spec'd out.

**Comment by zoranagee** [comment]
Is it easier to tackle several of these that are related - at once; rather than looking at each individually? I can group them into priority 1, 2 and 3.

**Comment by zoranagee** [comment]
Trello card updated.
