### ISSUE TITLE
Fails to enable Generator

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2191]
Clear the preferences, start Ps, switch to DS.

WebSocket connection to 'ws://localhost:59596/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
export.js:451 Export Service failed to initialize correctly because: Error: ExportService.init explicitly returned: Error: Domain 'generator-spaces' does not exist, nor was a domain path provided
fluxcontroller.js:548 Finished action export.afterStartup in 9572ms with RTT 9572ms; 1/0

Switching back to standard Ps, the prefs show Generator is enabled.

**Comment by iwehrman** [comment]
I just merged #2154 which may address this. Can you verify?

**Comment by mcilroyc** [comment]
I think that PR might help ... but I also think that a in-the-works PR which supports dynamic ports might provide even more stability.  So, I'll leave this bug open.  I've *might* still have seen some intermittent  occurrences of the above-referenced error.

**Comment by mcilroyc** [comment]
@ktaki I believe this should be resolved now (via #2216 and the associated plugin changes).  My hope is that it would take some serious tampering (eg, removing generator or the plugin by muddling with files) to result in the export service not loading.

**Comment by ktaki** [comment]
Verified the fix.
