### ISSUE TITLE
While an artboard child is selected, shapes drawn outside artboard stay in the artboard group and are masked out

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2192]
cmd/ctrl + n
r (rect tool) and drag out a shape inside AB
cmd/ctrl + g
click on Rectangle 1 layer
click and drag out a rect outside AB bounds

Result: shape is created outside AB but is nested incorrectly within it above the previously focused layer.

**Comment by chadrolfs** [comment]
related to #1937

**Comment by volfied** [comment]
Not sure if this is a bug. PS is placing that layer in the group, despite it being drawn outside the artboard.

If you think this is an issue, we need a watson bug because PS drives the shape drawing.

**Comment by volfied** [comment]
@chadrolfs Let me know if you think this should be fixed, given my description above. If so, please assign back to me and I'll write up a Watson bug.

**Comment by chadrolfs** [comment]
Yeah, this is what Zorana was running into and if the selected layer is nested in a collapsed group, it can be confusing.

**Comment by volfied** [comment]
Emailed Cyan team asking if this is expected behavior of artboards. Reason is, creating a shape in a group calculates it's reference rectangle using it's parent group, and if that group is intersecting the artboard (which in case it's a member of the artboard), layer stays in that group therefore the artboard.

**Comment by volfied** [comment]
Final verdict on this issue: This is expected behavior, we should make sure, in our own model, that a selected layer can never be hidden in the layers panel. @chadrolfs @iwehrman please verify.

**Comment by iwehrman** [comment]
Does that mean we should deselect descendants when a group is collapsed?

**Comment by chadrolfs** [comment]
@iwehrman in short, yes, but we do this by selecting the group you just collapsed.  See issue #2538

**Comment by iwehrman** [comment]
Currently if you click on the icon, the selection state does not change.
