### ISSUE TITLE
Redraw issue when moving from MBP to cinema display

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2193]
1. launch PS on MBP
2. drag PS window over to cinema display that is connected
3. expand to fill screen
4. click the jump to DS button
![screen shot 2015-08-24 at 3 16 47 pm 2](https://cloud.githubusercontent.com/assets/7904855/9454040/d9a25994-4a73-11e5-8a54-3b37e285e003.png)

**Comment by iwehrman** [comment]
@chadrolfs @ktaki @tiburbage Can somebody try to repro this and then file a Watson bug? This is definitely a core issue.

**Comment by ktaki** [comment]
Yes, I can repro this. Will open a watson bug.

**Comment by ktaki** [comment]
https://watsonexp.corp.adobe.com/#bug=4042399.

Between the step 1 and 2 in the description above, you need to switch to DS at least once and come back to Ps. DS seems to remember the application frame dimension and still stick to it when moved to bigger screen.

**Comment by ktaki** [comment]
It turned out that the issue was reported as
https://watsonexp.corp.adobe.com/#bug=4018312
Updated the bug with my comment.

**Comment by chadrolfs** [comment]
CNR in a dual monitor situation with a Dell 1905FP as 2nd monitor.  Will check with larger cinema display.

**Comment by ktaki** [comment]
I can reproduce this with today's mainline build r.224. Watson bug is still Open/ToFix.

**Comment by chadrolfs** [comment]
bummer. :cry:

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4018312 is fixed in the team sandbox @1046575. Note on Mac it introduced a redraw regression on Mac (https://watsonexp.corp.adobe.com/#bug=4069728) that will likely be addressed before integrating it to staging, so if not in a hurry, wait for our integration...
