### ISSUE TITLE
Zoom out with nothing selected moves the canvas oddly

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2194]
- Center a document artboard
- select none
- zoom out
- artboard will shift up and to the right oddly

https://www.dropbox.com/s/hkemdvftzffapgn/zoom-out-centers-things-strangely.mov?dl=0

**Comment by chadrolfs** [comment]
this may be a dupe of #2169

**Comment by placegraphichere** [comment]
Closing as dupe
