### ISSUE TITLE
On-canvas UI should be defined in rems instead of pixels

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2196]
So that our on-canvas UI scales along with the rest of the UI based on screen size, we should define our on-canvas UI in rems instead of pixels. (We can observe the font-size at runtime and use that for a rems-to-pixels conversion for compatibility with DOM APIs if necessary.)

Compare the images below, which show the same UI simulated with different screen sizes:
![image](https://cloud.githubusercontent.com/assets/1075154/9454607/262d02ce-4a78-11e5-9f02-5080068d604f.png)
![image](https://cloud.githubusercontent.com/assets/1075154/9454610/2d404ada-4a78-11e5-8477-ec66478f2dfb.png)

**Comment by volfied** [comment]
@iwehrman please close once you merge the rem PR.

**Comment by iwehrman** [comment]
Leaving this open because it isn't aware of `displayConfigurationChanged` events. Self-assigning.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
Closing this, but #2861 is related.
