### ISSUE TITLE
CC Lib: creating a new library should enter name field immediately upon creation and hide previous library assets

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2197]
click on Libraries drop down: Create New Library
start typing

Result: nothing.  
Expect: 1.) user should immediately have focus in Library Name field with that text selected so user can name their library 2.) assets from current library should be hidden until user clicks Create (dumping them into an empty library) or Cancel (reverting to previous library and assets.

**Comment by chadrolfs** [comment]
Looks fixed on Win - after Create New Library, I can start typing immediately to name, but not on Mac.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
partially fixed.  assets from current library should be hidden.  see related bug #2864

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs, again.
