### ISSUE TITLE
Stale empty layer remains after placing cloud-linked smart object in new artboard

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2201]
1. Create a new artboard document
2. Drag a graphic out of your CC library into the empty artboard.

Result:
The layers panel shows two layers: one for the new CLSO, and one for the original empty child layer. This is wrong because the original empty child layer is deleted in the PS document when adding the CLSO layer, so the layers panel is inconsistent with the PS document model.

Expected:
The empty child layer should be replaced by the CLSO layer.

**Comment by iwehrman** [comment]
Calling all `layers.addLayers` fans, CC @mcilroyc @volfied.

**Comment by volfied** [comment]
@iwehrman can you confirm this fixed?
