### ISSUE TITLE
Zoom shortcuts don't function correctly

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2206]
cmd/ctrl + n
drag out some rect shapes inside AB
layer > create new artboard
cmd/ctr + 0 (fit in window)

Result: only artboard 1 is set to fit zoom
even if you add shapes to artboard 2 and then hit cmd/ctrl + 0 again, it zooms to fit only artboard 1

**Comment by iwehrman** [comment]
FBNC to @chadrolfs!!!!!
