### ISSUE TITLE
Previously saved docs with shapes open with Stroke: mixed.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2207]
attempting to change stroke results in failure and `Unhandled rejection Error: Unable to set stroke properties of layer: inner shadow`

**Comment by chadrolfs** [comment]
let me know if you need a test file.

**Comment by chadrolfs** [comment]
This occurs on release so it is not a result of the new color picker design

**Comment by volfied** [comment]
I reproed it with one of my old documents, `AGMStrokeStyleInfo` property is not available for some layers!

**Comment by volfied** [comment]
Looks like AGMStrokeStyleInfo is not available when the stroke is disabled. Will fix our data structures

**Comment by volfied** [comment]
I messed up during singularizing strokes and fills... fixing.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
You can now change Stroke attributes without errors but previously saved doc with shapes open with Stroke: mixed

Leaving bug open and lowering priority

**Comment by mcilroyc** [comment]
@chadrolfs please see barkin's write-up in #2502
