### ISSUE TITLE
Coordinates for new artboards are not correct

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2209]
cmd/ctrl + n
cmd/ctrl + - to zoom out
select Artboard 1
click the plus sign to the left

Result: Artboard 2 is created but coordinates and plus overlay is not correct

**Comment by chadrolfs** [comment]
this is on current staging build with sprint 29.3 release html:

![screen shot 2015-08-25 at 11 22 02 am](https://cloud.githubusercontent.com/assets/8442631/9475399/512c93c4-4b1b-11e5-8fe8-de761bff094b.png)

**Comment by volfied** [comment]
Something is going on with artboards, since Divya is working on other artboard bugs, I'm going to wait on this one a bit.

**Comment by DivyaPrabhakar** [comment]
@volfied I am working on this now, will update you within an hour or so either way.

**Comment by iwehrman** [comment]
Here is my theory, as articulated to @DivyaPrabhakar:
![image](https://cloud.githubusercontent.com/assets/1075154/9509559/03dc487a-4c16-11e5-8913-e8b3695717d6.png)

**Comment by chadrolfs** [comment]
It would be great if we could fix this issue this sprint (30)

**Comment by DivyaPrabhakar** [comment]
I agree with Ian regarding his theory and apparently this race between CEF and PS is a commonly occurring bug that we need a more consistent way of solving. This was discussed at stand-up -- passing it back to @volfied.
