### ISSUE TITLE
Swapping artboards should also swap position in the Layers panel

### ISSUE THREAD

**Issue by davealonzo** [adobe-photoshop/spaces-design#2212]
Swap two artboards using the "swap position" tool in the properties panel.

Result: Artboards (and contents) swap successfully as expected on canvas, but not in the layers panel.

This can potentially be confusing when trying to export artboards in a certain order based on how they  are laid out on the canvas with the wrong correlating layer position.

**Comment by volfied** [comment]
Swap position swaps layers in X and Y dimensions. Layers panel lists them in Z-order. Mixing the dimensions together will not produce nice results, and is not a well defined behavior. Layers are never meant to be ordered in some way in the layers panel tied to their position on canvas.

This is not a bug.

**Comment by davealonzo** [comment]
But doesn't export-all currently determine the order of the list it generates in the modal based on how AB layers are ordered in the Layers panel? @mcilroyc Can you verify this?

The current design for the "add prefix" feature in export-all is dependent on generating the intended ordered list of ABs. So, It would be great if the export-all list was determined by how users typically order their ABs on canvas rather than by the Z-order from the Layers panel.

**Comment by iwehrman** [comment]
I believe the layers in the export dialog are ordered alphanumerically by layer name.

**Comment by mcilroyc** [comment]
Yes, *export-all* orders the artboards by index (z-order).

**Comment by mcilroyc** [comment]
@davealonzo after you have had a chance to review the new Export All dialog which sorts artboards by canvas layout, can you let us know if this issue is still outstanding?   That is: do we ALSO want to swap the order in the layers panel?  I'm hoping you say NO, of course : )

**Comment by davealonzo** [comment]
@mcilroyc Just caught this one (sorry)...

This is no longer an issue with the new sorting mechanism. So NO, we don't need to swap layer order  (thank you! :-)
