### ISSUE TITLE
Window maximizing always returns to primary display

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2213]
1. Launch DS on main display
2. Move it to secondary display
3. Press the green headlight to maximize the window

Result:
DS becomes maximized on the main display.

**Comment by iwehrman** [comment]
Needs watson issue.

**Comment by jsbache** [comment]
@iwehrman: I can't repro this. Remember to include your monitor configuration. This will be an Owl issue, so you should also be able to repro when you are in standard mode?

**Comment by chadrolfs** [comment]
try me if you feel lucky punk

**Comment by iwehrman** [comment]
Well, I can't repro now either. I guess it's fixed!
