### ISSUE TITLE
After switching displays, guide zones are the wrong size

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2214]
1. Launch on monitor A
2. Move window to monitor B
3. Drag out a guide:

![image](https://cloud.githubusercontent.com/assets/1075154/9478034/6a37a692-4b2a-11e5-9ea4-39b50fc79d45.png)

**Comment by iwehrman** [comment]
We should be able to use the new `displayConfigurationChanged` OS event to address this.

**Comment by volfied** [comment]
Giving this one to @chadrolfs as it's guides related.
