### ISSUE TITLE
Names truncated in the Libraries panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2219]
Names with all capital letters or Kanji characters are truncated prematurely.

<img width="302" alt="screen shot 2015-08-25 at 3 40 31 pm" src="https://cloud.githubusercontent.com/assets/2029597/9481676/2f841bd6-4b41-11e5-8546-8a21410dbd76.png">

**Comment by iwehrman** [comment]
Very weird. CC @placegraphichere or @designedbyscience in case they have any ideas about this one.

**Comment by shaoshing** [comment]
This is related to the `size` attribute in textinpu. Shall be fixed after merging #2225

**Comment by ktaki** [comment]
Verified the fix.
