### ISSUE TITLE
Swap performance is slow

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2231]
On my windows machine, it's in the 2553ms range.  On my mac pro it's 1600ms.

**Comment by chadrolfs** [comment]
with the App Ideas.psd file swapping each artboard.  Let me know if you need the file.

**Comment by volfied** [comment]
Seems like our extensive playLayerActions that calculates move for each child layer in the artboard takes 2.3 seconds in this file. We should first check and see if we can swap artboards without referring to their children.

**Comment by iwehrman** [comment]
dupe of #1513?

**Comment by volfied** [comment]
Not a dupe, #1513 was due to us having to wait for models to update so we can call swap in the next model (instead of immediately calling swap twice on the same model). This is an actual performance hit that happens during busy artboard calculations.

**Comment by volfied** [comment]
Note to self: if swapping artboards, don't break it down to layers and see if just swapping the artboard locations is faster.

**Comment by mcilroyc** [comment]
@chadrolfs FBNC via the above PR.

**Comment by chadrolfs** [comment]
Still slow.  (on mac) using dev build 586, master @ 312f909b.
` Finished action transform.swapLayersCurrentDocument in 6528ms with RTT 6533ms; 1/1`

**Comment by volfied** [comment]
At this point we're sending 5 commands to PS in total, so something in PS is slowing down. Sent a profile report to Jesper to see how we can make it fast on native side.

**Comment by chadrolfs** [comment]
now 159ms to 249ms.  So much better, thank you!
