### ISSUE TITLE
Sampler HUD fails to apply stroke to Type

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2234]
Create a Type and Shape layer
select the Type layer
(with Sampler) mouse over Shape, hit Space and click on Stroke

Result: `Action sampler.applyColor failed: TypeError: undefined is not a function`

**Comment by chadrolfs** [comment]
happens somewhat intermittently under specific circumstances.  Sent you video via slack

**Comment by chadrolfs** [comment]
apparently has to do with where you click on the stroke icon in the hud.  
when you hit it, you see applyColor
when you don’t you see applyStroke

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
