### ISSUE TITLE
UI font and icon sizes seem a bit too large on the Surface Pro 3 screen

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2235]
Is this by design?

![screenshot 4](https://cloud.githubusercontent.com/assets/2029597/9508952/554a0fd2-4c0f-11e5-8e4d-03b7b70ee667.png)

**Comment by chadrolfs** [comment]
This might be the same as #1345 (old bug)

**Comment by placegraphichere** [comment]
Maybe we can squash this with some of work on the "columns are too wide" work after the properties panel redesign?

**Comment by chadrolfs** [comment]
Try setting standard PS Pref > Interface from Auto to 100%.

**Comment by ktaki** [comment]
You need to have super good eyes to work with UI scaling 100% on Surface Pro 3. This cannot be a solution obviously.

**Comment by chadrolfs** [comment]
:eyes: :mag:

**Comment by iwehrman** [comment]
@ktaki: as of CL 1046822 (Windows pgdev.718) I believe this is fixed. The change may have adjusted the UI size on other Windows systems which have hi-dpi displays. However, I think the sizes on those displays should also now be "correct", in that they should be the same as on retina Macs. Back to you to verify the UI size on an SP3 and on any other hi-dpi Windows systems you can find. (I think @jfitz-adobe has a 4k display, for example.)

**Comment by ktaki** [comment]
It looks good on SP3.

**Comment by ktaki** [comment]
Will do further testing with hi-dpi Windows systems. At least it works with SP3 that is the original issue reported in this issue. Removing Fix Now label.

**Comment by ktaki** [comment]
John F. tested it on his 4K monitor and reported "OK". Will add a task to my task list to check it with other systems, and closing this issue.
