### ISSUE TITLE
Action modules should only export actions

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#2239]
Related to 8/27 parking lot discussion. We want all constants to be declared somewhere else, and all helper functions to be in correct modules.

**Comment by iwehrman** [comment]
I guess I'm not really sure I agree with this issue. It doesn't seem like a problem for these modules to export things other than actions. It mainly seems like a problem that we have a clean way to export actions as well as other things.

**Comment by iwehrman** [comment]
Distinguishing between exported actions and other objects is no longer a problem. I don't think this is a bug. Feel free to reopen + argue if you disagree, @volfied.
