### ISSUE TITLE
PS crash when creating guide

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2243]
1 - open the mt. hood_edit file in my transfer (under DesignSpaceBugs)
2 - zoom in a bit on the header
3 - position the header right under where you add guide
4 - click on blue area to create guide (really I accidentally created a guide - not sure if we should be able to create a guide by just clicking - rather than click and drag)
5 - scroll

RESULT - notice that PS is in a bad state - need to force restart I somewhat can't do anything

This image shows the add buttons scrolling in a strange way 

<img width="838" alt="screen shot 2015-08-27 at 2 07 18 pm" src="https://cloud.githubusercontent.com/assets/7904855/9533263/b7293c30-4cc5-11e5-8cd0-62619a988b5b.png">

**Comment by chadrolfs** [comment]
CNR with current resources (dev build 549)

**Comment by zoranagee** [comment]
Yeah, not happening in the latest 29 dot build that Chad gave me.

Z.
