### ISSUE TITLE
Fill and Stroke not shown after collapsing and expanding Style panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2244]
Create a shape and select it. Collapse and expand the style panel
Fill and stroke are not shown. Selecting another shape causes them to come back.

![screen shot 2015-08-27 at 2 26 51 pm](https://cloud.githubusercontent.com/assets/2029597/9533597/ec8b788c-4cc7-11e5-8dff-fdda238e7c69.png)

**Comment by designedbyscience** [comment]
This is addressed in my UI updates

**Comment by chadrolfs** [comment]
Looks fixed to me.

**Comment by ktaki** [comment]
Verified the fix.
