### ISSUE TITLE
Error applying style from CC lib after undo

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2248]
Create a shape layer
Apply a style, say, a drop shadow from the libraries panel
Undo
Apply the same style again from the libraries panel

![screen shot 2015-08-27 at 2 41 07 pm](https://cloud.githubusercontent.com/assets/2029597/9534983/da3703e0-4cd1-11e5-8a5b-c4bcd30831d0.png)

**Comment by chadrolfs** [comment]
@shaoshing you might need to work with the history king @mcilroyc on this.

**Comment by mcilroyc** [comment]
@shaoshing I recently did some history work w.r.t. exports, so this is somewhat fresh in my mind.  If you're stuck on this, or need history support, let me know.

**Comment by ktaki** [comment]
Verified the fix.
