### ISSUE TITLE
Ui loading appears to be in wrong order

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2250]
It appears as though libraries are loaded before the appearance panels like stroke and fill. We should try to have those panels load first and libraries last if possible,

**Comment by iwehrman** [comment]
I'm not exactly sure what this bug is about. Can you verify that this is still an issue, @placegraphichere and/or @chadrolfs?

**Comment by placegraphichere** [comment]
not an issue anymore
