### ISSUE TITLE
Color picker UI: sampling circles go outside sampling area

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2254]
![screen shot 2015-08-27 at 4 48 15 pm](https://cloud.githubusercontent.com/assets/8442631/9535925/54c6a116-4cdb-11e5-93cd-e17fa122a2b6.png)

**Comment by chadrolfs** [comment]
Re-assign to Eric if needed.

**Comment by iwehrman** [comment]
Or @placegraphichere.

**Comment by placegraphichere** [comment]
see #2478

**Comment by chadrolfs** [comment]
Hey, @placegraphichere when the PR that you reference is merged, please just re-assign the issue to the reporter with the label Fixed but not closed.  Thanks.

**Comment by mcilroyc** [comment]
one could argue that was my fault, as the PR merger.
