### ISSUE TITLE
Sampling multi-run text color has unexpected result

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2255]
Not sure what is expected.  Maybe this is as designed?  Colors swap.

https://www.dropbox.com/s/6di6bramif3whh8/sample-multirun-textcolor.mov?dl=0

**Comment by volfied** [comment]
Doesn't work with libraries/applyStyle as well.. seems like something changed with descriptors.

**Comment by volfied** [comment]
Also will fix the leading issue where text bunches up at the top...

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
