### ISSUE TITLE
Canceling type edit does not update style panel

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2257]
1. Create a text layer with multi-colored text.
2. Commit the text.
3. Click or double-click (depending on the tool) to begin editing the text. 
4. Place your selection in exactly one text-color run. Observe that color in the style panel.
5. Cancel the modal state with `cmd-.`.

Result: the style panel lists the same color.
Expected: the style panel lists "mixed".

**Comment by iwehrman** [comment]
Observed in #1936.

**Comment by iwehrman** [comment]
This bug is now blocked on core Watson issue 4045762.

**Comment by isonno** [comment]
Core watson bug 4045762 fixed in playground-dev branch

**Comment by iwehrman** [comment]
Thanks @isonno! FBNC to @chadrolfs.
