### ISSUE TITLE
Export "folder chooser" does not allow creation of New Folder

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2260]
When exporting, the user is prompted to choose a folder (via an OS dialog).  The dialog gives the open to create a new folder "on the fly", but strange and terrible things happen if you try this.  It may have something to do with keyboard focus wrt the sub-sub-sub-dialog that allows you to name the new folder.

**Comment by iwehrman** [comment]
@ktaki when you file this Watson bug, please mark it as high priority because this is probably something we need to fix for the mid-September internal release.

**Comment by ktaki** [comment]
https://watsonexp.corp.adobe.com/#bug=4047449

**Comment by ktaki** [comment]
As per the watson bug report, this issue will be fixed in JS.

**Comment by iwehrman** [comment]
Back to @ktaki for verification.

**Comment by ktaki** [comment]
The fix works on Mac, but Win has some issues.
In Choose Folder dialog on Windows, a folder named "New folder" is created under the currently selected folder. A customized folder name entered in the "Folder: [    ]" field is ignored. (You can change the name once it is created in the upper box in the dialog.) This behavior will result in the assets are generated under the folder named "New folder" inside of the folder selected when OK button is clicked in the Choose Folder dialog. The customized name entered is ignored.

**Comment by ktaki** [comment]
Well, sorry, user error. New folder is created with a name "New folder". User must rename it and select it. Make sure the name appear on the Folder: field at the bottom. Then click OK. It works, but not intuitive Windows UI.  :-(
