### ISSUE TITLE
Switching to DS fails with French locale

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2261]
Japanese and German work, but not French.

![screen shot 2015-08-28 at 11 00 07 am](https://cloud.githubusercontent.com/assets/2029597/9553482/3eb386d4-4d74-11e5-8870-40e1b5d19b7a.png)

**Comment by iwehrman** [comment]
I pushed small fix to master for this: 9b2df0fc094b414375c9ab3046af082d9af1efdf.

**Comment by ktaki** [comment]
Another bad key:
Action menu.beforeStartup failed: Error: Menu entry specifies unknown key code: ECHAP

**Comment by ktaki** [comment]
Verified the fix. Now switching to DS in French locale works.
