### ISSUE TITLE
Custom canvas color for artboards gets reset to default on swap

### ISSUE THREAD

**Issue by davealonzo** [adobe-photoshop/spaces-design#2263]
First, change matte background to a different color. Then, select 2 artboards and swap positions with the swap tool. Matte background color unexpectedly changes back to light color as a result of swapping. Should remain the same color as set by the user.

**Comment by iwehrman** [comment]
Hmm, I can't repro:
![swap](https://s3.amazonaws.com/f.cl.ly/items/133L26262C2Q1I25381J/Screen%20Recording%202015-08-28%20at%2011.52%20AM.gif)

**Comment by iwehrman** [comment]
Here's a video from @davealonzo:
http://cloud.wehrman.org/0p3j1S0K0V2I

**Comment by volfied** [comment]
I can't repro either. @davealonzo what build are you using? (switch to classic, Help>System Info..., entire first line)

**Comment by davealonzo** [comment]
@volfied Adobe Photoshop Version: 2015.1 20150828.pgdv.549 2015/08/28:11:18:47 x003  x64

**Comment by davealonzo** [comment]
It appears that this issue only occurs when you set the matte color to a custom color. The other default colors do not change after swapping.

**Comment by chadrolfs** [comment]
@volfied see if you can narrow this down and file a waston bug if needed.  thanks.

**Comment by volfied** [comment]
Found the core issue, contacted Artboards team about it.

**Comment by volfied** [comment]
Update: Tim Wright will take care of this in Cyan branch and I will integrate the change manually to our branch to test.

**Comment by volfied** [comment]
Once Cyan team's changes are in main->pg->pgdv, this bug should be fixed.

**Comment by volfied** [comment]
I believe ETA is September 30.

**Comment by chadrolfs** [comment]
@davealonzo can you confirm this is fixed in the latest mainline or playground builds?

**Comment by davealonzo** [comment]
@chadrolfs Looks good now, thanks!
