### ISSUE TITLE
Panel UI should have an inner border

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2264]
The right side of the toolbar and the left side of the properties panel should have the same dark grey border that is used to to separate the panel sections:

![image](https://cloud.githubusercontent.com/assets/1075154/9554579/b12291c2-4d7b-11e5-9b75-5d706008b1c6.png)

![image](https://cloud.githubusercontent.com/assets/1075154/9554582/b53d9716-4d7b-11e5-93d0-367d0451973a.png)

**Comment by iwehrman** [comment]
@placegraphichere: please assign back to @designedbyscience once your comps have been updated with this change, which we've discussed offline a few times.

**Comment by davealonzo** [comment]
@iwehrman I think this might be more of an issue of the matte bg color not matching the color of the dark grey borders separating the panel sections. They were designed to match.

**Comment by chadrolfs** [comment]
@iwehrman since both Dave and Seth are out, it doesn't look like this will get into M3/UIF unless someone else picks this up and runs with it.  

reviewed - probably not M3
