### ISSUE TITLE
No HTML panels if Design Space entered from Standard Photoshop while in modal state

### ISSUE THREAD

**Issue by tomwmcrae** [adobe-photoshop/spaces-design#2267]
1. In Standard Photoshop, enter a modal state. For example, edit a type layer or initiate a transform but do not commit.
2. Switch to Design Space via keyboard or menu.

Result: Design Space is entered, but only the canvas is seen. No HTML panels.

Workaround: Press <Esc> or return to Standard Photoshop.

Watson bug (Jesper wanted one): https://watsonexp.corp.adobe.com/#bug=4045558

Note: Bug is being logged in core Photoshop to disable switching to Design Space while in a modal state, but @iwehrman thought JavaScript side should do something. Hence this issue.

**Comment by tomwmcrae** [comment]
@ktaki points out that this happens too if you have a modal dialog up in Standard Photoshop and switch to Design Space. For example, do the following:
1. In Standard Photoshop choose "Help->System Info..."
2. Switch to Design Space via keyboard or menu.

**Comment by iwehrman** [comment]
Fixed by #2517.
