### ISSUE TITLE
Alignment icons missing a selected state

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2277]
The alignment icons are missing a selected state. Selected icons have class `split-button__item__selected`, but that doesn't seem to affect the style of the button.

**Comment by placegraphichere** [comment]
Was gonna say, you can assign to me

**Comment by iwehrman** [comment]
@placegraphichere I would still love your review of #2276!

**Comment by mcilroyc** [comment]
I merged this, but still worth @placegraphichere taking a look.

**Comment by iwehrman** [comment]
Fixed by #2276.
