### ISSUE TITLE
Choose your own adventure: pasting paths copied from Illustrator

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2282]
![image](https://cloud.githubusercontent.com/assets/1075154/9587522/d44b07e8-4fd7-11e5-8231-3628986bc673.png)
Four four four four bugs in one!

**Comment by placegraphichere** [comment]
does this need UX input? besides that blue type looking weird?

**Comment by iwehrman** [comment]
Well... It's not completely clear what this needs. We almost never want to show a dialog from standard in Design Space, but it seems like we might not have a choice here in the short term. So _if_ we're going to use this dialog, then this is primarily an engineering issue of how to make it work correctly. In particular, pasting paths seems to automagically create a vector mask on the selected layer? Alternatively, we might be able to suppress this dialog and use some default option from among the four possibilities. In that case, do you have a favorite?

**Comment by chadrolfs** [comment]
I think we should always paste as Shape Layer and suppress the dialog.

**Comment by placegraphichere** [comment]
I don't that there is a perfect default. It largely depends on what the user is doing. If I'm just copying a shape from Ai, then I probably want a shape layer. If it's more complicated, or includes imagery maybe I want a smart object. Or if I'm trying to keep my assets in from non-destructing, a SO would do. 

If I had to simplify the options, I'd want to choose between shape layer and smart object. But that doesn't really help remove the dialog completely.

**Comment by chadrolfs** [comment]
once you bring it in as a shape, you could create it as a library smart object.

**Comment by placegraphichere** [comment]
Problem with an only shape approach is that a shape layer will simply create a shape box where any images once were. So I don't think it's a good idea to default to something that yields quite different results. Here's a screen grab of before and after copying from Ai to Ps using just shape:
![shape-layer-paste](https://cloud.githubusercontent.com/assets/3229167/9595681/0e591cc0-502f-11e5-9f94-8539f77faa9f.png)

**Comment by chadrolfs** [comment]
Passing this to @shaoshing since he's been working with the place code.  What happens now is that the dialog is now suppressed and we paste as smart object but we can't commit the place.  User is essentially stuck.

Workaround: right-click on App is OS dock > Quit and then you get a Place dialog prompt.

**Comment by mcilroyc** [comment]
As of 2969, you can commit the placement with ENTER.  FBNC to @chadrolfs
