### ISSUE TITLE
Cannot display deeply nested groups in layers panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2286]
Practically, we only can support 6 levels plus artboard (total 7 levels of nested groups) currently.

![screen shot 2015-08-31 at 5 00 56 pm](https://cloud.githubusercontent.com/assets/2029597/9593353/2f871794-5002-11e5-8791-38a5023180bd.png)

In standard Ps,

![screen shot 2015-08-31 at 5 01 23 pm](https://cloud.githubusercontent.com/assets/2029597/9593360/3c280b48-5002-11e5-9958-bb35ad8c9667.png)

**Comment by placegraphichere** [comment]
see #2325 

![screen shot 2015-09-03 at 1 35 40 am](https://cloud.githubusercontent.com/assets/3229167/9651964/9648d784-51dc-11e5-955d-8aadfc796d7f.png)

**Comment by iwehrman** [comment]
@shaoshing In most cases, the filer of the original bug should be the one to verify fix and (hopefully) close the issue. FBNC to @ktaki.

**Comment by designedbyscience** [comment]
Also, wait a minute, this can't be correct:

![untitled-1___52_9___rectangle_2__rgb_8____](https://cloud.githubusercontent.com/assets/22372/9661452/c4eaacd8-5228-11e5-9fba-b4ae07aad6d2.png)

**Comment by ktaki** [comment]
@designedbyscience What was wrong with the picture you posted?

**Comment by shaoshing** [comment]
@ktaki the entire list is shifted to the left. my bad of not spotting that.

**Comment by designedbyscience** [comment]
Yea, not enough padding between border of container and left most icon. This is actually FBNC

**Comment by ktaki** [comment]
Got it. Verified the fix.

**Comment by ktaki** [comment]
@designedbyscience  Just to make sure. Since left padding was expanded, the deepest layer's name has been truncated. Is this acceptable?

![screen_shot_2015-04-23_at_11 16 50_am](https://cloud.githubusercontent.com/assets/2029597/9670862/95bd0fc6-5243-11e5-9bd3-db07f8027fe8.png)

**Comment by ktaki** [comment]
Retested with new UI. Closing this as fixed.
