### ISSUE TITLE
Info message for empty export and libraries should match visually

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2287]
![screen shot 2015-08-31 at 10 40 09 pm](https://cloud.githubusercontent.com/assets/3229167/9595829/4369fb58-5031-11e5-9119-aa555fc7eaa8.png)
![screen shot 2015-08-31 at 10 40 06 pm](https://cloud.githubusercontent.com/assets/3229167/9595828/43699d5c-5031-11e5-948f-d67e8216f107.png)

**Comment by iwehrman** [comment]
FBNC to @placegraphichere. I believe this message no longer appears in the panel at all.

**Comment by placegraphichere** [comment]
should be handled with #2323
