### ISSUE TITLE
Type datalist sometimes doesn't populate or expand

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2295]
Datalist doesn't populate.

**Comment by iwehrman** [comment]
WFM at f39ac6691e40bef6321a052c3ef4f3b83f755c8f with Mac pgdev.560. Anything in the console?

**Comment by iwehrman** [comment]
Also: can you `git bisect` it?

**Comment by volfied** [comment]
I don't see this either. Over to @chadrolfs to re-confirm.

**Comment by chadrolfs** [comment]
The cause is #2301.  When you get into this state, the datalist doesn't populate.  Otherwise, it functions correctly.

**Comment by chadrolfs** [comment]
I've been hitting this from time to time.  Not sure what the reliable repro case is.  Here's an instance I ran into it but repeating the steps didn't repro:
https://www.dropbox.com/s/equl4pg2c7dfhnc/Type-Commit-Datalist.mov?dl=0
could maybe related to #2313?  I dunno

**Comment by chadrolfs** [comment]
seems easier to repro on Win

**Comment by iwehrman** [comment]
Nothing in the console?

**Comment by ktaki** [comment]
No errors reported on console. With #2338, I placed the full log at:
smb://sjshare/photoshop/Transfer/ktaki/For_IanW/DevToolConsoleLog.zip

Repeating "Enqueuing/Executing/Finished action policy.addKeyboardPolicies" when I was trying to click on the menu. It looks like stuck in the editing of the font name whenever click on the typeface menu.

**Comment by iwehrman** [comment]
Here are some concrete repro steps:
1. Open this file from @zoranagee: http://cloud.wehrman.org/0T2e0d3m1k0u
2. Make sure the empty text layer is selected under Artboard 1 > Header > Text > ...
3. Edit the text layer. (I did so by double-clicking that layer's text icon).
4. Clicking the Typeface datalist does not open the the drop-down.

I also don't see anything on the console.

Also: I see the same behavior with the other text layers in that folder, so I don't think it has anything to do with the empty text layer in particular.

**Comment by volfied** [comment]
Question to all reproducers: Do you have font sync enabled?

**Comment by ktaki** [comment]
Font Sync? Yes.

In my case, it can be reproduced with the following steps.
1. New doc, select type tool, click on canvas, click on Tyepface menu. The menu appears. Commit edit.
2. New doc, select type tool, click on canvas, click on Tyepface menu. The menu does not appear.
I agree with Ian that this is not something do with with empty text layer.

**Comment by volfied** [comment]
I can repro with these steps, thank you.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
