### ISSUE TITLE
Changing UI layout caused Text tool and text selection to be dropped

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2297]
If you have Text layer in your doc, if you double-click on the layer, the Text tool is enabled and the text is selected (like in standard). If I do this, then open or close the Properties panel, the text selection is dropped and the Text tool is dropped, with the active tool becoming the Select tool.

It doesn't seem like opening/closing the UI panels should change tool/edit state.

1 - Using the Text tool, create a Text layer with some text (or open a doc with a text layer)
2 - Deselect all layers, switch to the Select tool if it isn't active. The Layers panel should be visible.
3 - Double click on the Text layer in the Layers panel, causing the active Tool to change to the Text tool, and to "select all" on the text
4 - Click the Properties panel show/hide button on the right.

Any changes to the text are committed, and the active tool switches to Select.

**Comment by volfied** [comment]
We set preferences to remember panel layout, and that is a `modal:true` action, which kills the modal state, which causes type tool to revert to select tool...

I wouldn't consider this a bug, we're being safe.

**Comment by ktaki** [comment]
Verified that opening/closing the UI panels no longer kill the modal state.
