### ISSUE TITLE
Request: modifer to swap between the two columns (only showing 1 column)

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2300]
Request: A modifier that allows me to swap between Layers or Style in the single-column panel. For example, if you have Layers only showing and you OPT or CMD click on Effects button, it will swap out Layers with the Effects panel - keeping 1-column view without have to to stack and unstack. Currently to do this you have to stack and collapse.

Also keeps my canvas area free and open - this is one of the underlying themes of DS that we can't overlook - UI only when you need it and your work - front and center taking up prime real estate (not all the UI).

This also affects videos that we (and 3rd parties) create as they are typically done on our MBP with a camera over our shoulders. UI is overwhelming.

**Comment by zoranagee** [comment]
@placegraphichere what do you think of this interaction?

**Comment by chadrolfs** [comment]
moved to [wishlist](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist)
