### ISSUE TITLE
marquee select flag not set correctly: highlights not shown (Sampler, HUD, etc)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2301]

**Comment by chadrolfs** [comment]
Gets you into a bad state where bad things happen (like the type datalist getting hosted).

**Comment by volfied** [comment]
I don't see the typeface datalist being broken, even when I repro this bug.

**Comment by chadrolfs** [comment]
I can't either with updated jenkins build and master

**Comment by chadrolfs** [comment]
although I just repro'd in a different scenario.  I'm not sure what the reliable repro case is.
