### ISSUE TITLE
Undo shortcut does not work after HUD Sampling

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2304]
Menu command works
Undo shortcut work when sampling without HUD

**Comment by volfied** [comment]
Looks like a core bug, because we're not even getting the menu event from adapter... and it starts working again if you click the canvas.

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4048288

**Comment by chadrolfs** [comment]
Thanks for logging that watson bug @volfied

**Comment by volfied** [comment]
@chadrolfs This bug was bounced back to us as cannot reproduce on Windows. They think one of the other fixes took care of it, can you confirm?
