### ISSUE TITLE
Tab order is incorrect in Type edit mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2307]
Tabbing through Type fields while in edit mode skips fields
(check also Shift + Tab)

**Comment by chadrolfs** [comment]
with new UI, pgdev build 619, master @ 5eb07a3, on Win Set Letterspacing is skipped in tab order

**Comment by iwehrman** [comment]
Is this Win only? I can't repro on Mac. CNR back to @chadrolfs for now.

**Comment by chadrolfs** [comment]
yup, sry, win only

**Comment by iwehrman** [comment]
I can repro, but it _only_ happens in modal tool state. It just seems like CEF isn't getting the tab event at all. Which is to say, this is another core focus bug for @jfitz-adobe.

**Comment by iwehrman** [comment]
[Watson 4078019](https://watsonexp.corp.adobe.com/#bug=4078019)

**Comment by iwehrman** [comment]
@jfitz-adobe reports this as ToTest as of CL 1049774. FBNC to @chadrolfs!
