### ISSUE TITLE
Having trouble drilling down to select layers using Select in VermilionArtboards.psd

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2311]
Testing with VermilionArtboards.psd, I found that I could not "drill down" into visible layers of the document where in standard mode with Auto-Select/Layer ON I had no trouble doing so.

1 - Open VermilionArtboard.psd
2 - Zoom in on the top portion of the "Desktop Large" artboard
3 - With the Select tool, try double-clicking on "QUEEN OF FLORA" (text, of text layer) or other nearby items.
I can keep repeating this, but selection seems to just jump between the "Search copy" folder and the "Header" folder (as if the selection type being set to Group instead of Layer?). However, I can drill all the way down to "Ellipse 1" shape if I keep double-clicking on the red filled circle near the middle of the "iPhone" artboard, so there must be something "special" about the elements at the top of "Desktop Large"

**Comment by iwehrman** [comment]
I think @volfied looked into this once and decided that it's because the structure of the VermilionArtboard PSD was weird.

**Comment by chadrolfs** [comment]
The way that file was built is totally annoying.  There are a lot of non-visible grid layers and group copies that get in the way of the actual content.  I usually delete the “grid” and “Search”/“Search copy” layer groups.

**Comment by volfied** [comment]
Also, Vermillion has clipping mask layers, which we don't support. And those are the reasons for a lot of the bounds not matching the visible part of layers.

**Comment by chadrolfs** [comment]
New changes abound.  Please retest and report results.  Thanks.

**Comment by ktaki** [comment]
This is no longer an issue. Drilling down to a leaf layer is successful. I, however, see an issue that the selected layer is sometimes not shown in the layers panel. I will report it separately. Closing this issue.

**Comment by ktaki** [comment]
Opened an issue
https://github.com/adobe-photoshop/spaces-design/issues/3746
