### ISSUE TITLE
CC Libraries panel scroll position changes with active document

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2312]
To reproduce:

1. Create a new document, reveal the Libraries panel, scroll it to the bottom.
2. Create a new document. Observe that the Libraries panel has jumped back to the top.

This is because we're keeping N copies of the Libraries panel in the DOM, just like all the other panels. This makes a lot more sense for the other panels, but not for the Libraries panel because it is not document-specific. Potential workarounds:

1. Just save the last scroll position and set it when switching documents.
2. Create just one Libraries panel at the `PanelSet` level and pass it as a prop to child `Document`-specific `Panel` instances.

**Comment by designedbyscience** [comment]
Fixed by 2486

**Comment by iwehrman** [comment]
Fixed by #2486, indeed.
