### ISSUE TITLE
CC Libraries: Contextual "Add" bar inconsistent show/hide/enable/disable

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2314]
There are 2 different sets of states for the icon buttons.  The first 3 (Add Graphic, Add Character Style, Add Layer Style) have enable/disable state.  The others (Add Fill Color, Add Stroke Color, Add Text Color) are contextual show/hide.  

Shouldn't we be consistent here?

**Comment by placegraphichere** [comment]
We're following behavior in Standard Ps Library panels on this. I'm not sure this is an issue unless the Lib team wanted to change the interaction pattern on this, or we really felt strongly this needed to be changed (or improved in some way) for Ds.

The only difference from Standard to Ds is that in Standard they show the foreground color swatch at all times. However, in Ds we do not have a foreground color swatch.

I would suggest closing with As-Designed.
