### ISSUE TITLE
Export options not saved with newly created document

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2320]
Create a new document. Add a shape. Add export options. Try export to make sure it works. Save the doc as Ps doc with any name. Close it, and re-open it.
RESULT: Export options are gone.

Note that export options set in existing docs are retained as expected.

**Comment by mcilroyc** [comment]
This is a weird bug.  I can confirm that photoshop reports the correct extension data prior to saving.  But after saving and re-opening, it does appear to be missing from photoshop.  This *could* be core related, but I'll continue to try and pare it down.

**Comment by ktaki** [comment]
This is still reproducible.

**Comment by mcilroyc** [comment]
I'll create a watson bug for this

**Comment by mcilroyc** [comment]
https://watsonexp.corp.adobe.com/#bug=4058934

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4058934 closed
playground/...@1043475
