### ISSUE TITLE
Placeholder text in libraries panel feels too real

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2336]
placeholder text is too bright and shiny, it feels like I can just click "create" and the lib will be named that. Need to change it so it feel more placeholder-like

**Comment by iwehrman** [comment]
Surely this is fixed now, @placegraphichere?

**Comment by iwehrman** [comment]
I'm declaring this fixed since @placegraphichere ain't readin' his email.
