### ISSUE TITLE
Typeface flyout menu does not open

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2338]
This is intermittent. Open a new doc. Select type tool  and click on canvas. Type something and commit. Go to type panel, click on the down arrow for Typeface menu. 
RESULT: the flyout menu does not open
Once get into this, DS needs to be reset to make the menu work again.

**Comment by iwehrman** [comment]
Can you report the full console log when this happens?

**Comment by ktaki** [comment]
smb://sjshare/photoshop/Transfer/ktaki/For_IanW/DevToolConsoleLog.zip

It was fairly easy to reproduce it this time. No errors have been reported on console. Repeating "Enqueuing/Executing/Finished action policy.addKeyboardPolicies" when I was trying to click on the menu. It looks like stuck in the editing of the font name whenever click on the typeface menu.

**Comment by chadrolfs** [comment]
dupe of #2295 but this additional info is helpful.  thanks @ktaki

**Comment by ktaki** [comment]
Closing as a dupe of #2295.
