### ISSUE TITLE
text reflows multiple times when in modal state

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#2344]
Steps:
Create a text block. 
Use text tool to enter modal text state
use the alignment buttons to realign the text 

observe two separate reflows happening. 

this only happens in a modal state

**Comment by ktaki** [comment]
This seems to be a core issue. Standard Ps behaves the same.

**Comment by pineapplespatula** [comment]
is there a core bug logged? should we delete this as a dupe?

**Comment by ktaki** [comment]
I don't recall this has ever been reported. I can check. I can repro it with shipping 16.0.1. It does not happen with 15.2.

**Comment by ktaki** [comment]
Opened a watson bug. Communicated to Vinod and David M.
https://watsonexp.corp.adobe.com/#bug=4049956

**Comment by ktaki** [comment]
@pineapplespatula May be we can close this issue now?

**Comment by chadrolfs** [comment]
Waston bug is against Staging currently (so not 16.1), moving this to M4

**Comment by ktaki** [comment]
@chadrolfs This is a pure core issue and considered to be a minor issue. We can close this issue in our side now.
