### ISSUE TITLE
Clicks in the layers panel when there's a shape underneath - requires two clicks to select layer

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2354]
The first click is handled by the underlying transform handle?
http://cl.ly/1M0p2s1s2z37

**Comment by volfied** [comment]
Is there a policy underneath?

**Comment by iwehrman** [comment]
Yes, I think that is what is happening...
![policy](https://s3.amazonaws.com/f.cl.ly/items/1n1L2o2i1Q2P3S1s3z1Y/Screen%20Recording%202015-09-08%20at%2010.58%20AM.gif)
