### ISSUE TITLE
radius slider is not updated after a multi-selection update.

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2358]
The position of the slider is not update, although the value is correct.

![ui-radius](https://cloud.githubusercontent.com/assets/118264/9745299/b97234c4-5625-11e5-913f-c0c48ecf00da.gif)

**Comment by iwehrman** [comment]
This is as designed. The max value for the slider range is based on the side length of the shape, so a bigger shape will have a bigger range, which means the slider will be further to the left. Life is good!
