### ISSUE TITLE
Create an unsupported layer effect in PS and then try to sample from it in DS

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2361]
1 - file new in PS
2 - create two rectangles; A - leave as is; B - with an overlay fx (change the color with the overlay fx)
3 - jump into DS
4 - select A and then pick up sample tool
5 - hover over B and click <spacebar>
6 - select fx

RESULT: nothing (we don't support overlays yet so we need to either support it ;), or handle it differently); maybe we shouldn't even show 'fx' if it's an unsupported fx.

**Comment by volfied** [comment]
What if there are shadows as well in that layer? I need UI input on this. @placegraphichere

**Comment by chadrolfs** [comment]
Totally rad, it works with Shao's new layer effects support.
