### ISSUE TITLE
Choose Folder dialog gets stuck behind Export dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2363]
Widows only. When Choose Folder dialog is moved on to the Export dialog, and the Exprot dialog is clicked accidentally, the Choose Folder dialog is placed behind the Export dialog.  Nothing you can do at this point other than killing Ps.

**Comment by ktaki** [comment]
This also happens when the Choose Folder dialog is got into behind the panels.

**Comment by ktaki** [comment]
https://watsonexp.corp.adobe.com/#bug=4052784

**Comment by mcilroyc** [comment]
I believe this is fixed as well, via watson  @ktaki

**Comment by ktaki** [comment]
Verified the fix.
