### ISSUE TITLE
Align type layers doesn't seem to align properly

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2364]
Create 5 different type layers and then select them all and Align Left (hit the button in the Styles Panel) (I created "FOOD, HIKING, CAMPING, BIKING and WATER")

Notice that the type layers don't seem to be left aligned (I dragged out a ruler to verify).

Jump into PS and select the same 5 layers and align left via Layer>Align>Left - layers get aligned

RESULT: I would expect Align left to line up all of those 5 layers to the left (and aligning them in PS and DS should result in the same perfectly aligned layers)

![screen shot 2015-09-08 at 2 27 40 pm](https://cloud.githubusercontent.com/assets/7904855/9747929/cdf72552-5635-11e5-85bf-619197e4a1a8.png)

**Comment by chadrolfs** [comment]
Please verify if behavior is the same in PS.  If they are the same, then Watson bug is needed.

**Comment by zoranagee** [comment]
It's not the same. PS does what I'd expect.

**Comment by ktaki** [comment]
Tested with a test file provided from Zorana. It seems working fine for me. Contacted Zorana.

**Comment by zoranagee** [comment]
Yup, seems to be working now in my sprint 30 build.

Z.

**Comment by ktaki** [comment]
OK. Thanks @zoranagee.
