### ISSUE TITLE
Select tool failed with error: Command is only a supported modifier on Mac

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2365]
Create a new doc. Create a rectangle. Select Select tool. Click on the rectangle.

![toolselectfailed](https://cloud.githubusercontent.com/assets/2029597/9748658/2a3211ec-563b-11e5-98a5-202488f8ffd0.png)

**Comment by ktaki** [comment]
I wonder if this is a side effect of the fix for #2168. So, assigning to @mcilroyc.

**Comment by volfied** [comment]
#2357 fixed this already

**Comment by ktaki** [comment]
It was fixed before I submitted the issue!!
