### ISSUE TITLE
Paste shape from Ai gives error, unable to continue in Ds

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2368]
- copy shape from Ai
- paste into Ds
- Choose "shape layer" from the options
- Ds freezes, quitting app is required 

![screen shot 2015-09-08 at 6 18 16 pm](https://cloud.githubusercontent.com/assets/3229167/9749787/0504645e-5656-11e5-8562-f5757049f273.png)

**Comment by iwehrman** [comment]
This seems to be something other than just a JS programming error. When I execute this:
```javascript
_spaces.ps.descriptor.get({_ref: "layer", _enum: "ordinal", _value: "targetEnum"}, {}, console.log.bind(console))
```

I get this:
```
"CActionControl::Get failed with error: -1 msg: error: -1 message: Could not complete your request because of a program error."
```
But, from standard PS, it just looks like a regular shape layer.

**Comment by volfied** [comment]
I can repro Ian's error. Looking into this now.

**Comment by volfied** [comment]
Well, PS is loading all the expected properties correctly, however, during RecordCommand, we get an error. I've opened a Watson bug.

https://watsonexp.corp.adobe.com/#bug=4065431

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4070186

**Comment by iwehrman** [comment]
[DECISION] Pasting AI objects will default to "smart object"

**Comment by tiburbage** [comment]
Note original John Peterson checked in a change related to a specific aspect of the "paste AI vector shape from the clipboard" issues: https://watsonexp.corp.adobe.com/#bug=4065431 and this bug has been closed.

**Comment by shaoshing** [comment]
Close (duplicate with #2282, and issue is fixed)
