### ISSUE TITLE
The Choose Folder dialog unresponsive when superselect tool is selected

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2369]
Create a doc with a shape layer and set export option, select superselect tool, and do Cmd-E or Ctrl-E.
Click Export. The Choose Folder dialog appears, but it is not responsive to any mouse click. Only an exception is the dismiss button "X" at the to right corner. If you move the dialog to outside of the application window, it will respond to mouse click. Windows only.

**Comment by mcilroyc** [comment]
My hunch is that this is the same root cause as #2363   - did I hear you volunteer to create a watson issue for this/these?  Or shall I? @ktaki

**Comment by ktaki** [comment]
I opened https://watsonexp.corp.adobe.com/#bug=4052784 for #2363.

**Comment by ktaki** [comment]
The watson bug 4052784 has been fixed. According to Jesper, this should be fixed by javascript disabling policies around showing the export dialog. @mcilroyc

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
