### ISSUE TITLE
Export "+" and other icons are visible but non-functional when panel is collapsed

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2371]
needs design input, but it's an issue

**Comment by iwehrman** [comment]
Thus buttons probably just need a disabled state.

**Comment by mcilroyc** [comment]
fyi, disabled state is now working (on my branch), and I will set these to be disabled if collapsed.  good start?

**Comment by placegraphichere** [comment]
I think that's a great start. I think at the end of the day, it'd be best to open the panel and "do" the action clicked. Lets close when your branch lands @mcilroyc?

**Comment by mcilroyc** [comment]
@placegraphichere  take a look at my branch `mcilroy/export-dbl-click-header` (the above-referenced PR).  This uses your "end of the day" suggestion of expanding the panel upon button click.

Alternately, for comparison, the first commit in that branch ( `git checkout HEAD~1` ) has it the simpler way: buttons are disabled when collapsed.

**Comment by iwehrman** [comment]
Over to @ktaki for verification.

**Comment by ktaki** [comment]
Verified expanding the panel upon button click. Clicking export button adds an asset if none added and opens folder chooser. Good!
