### ISSUE TITLE
Opening a very large file throws an exception

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2375]
open image found at https://www.dropbox.com/sh/h9zbex06an7s8nv/AACLTiX9CGJqXC4_FPRcSfWna?dl=0
RESULT:
Unrecoverable error: Error: Unexpected paragraph alignment value: justifyLeft

**Comment by chadrolfs** [comment]
You don't need to download the big doc to repro.  Here are steps:
new doc in classic PS
select Type tool and click-drag to create a text/paragraph box
populate it with text, select all the text
open the paragraph panel (Window > Paragraph), click on the Justify last left icon
press numPad enter to commit the text
enter DS

**Comment by chadrolfs** [comment]
When fixing, make sure all paragraph settings are handled (justify, hyphenation, etc)

**Comment by volfied** [comment]
Back over to @chadrolfs
