### ISSUE TITLE
search bar (cmd+f) error in console

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2378]
<img width="1243" alt="screen shot 2015-09-09 at 4 11 42 pm" src="https://cloud.githubusercontent.com/assets/3229167/9774357/93a81ea0-570d-11e5-991f-4f0c07c21b59.png">

**Comment by volfied** [comment]
What are the steps to reproduce @placegraphichere ?

**Comment by chadrolfs** [comment]
CNR with latest resources.  @placegraphichere can you still repro this?  If not, please close.

**Comment by chadrolfs** [comment]
same as #2505
