### ISSUE TITLE
Export through dialog fails when no layer is selected in the layers panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2379]
document+suffix.ext fails to be generated by going trough the export dialog (File->Export). Clicking an shortcut icon (down arrow and under score) does work.

**Comment by mcilroyc** [comment]
@ktaki  When you say "fails" to do you mean that you see some error or reset occurring?  Or just that the document-level export is not created?  If the latter, that is not currently supported.  (to wit: the only way to get a document-level asset is by using the export panel).

**Comment by ktaki** [comment]
Yes, I meant the latter. Thanks for the clarification.
