### ISSUE TITLE
Fatal error when Settings was edited with keyboard

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2381]
In the Export panel, clicks on Settings field (ex. PNG) and enter "tif" from keyboard.
Fatal error will result and DS needs to be reset.

![screen shot 2015-09-09 at 5 15 48 pm](https://cloud.githubusercontent.com/assets/2029597/9777324/b989ad82-5717-11e5-81ab-2332dca4e9a4.png)

**Comment by mcilroyc** [comment]
I can't repro this on my current bleeding edge export branch (still in PR #2374) - so I'll check back after that.

**Comment by mcilroyc** [comment]
This seems to have been fixed by #2374 - back to @ktaki to confirm

**Comment by ktaki** [comment]
This is no longer happening.
