### ISSUE TITLE
Error when setting stroke color for an empty layer or artboard

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2382]
Create a new artboard. With layer 1 selected, click on a box for setting stroke color and select a color.

![screen shot 2015-09-09 at 5 35 18 pm](https://cloud.githubusercontent.com/assets/2029597/9777450/7b68d152-5719-11e5-816a-a611ba9001b1.png)

The same error happens when an artboard (with some shape layers) is selected and stroke color is set.

**Comment by mcilroyc** [comment]
note: I think the desc should read "Create a new artboard *document* ..."
indeed it seems that for "empty" layers such as the placeholder dummy layer, the stroke buttons (inner, outer...) should be disabled.

**Comment by volfied** [comment]
Will fix this as part of my color picker work.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix. No color setting is allowed.
