### ISSUE TITLE
Opening a large file with many text layer takes a really long time: Update All Text Layers

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2389]
Open Vermillion

Result:
https://www.dropbox.com/s/tkeq2u1acol8hxv/updatingTextLayers4evs.mov?dl=0

![screen shot 2015-09-10 at 12 20 26 pm](https://cloud.githubusercontent.com/assets/8442631/9798706/948ab378-57b7-11e5-87aa-5b702c87be27.png)

**Comment by chadrolfs** [comment]
In classic PS, file opens relatively quickly and then provides a dialog prompt:
![screen shot 2015-09-10 at 12 33 06 pm](https://cloud.githubusercontent.com/assets/8442631/9798782/215d0620-57b8-11e5-89b1-898a6bd9a1c4.png)

Clicking update in classic takes just as long.  Ugh!

**Comment by iwehrman** [comment]
Should we re-think suppressing this dialog? @placegraphichere: is there a reasonable default? Or should the user decide each time?

**Comment by chadrolfs** [comment]
Options: suppress dialog and select No, Don't suppress the dialog, or keep current (suppress and update)

**Comment by iwehrman** [comment]
Re-assigning to @chadrolfs to create a new Watson bug, assigned to @jsbache, with the following request:

1. Change the behavior of the suppressed dialog on document open from "Update" to "No"
2. Make sure the dialog that is shown when you first select a layer with type that needs to be updated is suppressed with the default value of "OK, go ahead and update it".
3. If one of those doesn't make sense for some reason, please talk to Ian about it. 

@placegraphichere: If you disagree, now's the time to speak up!

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4066260

**Comment by iwehrman** [comment]
In theory this is FBNC via @dtristram. Over to @chadrolfs to verify.
