### ISSUE TITLE
If the user elects to have ESC cancel input, pressing ESC after editing text causes text layer to disappear from Layers panel

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2393]
If via Preferences > Type the user elects to have ESC cancel text edits (also set when a user uses the Text tool for the first time), pressing ESC after initiating a text edit causes the Text layer to disappear from the Layers panel. The data's not lost, just the layer display.

1 - In standard, Preference > Type > Use ESC key to commit text = UNCHECKED
2 - In DS, use the Text tool to create some text, use Fn+ENTER to complete
3 - Click in the text again and make some edit
4 - ESC
Layer disappears from LAYERS panel

**Comment by ktaki** [comment]
To retrieve the layer disappeared in the layers panel, click on the text layer on cnavas with the type tool, then hit Esc.

**Comment by volfied** [comment]
Happening due to Phosotop sending us deleteTextLayer events at all cancels, and not only when an initial edit is cancelled. Opening Watson bug.

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4054650

**Comment by isonno** [comment]
Fixed checked into `playground-dev` branch, CL 1041943

**Comment by volfied** [comment]
@chadrolfs please confirm with latest Jenkins pdgev build.Thanks @isonno !

**Comment by ktaki** [comment]
Verified the fix on Mac. Waiting for Windows build.

**Comment by ktaki** [comment]
Verified the fix on Windows.
