### ISSUE TITLE
Clear Guides with no guides results in TypeError: undefined is not a function

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2394]
cmd/ctrl + n
View > Clear Guides

`Action guides.clearGuides failed: TypeError: undefined is not a function`

**Comment by chadrolfs** [comment]
If there are guides in the doc, there will be a bunch of subsequent errors like:
`Action tools.beforeStartup failed: Error: Unknown policy ID: 1`

**Comment by volfied** [comment]
Can't repro with 606, latest master.

**Comment by chadrolfs** [comment]
me either, closing.
