### ISSUE TITLE
DS is not updating its view transform after a Hip transform pan or zoom gesture

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2396]
See Watson https://watsonexp.corp.adobe.com/#bug=4053853
The view coordinate space for Design Space is not updated to account for direct touch pan, zoom, and rotate transforms

I logged this against Spaces/core, but Jesper has requested feedback from the JS side.
(Win only, Surface or other touch enabled device only)

**Comment by iwehrman** [comment]
We can't support rotation in the short term. Otherwise, we should be getting scroll events from the adapter with the updated window transform that we need. So, the request is: 1) suppress rotation, somehow; and 2) send scroll events for pan and zoom transforms.

**Comment by tiburbage** [comment]
Closing: this issue was actually just a symptom of a larger problem where the Design Space context was getting invalidated. Problems entirely on the Spaces/C++ side.
