### ISSUE TITLE
When Export Dialog is open, hovering over the guides area still works 

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2399]
![Guides active when export dialog open](https://www.dropbox.com/s/uc2lgsdjxg9cznr/guides_active_dialog.gif?raw=1)

**Comment by mcilroyc** [comment]
Dup of #2138, or at least closely related.

**Comment by mcilroyc** [comment]
assigning this to @DivyaPrabhakar for a discount double check

**Comment by DivyaPrabhakar** [comment]
Looks good on my end
