### ISSUE TITLE
Export dialog remains open when new file dragged into PS 

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2400]
![Exports dialog still open](https://www.dropbox.com/s/ebd1tfvvp4zd839/exports_still_open.gif?raw=1)

**Comment by mcilroyc** [comment]
I refute this being high priority, but I guess I wasn't at the meeting, so...

**Comment by mcilroyc** [comment]
@ktaki if you run in to issues when verifying this fix, please make sure it is not caused by this separate issue: #2563

**Comment by ktaki** [comment]
Verified the fix.
