### ISSUE TITLE
Export header icons are misaligned vertically

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2401]
![image](https://cloud.githubusercontent.com/assets/1075154/9819028/6eb8f7a0-5860-11e5-8c35-cd1bdc36fff1.png)

**Comment by iwehrman** [comment]
@DivyaPrabhakar: this might be fresh in your mind.

CC @mcilroyc @placegraphichere.

**Comment by designedbyscience** [comment]
I think .layer-exports__workflow-buttons needs a height

**Comment by designedbyscience** [comment]
Fixed by #2386
