### ISSUE TITLE
Once a font at the top of the font menu is selected, subsequent changing of font becomes difficult

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2405]
Select a font at the top of the menu. Try select another font. Hovering a mouse over other fonts causes flickering the font name field between the font hovering and the font at the top of the menu. On Mac, it becomes nearly impossible to change the font selection. On Windows, it behaves the same way, but other fonts can be selected by careful positioning of the mouse.

**Comment by volfied** [comment]
Definitely related to https://github.com/adobe-photoshop/spaces-design/issues/2391, and probably related to my recent DataList changes.

I'm looking at it.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
