### ISSUE TITLE
CC Lib: newly added assets show up in (MRU) File > Open Recent >

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2414]

**Comment by shaoshing** [comment]
@volfied do you know if there is an option to ask PS to not put exported files in MRU? I read the CEP code and no luck on finding such option. The open-graphic-for-edit has the same issue that temp file is listed as MRU.

**Comment by shaoshing** [comment]
Assign to @volfied to look for option to skip or remove a file from the MRU list.

**Comment by volfied** [comment]
No possibility of this yet. Emailed Magenta team to ask if they had any plans to fix it on PS side so library graphic files don't show up in MRU list.

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4057744

**Comment by volfied** [comment]
Jesper and I chatted about this, eventually we'll be able to pass an option to open, to force External UI opened files to be added to MRU lists, and everything else will not be. So the fix will be not doing anything for library files, and passing "recordMRU" or some other flag for other open operations.

**Comment by volfied** [comment]
Jesper made the change in pgdv, I will make the changes in JS. This is a note to myself.

**Comment by shaoshing** [comment]
this fix require later dev build (659), @chadrolfs please verify.
