### ISSUE TITLE
Color picker solid-color swatch should be solid

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2416]
Instead of duplicating the outer context-specific swatch:
![swatch](https://s3.amazonaws.com/f.cl.ly/items/0d2K3k2J1y2s442U1V3a/Image%202015-09-11%20at%202.42.04%20PM.png)

**Comment by iwehrman** [comment]
The text input also is aligned and sized strangely. I also think we should ditch the swatch underline.

**Comment by iwehrman** [comment]
CC @placegraphichere @volfied.

**Comment by volfied** [comment]
Doh, I was passing the swatchOverlay directly.. maybe I shouldn't be :)

**Comment by iwehrman** [comment]
Fixed by #2419.
