### ISSUE TITLE
Esc in Color Picker, Type edit mode, commits Type before dismissing the Color Picker

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2417]
new doc
(t) for type tool, click on canvas and type multiple lines
select all the text
click in color picker field, type "red", hit enter to apply color change
hit Esc to exit color field edit mode, 
hit Esc again to dismiss Color Picker with the goal of adjusting Size next

Result: 2nd Esc commits the Type and leaves Color Picker open (you have to hit Esc a 3rd time to dismiss it)

Expect: The 2nd Esc should close the Color Picker.  The 3rd Esc should commit the type.

**Comment by chadrolfs** [comment]
This might be as designed.  Workaround is to simply click on the Color Picker swatch to close it.

**Comment by chadrolfs** [comment]
@placegraphichere may have an opinion on this.

**Comment by ktaki** [comment]
Here is how currently works. With color picker opened:
Mac: Esc: Color picker closes, Esc: Focus back to canvas, Esc: Commits Text
Win: Esc: Color picker closes, Focus back to canvas, and commits Text

So, here is a way works for both Mac and Windows if you continue typing after closing color picker.
Close the dialog by clicking fill icon, then hit Esc. Now focus is back to text layer and you can continue typing. Hit Esc to commit editing.

@chadrolfs I think you can close this bug as fixed.
