### ISSUE TITLE
Color picker text is small and misaligned

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2422]
![image](https://cloud.githubusercontent.com/assets/1075154/9827783/e96e49de-589a-11e5-9162-2b41faaf0fb1.png)

Input from @placegraphichere is required here, so assigning him first.

**Comment by placegraphichere** [comment]
this is progress on this:
<img width="323" alt="screen shot 2015-09-14 at 3 51 08 am" src="https://cloud.githubusercontent.com/assets/3229167/9856507/cd88a43e-5ada-11e5-91b6-b77ee3ce26bf.png">

**Comment by iwehrman** [comment]
Fixed by #2446.
