### ISSUE TITLE
Export dialog flickers while panning the canvas

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2424]
When the export dialog is open, the user can still move the canvas behind the dialog and this causes the dialog to flicker and only rest when the panning stops. 

![Export dialog flicker](https://www.dropbox.com/s/ohymkie6uw5npjp/export-flickers.gif?raw=1)

**Comment by iwehrman** [comment]
Nice catch!

**Comment by mcilroyc** [comment]
i hope you're both happy!  FBNC to @DivyaPrabhakar

**Comment by DivyaPrabhakar** [comment]
Verified on my end.
