### ISSUE TITLE
Libraries asset renaming interaction conflicts with secondary interactions

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2431]
If you single click the title of an asset, the title disappears and is replaced by the secondary-interaction buttons (delete, share, etc.). But you have to double-click the asset title to rename it, which is very confusing.  

My humble suggestion:

1. Move the icons to be right-aligned
2. Only show the icons when asset is selected.
3. When the icons are visible, truncate the asset name.
4. Double-click to rename the asset, just like in the layers panel.

CC @placegraphichere for confirmation.

**Comment by davealonzo** [comment]
This won't scale down the line when we add additional icons for duplicate, move to, and copy to, which is why I designed it this way.

**Comment by davealonzo** [comment]
We could just tooltip the title like this to indicate the double click action to rename.

![double_click_ttip](https://cloud.githubusercontent.com/assets/12259315/9829857/c014da40-58cb-11e5-9c76-8ec6bf942cfd.png)

**Comment by iwehrman** [comment]
I do not think putting instructions in a tooltip is a good solution. I also don't think we need to hobble the design due to concerns about having significantly more icons in the future. If the constraints change then the design can change, though I'm skeptical that having a large number of icons visible in the UI will ever end up being in line with the overall design philosophy of Design Space. In any case, I'm not sure how the design I've proposed fails to accommodate a few additional icons any less than in the current design.

**Comment by davealonzo** [comment]
It's not a hobble. It's accommodating for  the lack of a right click menu system on the same secondary level of interaction. I would also argue that it is more discoverable as a single click interaction compared to any right click exposure. Double click to rename a title is not too far fetched as well.

 It's also always good design practice to consider how things might scale out to accommodate more actions in the future, which the current design (as originally proposed) accomplishes.

My biggest concern is for longer strings like character styles in which there are two rows of metadata displayed per item. The asset title and style info will most likely truncate all the time since they are both usually pretty long strings if we add the icons on the same level. I would rather keep that metadata up front and center with out additional clutter and unnecessary truncation. The current library system in Ps also loads all of the metadata in "tooltips" if and when there is truncation. But I believe this was accounted for in a different bug.

I'm open to other solutions, but adding icons on the same level creates other issues for the reasons I've stated.

**Comment by iwehrman** [comment]
I'm certainly not arguing for a right-click. And double-click to rename is not the problem. The problem is that single click eliminates the opportunity to double click, which makes it hard to both discover and execute that operation. Putting metadata in the tooltips is fine, but I don't think most users will look to a tooltip for instructions on how to rename an asset. Note that I'm not advocating having the icons be visible all the time; I think it's great that they're only visible when selected. But moving them to the right and showing a possibly truncated title would still allow double-click to rename in the selected state. The fact that you can _only_ rename _unselected_ assets just does not seem tenable to me. I too am certainly open to other solutions, but as is I think it's just too obscure.

**Comment by davealonzo** [comment]
Ok Ian, I might have a reasonable solution for you. Get back shortly with a slight redesign.

**Comment by iwehrman** [comment]
Can't wait! :grin:

**Comment by davealonzo** [comment]
Here it is!
https://www.dropbox.com/sh/f4in5oeld9fw0y1/AADZArwaLsSqIATH6LlOZIsoa?dl=0

Hover state reveals the "Actions" icon – one icon to rule them all! Only single clicking on this icon reveals the rest, keeping this interaction from interfering with double clicking on the title to rename. Once the action icons are up in a selected state, a subsequent click outside any of the icons deselects the asset (like it does already).

Also, the actions icon would just remain up if the asset is selected in general.

Pros:
- Distinct hit areas that don't conflict with each other
- Improves discoverability of both interactions
- Minimizes truncation without cluttering up the normal state with more icons
- Scales for adding additional actions

I'll let you point out the cons ;-)

**Comment by iwehrman** [comment]
I like it! I agree with all your pros. The main con I think is the standard criticism of the :hamburger: menu, which is lack of discoverability, but a) I think those criticisms have a little more bite in the context of, say, a website in which you're relying on the user's understanding of a :hamburger: menu to buy something (i.e., they're very easily dissuaded), and b) even still, we're arguably moving in the right direction.

Here's one additional question, just to make things complicated (:grimacing:). Do you think it might be possible to show _two_ icons on the right, with one of them being whatever we think the single most important action is (delete?), and the other being the menu icon? If there were room for that, it would surely satisfy even more of our discoverability concerns. But, I realize horizontal space is limited and this might be impossible.

Thanks for arguing with me about this, @davealonzo!

**Comment by davealonzo** [comment]
@iwehrman I think we can make room for one more icon. Let me whip that up.

No worries on the critique, only makes things better :-)

**Comment by placegraphichere** [comment]
Here's my interim solution for this, I can have it be part of my library-tweaks PR. Dave is on board, waiting on your thoughts @iwehrman 

![libraries-select-hover-rename](https://cloud.githubusercontent.com/assets/3229167/9861292/ee2fea6e-5af6-11e5-83ed-1dcc58e44ad8.gif)

**Comment by iwehrman** [comment]
Fixed by #2429!
