### ISSUE TITLE
Mixed text is clipped in the appearance panel

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2436]
![image](https://cloud.githubusercontent.com/assets/1075154/9834127/3cd19e42-5962-11e5-8888-ad56984f59eb.png)

Sometimes I wonder if we should just eliminate the "mixed" string in favor of an empty (but enabled) input...

**Comment by designedbyscience** [comment]
This should have been addressed by my mixed PR

**Comment by iwehrman** [comment]
Fixed by @designedbyscience.
