### ISSUE TITLE
Mixed type styles with consistent family should show a family

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2437]
Currently mixed type styles with a consistent family show "mixed" in both the typeface and the type style datalist. Instead, the typeface datalist should use the _first_ typeface in the list to show its family name. The type style datalist should still show "mixed".

![mixed](https://s3.amazonaws.com/f.cl.ly/items/232z2O0n0t1E3P1x3f3C/Screen%20Recording%202015-09-12%20at%2003.26%20PM.gif)

**Comment by designedbyscience** [comment]
Came in on the mixed state PR

**Comment by iwehrman** [comment]
Nice! Fixed by @designedbyscience.
