### ISSUE TITLE
Infinite loop in Select binary search

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2438]
The relevant slice of state that results in the divergence is here: https://gist.github.com/iwehrman/d26909880ea138323ac1

The cause is #2408 commit a600cac719904490879cef085b37d8f3683d91d1.

**Comment by iwehrman** [comment]
This happened when typing in the typeface datalist, by the way.

**Comment by volfied** [comment]
Back to @iwehrman

**Comment by iwehrman** [comment]
Fixed by #2440, AFAICT.
