### ISSUE TITLE
No doc state shows doc title bar (and it's doesn't align with Recent Files divider)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2447]
this happened sometime between master pushed to P4 on Friday 9/11 and now.  84cd55642d1501cafdbb627f91382481337ec523  didn't show title bar in no doc state.
![ice_screenshot_20150914-105715](https://cloud.githubusercontent.com/assets/8442631/9857541/f5415c6a-5acf-11e5-868c-319a733f926f.png)

**Comment by iwehrman** [comment]
Showing document header in no-doc UI is intentional. We just need to tweak the Recent Files header so that, when it's empty, it has the right height.

**Comment by iwehrman** [comment]
CC @placegraphichere

**Comment by placegraphichere** [comment]
see #2476

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
