### ISSUE TITLE
Collapsed EFFECTS panel should expand when + icon is clicked and an effect is selected

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2448]

**Comment by iwehrman** [comment]
Also, it might be nice if the collapsed height were the same as the empty + expanded height? Basically, when empty, there should be no distinction between expanded and collapsed.

**Comment by designedbyscience** [comment]
@iwehrman I'm concerned about confusion over "Is this open or is it empty?" if the states are exactly the same

**Comment by iwehrman** [comment]
Mmm, yeah, you've got a point. Ok, I take it all back.

**Comment by designedbyscience** [comment]
(I originally did it how you proposed and got confused myself)

**Comment by chadrolfs** [comment]
reviewed - probably not M3

**Comment by ktaki** [comment]
This fails at every other try.
1. Collapse Effects panel
2. Click on '+' and select an effect
3. Effects panel expands, but collapses quickly.
4. Click on '+' and select an effect
5. This time, the effects panel expand and stay as expanded.

1 ~ 5 will repeat. So, if you do it again:
6. Collapse Effects panel again
7. Click on '+' and select an effect
8. Again, the effects panel expands, but collapses quickly.

**Comment by ktaki** [comment]
Verified the fix.
