### ISSUE TITLE
Unable to drag assets onto canvas.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2449]
New doc
drag a CC Lib asset onto canvas

Result:
`Action libraries.createLayerFromElement failed: Error: Can't find a usable representation for image element: Layer 27`

**Comment by chadrolfs** [comment]
![ice_screenshot_20150914-111454](https://cloud.githubusercontent.com/assets/8442631/9857798/a3701d48-5ad1-11e5-80a7-ae7d1cc1e419.png)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
