### ISSUE TITLE
Type: Esc to exit Typeface datalist results in policy error and bad state

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2454]
New doc
select Type tool, click on canvas and type
while still in edit mode, select all on canvas text you just typed
click in Typeface drop down to expand it
hit Esc twice

`Action policy.removeKeyboardPolicies failed: Error: Unknown policy ID: 11`

**Comment by iwehrman** [comment]
I've had a branch in the cooker for a while now that should address this. I was just waiting for @jfitz-adobe's focus changes to land. So, I'll have a look.

**Comment by ktaki** [comment]
Hasn't this been fixed with the #2472?
