### ISSUE TITLE
Appearance and Effects panels should remain even when no layers are selected

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2457]
![image](https://cloud.githubusercontent.com/assets/1075154/9859811/3069171c-5add-11e5-938e-45e7745879d3.png)

This is related to #2152. Not only should the export panel **not** change position based on layer selection, I think the other panels should remain in the UI, even when they're empty.

**Comment by designedbyscience** [comment]
I disagree with this, but I think a holistic pass needs to be made, design-wise

**Comment by chadrolfs** [comment]
reviewed - probably not M3

We would need fix in the next few days for UIF.  Out of time.

**Comment by DivyaPrabhakar** [comment]
Fixed by #3662
