### ISSUE TITLE
Attempting to add guides when AB is beneath highlight area moves the AB instead of creating guide

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2461]
cmd/ctrl + n
select and drag AB so that it is under the work area bounds
hover over area where guide creation highlight and AB over lap, click and try to drag out a guide

Result: AB is moved and a guide may be created.

**Comment by chadrolfs** [comment]
then subsequent attempts to add a guide either creates a guide below click area or fails to create one or moves the AB.

**Comment by chadrolfs** [comment]
https://www.dropbox.com/s/uexe1ifp92b1h2m/Guide-moveAB.mov?dl=0

**Comment by chadrolfs** [comment]
https://www.dropbox.com/s/uexe1ifp92b1h2m/Guide-moveAB.mov?dl=0

**Comment by mcilroyc** [comment]
to @chadrolfs
