### ISSUE TITLE
Blend modes datalist doesn't filter the full list

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2465]
drag out a rect shape
click in appearance blend mode datalist and type "Dis"
result: filters to Dissolve
Now type "Lum"
result: nothing is filtered even though Luminosity is in the list.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Well, I guess that's one way of fixing it.  :)
