### ISSUE TITLE
Export panel does not have a scroll bar

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2466]

**Comment by ktaki** [comment]
Can we fix this for MAX?

**Comment by DivyaPrabhakar** [comment]
@ktaki @mcilroyc I can take this. I would have fixed it in this: https://github.com/adobe-photoshop/spaces-design/issues/2152 but because of the time crunch, I talked to @ktaki and he said a PR for just the scrollbar is fine for now, so doing that now.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
