### ISSUE TITLE
With Export panel expanded, collapsed Effects panel cannot be expanded

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2468]
When Export panel is full (meaning that the contents reaches to the bottom), double clicking Effects panel header won't expand the Effects panel. You need to collapse Export panel first.

**Comment by ktaki** [comment]
It seems that the height of Export dialog depends on the contents of it. I think it should expand to a half of the Effects panel. The picture below shows when 2 assets exist in Export dialog and the dialog was clicked to expand.

![screen shot 2015-09-22 at 5 53 03 pm](https://cloud.githubusercontent.com/assets/2029597/10035784/d7ce4de4-6152-11e5-9de9-0a58dabb1771.png)

**Comment by placegraphichere** [comment]
see #2693

**Comment by ktaki** [comment]
Verified the fix.
