### ISSUE TITLE
Export spinner clipped

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2469]
In Export dialog, click Export. High res display only.

<img width="75" alt="screen shot 2015-09-14 at 3 16 16 pm" src="https://cloud.githubusercontent.com/assets/2029597/9863557/e2bf17dc-5af5-11e5-8009-17fb5be6b093.png">

**Comment by iwehrman** [comment]
Can whoever fixes this also make sure the same problem is fixed in the libraries panel?

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
