### ISSUE TITLE
Artboard title is not clean on non-retina low resolution displays

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2479]
![ab-non-retina-deselected](https://cloud.githubusercontent.com/assets/8442631/9881717/1c86673c-5b86-11e5-9777-5e3fbc931580.png)
![ab-non-retina-selected](https://cloud.githubusercontent.com/assets/8442631/9881716/1c7fe290-5b86-11e5-9102-22f6befe90e7.png)

**Comment by iwehrman** [comment]
This is a core issue, not a @designedbyscience bug. If you can provide repro steps, I suggest filing a Watson issue.

**Comment by chadrolfs** [comment]
@iwehrman I'm not sure it's a core issue b/c switching over to classic PS, the title looks fine/better than in DS.  

This is a dual monitor situation that I'm seeing this.  Monitor 1 is MPB/retina, monitor 2 is non-retina. Steps: move app to monitor 2, cmd + n

**Comment by iwehrman** [comment]
Still a core bug, but maybe assign to @jsbache.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4056811

**Comment by chadrolfs** [comment]
Not on us.  Watson bug is set to next rev so probably not M3

reviewed - not M3

**Comment by tiburbage** [comment]
I've closed Watson https://watsonexp.corp.adobe.com//#bug=4056811 at Jesper's request. I do think the display of some UI text, including Artboard titles, is blurry on a standard res display, but I couldn't see any connection between this and Spaces/Design Space: it appears to be a core font rendering issue.
