### ISSUE TITLE
Incorrect horizontal/vertical border widths

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2483]
This could be related to #2410: 
![image](https://cloud.githubusercontent.com/assets/1075154/9885280/306cc954-5b99-11e5-8ee4-289468b00d1b.png)

**Comment by chadrolfs** [comment]
Is this fixed now?  I'm not seeing this.

**Comment by iwehrman** [comment]
Fixed by @placegraphichere and/or @designedbyscience.
