### ISSUE TITLE
Dragging an asset off canvas bounds, nests incorrectly and doesn't expand canvas bounds leaving it unselectable

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2484]
cmd/ctrl + n
zoom out
drag an asset onto workarea well outside AB bound, hit enter to place
attempt to click and drag it

Result: you can't select it on canvas.  Classic PS updates correctly and you're able to select and move it.

https://www.dropbox.com/s/vi77lfc098l6hcw/asset-offcanvas.mov?dl=0

**Comment by chadrolfs** [comment]
@volfied can probably help here if not take this issue

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
This is still broken but may be a result of other issues that are in the way( #2522 #2523 ).  Sometimes it works, sometimes it doesn't.  For example it doesn't work with svg or illustrator assets.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
