### ISSUE TITLE
Double click export icons closes the export panel

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2485]
Double clicking the +, iOS, hdpi icons should not close the export panel.

**Comment by mcilroyc** [comment]
Is this on mac or windows?  CNR on my mac.

**Comment by placegraphichere** [comment]
you know, I bet I am clicking just to the left/right/top/bottom of the icons. This is not an issue, but maybe we should think about icon padding or something so it's not so easy to do.
