### ISSUE TITLE
superselect.click fails when 4x click on-canvas Type to edit

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2488]
new doc, create some text on canvas and commit it, 
make the Select tool active and quickly click on on-canvas Type 4+ times to enter edit mode and select all

Result:  enter a bad state, CC Lib panel flashes.  
`Action superselect.click failed: Error: Host is in a modal state and the request cannot be executed.    at eval (eval at undefined, <anonymous>:1:5)`

![screenshot_tue_sep_15_17 00 09](https://cloud.githubusercontent.com/assets/8442631/9893233/4ce2d308-5bcb-11e5-9f72-7be9040ca4db.png)

**Comment by volfied** [comment]
I can't repro this @chadrolfs I can see the same action queue as your picture, but don't get the error.
