### ISSUE TITLE
Focus is not coming back to canvas after changing color in the text editing mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2490]
Windows only. After or during changing the color of font with the color picker tool, you cannot continue typing. Closing the color picker, reopening it, and closing it again will regain the focus on the type layer on canvas. On Mac, you can continue typing while the color picker UI is open.

A comment by John F in https://watsonexp.corp.adobe.com/#bug=4051807

NotThisProduct

This looks to be a Javascript issue.
The JS font color picker will correctly invoke keyboardFocusAcquire / keyboardFocusRelease when it is click-activated "from the FontIconButton" and a color is selected. However, the JS font color picker also will remain persistently open in the DS UI until dismissed with another click on the FontIconButton. When the JS font color picker is in this "persistently open state", it fails to call keyboardFocusAcquire / keyboardFocusRelease which causes loss of focus issues described by Taki.

**Comment by volfied** [comment]
Bounced the bug back, we're not getting the identical set of events from the adapter. I don't see how this can be fixed on the JS side.

**Comment by volfied** [comment]
Passing to @tiburbage while it's being fixed on Watson side.

**Comment by iwehrman** [comment]
I don't think I understand the bug. I don't see anything out of the ordinary on Windows. If there is a subtle focus transfer problem, can you try to give very concrete repro steps? Also, are we sure this is still a high-priority bug?

**Comment by iwehrman** [comment]
Also, is this different from #2753?

**Comment by ktaki** [comment]
I can close this as fixed. #2753 remains as an issue.
