### ISSUE TITLE
Phantom line in the color picker above the swatch

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2493]
:ghost: 
![image](https://cloud.githubusercontent.com/assets/1075154/9914499/0c38f156-5c67-11e5-8a67-b1c43df61222.png)

**Comment by chadrolfs** [comment]
looks to be on retina only.

**Comment by iwehrman** [comment]
Also the triangle is slightly disconnected. 
![image](https://cloud.githubusercontent.com/assets/1075154/10325926/6d1ae716-6c4a-11e5-8d97-b1ffcae48023.png)

**Comment by iwehrman** [comment]
Fixed by #2853.
