### ISSUE TITLE
Creative Cloud Desktop installer kills Generator

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2496]
Here's what happens when I run the CC Desktop installer with Design Space running:
![image](https://cloud.githubusercontent.com/assets/1075154/9915843/3724e648-5c6e-11e5-8798-703f6ad50b9b.png)
![image](https://cloud.githubusercontent.com/assets/1075154/9915847/3b87dcea-5c6e-11e5-839a-4310e3747ddc.png)
Over to @chadrolfs to file a Watson issue (or whatever) with the CC Desktop team.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4058797
Bug Group Id: BG170941

**Comment by iwehrman** [comment]
I nudged the CC Desktop team again today.

**Comment by chadrolfs** [comment]
bug is marked fixed now, needs build.  Thanks for the nudge!
