### ISSUE TITLE
Mixed swatch overlay needs updated styling

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2501]
Here's what it looks like now:
![image](https://cloud.githubusercontent.com/assets/1075154/9919051/4f16c5a8-5c7f-11e5-8a0d-9cbb37a83edc.png)

But I think @placegraphichere's comps use an oblique gresh strike to denote mixed state:
![image](https://cloud.githubusercontent.com/assets/1075154/9919144/d7f7b184-5c7f-11e5-8bcb-efb0f212e4a2.png)

**Comment by designedbyscience** [comment]
This is covered by my in-progress PR

**Comment by designedbyscience** [comment]
Updated in my now merged PR

**Comment by iwehrman** [comment]
Fixed by @designedbyscience.
