### ISSUE TITLE
Cannot move shapes at the outside of artboard

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2509]
Create a new artboard doc. Add three rectangles. Rect 1, Rect 2, Rect 3.
Move the Rect 3 to outside of the artboard.
Move the Rect 1 and Rect 2 to outside of the artboard.
Try moving Rect 1 and Rect 2 to bring them back on to the artboard.
You cannot move the Rect 1 and Rect 2.
Now, you move the Rect 3 to artboard. This is successful.
Now, you can move the Rect 1 and Rect 2 to the artboard.
It seems that the first rectangle moved out from the artboard needs to be back to the artboard in order for other two to be freely moved.

**Comment by volfied** [comment]
In step 3, we're not counting for rect 1 and 2 being reordered out of the artboard.

**Comment by volfied** [comment]
@ktaki please re-test with 646 or later pgdv Mac Jenkins buids

**Comment by ktaki** [comment]
Verified the fix.
