### ISSUE TITLE
Unable to select Libraries datalist items; can't change libraries

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2512]
![screen shot 2015-09-17 at 1 54 49 pm](https://cloud.githubusercontent.com/assets/8442631/9945745/f632f8a6-5d43-11e5-8509-d51356c0847b.png)

**Comment by iwehrman** [comment]
It looks like somehow the blur handler of the text input inside the libraries datalist is executing before the select onClick handler can run...

**Comment by iwehrman** [comment]
Here's the cause from #2486: https://github.com/adobe-photoshop/spaces-design/commit/a6f60d9e0f9d15229ad83bd98be994a856155824#diff-2679935a0e56611617e48e9185145f97R696

Looking for a "good" solution to the original problem he found...

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs
