### ISSUE TITLE
Error on changing the color of font in editing mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2516]
With type tool, click on canvas and start typing. Click on the set color box to invoke color picker.
(pgDev Mac 648 and the latest master)

Action policy.addKeyboardPolicies failed: Error: Trying to add new policies but a cached state exists

![screen shot 2015-09-17 at 2 24 31 pm](https://cloud.githubusercontent.com/assets/2029597/9946465/471cb668-5d48-11e5-8e36-005508fa5a4b.png)

**Comment by pineapplespatula** [comment]
i backed out my text policy change, this bug should be gone for now... but i'm not sure what the longer term plan is for modal tool states and keyboard policy

**Comment by ktaki** [comment]
No longer happening.
