### ISSUE TITLE
Enter key does not work to place LLSO assets with tools other than Select

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2522]
select the Rect tool, drag out a Library asset onto canvas and hit Enter

Result: asset does not place
Workaround: double-click it or use Select tool instead

**Comment by shaoshing** [comment]
This seems to be working in dev 655

![issue-2522](https://cloud.githubusercontent.com/assets/118264/9968498/aeb83f3a-5dfd-11e5-9c04-a0f4f075d65d.gif)

**Comment by chadrolfs** [comment]
indeed it does
