### ISSUE TITLE
Textbox with missing font changes size when font is changed

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2525]
Text box is "Lust Script" and when changed to another font, the size will grow in height. 

![missing-font-changes-size](https://cloud.githubusercontent.com/assets/3229167/9950379/9494c67e-5d7f-11e5-9806-949ba32b2631.gif)

**Comment by chadrolfs** [comment]
`mixed` is suspect.

**Comment by ktaki** [comment]
This is as designed. Changing the font will display paragraph box. The initial box shown was transformation bounding box for a missing font. With missing font, you cannot edit the text. Changing the font to a font you have will allow you to edit the paragraph. Therefore, the paragraph box is shown.
