### ISSUE TITLE
Font menu sorted by captial letters first

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2530]
'a' should be with 'A' not after 'Z'.

**Comment by chadrolfs** [comment]
Should not be case sensitive sorted (like classic PS)

**Comment by chadrolfs** [comment]
marking M3 unless we run out of time or fix is too risky.

**Comment by iwehrman** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
