### ISSUE TITLE
Collapsing or expanding AB or group in layers panel should also select it (like PS) does

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2538]
This will help so you don’t end up with a layer selected that’s in a collapsed group/AB
related to #2192

**Comment by iwehrman** [comment]
Clicking the disclosure arrow does not change the selection state in standard PS, and that's how it works in Design Space too.

**Comment by iwehrman** [comment]
But, I agree that we should ensure that descendants of collapsed groups should not be selected.

**Comment by chadrolfs** [comment]
Hmmm, I'm not sure what you're seeing but in standard PS, if you click on the disclosure arrow for a group or AB in the layers panel it collapses and changes the selection to the group/AB.

**Comment by chadrolfs** [comment]
M3 if time.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
I was going to bounce this because with the test file from Zorana, i can still get into a state where this doesn't work but that's only because it was saved in that state from a previous build where this was broken.  You won't be able to get into this state with files created/saved from here forward (optimistically).

Brilliant!
