### ISSUE TITLE
Unable to open/edit some CC Lib assets

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2547]
Load shared library (Test - OK to accidentally nuke) 
drag long file name asset (ac69f7a1d57a28...) onto canvas and double-click to edit

Result: it won't open 

AI and SVG don't open either (assuming as designed because that requires a different application.  classic results in a dialog that is probably suppressed in DS).

**Comment by shaoshing** [comment]
@chadrolfs Currently we only support editing PS files in DS. In classic, you can edit images (png, jpeg, with limitation) and PS files; editing unsupported files will show a modal dialog saying "file cannot directly edited in PS". 

Adding @davealonzo to this conversation for advise on handling unsupported files.

**Comment by davealonzo** [comment]
I would suggest to ignore double-click to edit for now until we can get better support for messaging in the UI and for editing such file types.

Also, I asked Bradee if Ps plans on supporting editing SVGs from libraries. She said they will be in November. I am inquiring more about what they're up to.

**Comment by chadrolfs** [comment]
@davealonzo are you saying we should ignore 2x-click on canvas or in layers panel or in CC Lib panel or all of the above (I assume this is for Library assets only, correct)?  What about the Enter key?  Are you saying we should not allow Library asset editing at all?  

Disabling this functionality probably affects editing objects/layers in general (shape, text, pixel, embedded smart objects, linked smart objects).   

Need clarity on how to proceed on each path.

**Comment by davealonzo** [comment]
OK... did some heavy soul searching on this one with the help of Chad, Shaoshing and Ian. With continuing to support editable library assets in mind (e.g. psd, psb), here's the proposal:

**Hover title modifications for Libraries panel**
* For editable asset types, add "Double click graphic to edit" to second line
* For non-editable asset types, add "Not editable in this app" to second line

**Double click interaction to edit**
* Implement double click interaction to thumbnail graphic (if editable)
* Implement double click interaction to placed canvas asset (if editable)
* Continue to support double click interaction in Layers panel (if editable) 
* Ignore double click interactions for all non editable instances (informed by the hover title)

Yes?

**Comment by chadrolfs** [comment]
Yes!  Sounds great.
