### ISSUE TITLE
Errors closing CC Lib asset after editing

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2548]
drag an asset onto canvas
double-click to open/edit
change it and close (click save to prompt)

Result: `Action documents.close failed: TypeError: undefined is not a function`

**Comment by shaoshing** [comment]
@chadrolfs once this is fixed, you will need latest Jenkin build (>= 676) in order the have the graphic's preview updated correctly to the changes via the close-and-save dialog.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
