### ISSUE TITLE
Datalist: Blend mode menu does not scroll with mouse wheel or finger movement on mouse

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2555]

**Comment by iwehrman** [comment]
Are you talking about changing the selected option with the scroll wheel instead of using arrow up/down?

**Comment by ktaki** [comment]
Yes. Why not?

**Comment by chadrolfs** [comment]
only workaround is using arrow keys.

**Comment by ktaki** [comment]
Closing this as designed. This is a short menu. Scrolling is not necessary.

**Comment by chadrolfs** [comment]
I disagree that this is as designed.  It should function the same as other datalists.  Re-opening but lowering priority.

**Comment by chadrolfs** [comment]
Nevermind, after looking at the other datalists, I'm incorrect.  Datalists are all functioning alike.
