### ISSUE TITLE
Truncation of assets will happen after around 8 assets in Export dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2557]
![screen shot 2015-09-21 at 4 03 53 pm](https://cloud.githubusercontent.com/assets/2029597/10007506/b5ab1c66-607a-11e5-843c-76d289334145.png)

**Comment by chadrolfs** [comment]
should have an ellipsis (...)

**Comment by mcilroyc** [comment]
ellipsis added by PR.  FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
