### ISSUE TITLE
New Export button on the doc title bar can be overwritten by doc names

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2558]
Any other better place to be?

**Comment by mcilroyc** [comment]
assigned to @DivyaPrabhakar , cc: @designedbyscience

**Comment by iwehrman** [comment]
I don't see this problem any longer. FBNC to @ktaki.

**Comment by ktaki** [comment]
This may be a minor issue, bug I see some unnatural behavior of showing document titles on the document bar. Try Cmd+n several times. The font size becomes smaller suddenly when reached to the middle of the bar with a half of the space still left on the bar. Can that be wait till the doc titles reaches near the end of the bar?

**Comment by ktaki** [comment]
See the picture below. 8 document open and the last doc is selected, but it does not show full document name, in this case, "Untitled 8".

![screen shot 2015-10-12 at 1 27 58 pm](https://cloud.githubusercontent.com/assets/2029597/10437928/5506911c-70e5-11e5-819f-f2a1d1fea430.png)

**Comment by chadrolfs** [comment]
Removing FIX NOW since this is a positional issue and issue as it was originally written no longer occurs (Export icon is no longer being overwritten by doc name).  The issue here now is that the last doc name is under the header icons, but clicking on it can correct.

**Comment by ktaki** [comment]
No, clicking on it won't correct it, but I agree this is to be fixed by M3, not for UI F.

**Comment by DivyaPrabhakar** [comment]
@ktaki @chadrolfs Isn't is supposed to go behind the icons because we agreed that we would have users scroll the document header if there are too many titles? What is the ideal case -- have all the document tabs resize so that they are all visible at once in the documents header and have no scroll?

**Comment by chadrolfs** [comment]
I think the main issue right now is that they don't scroll well or fluidly and can get stuck, at least via mouse move or clicking on the 1/2 exposed title, especially on windows.  The full name should be exposed for the document that has focus IMO.

**Comment by ktaki** [comment]
Chad is right. With exceptions of unusual long names, the doc bar should display full name when the doc is selected.

**Comment by designedbyscience** [comment]
Back to @ktaki for verification

**Comment by ktaki** [comment]
Looks good!!
