### ISSUE TITLE
Uncaught SyntaxError: Invalid number after editing/saving/closing a CC Lib asset

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2559]
create a new doc
load library: Test - OK to accidentally nuke
drag Graphic: Climber onto canvas, hit enter to place
double-click to open/edit it
hit Delete to remove layer: Rectangle 1
cmd/ctrl + s to save
cmd/ctrl + w to close

Result:
`Uncaught SyntaxError: Invalid number`
`Action documents.close failed: Error: Invariant Violation: findComponentRoot(..., .0.4.0.0.1:$1137.1.0.0.1.0.2): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.`

**Comment by chadrolfs** [comment]
![screen shot 2015-09-21 at 4 39 41 pm](https://cloud.githubusercontent.com/assets/8442631/10008138/4660dfa2-6080-11e5-956c-68b25dc50286.png)
![screen shot 2015-09-21 at 12 18 31 pm](https://cloud.githubusercontent.com/assets/8442631/10008139/4662e20c-6080-11e5-9daa-894f224a3fb0.png)

**Comment by chadrolfs** [comment]
@shaoshing is this fixed?  Looks like the other 2 related bugs are so just wondering.  I'll test after bug scrub to see or if you know, just comment/mark as such.  Thanks.

**Comment by shaoshing** [comment]
Hi @chadrolfs , no I didn't do anything :), and I cannot reproduce it with latest master either. I do see the exception was coming from the number input component via the log. However I am unable to tell which panel the input is in, as the log is truncated.

**Comment by chadrolfs** [comment]
I'll take another look, thanks.

**Comment by chadrolfs** [comment]
I can still repro with latest master and latest Jenkins build.  I hit the `Invalid Number` error right after Save before I close it now.

**Comment by chadrolfs** [comment]
and if I try to undo (after that save), I hit this:
`Action edit.undo failed: Error: Invariant Violation: findComponentRoot(..., .0.4.0.0.1:$481.1.0.0.0.0): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a <tbody> when using tables, nesting tags like <form>, <p>, or <a>, or using non-SVG elements in an <svg> parent. Try inspecting the child nodes of the element with React ID ``.`

**Comment by chadrolfs** [comment]
CNR with current sources
