### ISSUE TITLE
Color Picker UI opens above swatch with smaller App window 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2560]
new doc, draw rect, add drop shadow, resize app window (or use an SP3) so that vertical is smaller.
click on color swatch

result: color picker opens above the swatch
![screen shot 2015-09-21 at 4 48 42 pm](https://cloud.githubusercontent.com/assets/8442631/10008193/f009b81c-6080-11e5-999f-a7198f686a43.png)

**Comment by chadrolfs** [comment]
remove or change position of triangle if repositioned from default?

**Comment by ktaki** [comment]
A bit of confused moment.

<img width="273" alt="screen shot 2015-09-30 at 9 15 55 am" src="https://cloud.githubusercontent.com/assets/2029597/10199117/1f3a6c92-6754-11e5-87e9-e6c65ec087c7.png">

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
yay!  nice work!
