### ISSUE TITLE
Drag file onto PS icon doesn't always show the resultant document in the header

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2563]
*With a document open, and a layer selected*, drag a JPG file onto the photoshop icon in the mac OS toolbar.  This will open the JPG file as a new document, but *sometimes* the DS document header bar will not show the new document until after the first canvas click.

http://cl.ly/2B1X0P0s0A0M

**Comment by mcilroyc** [comment]
After a quick check, this does seem to be fixed.

**Comment by chadrolfs** [comment]
Yeah, I CNR.
