### ISSUE TITLE
Mixed icon needs to be scaled for Effects panel

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2569]
<img width="258" alt="screen shot 2015-09-22 at 11 05 50 am" src="https://cloud.githubusercontent.com/assets/2029597/10027167/765d8936-611a-11e5-951f-9490ad50c90f.png">

**Comment by designedbyscience** [comment]
This is no longer a problem since the swatch for effects should be the same size as the appearance swatches

**Comment by ktaki** [comment]
Verified the fix.
