### ISSUE TITLE
Toggling fill and stroke visibilities changes their colors when multiple layers are selected

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2570]
Create two rectangles. Change the colors of fill and stroke for each rectangle. Use different colors. Select the both rectangle in layers panel. Click visibility icons of fill and strokes in the Appearance panel to turn off and then on the visibility.

RESULT: 
The fill colors for the both rectangles become black. 
The stroke colors for the both rectangles become one of the stroke colors.

**Comment by mcilroyc** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
