### ISSUE TITLE
Export panel should maintain minimum height

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2585]
As adding more effects,the header part of Export dialog shrinks.

![screen shot 2015-09-22 at 5 38 26 pm](https://cloud.githubusercontent.com/assets/2029597/10035602/f225fbc6-6150-11e5-90a6-a69eb995cb2e.png)

**Comment by iwehrman** [comment]
I don't think this has anything to do with the panel being collapsed? It should just always have a minimum height. 
![image](https://cloud.githubusercontent.com/assets/1075154/10062749/f310b222-621a-11e5-8d61-b9fe30354dc8.png)

**Comment by placegraphichere** [comment]
see #2693

**Comment by ktaki** [comment]
Verified the fix.
