### ISSUE TITLE
Zoom can be set to < 5% or > 3200%

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2592]
Using down arrow and up arrow, the zoom level number can be set to out side of 5% and 3200%. Also, entering number outside of the range (including negative numbers) from keyboard is accepted if you type it more than once consecutively.

**Comment by mcilroyc** [comment]
@ktaki note that in addition to fixing the bug, arrow keys are now disabled for this input.

**Comment by ktaki** [comment]
Verified the fix. up and down arrow keys have been disabled. Number input has been adjusted.
