### ISSUE TITLE
Add artboard canvas UI should not show when layer visibility is off

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2596]
cmd/ctrl + n
select the AB in the layers panel and either click the visibility icon or use the shortcut ( cmd/ctrl + alt + , ) to turn visibility off.

Result: 
![screen shot 2015-09-23 at 1 36 24 pm](https://cloud.githubusercontent.com/assets/8442631/10058105/98f69634-61f8-11e5-9596-6e7adbd1ee9e.png)

**Comment by volfied** [comment]
I think @DivyaPrabhakar should look into this, and learn a little about our overlay code. Please come bug me if you get stuck. Artboard adders are drawn in superselectOverlay.jsx

**Comment by chadrolfs** [comment]
Marking this M3, but also happens in standard PS.  Logging watson issue

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4069676

**Comment by chadrolfs** [comment]
Verified fix in standard PS, but not fixed on JS side.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
