### ISSUE TITLE
Unable to move more than one artboard at a time via Select tool click and drag on title

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2597]
create a new doc with multiple artboards
select on canvas by Shift + click on titles with Select tool
click + drag on title

Result: artboards don't move (arrow keys work)

**Comment by volfied** [comment]
if I don't get to it in time, superselect click/drag first attempts a selection, and only starts a drag by using OS.postEvent if selection is valid. The logic seems to be broken for this case.

**Comment by volfied** [comment]
Good and bad news, our code is correct and we send a LMD event to Photoshop... so drag code in core is not starting.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
verified fix but also verified regression of #1613
