### ISSUE TITLE
Zoom level can be less than 5% when app window is moved from high res screen to low res

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2600]
Set zoom level to 5% in high res screen. Move the app window to low res screen. Pan the canvas (issue #2598) the zoom level display is updated to 2.5%. This should stay at the minimum value allowed (5%).

Note that if the zoom level is set to 3200% at low res screen and move the app window to high res, the zoom level stays at 3200%. This is fine.

**Comment by tiburbage** [comment]
I think the minimum zoom factor is 0.27%. The zoom factor should never go below that, but will be doubled when dragging from a Retina display to a non-HiDPI display, and halved when going in the other direction. This keeps the apparent sizes of things uniform when going between the displays.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
The PR #2603 fixed #2598, not this issue. Please review.

**Comment by iwehrman** [comment]
FBNC to @ktaki again!

**Comment by ktaki** [comment]
Entering number less than 5% will result in 5%.
With Cmd+minus, the smallest value is 0.3%
If App window is moved from retina to normal display, 0.3% becomes 0.1%. 

In all above situations, standard Ps keeps 0.15% as the minimum. Can we do the same? At least, we should have a consistent minimum zoom value.

**Comment by volfied** [comment]
@ktaki After playing with this, even if I allow 0.15, PS actually keeps the zoom value at 0.27%... Despite us passing it a zoom value of 0.15

I think at those zoom levels, document size comes into play, and it's not worth our time to make this as close to PS as possible. If you disagree, please let me know, and I will allow 0.15 to be a valid input. Window screen density allowing those zoom sizes is not a big deal for me, we should aspire to keep the user within reasonable zoom levels in our own UI.

**Comment by ktaki** [comment]
So, Ps lies about the minimum zoom value? Fine, case closed.
