### ISSUE TITLE
Artboard does not show as selected in layers panel when active on canvas after layer delete

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2601]
new doc with one shape inside the AB and one outside
select the layer outside and delete 

Result: AB is now selected on canvas but layers panel does not confirm that.

https://www.dropbox.com/s/idz9i8m3yxnhtpr/AB-selectionConfusion.mov?dl=0

**Comment by volfied** [comment]
I think recent changes in SCU of LayersPanel fixed this. back to @chadrolfs

**Comment by chadrolfs** [comment]
Nope, unfortunately not.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
