### ISSUE TITLE
Guides blue rects are not drawn correctly when the app is dragged across Retina/standard displays

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2604]
The blue guide regions (rects) appear at 1/2 their apparent width when the app is dragged from a Retina display to a standard/non-HiDPI display. On the other hand, when the app is dragged from a standard display to a Retina display, the guides have the right apparent width but are drawn offset from their correct position.

Strangely, the bottom rect in both cases seems to be correct: it is only the left, right, and top ones which are wrong. Tested with 20150923.m.235

**Comment by volfied** [comment]
@ktaki can you confirm this, Ian made changes last week related to displayConfigurationChanged events which should have fixed this.

**Comment by ktaki** [comment]
This issue is resolved for the scenario written by Tom as long as you do not resize the app window. I will open a separate issue for it.

**Comment by ktaki** [comment]
New issue #2684 has been added.
