### ISSUE TITLE
Cloaking problems with modal dialogs on 5k display

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2607]
1. Here's what happens on master when I search: http://cloud.wehrman.org/371l0k3D0V38
2. Here's what I saw on startup with fresh prefs:
![image](https://cloud.githubusercontent.com/assets/1075154/10062931/dee32620-621c-11e5-966d-cc44c502d7c1.png)

**Comment by iwehrman** [comment]
Actually, it turns out we're never calling `cloak` or `setOverlayCloaking`, so I don't think this has to do with the cloaking at all. @chadrolfs: can you create a Watson issue for this and assign it to @jsbache? Thanks!

**Comment by chadrolfs** [comment]
Hmmm, i can't repro this but sure.  Will do.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com//#bug=4062855

**Comment by iwehrman** [comment]
It may well be specific to a 5k iMac.

**Comment by iwehrman** [comment]
@chadrolfs: I think this was user error due to the fact that I was running CEF with gpu compositing disabled. So, I think the Watson bug can be closed. I'll mark this FBNC so that you can deal with the Watson issue, and then you can close this bug. SORRY.
