### ISSUE TITLE
Checkbox styling problems

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2608]
On a 5k iMac with `font-size: 62.5%`, checkboxes look like this:
![image](https://cloud.githubusercontent.com/assets/1075154/10063270/a84b01ec-6220-11e5-8620-4712b57fae5e.png)

**Comment by placegraphichere** [comment]
take a look at #2691

**Comment by chadrolfs** [comment]
PR is still open assigned to Seth

**Comment by iwehrman** [comment]
FBNC to @designedbyscience.

**Comment by designedbyscience** [comment]
I have another PR which addresses this even further #2908
