### ISSUE TITLE
Copy of an empty pixel layer is placed out of its art board.

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2612]
#### copy-paste an empty pixel layer in classic - wrong
![classic-duplicate](https://cloud.githubusercontent.com/assets/118264/10253864/cda1b794-68f4-11e5-8ff0-3517858a8806.gif)

#### copy-paste a non-empty pixel layer in classic - correct
![classic-duplicate-2](https://cloud.githubusercontent.com/assets/118264/10253881/ea56fb06-68f4-11e5-9356-0970637c2cd9.gif)

**Comment by shaoshing** [comment]
Identified as a core bug. Created watson bug https://watsonexp.corp.adobe.com/#bug=4068370

**Comment by iwehrman** [comment]
Please file a new JIRA bug and assign to John Worthington. This bug can be closed at that point.

**Comment by chadrolfs** [comment]
https://jira.corp.adobe.com/browse/PS-1206
