### ISSUE TITLE
Stroke color swatch in Appearance panel is not right

### ISSUE THREAD

**Issue by davealonzo** [adobe-photoshop/spaces-design#2614]
Color swatch for stroke doesn't convey well that it's a stroke color.

Current...
<img width="318" alt="screen shot 2015-09-24 at 11 15 28 am2" src="https://cloud.githubusercontent.com/assets/12259315/10082576/4261f9f0-62af-11e5-9cd3-1131329e0c61.png">

Should look like...
<img width="318" alt="stroke_color" src="https://cloud.githubusercontent.com/assets/12259315/10085462/27138128-62be-11e5-9f4d-4d138fec12db.png">

**Comment by iwehrman** [comment]
Fixed by @designedbyscience. 
![image](https://cloud.githubusercontent.com/assets/1075154/10290004/6c144104-6b56-11e5-9a93-f2a03f542898.png)
