### ISSUE TITLE
Can't read text while renaming a library asset

### ISSUE THREAD

**Issue by davealonzo** [adobe-photoshop/spaces-design#2621]
<img width="419" alt="screen shot 2015-09-24 at 2 37 27 pm" src="https://cloud.githubusercontent.com/assets/12259315/10087794/0dd38660-62cb-11e5-8c8a-d4ab6d142c69.png">

**Comment by chadrolfs** [comment]
@designedbyscience should this be assigned to you?

**Comment by volfied** [comment]
@chadrolfs Can you confirm the fix?
