### ISSUE TITLE
Inconsistent subheader styling

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2629]
Effects:
![image](https://cloud.githubusercontent.com/assets/1075154/10090502/034b45c4-62e5-11e5-8d11-12425107a9a5.png)

Libraries:
![image](https://cloud.githubusercontent.com/assets/1075154/10090497/fe996ad8-62e4-11e5-8895-8e1af050c9f0.png)

**Comment by DivyaPrabhakar** [comment]
@iwehrman @designedbyscience 

I am not sure what happened to the screenshot I posted yesterday but how does this look?
![](https://www.dropbox.com/s/5ygsjxmciq3wknw/Screenshot%202015-10-08%2015.51.49.png?raw=1)

**Comment by designedbyscience** [comment]
Consistent!

**Comment by iwehrman** [comment]
It looks like the subheaders in the libraries panel are somewhat dimmed compared to the header, but not in the effects panel. I like the fact that they're somewhat dimmed in the libraries panel because it helps to distinguish between the header and subheaders. I would be in favor of making a similar change to the effects panel. Any thoughts, @DivyaPrabhakar or @designedbyscience or @placegraphichere?

**Comment by DivyaPrabhakar** [comment]
I agree with Ian. It is a subtle color change but the all caps and the close size of the headers and subheaders make them look quite similar so distinctions are good. Also something that I wanted to bring attention to is that the Libraries panel has so much space between the naming input and the first subheader. In terms of consistency, where other panels do not have this space, should changes be made there to match the other panels?

**Comment by iwehrman** [comment]
That could be intentional (in the short term) in order to accommodate the create/rename pseudo-dialog. But I agree that it looks weird.

**Comment by DivyaPrabhakar** [comment]
@designedbyscience @iwehrman @placegraphichere 

How does this look, with respect to the title and subtitle colors now? 

![](https://www.dropbox.com/s/y3qbo4gq8ozjsde/Screenshot%202015-10-09%2014.30.47.png?raw=1)

**Comment by DivyaPrabhakar** [comment]
FBNC @iwehrman

**Comment by iwehrman** [comment]
Fixed by #2884.
