### ISSUE TITLE
Toolbar UI bounds are off by 1px on retina

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2639]
![image](https://cloud.githubusercontent.com/assets/1075154/10110649/6cfd80ce-6383-11e5-9702-429392ccdc08.png)

**Comment by chadrolfs** [comment]
grabbing to verify

**Comment by chadrolfs** [comment]
If #2264 is addressed, that could impact this.  As of now, this is fixed.
