### ISSUE TITLE
Clicking in guide zone should not create a guide

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2640]
If you click in a guide zone, it creates a guide and drops it inside the guide zone. This should be disallowed because it's very easy to accidentally create guides here when trying to grab a new guide from the zone. The desired behavior here:

1. If you drop an existing guide in the guide zone, it should delete the guide.
2. If you drop a fresh guide in the guide zone, it should never be created.

**Comment by tiburbage** [comment]
I have also run into this and was going to log a bug. In some cases, this results in an "orphaned" guide you can't get at again to move or delete.

**Comment by volfied** [comment]
I am working on fixing this, but I don't think dropping a guide on the guide zone should delete it. We don't highlight guide zones during guide drag, so it would confuse the user to delete a guide if they drag it to the edge of visible canvas.

**Comment by iwehrman** [comment]
I think dropping on the guide zone should delete it, but that there should be some feedback about what you're about to do, like changing the cursor in some way.

**Comment by volfied** [comment]
@placegraphichere Ian and I disagree, can you be the tie breaker?

**Comment by ktaki** [comment]
How about deleting it if no dragging happens in the guide zone? Currently, just clicking the area will create a guide and it is hard to re-grab without scrolling the canvas. If the minimum dragging is required, it will avoid mis-creation of a guide.

**Comment by volfied** [comment]
@ktaki, my PR #3506 implements that. We are currently disagreeing on what happens if you drag an existing guide to one of the zone areas.

**Comment by ktaki** [comment]
Oh, OK. Then, I agree with you, @volfied, that moving a guild to the guide zone should not delete the guide. You do not see the guide zone when you are dragging a guide anyway. It is a part of regular canvas.

**Comment by mcilroyc** [comment]
The PR (just merged) prevents guide from being created with a simple click on the guide-zone.  Is this ready to FBNC?

**Comment by volfied** [comment]
@mcilroyc I'd like @placegraphichere's opinion on the second part before test/close.

**Comment by placegraphichere** [comment]
So the fact that you do not see the guide zone when dragging an existing guide over a guide zone to me tells me it should _not_ delete. I would have no feedback that a delete would occur, and it would be confusing.

**Comment by volfied** [comment]
Given Taki and Seth's reply, I'm setting this to FBNC and passing it back to Ian to close (or assign to Taki/Chad to verify)

**Comment by iwehrman** [comment]
Sorry, I assumed that we _would also_ show the guide zone in this case. I don't expect users to reliably be able to figure out that they need to drop a guide onto the paneling in order to delete it without any other feedback.

**Comment by iwehrman** [comment]
My wish:

1. Show the drag zone when you drag a guide to the edge of the canvas.
2. Change the cursor to somehow indicate that you are about to delete the guide when in the guide zone while still dragging.
3. Delete the guide when you drop it in the guide zone, ideally with some whizzy exploding-guide animation to explain further what just happened.

**Comment by chadrolfs** [comment]
^ I like it

**Comment by chadrolfs** [comment]
Another idea to give user feedback about deleting a guide would be to change the drop zone color if you are dragging a guide into it.  Not sure which is easier, changing the drop zone color or changing the cursor plus a whizzy exploding-guide animation.

**Comment by volfied** [comment]
While I like @iwehrman's wish, but it is beyond bordering, and now far into workflow category.

PS is driving the guide drag interaction, we're in modal state. I don't see it as possible to highlight guide zones during this state. And I do not wish to die on this hill.

**Comment by volfied** [comment]
Also, as a rebuttal, it is a known PS interaction that dragging a guide outside app window deletes it, we are doing one better by allowing deletion by dragging outside canvas.

**Comment by chadrolfs** [comment]
There appears to be 2 bugs here. 1, which i consider this one, guide creation under guide zone (this is fixed and this bug should be closed IMO) and 2, a change to guide zone functionality to also be used to delete guides (as opposed to existing behavior which is similar to standard PS where you drag a guide outside app window, stated by @volfied above).

That said, I'd like to close this (as fixed) and move the change to guide deletion proposal to a JIRA card as a backlog item to be prioritized.

**Comment by ktaki** [comment]
I agree with @chadrolfs.

**Comment by volfied** [comment]
@chadrolfs I agree with you, as well. Please close this bug once you confirm it fixed.
