### ISSUE TITLE
Select All shortcut results in Uncaught TypeError and bad state

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2641]
New doc
create a shape 
cmd/ctrl + a to select all

Result: Uncaught TypeError: Cannot read property 'get' of undefined

Additional note: if you reset DS and then Select All, it works without error but you are unable to move the Artboard (separate issue?)

**Comment by volfied** [comment]
This happens in DocumentExports.getUniformAssets method. Passing to @mcilroyc
