### ISSUE TITLE
Attempting to edit/open an CC Library asset results in Open dialog

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2642]
create a new doc
drag an asset onto canvas (Test - OK to accidentally nuke: Climber)
hit Enter

Result: Open dialog

**Comment by shaoshing** [comment]
The exact steps to reproduce this:

1 switch to DS, double click to open any graphic for edit.
2 switch to classic and close the document 
3 switch to DS, open the same graphic again and then close it
4 open the same graphic -- open dialog appears.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
