### ISSUE TITLE
Ungroup: layers panel does not seemingly update correctly

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2643]
It takes some time before the layers panel will update when a large group is ungrouped. The layers do not seem to respond until another click is made, or other UI is interacted with.

Example is using the vermillion PSD and ungrouping one of the large top level groups inside one of the artboards.

**Comment by iwehrman** [comment]
I can confirm that the panel isn't updated until you click on something to change the selection state.

**Comment by volfied** [comment]
@placegraphichere this should be fixed. can you confirm?

**Comment by iwehrman** [comment]
Kicking over to @chadrolfs to verify.
