### ISSUE TITLE
Unable to transform CLSO 

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2648]
1. import the graphic from http://adobe.ly/1YGnw3g to your library
2. drag the graphic to a canvas
3. try to transform the graphic on the canvas

result: unable to transform the CLSO 

This is probably a core bug. I will attach the watson bug link later.

![clso](https://cloud.githubusercontent.com/assets/118264/10114352/56a97c3a-63a4-11e5-9951-d8903a488383.gif)

**Comment by shaoshing** [comment]
watson: https://watsonexp.corp.adobe.com/#bug=4064553

**Comment by chadrolfs** [comment]
As of pgdev.799 (mac), I still see transform issue in DS; I can’t rotate or transform.  In classic, I can though.

**Comment by chadrolfs** [comment]
new comments in watson bug.  is there something we need to do on our side since this is fixed in classic PS?

**Comment by chadrolfs** [comment]
Here’s what I’m seeing this morning (r.263 on mac, pgdev.788 on win); Scale and Rotate work on initial place in both DS and classic PS.  Subsequent Scale/Rotate (after place) works in PS but not in DS.

**Comment by chadrolfs** [comment]
It appears that #2965 fixes this too!
