### ISSUE TITLE
missing dialogs cause policy swap issues

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2650]
![screen shot 2015-09-25 at 4 41 56 pm](https://cloud.githubusercontent.com/assets/8442631/10114510/6a423708-63a6-11e5-9e2a-e9d899593326.png)
![screen shot 2015-09-25 at 4 50 18 pm](https://cloud.githubusercontent.com/assets/8442631/10114511/6a429702-63a6-11e5-80e9-a663cc738f68.png)

**Comment by mcilroyc** [comment]
I think this may have been addressed by #2662.  In any case, I can no repro in 9070a9a43c5d458f416d8cae19f6376c80d9f6d4.  @chadrolfs back to you, or please provide detailed repro steps if you can.

**Comment by chadrolfs** [comment]
re-assigning to you until #2865 is merged
