### ISSUE TITLE
React warnings about duplicate key props

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2651]
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of DropShadowList. See https://fb.me/react-warning-keys for more information.`

To repro, ungroup the last artboard in Vermilion.

**Comment by iwehrman** [comment]
I'm also seeing this: 
`Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of UnsupportedEffectList. See https://fb.me/react-warning-keys for more information.`

**Comment by iwehrman** [comment]
It's back! I'm seeing this:
` Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of DropShadowList. See https://fb.me/react-warning-keys for more information.` 

To repro, open Vermilion and select the following layer range:
![image](https://cloud.githubusercontent.com/assets/1075154/10297514/e9b9f4be-6b88-11e5-83d1-35ed3cb03e8c.png)

**Comment by mcilroyc** [comment]
@iwehrman mind validating this?

**Comment by iwehrman** [comment]
No warnings in sight. Fixed by #2942.
