### ISSUE TITLE
Datalist hairline alignment issues

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2656]
Here are three instances of expanded `Datalist` components:

1. Blend mode for groups:
![image](https://cloud.githubusercontent.com/assets/1075154/10120054/ff23d486-645e-11e5-8c2d-952a3d72a909.png)
Note that the hairline is not visible when the `Datalist` is expanded. Compared to the next two examples, this should be considered the "correct" implementation of the design.

2. Blend mode for type/vectors:
![image](https://cloud.githubusercontent.com/assets/1075154/10120056/14a44174-645f-11e5-8863-442df5faf913.png)
So close... note that the hairline is peeking out from behind the `Select` menu.

3. Libraries list:
![image](https://cloud.githubusercontent.com/assets/1075154/10120063/42dac25c-645f-11e5-9100-4c3a6232bca2.png)
Argh! The `Select` component should both be widened to cover the entire hairline, and the entry titles should be left aligned with the text in the input, as in the previous two examples.

**Comment by iwehrman** [comment]
The Type datalists have problems too:

1. Type face has a peeking hairline: 
![image](https://cloud.githubusercontent.com/assets/1075154/10123990/9ee5314c-64fd-11e5-8650-9e289ec2734a.png)

2. Type weight has all that and a menu alignment problem:
![image](https://cloud.githubusercontent.com/assets/1075154/10123993/ac27f8da-64fd-11e5-9c6f-f2ca81d93ffe.png)

**Comment by placegraphichere** [comment]
these are all set individually for some reason. So time just needs needs to be made to get them into shape. 

@davealonzo also mentioned that we could try to hide the underscore when open too. Assigning to myself

**Comment by placegraphichere** [comment]
See #2690

**Comment by iwehrman** [comment]
Fixed by #2690.
