### ISSUE TITLE
Uncaught error switching tools in Edit Mask mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2667]
Open GearSale.psd, 
select Climber (pixel) layer, 
hit m to enter Mask mode, 
hit r to select Rect tool, 
draw out a rect mask on climber, 
click on (+) Effect to add a drop shadow, 
hit v to switch to Select tool, 
then click on (+) again. 

Result: `Uncaught Error: Photoshop returned an error when executing command number: 1 Photoshop code: -128 Photoshop message:`

**Comment by pineapplespatula** [comment]
We intentionally end the modal tool state when adding a drop shadow. I need to talk to Jesper about why this is causing a cancel event in PS

**Comment by pineapplespatula** [comment]
#2798 should fix this
