### ISSUE TITLE
Entering and exiting mask mode leaves layer icon indicating it has a mask 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2669]
select a layer, hit m to enter mask mode, hit m again to exit it (without adding a mask)
Result: layer is still red

Layer indicator should be cleared when the mask is deleted.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs  - please note that this fix introduces a history bug for which we are blocked by core.  So THIS bug should be fixed, but please note that history store gets nuked by this "double m" workflow now.
