### ISSUE TITLE
Use of Enter and Esc is confusing attempting to move/edit an existing layer mask

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2670]
(layer with existing mask) hit m to enter mask mode so you can move the mask independent of the image it's masking, with Select tool move the mask, hit Esc to exit mask mode
Result: mask jumps back to where it was previously
Expect: exit mask mode
Workaround: hit Enter instead, then m to exit mask mode (don't hit Enter twice) - this is confusing.

**Comment by placegraphichere** [comment]
Escape should not cancel the edit. Similar to text editing, ESC should exit the mode applying the changes. The edits are maintained. The same should be followed here with masks. Gonna plop this on someone else...

**Comment by chadrolfs** [comment]
you heard the man.

**Comment by pineapplespatula** [comment]
This is tied up in the keyboard policy changes that jesper just allowed us to make, so i should be able to finally make some progress on this

**Comment by chadrolfs** [comment]
sucking in comments from #2682 and closing that one as a dupe since this one has more comments:

Press 'm' to enter the vector mask transform mode.
Hit Esc - Enters editing mode
Hit Esc - Enters transform mode
Hit Esc - Enters editing mode
Hit Esc - Exits vector mask mode
The doc title stays blue. <--- Redraw issue?

**Comment by ktaki** [comment]
Here is the latest behavior.

Press 'm' to enter the vector mask transform mode.
'a' - Enters editing mode
Hit Esc - Enters transform mode
Hit Esc - Exits vector mask mode
mask mode icon stays blue. (issue #2890)

The Esc key works only superselect tool is selected. Shouldn't it also work when shape tools are selected?

**Comment by chadrolfs** [comment]
Bouncing:

*With Select tool: hit m to enter mask mode, hit Esc (doesn't exit), hit Esc again then it exits*
With Rect and Ellipse tool: m to enter, hit Esc exits (as expected)
*With Pen tool: m to enter, Esc does not work to exit no matter how many times you hit it (related to #2988?)*
With Type and Sampler tool: you can't enter mask mode (as expected)

**Comment by iwehrman** [comment]
Back to @chadrolfs to verify.

**Comment by chadrolfs** [comment]
Looks good to me.  @ktaki wanna take a look and then close if you agree?

**Comment by ktaki** [comment]
Thanks @chadrolfs. Yap! Works great. Closing.
