### ISSUE TITLE
Check boxes clipped in Export dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2673]
Retina display:

<img width="502" alt="screen shot 2015-09-28 at 2 06 23 pm" src="https://cloud.githubusercontent.com/assets/2029597/10148747/33b145bc-65ea-11e5-970d-c6c5348f516d.png">

**Comment by iwehrman** [comment]
I see this on MBP 15" default res: 
![image](https://cloud.githubusercontent.com/assets/1075154/10228818/ad707f80-6829-11e5-835b-12cb50774ba1.png)

**Comment by iwehrman** [comment]
Pretty sure that @designedbyscience's recent checkbox PR addressed this. FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
