### ISSUE TITLE
Lost keyboard focus after color picker

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2676]
Select rectangle tool, and draw a rectangle.
Click on fill icon and open color picker.
Choose a color and dismiss the color picker by clicking fill icon or hit Esc.
Press v, e, p, t, or i to switch tool. This fails.

Could be another manifestation of #2552 ?

**Comment by chadrolfs** [comment]
Currently as designed.  First Esc closes color picker but leaves swatch in focus, 2nd Esc will release focus.

**Comment by ktaki** [comment]
I agree this is as designed. Need to close the dialog first, then Esc returns keyboard focus.
