### ISSUE TITLE
Uncaught error on exiting vector mask mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2677]
In vector mask editing mode, press 'm' or Esc to exit the vector mask mode.

Result: Uncaught Error: Photoshop returned an error when executing command number: 1 Photoshop code: -128 Photoshop message:

Jeffrey says:
"This is a known issue, Because PS considers canceling out of a modal state to be an error. Once Design Space can handle its own modal keyboard commands during modal tool states. we can handle this properly."

Note that the same error has been reported in the #2667. Since the issue is ending modal tool state when adding a drop shadow, I opened this as a separate issue.

**Comment by pineapplespatula** [comment]
should be fixed by my jecohen/2669 PR

**Comment by ktaki** [comment]
Verified the fix.
