### ISSUE TITLE
If layer is locked, do not enter vector mask editing mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2678]
Select locked layer and press 'm' to enter vector mask editing mode.
Layer icon turns red. 
Click on rectangle tool and draw a rectangle.

![screen shot 2015-09-28 at 2 56 00 pm](https://cloud.githubusercontent.com/assets/2029597/10149881/400d44c6-65f1-11e5-9b86-7a8621cac6a9.png)

**Comment by mcilroyc** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
