### ISSUE TITLE
Pressing 'm' does not exit vector mask mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2679]
It must be in editing mode (direct selection tool mode (white arrow cursor), or E, R, P) to exit vector mask mode by pressing 'm'. In vector mask transform mode (black arrow cursor), 'm' does not exit the vector mask mode.

Jeffrey says:
"this is a known issue waiting on a fix to the modal tool keyboard policy work"

**Comment by pineapplespatula** [comment]
this was magically fixed by some core changes.

**Comment by ktaki** [comment]
Yes, this seems to be fixed.
