### ISSUE TITLE
Opening a file while should ends vector mask mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2683]
Open a image file. Enter vector mask mode and draw a rectangle. Open another image file. (or close the opened file without saving it and reopen it.) It is still in vector mask mode. Doc title is in blue. Drawing a shape, however, only draw a path. Vector mask is not created.

**Comment by mcilroyc** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
The scenario above (Open a image file. Enter vector mask mode and draw a rectangle. Open another image file) will cause the following error.

![screen shot 2015-10-02 at 3 33 05 pm](https://cloud.githubusercontent.com/assets/2029597/10259262/1b501a28-691b-11e5-85cf-c0ba8c036e09.png)

**Comment by mcilroyc** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
