### ISSUE TITLE
Guides blue rects are not drawn properly when app window is resized

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2684]
The regions for the blue rectangles are not adjusted when app window is resized. 
In standard Ps, make the app window small, then switch to DS. 
Open a new artboard dox, check blue rect regions appear at each edge of the canvas.
Grab the lower right corner of the app window and drag it to make app windows larger.
Check the four blue rect regions.
RESULT: They are not adjusted to new canvas view. If app window is made to smaller, right and bottom regions will be lost.

**Comment by ktaki** [comment]
Tested with the fix for the issue #2604.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
