### ISSUE TITLE
Win: It takes two clicks to select a layer in the Layers panel

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2687]
I'm finding that I have to click on a Layer thumbnail twice to select. These clicks can be seconds apart or dblclicks. Only an issue on Windows.

Note there is another issue of a similar nature relating to expanding/collapsing Layer Groups. These are probably related if not the same issue.
https://github.com/adobe-photoshop/spaces-design/issues/1781

**Comment by iwehrman** [comment]
I'm fairly sure this is a dupe of #1781, but I guess we'll see!

**Comment by chadrolfs** [comment]
definitely a dupe but not specific to Win.  It is harder to repro on mac but happens on both OSes
