### ISSUE TITLE
Rapid creation of new docs will result in error

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2696]
Repeat Cmd+n quickly four or five times. 

RESULT: Action documents.createNew failed: Error: Can not find document undefined to addDefaultAsset

This is a fatal error and DS needs to be reset to recover. This is new issue. Could this be related to PR #2663?

![screen shot 2015-09-29 at 9 46 46 am](https://cloud.githubusercontent.com/assets/2029597/10171562/9f66cb24-668f-11e5-970e-bdb9a87079d7.png)

**Comment by mcilroyc** [comment]
I'll take this one

**Comment by iwehrman** [comment]
@mcilroyc: see the `lockUI` flag on some actions. In theory, we should use this to prevent menu actions while we're in the middle of sensitive actions.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4067884

**Comment by iwehrman** [comment]
@jsbache claims this is fixed in CL 1046056. Over to @chadrolfs to verify.

**Comment by iwehrman** [comment]
Er, sorry, @ktaki was the original filer.

**Comment by ktaki** [comment]
Verified the fix.

**Comment by tiburbage** [comment]
Watson also closed: https://watsonexp.corp.adobe.com/#bug=4067884
