### ISSUE TITLE
Sampling stroke fails across artboard multi-layered doc

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2699]
https://photoshop.slack.com/files/zorana/F0BGMNP1R/sampling.mp4

you can use explore-mt-hood.psd to repro (in my transfer folder on sjshare/photoshop).

Open psd from my transfer
(Select tool) select Activities rect in INDEX AB (Rounded Rectangle 1)
apply a stroke (change size and color)
apply an inner shadow
select Activities rect in Mt. Hood AB (also named Rounded Rectangle 1)
hit i for Sampler
mouse over Rounded Rect 1 in INDEX AB
hit space and select stroke

**Comment by chadrolfs** [comment]
![screen shot 2015-09-29 at 11 16 34 am](https://cloud.githubusercontent.com/assets/8442631/10173875/7ed7e134-669b-11e5-9f40-f9b412308e47.png)

**Comment by volfied** [comment]
Please re-assign after steps are added.

**Comment by volfied** [comment]
I don't know what's happened, but none of these shape layers have their `AGMStrokeStyleInfo` fields available to us.

This is not an initialization issue, PS is not initializing these shapes completely.

**Comment by volfied** [comment]
https://watsonexp.corp.adobe.com/#bug=4066169

**Comment by isonno** [comment]
This is as designed.

Layers created without strokes (or more specifically, without the stroke machinery activated) do not have `AGMStrokeStyleInfo` attributes.  The fill color is buried in the Layer's `adjustment` attribute, and the `fillEnabled` attribute is set to `null` (vs. set to `false` if `AGMStrokeStyleInfo` is present and there is no fill specified).

We could explore some way to force the creation of `AGMStrokeStyleInfo` attributes, but this could incur significant overhead and may have backwards compatibility issues.  It's more expedient to deal with this in JS code (CopyCSS also works around this issue).

**Comment by volfied** [comment]
John is right, fix incoming.

**Comment by tiburbage** [comment]
OK, accepting AsDesigned for Watson bug and closing.
