### ISSUE TITLE
Unable to edit type in initial modal state

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2700]
new doc
t for type
click on canvas and start typing

Result: no options in Appearance panel, can't change color, font, etc

**Comment by volfied** [comment]
Our `get` batchPlay calls don't return to us form Photoshop while in modal tool state. Emailed Jesper.

**Comment by volfied** [comment]
Likely related to the new CEF build in dev.

**Comment by volfied** [comment]
Fixed with pgdv.mac.703 or later

**Comment by chadrolfs** [comment]
Options are now there but you can't edit them on Win ( #2725 )
