### ISSUE TITLE
Dragging SVG seems broken

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2702]
File New
From libraries, drag an SVG to document
Nothing happens

**Comment by zoranagee** [comment]
I'll also note that after doing this, my add AB buttons don't show and I can't get them to show without relaunching the app.

**Comment by chadrolfs** [comment]
I think this was fixed.  CNR with current resources.

**Comment by zoranagee** [comment]
Not fixed - I still see this problem.

**Comment by chadrolfs** [comment]
#2719
