### ISSUE TITLE
File New: Artboard chrome looks too dark upon creation (File>New)

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2703]
Expected:
<img width="242" alt="screen shot 2015-09-29 at 12 04 18 pm" src="https://cloud.githubusercontent.com/assets/7904855/10175328/1636626a-66a3-11e5-8431-a121e4e402ab.png">

Result:
<img width="233" alt="screen shot 2015-09-29 at 12 04 10 pm" src="https://cloud.githubusercontent.com/assets/7904855/10175329/163be366-66a3-11e5-965c-1b23879cf1d6.png">

**Comment by zoranagee** [comment]
Font looks weird too (different)

**Comment by iwehrman** [comment]
Your "result" above is what it looks like in standard PS mainline. So, I believe that is as designed. I think your second comment is a dupe of #2479. Please re-open if you disagree!

**Comment by zoranagee** [comment]
Whatever we do, we should be consistent. We're not. With File New we get dark chrome, when you click and move the AB, it changes to the lighter chrome.

**Comment by iwehrman** [comment]
Your two pictures above look like what standard PS looks like in my build when a) there are no layers inside the artboard selected, and b) there are layers inside the artboard selected. Are you sure your selection is exactly the same in both cases?

**Comment by iwehrman** [comment]
![img](https://s3.amazonaws.com/f.cl.ly/items/0W1p3m0p2N2u2d0m2f1t/Screen%20Recording%202015-09-29%20at%2012.47%20PM.gif)

**Comment by placegraphichere** [comment]
You may be encountering a focus state. Whether or not you are "within" the artboard will determine the way Ps will draw the artboard. @iwehrman's example is probably it.

Also, there are now settings in Ps for artboard borders:
- Line
- Drop Shadow
- None

This may account for some of the discrepancy.

**Comment by zoranagee** [comment]
You're right - core does the same thing. I'll take it up with them. :)
