### ISSUE TITLE
Color swatch for Vector Fill clipped on Retina

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#2710]
<img width="298" alt="untitled-28___100___rectangle_1__rgb_8____" src="https://cloud.githubusercontent.com/assets/22372/10179146/20137c9e-66d2-11e5-94bb-508976a3111f.png">

**Comment by iwehrman** [comment]
Must-fix for UIF on Monday.

**Comment by iwehrman** [comment]
Closing this on behalf of @designedbyscience since he filed it, he fixed it, and we both darn well believe it to be fixed.

**Comment by chadrolfs** [comment]
huzzah!  Looks great!
