### ISSUE TITLE
Creating a new document after simple actions in previous doc result in Invalid Number error

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2712]
new doc 
drag out rect shapes; one shape inside the AB and one outside
select the layer outside and delete
cmd/ctrl + n

Result: `Action documents.createNew failed: SyntaxError: Invalid number`

**Comment by chadrolfs** [comment]
![screen shot 2015-09-29 at 2 52 47 pm](https://cloud.githubusercontent.com/assets/8442631/10179272/bda4b680-66b9-11e5-8eab-36389f1f8d55.png)

**Comment by shaoshing** [comment]
I will look at this one while working on #2559. They are probably related.

**Comment by mcilroyc** [comment]
@shaoshing - depending on what else you have going on - this issue might be related to things I've been working with recently... LMK if you want to reassign.

**Comment by shaoshing** [comment]
Cory and I are both unable to reproduce this issue. @chadrolfs could you try to reproduce?
