### ISSUE TITLE
Artboard coordinates are incorrect after deleting a layer

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2713]
new doc
draw rect shapes; one shape inside the AB and one outside
with Select tool delete the second layer drawn outside the AB

Result: AB is now selected but coordinates are off

https://www.dropbox.com/s/160dh280hb9lh1n/AB-badCoord-afterDelete.mov?dl=0

**Comment by chadrolfs** [comment]
![screen shot 2015-09-29 at 3 12 19 pm](https://cloud.githubusercontent.com/assets/8442631/10179678/6ac6ee8a-66bc-11e5-85cb-15c9d51dfb50.png)

**Comment by chadrolfs** [comment]
found confirming fix of #2601

**Comment by volfied** [comment]
In case I can't fix this before I leave, here is the problem:

With removeLayer transferring to `initializeLayers` for the selected layers. I get the updated bounds of the artboard. And then I get a autoCanvasResizeShift event, and I translate all the bounds by that amount, where the artboard's bounds were already up to date, and didn't need translating.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
With these steps, yes, this bug is not reproducible but #2754 still occurs
