### ISSUE TITLE
Close document throws error if the "next" document has not been initialized

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2715]
one way to repro:
- create two documents (cmd+n, 2x)
- reset design space
- close the active document
- see exception

Assigning to myself, fix in progress.

**Comment by iwehrman** [comment]
For posterity: caused by #2660.

**Comment by shaoshing** [comment]
@chadrolfs can you verify?

**Comment by chadrolfs** [comment]
Now if I create 3 docs, reset DS and then close them.  On the last one, console spews:
`Action documents.close failed: Error: Next selected document ID should be null iff there are no open documents`
 
![screen shot 2015-09-30 at 3 36 28 pm](https://cloud.githubusercontent.com/assets/8442631/10208563/077cd0f6-6789-11e5-8dc4-a42a18fde2ee.png)

**Comment by shaoshing** [comment]
Cory just fixed this, @chadrolfs please verify again.
