### ISSUE TITLE
Strange highlighting not wrt to where cursor is

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2716]
I'm not sure this is the same issue that Chad saw with coordinates but he said to log it. Check out this video and where my cursor is relative to what is getting highlight. Not consistently wrong, just in the beginning I have cursor in the middle of the AB and the top group of text is selected. Then I move my cursor and select the image on the 3rd AB and the bottom icons are highlight (blue outline). 

Video posted (titled "outline") on my transfer in sjshare.

**Comment by chadrolfs** [comment]
will regress and reprioritize accordingly

**Comment by chadrolfs** [comment]
I think this is the coordinates issue.  might be a result of #2713 which essentially makes this a dupe

**Comment by zoranagee** [comment]
OK - but for the record, I still see this in sprint 32.

**Comment by chadrolfs** [comment]
Yeah, if the coordinates are off,  you'll see this.  2713 is still open and needs resolution.
