### ISSUE TITLE
Drag image from libraries freezes the app

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2719]
File New
Drag an image from libraries
Application freezes

NOte: I am using jenkins playgroundev build 697 with the JS bits that Chad sent (so what's labeled as sprint 32?)

**Comment by chadrolfs** [comment]
Depending on what you drag, it may freeze.  See #2562

**Comment by chadrolfs** [comment]
just repro'd this.

**Comment by chadrolfs** [comment]
gets stuck on place

**Comment by chadrolfs** [comment]
only way I've found out of it is to right-click on app icon in OS dock > Quit and then you get a prompt to Place, then you can click Cancel on the prompt to save to continue working.

**Comment by shaoshing** [comment]
this will need Jenkin build (>= 703) to fully work, @chadrolfs
