### ISSUE TITLE
Numeric fields in the panels do not accept keyboard input

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2725]
Windows only. Current pg-dev and master. All panels affected.

**Comment by tiburbage** [comment]
Note this isn't generically true in my testing, but it is very easy to get into a state where you don't seem to be able to set and have an input keep focus. I was just able to create a rectangle, then adjust its Radius using the arrow/shift-arrow keys. However, I then switched to the Select Tool and then was unable to set focus to that Radius input again.

**Comment by volfied** [comment]
Just got off the phone with Jesper and Fitz, this is a core issue. They're working on it.

As soon as we call OS.acquireKeyboardFocus, we get 4 `keyboardFocusChanged` events where isActive alternates `true`,`false`,`true`,`false`, they're trying to figure out why.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4067068

**Comment by volfied** [comment]
Fixed with pgdv.694 on Win. Please confirm.

**Comment by ktaki** [comment]
It works now.
