### ISSUE TITLE
The "dialog" frame around the Text Color color picker isn't sized correctly vertically

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2726]
The controls draw partly outside the frame. Mac and Win, using master at a2aca91.

1 - With the Text Tool active, mousedown on the document
2 - Click on the Text Color swatch

**Comment by chadrolfs** [comment]
assign to ian if not fixed

**Comment by ktaki** [comment]
Yes, this is fixed.
