### ISSUE TITLE
Limit maximum number of effect instances to be 10 per effect

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2729]
Otherwise, Ps may crash. The menu item in '+' flyout should be dimmed when the max number has been reached.

**Comment by chadrolfs** [comment]
Core needs to know.  Please file a watson bug saying don't let people do with an action descriptor and assign to Jesper or JP.

**Comment by shaoshing** [comment]
created watson bug and assigned to Taki https://watsonexp.corp.adobe.com/#bug=4068367

**Comment by mcilroyc** [comment]
prevented on the DS side by @shaoshing 's PR

**Comment by shaoshing** [comment]
Taki, this layer effect might save your from clicking your mouse :P http://adobe.ly/1jDyVku

**Comment by ktaki** [comment]
Thanks @shaoshing. Looks good.
