### ISSUE TITLE
Guide drop zones are incorrect with Single Column Mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2731]

**Comment by chadrolfs** [comment]
<img width="1440" alt="screen shot 2015-09-30 at 2 16 28 pm" src="https://cloud.githubusercontent.com/assets/8442631/10206859/022020d2-677e-11e5-9cc5-97919f909918.png">

**Comment by chadrolfs** [comment]
re-assign to @volfied if needed. You have less than half a day.  :stuck_out_tongue_winking_eye:

**Comment by designedbyscience** [comment]
This is a cloaking issue, I believe

**Comment by iwehrman** [comment]
I re-did the overlay offsets stuff last, so I'll take this one.
