### ISSUE TITLE
Layers header is squashed in single column mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2734]
<img width="256" alt="screen shot 2015-09-30 at 2 48 00 pm" src="https://cloud.githubusercontent.com/assets/2029597/10207654/949b1c74-6782-11e5-8f15-c4f2160fffd8.png">

**Comment by chadrolfs** [comment]
Repro: load this library - http://adobe.ly/1KBVjAb
create a rect and apply asset: effects - a lot
collapse panels: Libraries, Export, Layers

**Comment by ktaki** [comment]
Thanks Chad. Or just make the height short enough.

<img width="263" alt="screen shot 2015-09-30 at 3 01 25 pm" src="https://cloud.githubusercontent.com/assets/2029597/10207907/3d48f25a-6784-11e5-8236-9e892e3b737f.png">

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
