### ISSUE TITLE
Can't marquee select multiple layers on the canvas

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2735]
If I have multiple shapes defined, and drag out a marquee over them on canvas with the Select Tool, nothing happens. Based on "pre-selection edge highlighting", they appear as if they will be selected, but then no selection occurs. I can marquee select them individually. Testing with pgdev.1615 w/ DS master 8142f96 (Mac or Win)

1 - Create a document with at least 2 shapes (say non-overlapping)
2 - Switch to the Select Tool
3 - Drag out a marquee over a couple of shapes

Expect: an shapes the bounding box of which falls under the marquee should be selected

**Comment by mcilroyc** [comment]
can you re-check with latest github master now @tiburbage ?

**Comment by tiburbage** [comment]
@mcilroyc  Looks good on Mac and Win at 024d8ef. Should I just close and remove the "Fixed but not closed" label, or remove all the labels?

**Comment by mcilroyc** [comment]
closing it is sufficient, labels can stay put
