### ISSUE TITLE
Cannot open Export dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2737]
Cmd+e or clicking export button at doc bar will produce warning and no dialog is opened. No errors reported. After this, menus all dimmed just like modal dialog is open somewhere. Quick export works.

![screen shot 2015-09-30 at 3 39 23 pm](https://cloud.githubusercontent.com/assets/2029597/10208628/7ee6e4ec-6789-11e5-9f7c-9b9257649691.png)

**Comment by mcilroyc** [comment]
first bad commit 
ceee37ead61a5ef21a499e663a2f3be12ca29203
@designedbyscience :fork_and_knife:

**Comment by mcilroyc** [comment]
Assigning to eric.  per slack our slack convo, we're exploring ways to provide static dialog IDs when necessary, but also not throw collision errors.

**Comment by mcilroyc** [comment]
This has been addressed by #2739

**Comment by ktaki** [comment]
Verified the fix.
