### ISSUE TITLE
Intro: Contact: Links for Gtihub and Forum have been reversed

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2742]
Clicking Github opens forum, and clicking Forum opens GitHub.
Also, "Github" should be "GitHub".

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Links are fixed.
GitHub is still shown as "Github". Is this a design consideration?

**Comment by ktaki** [comment]
Verified the fix.
