### ISSUE TITLE
CC Lib: dragging in empty or missing asset doesn't place and leaves app in bad state

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2743]
create a new doc
load library that contains an empty or missing asset (e.g. Test - OK to accidentally nuke)
drag missing or empty graphic onto canvas (e.g. I am 3D)

Icon indicates it's empty or missing:  <img width="51" alt="screen shot 2015-09-30 at 5 13 35 pm" src="https://cloud.githubusercontent.com/assets/8442631/10227136/818071f4-6820-11e5-82be-7bc95fdc3078.png">

Result: it doesn't place and you are stuck in whatever tool you started with

**Comment by shaoshing** [comment]
Fixes are:

* disabled drag-n-drop for empty graphic asset
* hovering over empty asset will show "Graphic has no content"

**Comment by chadrolfs** [comment]
after you attempt to drag and drop an empty asset, it fails as expected but subsequent attempts to drag valid assets also fail.

**Comment by shaoshing** [comment]
Hmm, I am unable to reproduce this; drang-n-drop on empty and valid asset are both working. Do you mind record a video for me?

**Comment by chadrolfs** [comment]
have you tried on Windows?  I can't seem to repro any more on Mac, but it looks like there are some serious performance issues on Windows.

**Comment by chadrolfs** [comment]
Blocked by #2805

**Comment by chadrolfs** [comment]
Able to test current master a16a13d1e39f01cd6f4e302ce729ccfb9ca6db1d with FC staging build (1600) to verify this fix
