### ISSUE TITLE
CCLib auto vacuum feature

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2751]
When a doc is opened, "Add to Library" dialog opens. If user clicks "Create New Library", it will creates new library with all or selected assets extracted from the file. In standard Ps, the file is opened and new library is selected and shown in libraries panel. In DS, the file is opened and new library is created, but the library is not shown in libraries panel.

Also, the dialog has Don't Show Again checkbox. If this is clicked, use can invoke this functionality from flyout menu attached to libraries panel (Create New Library from Document...).

Our options may be:
1. Do nothing - New library can still be selected by the user. The library name is the same as the document name. User can find it and select it easily.
2. Automatically select new library in libraries panel.
3. Add menu item "Create New Library from Document" for the case DNSA is on.
4. Suppress the dialog. DS does not support the feature at this time.

**Comment by davealonzo** [comment]
WRT #3, I already have designs done for this feature in the backlog – There's a new icon added to the bottom lineup that invokes the auto-vac workflow from the panel (Ps will be adding this icon too).
https://trello.com/c/xJrjQMEu

Although it might be too late to get this in as a integrated feature, we could consider invoking the "Add to Library" dialog again from this same icon for the time being.

**Comment by iwehrman** [comment]
Since we don't have time to support this fully for the next release, we're just going to suppress the dialog for now. [Watson 4069056](https://watsonexp.corp.adobe.com/#bug=4069056).

**Comment by tiburbage** [comment]
Taki, Ian said in the Watson to assign to you and add the "Fixed but not closed" label. I've closed the Watson side as the fix is now in staging. Please verify as well with content you know will trigger the dialog just to be sure it is fixed.

**Comment by ktaki** [comment]
Verified the fix on Mac. Will close this after testing it on Windows tomorrow morning.

**Comment by ktaki** [comment]
Verified on Windows 10.
