### ISSUE TITLE
Copy Style (Appearance) should include Opacity, Blend and Radius (if applicable)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2755]

**Comment by chadrolfs** [comment]
expectation based on user feedback

**Comment by iwehrman** [comment]
@placegraphichere: do you agree?

**Comment by shaoshing** [comment]
Just encountered this. I can take this if we decide to include these attributes.

**Comment by chadrolfs** [comment]
Do it!

**Comment by shaoshing** [comment]
When #3100 is fixed, this should become FNBC
