### ISSUE TITLE
Artboard rotates incorrectly from the Layer menu

### ISSUE THREAD

**Issue by davealonzo** [adobe-photoshop/spaces-design#2757]
* Select a new artboard
* From the Layer menu, Transform/Rotate Left (or right)

Result: Transform box rotates but not AB canvas. Expect canvas to rotate as well.

Note: Seems to correct itself when you start drawing on the canvas.

Also, we might want to consider up leveling this as an artboard related action in the file menu if fixable.

<img width="2052" alt="screen shot 2015-10-01 at 6 16 38 pm" src="https://cloud.githubusercontent.com/assets/12259315/10237670/892e6552-6869-11e5-82cd-04d861829e5f.png">

**Comment by iwehrman** [comment]
Nice catch!

**Comment by chadrolfs** [comment]
Yes!  Nice one!

**Comment by iwehrman** [comment]
This must be a core bug. Everything seems to be working correctly except that the canvas isn't re-drawing correctly. It eventually does draw correctly though, e.g., if you move a shape within the artboard. I'll file a core bug!

**Comment by iwehrman** [comment]
[Watson 4068470](https://watsonexp.corp.adobe.com/#bug=4068470)

**Comment by tiburbage** [comment]
Closed/Fixed: https://watsonexp.corp.adobe.com/#bug=4068470
Regressed in playground/...@1047501
