### ISSUE TITLE
The origin of artboard coordinates should never change

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2763]
The origin of artbpard coordinates (X, Y) is set when the artboard document is created or the first artboard is created on a document. This should never change. When layers are created outside of artboards, canvas itself may be auto-expanded, and those layers coordinates may change, but the artboard coordinates should not change.

**Comment by iwehrman** [comment]
@placegraphichere @designedbyscience: I thought, in the past, we agreed that we should just not show x/y coordinates in "infinite canvas" mode?

@ktaki: I don't really know how we can both a) show coordinates; and b) not change them when the canvas auto expands.

**Comment by ktaki** [comment]
We need to maintain the origin for artboards and the origin of layers outside of the artboards separately. The former never changes, but the latter changes.

**Comment by iwehrman** [comment]
What do you think the origin should be if not the document origin?

**Comment by ktaki** [comment]
The upper left corner of the first artboard in artboard docs.
The upper left corner of non-artboard doc (the original document origin) if artboards are added later.

**Comment by ktaki** [comment]
On the second thought, it might make more sense if coordinates of both arboards and layers outside artboards are based on the origin of artboards. That is not what standard Ps does, but it is reasonable thing to do if feasible.

**Comment by iwehrman** [comment]
This is an incredibly delicate part of the code, so I'm skeptical that we can accomplish any changes to this without significant risk. I'd also like @placegraphichere's and @designedbyscience's opinion on what they think the correct behavior should be, and whether the current state of things is a major blocker.

**Comment by iwehrman** [comment]
I'm kicking this out of M3 because I think the risk is too high.

**Comment by ktaki** [comment]
Agreed.

**Comment by chadrolfs** [comment]
reviewed - no M3

**Comment by ktaki** [comment]
@chadrolfs We should close this one too. The current coordinate system is working and we do not want to touch unless it produces significant problems.

**Comment by iwehrman** [comment]
I'm not sure I agree that the current coordinate system is working with artboards and other layers not in an artboard in artboard docs...

**Comment by ktaki** [comment]
Then, this could be converted to a story and put it in the backlog. It doesn't sound like a bug.

**Comment by chadrolfs** [comment]
I think #2756 addresses @iwehrman's concerns.  I think we can close this and maybe create a story out of it, although I'm not sure would could actually do anything with it because PS architecture doesn't allow for negative canvas coordinates.  For example, in standard PS, you can't go into Image > Canvas Size and enter a negative number.  You'll get an alert something like this (depending on what your units are set to): "A number between 0.014 and 4166.666 is required.  Closest value inserted."

I would close this and leave it at that.

**Comment by ktaki** [comment]
The way standard Ps works is the first artboard created at (0,0). This will never change.if an artboard is added to the left, then the artboard's X position becomes a negative value. With DS, it is relative to the canvas size. If the canvas is expanded to the left or up, the origin moves, therefore the existing artboard position X and Y values change.

**Comment by chadrolfs** [comment]
Ahhh, I see now.  Yeah, let's close this and do a JIRA story/task: Artboard coordinates should work like standard PS.

**Comment by ktaki** [comment]
Opened a story https://jira.corp.adobe.com/browse/PS-1414. Closing this issue.
