### ISSUE TITLE
Place linked / embedded SO freezes the app

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2770]
1 menu: file > Place Linked / Embedded ...
2 select any file and hit return
3 app frozen

This is probably related to keyboard and mouse policy as well.

**Comment by iwehrman** [comment]
FBNC. Over to @chadrolfs to verify.

**Comment by shaoshing** [comment]
@chadrolfs This is fixed but it has the side effect described in #2849 which I am working on
