### ISSUE TITLE
Transform controls no longer show when more than one artboard is selected

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2775]
new doc
create more than one artboard 
select them either via cmd+click in layers panel or via shift+click on canvas with Select tool

**Comment by iwehrman** [comment]
Possibly related to #2723?

**Comment by iwehrman** [comment]
Over to @chadrolfs for a `git bisect` as time allows and priority dictates.

**Comment by chadrolfs** [comment]
tried to bisect but kept running into errors loading due to adapter issues.

**Comment by iwehrman** [comment]
I would say "you probably have to run `bower install`" between bisecting steps, but a) I don't think it will be that easy, and b) it's probably not worth it. I'll have a look.

@mcilroyc: this is a good one to keep in mind when we have our next quarterly release engineering showdown.

**Comment by mcilroyc** [comment]
[release mgmt subtopic] Yes.  I also think there's another level of unfortunateness when bisecting across PS build versions; this should be considered to some degree.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4071094

**Comment by iwehrman** [comment]
According to CJB, this is as designed.

**Comment by chadrolfs** [comment]
Yeah, makes me a little sad.
