### ISSUE TITLE
Type color picker is sized incorrectly

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2778]
![image](https://cloud.githubusercontent.com/assets/1075154/10260507/b13bac40-692b-11e5-8f0c-ca027d65979c.png)

**Comment by chrisbank** [comment]
This is probably more or a feature request, but you could also add a lightness slider in there. Here's an example from the Reflow color picker (that was done in JS). I know Dreamweaver and Animate have similar color pickers. 
![colorpicker](https://cloud.githubusercontent.com/assets/458642/10285982/2f187e70-6b40-11e5-881a-16237012d81f.png)

**Comment by iwehrman** [comment]
Good idea! I'll add this to the [wishlist](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist).

**Comment by iwehrman** [comment]
@designedbyscience Can you take a look at this before UIF?

**Comment by iwehrman** [comment]
Fixed by #2829.
