### ISSUE TITLE
Opening file results in Uncaught TypeError

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2779]
Open explore-mt-hood.psd  (in my transfer on sjshare if you don't have it already)

Result: `Action documents.open failed: TypeError: Cannot read property 'layers' of null`

**Comment by iwehrman** [comment]
Can you post the entire stack trace?

**Comment by chadrolfs** [comment]
<img width="1037" alt="screen shot 2015-10-05 at 9 15 17 am" src="https://cloud.githubusercontent.com/assets/8442631/10286233/a6aa99e0-6b41-11e5-8de9-840ee62dc78f.png">

**Comment by chadrolfs** [comment]
Also happens when you open Vermillions
