### ISSUE TITLE
Layers panel moves with every click in single-column mode

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2783]
Single-column mode is difficult to use because whenever you click in the panel to select a different layer, the panel position shifts vertically. This is because its position is dependent on the contents of the appearance and effects of that layer. I think, in order for it to be usable, we need to find a way to affix the layers panel to the bottom of the column in single-column mode so that only the usable height _above_ the layers panel changes when selecting different layers.

CC @designedbyscience @placegraphichere

**Comment by chadrolfs** [comment]
grabbing this to verify fix
