### ISSUE TITLE
Controller transfer is not currency-safe

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2791]
First observed in the wild in #2790, the problem is that `this.transfer` does not provide the same concurrency-safety guarantees that top-level actions provide. For example, if a transaction transfers to two actions concurrently, their execution may be interleaved _even if they read and write the same state_. The controller protects against this among top-level actions, but not among intra-action transfers. 

A possible solution may be to rewrite `transfer` to make use of per-action `AsyncDependencyQueue` instances, which sounds like fun.

**Comment by shaoshing** [comment]
Assign back to @iwehrman in case he has other plan for this issues.

**Comment by iwehrman** [comment]
Nope! The only other action item here would to reconsider our use of many `transfer` calls in place of coarser actions that manage concurrency manually in order to improve performance. An example is `tools.beforeStartup` which was previously transferring to `addShortcut` once for each tool shortcut. After #2790, these are all serialized because they all write to the policy store. I added a new action `addShortcuts` which bulk-adds shortcuts using a single call to update the policies, and that is unsurprisingly much faster! There may be other cases where we can do the same thing. But I'm still going to close this bug. I'm just writing this here for @shaoshing so we're on the same page :sunflower:
