### ISSUE TITLE
Slow Generator failure blocks File > New

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2799]
When Generator fails to start, `exports.beforeStartup` holds the `JS_EXPORT` write lock for a very long time. The `documents.createNew` action also requires the `JS_EXPORT` lock because. This prevents File > New from working while Generator is slowly failing. 

In some sense, this is how it should be working. On the other hand, it would be nice to break up at least one of these actions so that system can remain responsive while Generator is starting up. Even when Generator is installed correctly, this will cause the system to be unresponsive while Generator is first starting up, which can take a while even in the best case.

CC @mcilroyc

**Comment by iwehrman** [comment]
@pineapplespatula: do you mind verifying the fix?

**Comment by pineapplespatula** [comment]
Nicely done this looks good
