### ISSUE TITLE
Typeface datalist field is empty for missing fonts

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2804]
Open a file with missing fonts and select one of those layers in the layers panel

Result: Typeface field is empty
Expected: `missing`

![screen shot 2015-10-05 at 1 55 14 pm](https://cloud.githubusercontent.com/assets/8442631/10293344/db2921a6-6b68-11e5-8775-b16ac035115f.png)

**Comment by ktaki** [comment]
We should show the font name with an indication of the font is missing. In standard Ps, the font name is surrounded by [ ].

**Comment by designedbyscience** [comment]
FBNC over to @chadrolfs
