### ISSUE TITLE
Windows performance lag after dragging CC Lib asset 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2805]
ctrl + n
select and drag a graphic library asset onto canvas, hit Enter to place, then Delete
click on CC Library drop down menu to select a new library

Result: performance now goes to a crawl and it's hard to select a new library

Selecting tools takes two or more clicks

**Comment by chadrolfs** [comment]
rendered file:///C:/Users/crolfs/Documents/GitHub/spaces-design/src/style/main.less successfully.
less.js:775 css for file:///C:/Users/crolfs/Documents/GitHub/spaces-design/src/style/main.less generated in 286ms
less.js:775 less has finished. css generated in 288ms
react-with-addons.js:4486 Download the React DevTools for a better development experience: https://fb.me/react-devtools
main.js:74 Spaces plugin version: 2.0.7
fluxcontroller.js:533 Enqueuing action ui.updateToolbarWidth; 0/0
fluxcontroller.js:533 Enqueuing action ui.updatePanelSizes; 1/0
fluxcontroller.js:533 Enqueuing action ui.updatePanelSizes; 1/1
main.js:91 Main component mounted: 63ms
fluxcontroller.js:554 Executing action ui.updateToolbarWidth after waiting 4ms; 1/2
fluxcontroller.js:533 Enqueuing action ui.beforeStartup; 1/2
fluxcontroller.js:533 Enqueuing action menu.beforeStartup; 1/3
fluxcontroller.js:533 Enqueuing action history.beforeStartup; 2/3
fluxcontroller.js:533 Enqueuing action keyevents.beforeStartup; 3/3
fluxcontroller.js:533 Enqueuing action layers.beforeStartup; 4/3
fluxcontroller.js:533 Enqueuing action libraries.beforeStartup; 4/4
fluxcontroller.js:533 Enqueuing action guides.beforeStartup; 5/4
fluxcontroller.js:533 Enqueuing action policy.beforeStartup; 6/4
fluxcontroller.js:533 Enqueuing action search.beforeStartup; 6/5
fluxcontroller.js:533 Enqueuing action shortcuts.beforeStartup; 7/5
fluxcontroller.js:533 Enqueuing action tools.beforeStartup; 8/5
fluxcontroller.js:533 Enqueuing action transform.beforeStartup; 8/6
fluxcontroller.js:533 Enqueuing action documents.beforeStartup; 8/7
fluxcontroller.js:554 Executing action menu.beforeStartup after waiting 1ms; 8/8
fluxcontroller.js:554 Executing action history.beforeStartup after waiting 0ms; 8/8
fluxcontroller.js:554 Executing action keyevents.beforeStartup after waiting 0ms; 8/8
fluxcontroller.js:554 Executing action libraries.beforeStartup after waiting 0ms; 8/8
fluxcontroller.js:554 Executing action guides.beforeStartup after waiting 0ms; 8/8
fluxcontroller.js:554 Executing action search.beforeStartup after waiting 0ms; 8/8
fluxcontroller.js:554 Executing action shortcuts.beforeStartup after waiting 0ms; 8/8
fluxcontroller.js:564 Finished action menu.beforeStartup in 65ms with RTT 66ms; 8/8
fluxcontroller.js:564 Finished action history.beforeStartup in 65ms with RTT 65ms; 8/8
fluxcontroller.js:564 Finished action keyevents.beforeStartup in 65ms with RTT 65ms; 8/8
fluxcontroller.js:564 Finished action libraries.beforeStartup in 64ms with RTT 64ms; 8/8
fluxcontroller.js:564 Finished action guides.beforeStartup in 65ms with RTT 65ms; 8/8
fluxcontroller.js:564 Finished action search.beforeStartup in 68ms with RTT 68ms; 8/8
fluxcontroller.js:564 Finished action shortcuts.beforeStartup in 67ms with RTT 67ms; 8/8
fluxcontroller.js:554 Executing action transform.beforeStartup after waiting 83ms; 2/7
fluxcontroller.js:564 Finished action transform.beforeStartup in 44ms with RTT 127ms; 2/7
fluxcontroller.js:564 Finished action ui.updateToolbarWidth in 285ms with RTT 289ms; 1/7
fluxcontroller.js:554 Executing action ui.updatePanelSizes after waiting 299ms; 1/6
fluxcontroller.js:564 Finished action ui.updatePanelSizes in 101ms with RTT 400ms; 1/6
fluxcontroller.js:554 Executing action ui.updatePanelSizes after waiting 416ms; 1/5
fluxcontroller.js:564 Finished action ui.updatePanelSizes in 99ms with RTT 515ms; 1/5
fluxcontroller.js:554 Executing action ui.beforeStartup after waiting 478ms; 2/3
fluxcontroller.js:554 Executing action documents.beforeStartup after waiting 472ms; 2/3
fluxcontroller.js:564 Finished action documents.beforeStartup in 73ms with RTT 545ms; 2/3
fluxcontroller.js:564 Finished action ui.beforeStartup in 149ms with RTT 627ms; 1/3
fluxcontroller.js:554 Executing action layers.beforeStartup after waiting 645ms; 1/2
fluxcontroller.js:564 Finished action layers.beforeStartup in 167ms with RTT 812ms; 1/2
fluxcontroller.js:554 Executing action policy.beforeStartup after waiting 829ms; 1/1
fluxcontroller.js:564 Finished action policy.beforeStartup in 52ms with RTT 881ms; 1/1
fluxcontroller.js:554 Executing action tools.beforeStartup after waiting 897ms; 1/0
fluxcontroller.js:564 Finished action tools.beforeStartup in 308ms with RTT 1205ms; 1/0
fluxcontroller.js:533 Enqueuing action ui.afterStartup; 0/0
fluxcontroller.js:533 Enqueuing action application.afterStartup; 1/0
fluxcontroller.js:533 Enqueuing action export.afterStartup; 1/1
fluxcontroller.js:533 Enqueuing action help.afterStartup; 2/1
fluxcontroller.js:533 Enqueuing action layers.afterStartup; 2/2
fluxcontroller.js:533 Enqueuing action libraries.afterStartup; 3/2
fluxcontroller.js:533 Enqueuing action menu.afterStartup; 4/2
fluxcontroller.js:533 Enqueuing action documents.afterStartup; 5/2
main.js:86 Actions loaded: 1372ms
fluxcontroller.js:554 Executing action ui.afterStartup after waiting 1ms; 5/3
fluxcontroller.js:554 Executing action export.afterStartup after waiting 1ms; 5/3
fluxcontroller.js:554 Executing action layers.afterStartup after waiting 0ms; 5/3
fluxcontroller.js:554 Executing action libraries.afterStartup after waiting 0ms; 5/3
fluxcontroller.js:554 Executing action menu.afterStartup after waiting 1ms; 5/3
main.js:97 Startup complete: 1392ms
fluxcontroller.js:564 Finished action layers.afterStartup in 43ms with RTT 43ms; 5/3
fluxcontroller.js:564 Finished action menu.afterStartup in 41ms with RTT 42ms; 5/3
export.js:296 Export: Found configured port: 59596
fluxcontroller.js:564 Finished action libraries.afterStartup in 53ms with RTT 53ms; 5/3
fluxcontroller.js:564 Finished action ui.afterStartup in 65ms with RTT 66ms; 3/3
fluxcontroller.js:554 Executing action application.afterStartup after waiting 65ms; 3/1
fluxcontroller.js:554 Executing action documents.afterStartup after waiting 63ms; 3/1
fluxcontroller.js:564 Finished action documents.afterStartup in 3ms with RTT 66ms; 3/1
fluxcontroller.js:533 Enqueuing action ui.updatePanelSizes; 2/1
fluxcontroller.js:564 Finished action application.afterStartup in 53ms with RTT 118ms; 2/2
fluxcontroller.js:554 Executing action help.afterStartup after waiting 118ms; 2/1
fluxcontroller.js:564 Finished action help.afterStartup in 1ms with RTT 119ms; 2/1
fluxcontroller.js:554 Executing action ui.updatePanelSizes after waiting 5ms; 2/0
fluxcontroller.js:564 Finished action ui.updatePanelSizes in 38ms with RTT 43ms; 2/0
export.js:858 Export: Generator plugin connection established
fluxcontroller.js:564 Finished action export.afterStartup in 376ms with RTT 377ms; 1/0
fluxcontroller.js:533 Enqueuing action documents.createNew; 0/0
fluxcontroller.js:554 Executing action documents.createNew after waiting 2ms; 1/0
fluxcontroller.js:533 Enqueuing action ui.updatePanelSizes; 1/0
fluxcontroller.js:533 Enqueuing action ui.setTransform; 1/1
history.js:331 Initializing history based on historyState event from ps. Object
history.js:185 Initializing history with 2 states
fluxcontroller.js:564 Finished action documents.createNew in 1399ms with RTT 1401ms; 1/2
fluxcontroller.js:554 Executing action ui.updatePanelSizes after waiting 603ms; 1/1
fluxcontroller.js:564 Finished action ui.updatePanelSizes in 19ms with RTT 622ms; 1/1
fluxcontroller.js:554 Executing action ui.setTransform after waiting 195ms; 1/0
fluxcontroller.js:564 Finished action ui.setTransform in 11ms with RTT 206ms; 1/0
fluxcontroller.js:533 Enqueuing action policy.addKeyboardPolicies; 0/0
fluxcontroller.js:554 Executing action policy.addKeyboardPolicies after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action policy.addKeyboardPolicies in 10ms with RTT 10ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action dialog.openDialog; 1/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 1/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 3ms with RTT 3ms; 1/1
fluxcontroller.js:554 Executing action dialog.openDialog after waiting 3ms; 1/0
fluxcontroller.js:564 Finished action dialog.openDialog in 15ms with RTT 18ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action libraries.selectLibrary; 1/0
fluxcontroller.js:533 Enqueuing action dialog.closeDialog; 2/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 1ms; 2/1
fluxcontroller.js:554 Executing action libraries.selectLibrary after waiting 0ms; 2/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 81ms with RTT 82ms; 2/1
fluxcontroller.js:564 Finished action libraries.selectLibrary in 82ms with RTT 82ms; 2/0
fluxcontroller.js:554 Executing action dialog.closeDialog after waiting 81ms; 2/0
fluxcontroller.js:564 Finished action dialog.closeDialog in 3ms with RTT 84ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action dialog.openDialog; 1/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 1/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 4ms with RTT 4ms; 1/1
fluxcontroller.js:554 Executing action dialog.openDialog after waiting 3ms; 1/0
fluxcontroller.js:564 Finished action dialog.openDialog in 11ms with RTT 14ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action libraries.selectLibrary; 1/0
fluxcontroller.js:533 Enqueuing action dialog.closeDialog; 2/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 2/1
fluxcontroller.js:554 Executing action libraries.selectLibrary after waiting 1ms; 2/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 120ms with RTT 120ms; 2/1
fluxcontroller.js:564 Finished action libraries.selectLibrary in 122ms with RTT 123ms; 2/0
fluxcontroller.js:554 Executing action dialog.closeDialog after waiting 121ms; 2/0
fluxcontroller.js:564 Finished action dialog.closeDialog in 5ms with RTT 126ms; 1/0
fluxcontroller.js:533 Enqueuing action libraries.selectLibrary; 0/0
fluxcontroller.js:554 Executing action libraries.selectLibrary after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action libraries.selectLibrary in 53ms with RTT 54ms; 1/0
fluxcontroller.js:533 Enqueuing action policy.removeKeyboardPolicies; 0/0
fluxcontroller.js:554 Executing action policy.removeKeyboardPolicies after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action policy.removeKeyboardPolicies in 12ms with RTT 12ms; 1/0
fluxcontroller.js:533 Enqueuing action libraries.createLayerFromElement; 0/0
fluxcontroller.js:554 Executing action libraries.createLayerFromElement after waiting 1ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.handleToolModalStateChanged; 1/0
fluxcontroller.js:564 Finished action libraries.createLayerFromElement in 230ms with RTT 231ms; 1/1
fluxcontroller.js:554 Executing action tools.handleToolModalStateChanged after waiting 55ms; 1/0
fluxcontroller.js:564 Finished action tools.handleToolModalStateChanged in 6ms with RTT 61ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.handleToolModalStateChanged; 0/0
history.js:305 History state event from photoshop (raw): currentState (index) 1, total states: 1
fluxcontroller.js:533 Enqueuing action history.handleHistoryState; 1/0
fluxcontroller.js:542 Killing modal state for action history.handleHistoryState
fluxcontroller.js:554 Executing action tools.handleToolModalStateChanged after waiting 0ms; 2/0
fluxcontroller.js:564 Finished action tools.handleToolModalStateChanged in 7ms with RTT 7ms; 2/0
history.js:305 History state event from photoshop (raw): currentState (index) 2, total states: 2
fluxcontroller.js:533 Enqueuing action history.handleHistoryState; 1/0
fluxcontroller.js:533 Enqueuing action documents.handlePlaceEvent; 1/1
fluxcontroller.js:533 Enqueuing action libraries.handleCompletePlacingGraphic; 1/2
fluxcontroller.js:554 Executing action libraries.handleCompletePlacingGraphic after waiting 0ms; 2/2
fluxcontroller.js:564 Finished action libraries.handleCompletePlacingGraphic in 37ms with RTT 37ms; 2/2
fluxcontroller.js:554 Executing action history.handleHistoryState after waiting 0ms; 1/2
fluxcontroller.js:564 Finished action history.handleHistoryState in 114ms with RTT 114ms; 1/2
fluxcontroller.js:554 Executing action history.handleHistoryState after waiting 74ms; 1/1
history.js:308 This is a ROGUE history-changing event Object
history.js:663 History state added or merged: 2
fluxcontroller.js:564 Finished action history.handleHistoryState in 2ms with RTT 76ms; 1/1
fluxcontroller.js:554 Executing action documents.handlePlaceEvent after waiting 73ms; 1/0
history.js:553 Pushing history for an action for which we expect to have gotten a rogue history event
history.js:643 Updating the previous history state instead of pushing (coalesce or rogue-catchup)
history.js:663 History state added or merged: 2
fluxcontroller.js:564 Finished action documents.handlePlaceEvent in 83ms with RTT 156ms; 1/0
fluxcontroller.js:533 Enqueuing action layers.deleteSelected; 0/0
fluxcontroller.js:554 Executing action layers.deleteSelected after waiting 1ms; 1/0
history.js:305 History state event from photoshop (raw): currentState (index) 3, total states: 3
fluxcontroller.js:533 Enqueuing action history.handleHistoryState; 1/0
history.js:553 Pushing history for an action for which we expect to have gotten a rogue history event
history.js:663 History state added or merged: 3
fluxcontroller.js:564 Finished action layers.deleteSelected in 134ms with RTT 135ms; 1/1
fluxcontroller.js:554 Executing action history.handleHistoryState after waiting 100ms; 1/0
fluxcontroller.js:564 Finished action history.handleHistoryState in 1ms with RTT 101ms; 1/0
fluxcontroller.js:533 Enqueuing action policy.addKeyboardPolicies; 0/0
fluxcontroller.js:554 Executing action policy.addKeyboardPolicies after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action policy.addKeyboardPolicies in 22ms with RTT 23ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 4ms with RTT 5ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action dialog.openDialog; 1/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 1/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 3ms with RTT 3ms; 1/1
fluxcontroller.js:554 Executing action dialog.openDialog after waiting 2ms; 1/0
fluxcontroller.js:564 Finished action dialog.openDialog in 11ms with RTT 13ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 3ms with RTT 3ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action libraries.selectLibrary; 1/0
fluxcontroller.js:533 Enqueuing action dialog.closeDialog; 2/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 2/1
fluxcontroller.js:554 Executing action libraries.selectLibrary after waiting 0ms; 2/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 808ms with RTT 808ms; 2/1
fluxcontroller.js:564 Finished action libraries.selectLibrary in 826ms with RTT 826ms; 2/0
fluxcontroller.js:554 Executing action dialog.closeDialog after waiting 824ms; 2/0
fluxcontroller.js:564 Finished action dialog.closeDialog in 7ms with RTT 831ms; 1/0
fluxcontroller.js:533 Enqueuing action libraries.selectLibrary; 0/0
fluxcontroller.js:554 Executing action libraries.selectLibrary after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action libraries.selectLibrary in 34ms with RTT 35ms; 1/0
fluxcontroller.js:533 Enqueuing action policy.removeKeyboardPolicies; 0/0
fluxcontroller.js:554 Executing action policy.removeKeyboardPolicies after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action policy.removeKeyboardPolicies in 19ms with RTT 20ms; 1/0
fluxcontroller.js:533 Enqueuing action superselect.marqueeSelect; 0/0
fluxcontroller.js:533 Enqueuing action tools.select; 1/0
fluxcontroller.js:554 Executing action superselect.marqueeSelect after waiting 0ms; 1/1
fluxcontroller.js:564 Finished action superselect.marqueeSelect in 5ms with RTT 5ms; 1/1
fluxcontroller.js:554 Executing action tools.select after waiting 4ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 156ms with RTT 160ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 102ms with RTT 102ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 116ms with RTT 117ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 100ms with RTT 101ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 91ms with RTT 91ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 1ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 98ms with RTT 99ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 185ms with RTT 185ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 118ms with RTT 118ms; 1/0
history.js:305 History state event from photoshop (raw): currentState (index) 4, total states: 4
fluxcontroller.js:533 Enqueuing action history.handleHistoryState; 0/0
fluxcontroller.js:533 Enqueuing action layers.addLayers; 1/0
fluxcontroller.js:554 Executing action history.handleHistoryState after waiting 0ms; 1/1
history.js:308 This is a ROGUE history-changing event Object
history.js:663 History state added or merged: 4
fluxcontroller.js:564 Finished action history.handleHistoryState in 2ms with RTT 2ms; 1/1
fluxcontroller.js:554 Executing action layers.addLayers after waiting 2ms; 1/0
history.js:553 Pushing history for an action for which we expect to have gotten a rogue history event
history.js:643 Updating the previous history state instead of pushing (coalesce or rogue-catchup)
history.js:663 History state added or merged: 4
fluxcontroller.js:564 Finished action layers.addLayers in 140ms with RTT 142ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 0ms; 1/0
fluxcontroller.js:564 Finished action tools.select in 169ms with RTT 169ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 0/0
fluxcontroller.js:554 Executing action tools.select after waiting 0ms; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 1/0
fluxcontroller.js:533 Enqueuing action tools.select; 1/1
fluxcontroller.js:533 Enqueuing action tools.select; 1/2
fluxcontroller.js:533 Enqueuing action tools.select; 1/3
fluxcontroller.js:533 Enqueuing action tools.select; 1/4
fluxcontroller.js:533 Enqueuing action tools.select; 1/5
fluxcontroller.js:533 Enqueuing action tools.select; 1/6
fluxcontroller.js:533 Enqueuing action tools.select; 1/7
fluxcontroller.js:533 Enqueuing action tools.select; 1/8
fluxcontroller.js:533 Enqueuing action tools.select; 1/9
fluxcontroller.js:533 Enqueuing action layers.handleCanvasShift; 1/10
history.js:305 History state event from photoshop (raw): currentState (index) 5, total states: 5
fluxcontroller.js:533 Enqueuing action history.handleHistoryState; 1/11
fluxcontroller.js:554 Executing action history.handleHistoryState after waiting 1ms; 2/11
history.js:308 This is a ROGUE history-changing event Object
history.js:663 History state added or merged: 5
fluxcontroller.js:564 Finished action history.handleHistoryState in 3ms with RTT 4ms; 2/11
fluxcontroller.js:533 Enqueuing action layers.addLayers; 1/11
fluxcontroller.js:533 Enqueuing action ui.setTransform; 1/12
fluxcontroller.js:564 Finished action tools.select in 10980ms with RTT 10980ms; 1/13
fluxcontroller.js:554 Executing action tools.select after waiting 9606ms; 1/12
fluxcontroller.js:533 Enqueuing action layers.addLayers; 1/12
fluxcontroller.js:533 Enqueuing action tools.handleToolModalStateChanged; 1/13
fluxcontroller.js:533 Enqueuing action tools.handleToolModalStateChanged; 1/14
history.js:305 History state event from photoshop (raw): currentState (index) 6, total states: 6
fluxcontroller.js:533 Enqueuing action history.handleHistoryState; 1/15
fluxcontroller.js:554 Executing action history.handleHistoryState after waiting 0ms; 2/15
history.js:308 This is a ROGUE history-changing event Object
history.js:663 History state added or merged: 6
fluxcontroller.js:564 Finished action history.handleHistoryState in 4ms with RTT 4ms; 2/15
fluxcontroller.js:564 Finished action tools.select in 431ms with RTT 10037ms; 1/15
fluxcontroller.js:554 Executing action tools.select after waiting 9196ms; 1/14
fluxcontroller.js:564 Finished action tools.select in 76ms with RTT 9272ms; 1/14
fluxcontroller.js:554 Executing action tools.select after waiting 8409ms; 1/13
fluxcontroller.js:564 Finished action tools.select in 68ms with RTT 8477ms; 1/13
fluxcontroller.js:554 Executing action tools.select after waiting 8069ms; 1/12
fluxcontroller.js:564 Finished action tools.select in 67ms with RTT 8136ms; 1/12
fluxcontroller.js:554 Executing action tools.select after waiting 7520ms; 1/11

**Comment by chadrolfs** [comment]
looks specific to dev build 702.  Core issue?

**Comment by chadrolfs** [comment]
I don't see this issue using the FC staging build (1600) with current master @ a16a13d1e39f01cd6f4e302ce729ccfb9ca6db1d

**Comment by iwehrman** [comment]
Were you switching tools? It looks like that's the action that's taking a very long time. What tools were you switching to/from?

**Comment by iwehrman** [comment]
It seems like this is FBNC by @jsbache. Back to @chadrolfs.
