### ISSUE TITLE
Setting stroke alignment fails

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2806]
new doc
hit r to make Rect tool active and drag out a rect
click on Outside icon for Apperance Stroke

Result: `Action shapes.setStrokeAlignment failed: TypeError: Cannot read property 'every' of undefined`

**Comment by chadrolfs** [comment]
![screen shot 2015-10-05 at 2 55 03 pm](https://cloud.githubusercontent.com/assets/8442631/10294781/3d16d6f8-6b71-11e5-861d-dee5485a5988.png)

**Comment by iwehrman** [comment]
I'll take a look.

**Comment by iwehrman** [comment]
I pushed a tiny fix right to master for this in 1c8bfb2dc41d718a571c04d67d51cf1566635273. FBNC to @chadrolfs.
