### ISSUE TITLE
ESCing out of export dialog throws error

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#2807]
1. Add Asset
1. Click "PNG" drop down
1. Hit ESC key

![ss](http://cl.ly/image/2s382E3l0R1k/Image%202015-10-05%20at%204.56.29%20PM.png)

**Comment by mcilroyc** [comment]
Asking @ktaki to validate this.  Note that I closed related bug #2808 myself, but wanted you to at least be aware of it.  I believe there is an annoyance remaining: after making a selection by hitting the enter key, the input loses focus, but I wanted to keep this bug fix narrow.

**Comment by ktaki** [comment]
Verified the fix.
