### ISSUE TITLE
Standard PS context menu available in mask mode

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2811]
![image](https://cloud.githubusercontent.com/assets/1075154/10295570/5c5363ba-6b76-11e5-8da2-fac38a9dfd8d.png)

**Comment by pineapplespatula** [comment]
watson bug 4070997

**Comment by iwehrman** [comment]
I can't repro this any longer, but I'm not sure why because that Watson bug hasn't budged...

**Comment by iwehrman** [comment]
FBNC to @chadrolfs. pgdev.800 required.
