### ISSUE TITLE
Error on pressing 'a' to enter vector mask editing mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2813]
Press 'm' then 'a', Escape or Enter to end editing mode. Reenter editing mode by 'a'.

Uncaught Error: Photoshop returned an error when executing command number: 1 Photoshop code: -128 Photoshop message:

![screen shot 2015-10-05 at 3 48 09 pm](https://cloud.githubusercontent.com/assets/2029597/10295894/c572a35e-6b78-11e5-9327-90990fcdce80.png)

**Comment by pineapplespatula** [comment]
@ktaki is this issue still occurring?

**Comment by ktaki** [comment]
I do not see the error in console anymore. However, 'a' does not work most of the time. It seems the mode got stuck in transformation mode.

**Comment by ktaki** [comment]
This error is no longer happening, but the action still causes an error. Reported as #2868. Closing this one.
