### ISSUE TITLE
Incorrect layer index after placing file

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2819]
1. Create a new artboard document.
2. Drag an image from the desktop onto the document.
3. Place the image.

Result: the empty layer remains next to the new layer that corresponds to the placed layer. But, the empty layer has been removed by Photoshop.
Expected: The artboard has only one child layer, which is the placed layer.

**Comment by iwehrman** [comment]
CC @mcilroyc @shaoshing. Is this a dupe? I know we've gone back and forth on this with `addLayers`...

**Comment by mcilroyc** [comment]
I'm not aware of a dupe.  It is semi-related to a bug on my plate, but not a dupe.  1613.  I can take this if neither of you has an affinity for it.

**Comment by shaoshing** [comment]
For future reference:

The expected behaviors after placing file 

1. place file via menu item (place linked or embedded): empty layer will be replaced.
2. drag-n-drop local file: empty layer will be replaced.
3. drag-n-drop CC libraries graphic: empty layer will not be replaced.

https://www.dropbox.com/s/j2zso98s9qzd927/replace-layer.mov?dl=0

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
caveat: empty layer needs to be targeted (selected in layers panel) for it to be replaced.

**Comment by mcilroyc** [comment]
yes, just confirming/agreeing, that is part of PS's heuristic, as far as we can tell
