### ISSUE TITLE
Change Width/Height will change X and Y instead

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2820]
Reproduce: 

1 create a vector
2 deselect and then select the vector
3 use up/down arrow keys to change width or height
4 double click the vector
5 use up/down arrow keys to change width or height
6 go back to setp 2 

https://www.dropbox.com/s/1fe0jpo59xu0idj/rp-2.mov?dl=0

**Comment by chadrolfs** [comment]
I think this is a dupe of #2776.
