### ISSUE TITLE
Need to make tracking field wider 

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2821]
The maximum number allowed is 10,000.

![screen shot 2015-10-05 at 5 26 09 pm copy](https://cloud.githubusercontent.com/assets/2029597/10297381/f11f9954-6b86-11e5-9403-87c2cf477c40.png)
![screen shot 2015-10-05 at 5 26 19 pm copy](https://cloud.githubusercontent.com/assets/2029597/10297382/f3978be2-6b86-11e5-8a60-65148826150b.png)

**Comment by designedbyscience** [comment]
Back for verification

**Comment by ktaki** [comment]
Verified the fix.
