### ISSUE TITLE
Clicking 'x' in search box does not dismiss the search dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2824]
Reported by John F. I wonder if this 'x' ever worked. If we follow the Export dialog's case, we might want to simply remove it. (Or, if this simple 'x' is useful for reminding users clicking it to dismiss the dialog, we might want to add it to Export dialog also.)

**Comment by iwehrman** [comment]
FBNC to @ktaki. The "X" is designed to clear the input. It is now only visible when the search field is non-empty.

**Comment by ktaki** [comment]
A Ha! Opened #2848 as UI issue.
