### ISSUE TITLE
Sampler: Shift + click to sample Typeface fails

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2826]
create two type layers with different properties (including Typeface)
with one type layer selected, hit i for the Sampler tool
mouse over the other type layer, hold down Shift and click

Result: `Action sampler.click failed: TypeError: undefined is not a function`

**Comment by chadrolfs** [comment]
![screen shot 2015-10-06 at 8 44 17 am](https://cloud.githubusercontent.com/assets/8442631/10313804/52b7e0e8-6c06-11e5-9677-782223a2ad22.png)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
