### ISSUE TITLE
Document header resets when mask mode is active 

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2843]
Repro: 

1. Create a lot of new documents so there is overflow in the document header
2. Press "m"
3. Header should clear and then open all the documents again. Exaggerated flicker.

**Comment by iwehrman** [comment]
The problem specifically here is the exaggerated flicker. It should be possible to repro this also with Help > Test Action Failure. The fix is to ensure that the DocumentHeader sCU does not allow rendering when the controller is resetting.

**Comment by mcilroyc** [comment]
To @DivyaPrabhakar for validation of the fix

**Comment by DivyaPrabhakar** [comment]
Looks good @mcilroyc!
