### ISSUE TITLE
Confusing icon 'x' in the search dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2848]
Most of people think that 'x' in the search dialog is for dismissing the dialog. It is, however, meant to be clearing the input. The icon need to be modified to avoid confusion.

**Comment by iwehrman** [comment]
This is the pattern in use:
![image](https://cloud.githubusercontent.com/assets/1075154/10326506/d9d446e4-6c50-11e5-89da-c498d4a1eeba.png)

**Comment by iwehrman** [comment]
@placegraphichere: do you think this is a bug? Can you either a) articulate exactly how you think this should work and then assign to @DivyaPrabhakar; or, if it already works exactly as intended, b) close the bug?

**Comment by iwehrman** [comment]
@ktaki: @placegraphichere has updated the icon to be less confusing. Let us know what you think!

**Comment by chadrolfs** [comment]
As in, there is no more `x`?

**Comment by iwehrman** [comment]
It's a different X that may look more like the Mac OS "clear input" icon compared to a "close window" icon.

**Comment by ktaki** [comment]
Yes, that is better.
