### ISSUE TITLE
Placing CC Lib asset breaks scrim layer highlighting

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2849]
https://www.dropbox.com/s/kty0gmxwvhhwypo/CCLibAsset-breaksLayerHighlight.mov?dl=0

**Comment by iwehrman** [comment]
Weird. Looks like a policy problem. I wonder if @shaoshing's current branch in his open PR #2837 solves this?

**Comment by shaoshing** [comment]
@iwehrman this is not related to the PR. I will look into it.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
