### ISSUE TITLE
Doc titles no longer showing

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2855]
Open several documents

Result: nothing in title bar.  they are still listed under the Window menu

**Comment by iwehrman** [comment]
I probably broke this somehow with #2847.

**Comment by DivyaPrabhakar** [comment]
@chadrolfs happened to me too. I checked and yes, @iwehrman it was your PR

**Comment by chadrolfs** [comment]
looks fixed now with last git pull

**Comment by iwehrman** [comment]
I can't repro this. Are there different steps?

**Comment by DivyaPrabhakar** [comment]
@iwehrman close all documents in Ds and Ds completely. Restart it and then try to create new document.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs
