### ISSUE TITLE
Re-entering Mask mode to edit results in free transform error

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2859]
Open an image (target a pixel layer)
hit m to enter Mask Mode
hit r for Rect tool and drag out a shape
hit a to edit vector anchor points and drag an anchor point
hit m to exit Mask mode
hit m to re-enter Mask mode
hit a to edit and click on an anchor point

Result: `Photoshop returned from free transform path modal state with an error`

https://www.dropbox.com/s/51w812lij670ury/Mask-edit-Err.mov?dl=0

**Comment by pineapplespatula** [comment]
exiting the modal state without changing anything results in a PS error. I think it is too late in the cycle to change this in PS, 
i could change the log.error to just a warning, if you would prefer
