### ISSUE TITLE
Hitting Delete upon entering Mask mode should remove existing mask

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2860]
Deleting a mask should be easy and straight forward.

Open an image (target a pixel layer)
hit m to enter Mask Mode
hit r for Rect tool and drag out a shape
hit m to exit Mask mode
hit m to re-enter Mask mode
hit Delete

Result: nothing
Expect: Mask is removed

Workaround: enter mask mode, hit a, then hit Delete.

**Comment by chadrolfs** [comment]
If there is no mask, hitting Delete should do nothing if you're in Mask edit mode.

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs.   I'll note for the record that when you delete the existing mask, it seems a little unfortunate to me that you get kicked out of mask mode ... but I could be wrong, or maybe that's hard, dunno.

**Comment by ktaki** [comment]
Hitting delete key deletes all paths. If multiple paths exit, I expect only selected path is deleted.

**Comment by pineapplespatula** [comment]
I'm trying for an improved workflow

**Comment by chadrolfs** [comment]
ah ok, does that cover #2977 case?

**Comment by pineapplespatula** [comment]
yes

**Comment by chadrolfs** [comment]
Closing this.  As the issue is written, this is fixed.  #2978 can cover #2977
