### ISSUE TITLE
CC Libraries asset names do not scale with UI

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2861]
Here's the UI with a root font-size of 43%:
![image](https://cloud.githubusercontent.com/assets/1075154/10351418/4be74210-6cfe-11e5-8b72-d120d7b85f6a.png)

Here's the UI with a root font-size of 100%:
![image](https://cloud.githubusercontent.com/assets/1075154/10351407/46f3c10c-6cfe-11e5-9bf2-0a6a644c07d7.png)

**Comment by iwehrman** [comment]
Marking this as FIX NOW because it will block any future work to correct the UI size on SP3. See: #2235.

**Comment by chadrolfs** [comment]
:+1:

**Comment by chadrolfs** [comment]
Eric can you take this?  If not, please pass along to Shaoshing.  Thanks!

**Comment by iwehrman** [comment]
Fixed by #2875.
