### ISSUE TITLE
CC Lib: force Create/Cancel when creating a new library

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2864]
new doc
drag out some rects on canvas
click on Libraries drop down > Create New Library
give it a name and hit Enter twice, then hit Delete or drag an asset onto the canvas

Result: you're now in a state where you can continue working on your document, switch tools, etc, but you still haven't clicked Cancel or Create yet and you can continue to use assets for a library that is still active in the background.

**Comment by mcilroyc** [comment]
@chadrolfs , @shaoshing claims this is fixed by his PR 2882
