### ISSUE TITLE
Open Recent does not list a doc saved and closed at the same time

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2866]
New doc, dirty it, and close it. In save? dialog, give a name  and save it. Open menu File -> Open Recent
RESULT: the file name is not listed.

**Comment by shaoshing** [comment]
watson: https://watsonexp.corp.adobe.com/#bug=4073894

**Comment by shaoshing** [comment]
After the core bug is fixed, we need to update the recent files list in the close  document action.

**Comment by jsbache** [comment]
I disagree with the "high priority" marker, and I have lowered the priority on the core side.
When investigating this, I found:
1) eventClose disables background-save and saves the document synchronously. This means that play-level > 1 when the save code is executed and this means that UMRUList::MRUAddEnabled returns false
2) If I disable the code that turns off background saving then the MRU is properly updated as play level is 1 when UMRUList::MRUAddEnabled is called later. There is a comment regarding crashes related to using eventClose with bg-save, ( and some slightly worrisome code)
To fix this in a non hacky way, I will have to change the way that bg save decides whether or not it should update the MRU. We need to capture this information in "extraData" (probably) or in save-options. I will chat with Russell (the bg save owner)

**Comment by shaoshing** [comment]
Thank you for the update Jesper.

**Comment by jsbache** [comment]
I think we'll add a hack to Photoshop - I am testing right now. This would require that you add the following boolean to your eventClose descriptor:   "forceMRU":true
(similar to flag that is passed on save events)

**Comment by jsbache** [comment]
Fixed in team sandbox with CL: 1048150
javascript must add the following key to the eventClose descriptor:  "forceMRU":true

**Comment by shaoshing** [comment]
Got it. I will give it a try.

**Comment by ktaki** [comment]
Verified the fix.
