### ISSUE TITLE
Error by re-entering vector mask mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2869]
Create a vector mask and end vector mask mode. Then go back to vector mask mode.

Action tools.changeVectorMaskMode failed: TypeError: Cannot read property 'flux' of undefined

![screen shot 2015-10-07 at 5 20 58 pm](https://cloud.githubusercontent.com/assets/2029597/10354752/128ca7b6-6d18-11e5-9707-1b7975614647.png)

**Comment by chadrolfs** [comment]
#2868
