### ISSUE TITLE
Smart Object properties change type

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#2873]
Sometimes layer.smartObject is a vanilla object, sometimes it is BitmapIndexedNode.

It should be a vanilla object.

It seems to be set correct on reset of Design Space but when selecting a layer, it changes.

**Comment by mcilroyc** [comment]
I can confirm that the `merge` in model/layer's `resetFromDescriptor`.  Ian's suggestion of creating a new record type for SmartObject seems like it will solve this.  Although, I will note *this* seems a little fishy to me: ![ss](http://cl.ly/image/0b1P1j430U0F/Image%202015-10-08%20at%202.44.21%20PM.png) - like maybe Immutable is being weird.  cc @iwehrman

**Comment by iwehrman** [comment]
I suggest creating a new `SmartObject` model and then using the ol' static construction function + update method pair.

**Comment by iwehrman** [comment]
FBNC to @designedbyscience.

**Comment by designedbyscience** [comment]
Yay! Thanks Cory
