### ISSUE TITLE
superselect tool in vector mask mode is broken when you eneter vector mask mode through a different tool

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#2892]
steps:

on a document with a pixel layer 
1: press 'r' to go to rect tool
2: press 'm' to go to vector mask mode
3: make a vector mask
4: press 'v' to got super select. 
5: click and drag outside of the mask to rotate

result: modal state ends
expected: same behavior as if we entered vector mask mode in super select tool

**Comment by pineapplespatula** [comment]
@ktaki  do you see this behavior

**Comment by ktaki** [comment]
Yes, I did on Friday, and I do today.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
