### ISSUE TITLE
Transform controls extended over toolbar and document title bar in vector mask transform mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2893]
In vector mask transform mode, rotation control sometimes extended over to toolbar and/or doc title bar making not possible to change tool or doc by clicking on them. Once this happens, exiting vector mask mode does not fix the problem. The cursor won't change to arrow over the toolbar or doc bar. Could this be another policy frame issue?

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
