### ISSUE TITLE
File > New... dialog takes up the whole screen

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2900]
Start with fresh prefs
dismiss Hello
cmd + ctrl + ` to switch to DS
click to dismiss Intro 
cmd + alt + n

Result:  giant dialog
Expect: constrained and centered dialog

**Comment by chadrolfs** [comment]
![screen shot 2015-10-12 at 10 54 06 am](https://cloud.githubusercontent.com/assets/8442631/10434637/a9f8c16a-70cf-11e5-91b6-83dd5ebc89df.png)

**Comment by chadrolfs** [comment]
second attempt has window sized correctly.

**Comment by ktaki** [comment]
This happens with standard Ps mode in pgDev 750, but not with today's mainline build m.249. Core issue?

**Comment by ktaki** [comment]
https://watsonexp.corp.adobe.com/#bug=4072406

**Comment by iwehrman** [comment]
I also saw this in standard PS the first time I created a new document after resetting my prefs.

**Comment by chadrolfs** [comment]
Removing FIX NOW because this isn't on us.

**Comment by chadrolfs** [comment]
Fixed on mainline.
