### ISSUE TITLE
Uncaught Photoshop error double-clicking on background layer

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2901]
cmd/ctrl + alt/opt + n
select : Default Photoshop Size, OK
double-click on layer name for Background layer

Result: `Transfer from tools.changeVectorMaskMode to layers.resetLayers failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Get” is not currently available.
    at eval (eval at undefined, <anonymous>:1:5)`

**Comment by mcilroyc** [comment]
assigning this to @pineapplespatula - but if this turns out to be unrelated to your ongoing vector mask work, you can assign it back to me.

**Comment by pineapplespatula** [comment]
I cannot reproduce this bug. sending back to @chadrolfs  to verify it still happens

**Comment by chadrolfs** [comment]
Weird, I CNR now as well.  Hmmph
