### ISSUE TITLE
Inconsistent borders along window edge

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2902]
The toolbar does not have a panel border:
![image](https://cloud.githubusercontent.com/assets/1075154/10434988/03689ad4-70d2-11e5-8c38-6414548c3471.png)

The icon bar does have a panel border:
![image](https://cloud.githubusercontent.com/assets/1075154/10435001/1669bcd0-70d2-11e5-81fa-bdfc9c3ca7cd.png)

And so does single-column mode:
![image](https://cloud.githubusercontent.com/assets/1075154/10435005/29d5ea14-70d2-11e5-9f5c-55776f224491.png)

**Comment by iwehrman** [comment]
CC  @placegraphichere or @designedbyscience

**Comment by designedbyscience** [comment]
@placegraphichere says the right border is incorrect. I'm on it

**Comment by iwehrman** [comment]
Fixed by #2909.
