### ISSUE TITLE
The transform system is getting borked when new artboards are created left/above

### ISSUE THREAD

**Issue by tiburbage** [adobe-photoshop/spaces-design#2915]
1 - File > New > Artboard doc
2 - Select the artboard if it isn't already, then click on the left side "new artboard" widget
3 - Cmd+0

Notice where DS thinks the artboard is now (way offset to the left). The same thing will happen for the top, but not the right or bottom. I think we are in a pretty unstable state at this point. Repro's on Mac and Windows using the latest staging builds (10/12, late afternoon). I can switch back to standard and there is no sign of problems there, and on returning to DS, the wierd state seems to be corrected.

Please advise if on investigation you believe this to have origin on the core side and I'll open a Watson for it.

**Comment by ktaki** [comment]
This issue has been reported as #2831. We still have border open policies issues.

**Comment by iwehrman** [comment]
Possibly related to #2881. Can somebody try to regress this with the commit before #2881 landed to see if that broke it?

**Comment by chadrolfs** [comment]
AB coords has been an issue for a while, see: #2754 #2756 and the one Taki mentioned above.

**Comment by tiburbage** [comment]
I looked at Artboard bugs and didn't see anything that sounded like a dup...

**Comment by iwehrman** [comment]
Eh, never mind, probably not related to #2881.

**Comment by iwehrman** [comment]
This is high priority, but not a UIF stopper, so I'm swapping FIX NOW with High Pri.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Creation of artboards to the top or left of current artboard works. There are still some undo issues that is tracked by #2831.
