### ISSUE TITLE
Typeface datalist field is not updated if text layers with missing fonts are selected consecutively

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2917]
Text layer A has a font missing, the name is font_a.
Text layer B has a font missing, the name is font_b.

Select the text layer A in layers panel. The typeface datalist now shows [font_a]. This is correct.
Then, select the text layer B in layers panel. The typeface datalist still shows [font_a]. This should be updated to [font_b].

Tested the fix for #2804.

**Comment by ktaki** [comment]
@DivyaPrabhakar When multiple text layer is selected (I remember we had a conversation on this topic on Slack yesterday), show the following.

1.) what should the datalist show if multiple missing font text layers are selected at the same time?

If the missing fonts selected are the same fonts, it should show the font name in []. 
If the missing fonts are different, show "[Mixed Fonts]"

2.) what should the datalist show if there is a combination of missing and not missing font text layers selected at the same time?

If you have one or more missing fonts in your selection, show "[Mixed Fonts]"

Since missing font is indicated by square brackets, you do not have to spell it out.

**Comment by iwehrman** [comment]
FBNC to @ktaki again to text @DivyaPrabhakar's improvements.

**Comment by ktaki** [comment]
@DivyaPrabhakar Can you double check the PR #3026 has all the fixes? Here are the test results.

Case | Placeholder Text | Result
------------ | ------------- | -------------
1 missing font | [name of the font] | Pass
2+ missing fonts  | [Mixed Fonts] | [Missing Font]
1 present font 	| name of font | Pass
2+ present fonts  | Mixed Fonts | Pass
1+ missing and present fonts  | [Mixed Fonts] | Mixed Fonts
1+ missing & all the same font  | [name of the font] | [Missing Font]
1+ present & all the same font  | name of the font | Pass

**Comment by DivyaPrabhakar** [comment]
@ktaki Can you verify these? 

__2+ missing fonts__ -- I am seeing the correct result where it reads as [Mixed Fonts] (I am using the most recent master and latest build) 
![](https://www.dropbox.com/s/vfbh69u9bk7g80t/2%2Bmissing%20fonts.gif?raw=1)

__1+ missing and present fonts__ -- I can verify this one is incorrect. I will change it now. 

__1+ missing & all the same font__  -- Again I see the correct result. I took one missing font layer, copy pasted it a couple times, and then selected all the layers of the same missing font. I get the result of [name of font]
![](https://www.dropbox.com/s/fglp5oxzrf60y9v/1%2Bmissingsamefont.gif?raw=1)

**Comment by ktaki** [comment]
Hum. Yes, all look good. Sorry, I must have connected to wrong branch.
