### ISSUE TITLE
Broken Smart Object layer icon contrast against new color stop is too low

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2920]
<img width="264" alt="screen shot 2015-10-12 at 9 45 30 pm" src="https://cloud.githubusercontent.com/assets/8442631/10445743/5d1c501c-712b-11e5-97a8-1af0daf8fcbf.png">

**Comment by chadrolfs** [comment]
<img width="258" alt="screen shot 2015-10-12 at 10 16 35 pm" src="https://cloud.githubusercontent.com/assets/8442631/10446012/f3190a12-712e-11e5-92d0-355a34063010.png">

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
