### ISSUE TITLE
Doc header anomaly in normal resolution 

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2924]
On an external monitor with normal resolution, doc names are truncated prematurely when app window is moved from hi-dpi to normal dpi.

![screen shot 2015-10-13 at 11 05 37 am](https://cloud.githubusercontent.com/assets/2029597/10463685/c9b6e98e-719a-11e5-8df5-8a5d40f5e27d.png)

Retina display

<img width="748" alt="screen shot 2015-10-13 at 11 05 24 am" src="https://cloud.githubusercontent.com/assets/2029597/10463694/d7505c2e-719a-11e5-9aa2-49b1e777ec9e.png">

**Comment by DivyaPrabhakar** [comment]
@ktaki This is not happening for me. What do you mean by prematurely in that screenshot?

**Comment by ktaki** [comment]
@DivyaPrabhakar   Retested with the latest build and master branch. You are right. This is no longer happening for me, either. By "truncated prematurely" I meant only showed U while it had more space for display. Thanks for looking at this issue. I am closing this now.
