### ISSUE TITLE
Can't select artboards on canvas when name is hidden

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#2928]
From CJB:

    Clicking on interior of empty artboard is supposed to select the artboard. Not working in DS. 
    (This is important because you can now hide artboard names)

    When AB names are hidden and you switch to DS, it’s very hard to select the AB by clicking on the
    canvas. In fact, I couldn’t; I could only select in the layer palette.

    I wonder if DS might want to always show AB names.

**Comment by chadrolfs** [comment]
related to #2720

**Comment by ktaki** [comment]
Make sure marquee select can select layers on an artboard if any, not artboard itself, when fixing this.

**Comment by iwehrman** [comment]
I suggest deferring the change to make clicking artboard background select the artboard.

**Comment by iwehrman** [comment]
In the short term, the best workaround is probalby to ensure that artboard titles are always visible.

**Comment by DivyaPrabhakar** [comment]
Emailed @jsbache about this

**Comment by chadrolfs** [comment]
we DO NOT want clicking the AB background to select the AB

**Comment by chadrolfs** [comment]
it screws up our Select/marquee model

**Comment by ktaki** [comment]
Clicking should select AB, but dragging should not. Actually, I believe being able to select AB by clicking on it improves workflow regardless of visibility of AB names.

**Comment by ktaki** [comment]
But, I agree. If this is a risky fix, we should punt it to M4.

**Comment by chadrolfs** [comment]
No, if you are trying to marquee select within the artboard, your first click will select the artboard because you're clicking on the background.  We DON'T want that.  Only clicking on the Title or the AB layer in the layers panel should select it.

**Comment by chadrolfs** [comment]
see #2238
I know there was another issue where Seth was a part of the same type of discussion and agreed that the current behavior is correct.

**Comment by chadrolfs** [comment]
What we should do is always enable View > Show > Artboard Names when entering DS and then set it back to whatever it was set to previous to entering DS when re-entering classic PS

**Comment by chadrolfs** [comment]
Or, we don't do anything, boot this to M4.

**Comment by ktaki** [comment]
Well, I disagree with the arguments for disabling click-and-select in #2238. (I am on Zorana's side.) Marquee select should not select AB, but clicking, i.e., mouse-down and mouse-up in the same position, should select AB. Currently AB is very hard to be selected by mouse.

**Comment by iwehrman** [comment]
Artboard names are forced on as of CL 1048641 (Mac pgdev.794), so I'm marking this FBNC. If we want, we should open a different bug about the behavior of the behavior of select clicking on empty artboard backgrounds. Over to @ktaki and/or open a different issue.

**Comment by chadrolfs** [comment]
Just make sure that when returning to classic PS, that whatever the setting was previous to entering DS, that it is restored.

**Comment by ktaki** [comment]
Opened a new issue #3018 for a minor problem found during the testing. Closing this issue. The issue of artboard selection by mouse click will be revisited later if necessary.
