### ISSUE TITLE
Layer re-ordering broken

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2941]
Open a test multi-layered test file
attempt to re-order or drag layers to bottom of the stack

Result: layers reorder on canvas but not in layers panel and console errors result

**Comment by iwehrman** [comment]
Can you post the stack trace?

**Comment by chadrolfs** [comment]
master @ 7b4ccbcd26673653da9d19882fc3ad1fad0e903d with jenkins playground build 1676.

https://www.dropbox.com/s/7ldwcw15e27gol6/LayerReOrder-broke.mov?dl=0

**Comment by chadrolfs** [comment]
`Action layers.reorder failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Move” is not currently available.`

**Comment by chadrolfs** [comment]
`Transfer from documents.open to application.updateRecentFiles failed: SyntaxError: Invalid number`

**Comment by chadrolfs** [comment]
![screen shot 2015-10-14 at 9 17 31 am](https://cloud.githubusercontent.com/assets/8442631/10490447/e8f86ef6-7255-11e5-8ddb-fe1487e9a7c6.png)
![screen shot 2015-10-14 at 9 29 02 am](https://cloud.githubusercontent.com/assets/8442631/10490446/e8f834a4-7255-11e5-9b0c-ad6b471bb09b.png)

**Comment by chadrolfs** [comment]
moving something on canvas will force layers panel to update

**Comment by shaoshing** [comment]
Steps to reproduce:

1 deselect all layers
2 reset DS
3 reorder any layer without selecting it
4 [BOOM]

**Comment by iwehrman** [comment]
FBNC to @chadrolfs .
