### ISSUE TITLE
The icons on the Welcome screenshots of Design Space (Preview) work space are missing.

### ISSUE THREAD

**Issue by fzhu1978** [adobe-photoshop/spaces-design#2943]
Watson bug 4072721
https://watsonexp.corp.adobe.com//#bug=4072721

Problem: The icons on the Welcome screenshots of Design Space (Preview) work space are missing.

Method:
1. Launch PS 20151012.M.251 build and switch into Design Space (Preview) work space on JPN OS.
2. Help->Design Space Introduction,check the welcome screen.

Result: The icons on the Welcome screenshots of Design Space (Preview) work space are missing.

Expected: No missing.

Notes:
1. This issue occur on both WIn and Mac OS on FRA/DEU/JPN/

**Comment by fzhu1978** [comment]
Verified on 10/13 build, it still occurs.  Please help to fix @iwehrman.

**Comment by DivyaPrabhakar** [comment]
FBNC @iwehrman @fzhu1978

**Comment by iwehrman** [comment]
Let's just have @ktaki regress this one.

**Comment by ktaki** [comment]
This still happens. It looks like svg file names have been translated.

![screen shot 2015-10-14 at 4 57 05 pm](https://cloud.githubusercontent.com/assets/2029597/10501420/30956206-7296-11e5-8a7a-a11de4f46d37.png)

**Comment by ktaki** [comment]
Retested it. The icons are displayed this time.
