### ISSUE TITLE
Dragging SVG in DS fails - empty drag (file not added)

### ISSUE THREAD

**Issue by zoranagee** [adobe-photoshop/spaces-design#2945]
Select an SVG file in CC Libraries and drag to document

RESULT: nothing
EXPECTED: SVG file to be placed (works in standard)

**Comment by chadrolfs** [comment]
I CNR, this works for me with current staging build 1676

**Comment by zoranagee** [comment]
There are so many flavors of SVG - I'll add you to my library and you can try that file there.

**Comment by chadrolfs** [comment]
Repro: (quick) - attempt to drag "Trash" from  library: Test - OK to accidentally nuke" onto canvas

**Comment by chadrolfs** [comment]
Repro: (real-world) - from CC (icon on OS menu bar) click on Assets, search for SVG, add asset to a library, drag it from library to canvas

**Comment by shaoshing** [comment]
@chadrolfs Thank you for the repro and file, I am looking at it now.

**Comment by mcilroyc** [comment]
@shaoshing can you push this over to @chadrolfs if you think it is addressed now with his latest repro file?
