### ISSUE TITLE
Switching apps from Ds and returning: column tab buttons work incorrectly

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#2946]
- Open a doc, and open all columns
- swtich to another application (try CMD+tab)
- return to Ds (try CMD+tab, or just clicking back into Ds)
- click the button for either properties or layer column
- all columns close

- expected only the column clicked should change

This is how I've been able to repro, but it seems to come and go sometimes.

**Comment by iwehrman** [comment]
May have something to do with the modifiers being set incorrectly? I bet it only happens when you cmd-tab?

**Comment by placegraphichere** [comment]
that could be the case... I will edit with that note

**Comment by tiburbage** [comment]
The Watson which referenced this issue has been closed, Jesper asserting he's not convinced action on the Spaces/C++ side is the right remedy.

https://watsonexp.corp.adobe.com//#bug=4074645
