### ISSUE TITLE
vector mask outlines not visable when coming from text tool

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#2951]
open a file with a  text block that has a vector mask on it 

steps:
hit 'T' to enter text mode, 
hit 'R' to enter rectangle mode,
hit 'M' to enter mask mode

result:
![screen shot 2015-10-14 at 1 45 41 pm](https://cloud.githubusercontent.com/assets/1008531/10497164/5b8181b0-7279-11e5-8c1e-86b4279ebad0.png)

expected result:
![screen shot 2015-10-14 at 1 46 43 pm](https://cloud.githubusercontent.com/assets/1008531/10497185/74e89332-7279-11e5-95fa-0ea3418e315a.png)

**Comment by pineapplespatula** [comment]
The work around is to enter mask mode via the super select tool

**Comment by pineapplespatula** [comment]
I'm pretty stuck on this one.

**Comment by chadrolfs** [comment]
ask for some help?

**Comment by pineapplespatula** [comment]
I'm talked to @isonno and have some potential leads. (not sure if this requires core changes yet. lets hope not)

**Comment by pineapplespatula** [comment]
created waston bug https://watsonexp.corp.adobe.com//#bug=4076976

**Comment by iwehrman** [comment]
This may now be fixed with CL 4076976. Over to @chadrolfs to test. (Or @pineapplespatula, if you have the cycles, feel free to close it after testing.)

**Comment by pineapplespatula** [comment]
fixed. thanks @jsbache
