### ISSUE TITLE
Lost underscore in Export icon

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2956]
Retina only

<img width="120" alt="screen shot 2015-10-14 at 2 58 27 pm" src="https://cloud.githubusercontent.com/assets/2029597/10499260/29506fc0-7284-11e5-98a3-cad66ce57535.png">

**Comment by iwehrman** [comment]
Can you report the results of `window.screen` from the console with this display here?

**Comment by ktaki** [comment]
Screen {orientation: ScreenOrientation, availWidth: 1440, availHeight: 841, availTop: 23, availLeft: 0…}
availHeight: 841
availLeft: 0
availTop: 23
availWidth: 1440
colorDepth: 24
height: 900
orientation: ScreenOrientation
pixelDepth: 24
width: 1440
__proto__: Screen

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix on Mac Book Pro and Surface Pro 3.
