### ISSUE TITLE
"Continue" button on Welcome Screen is not positioned correctly for languages other than EN

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#2960]
For example, in Japanese: 
![](https://www.dropbox.com/s/ksptk4bs6yv3hmi/Screenshot%202015-10-14%2012.27.21.png?raw=1)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Japanese and German lntros look good. Though I cannot tell German translation quality, Japanese translations have been much improved. Thanks to @DivyaPrabhakar and Feng Zhu.
