### ISSUE TITLE
LOC: Design Space: No space between the icons strings on the Welcome screenshots of Design Space (Preview) work space.

### ISSUE THREAD

**Issue by fzhu1978** [adobe-photoshop/spaces-design#2966]
Watson bug: https://watsonexp.corp.adobe.com//#bug=4073374

Method:
1. Launch PS PS 20151013.m.254 and switch into Design Space (Preview) work space on FRA/DEU OS.
2. Help->Design Space Introduction,check the welcome screen.

Result: No space between the icons strings.

Expected: There should be extra space between the icons strings

Notes: This issue occur on both WIn and Mac OS on FRA/DEU, does not occur on JPN.

**Comment by fzhu1978** [comment]
The strings are overlapped for fr/de, is it possible to extend the dialog width for fr/de?

**Comment by iwehrman** [comment]
CC @DivyaPrabhakar

**Comment by mcilroyc** [comment]
@fzhu1978 a fix was just merged in to master

**Comment by fzhu1978** [comment]
Thanks!

**Comment by DivyaPrabhakar** [comment]
Closing this issue
