### ISSUE TITLE
Tab in Color picker skips RGB HSB field

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2971]
create a rect or text layer 
click on swatch to open color picker 
hit Tab several times

Result: toggles between full rgb(n,n,n) value and alpha fields

reverse order works (using Shift + Tab).

**Comment by iwehrman** [comment]
I just pushed a small fix for this directly to master at 7564a4ce100a10219ba3cc42de93551d17cdcc5b. FBNC to @chadrolfs.
