### ISSUE TITLE
Some modifier combinations bring up UI and undesired dialogs in modal text edit mode or with shape tools

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2973]
create and select on canvas type
ctrl + cmd + alt and click = contextual color picker
shift + cmd + alt and click = Paragraph Text Size dialog

https://www.dropbox.com/s/6h7340fc11n1h6k/TextSecrets.mov?dl=0

**Comment by chadrolfs** [comment]
happens with Rect, Ellipse and Pen tool as well (contextual color picker)

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4074561 - color picker (mac only)
https://watsonexp.corp.adobe.com/#bug=4074567 - type dialog

**Comment by jsbache** [comment]
How about using the color that is selected in the HUD color picker. When the color changes the following notification is sent:
_spaces.ps.descriptor.play("set", {"null":{"_property":"foregroundColor","_ref":"color"},"source":"colorPickerHUD","to":{"_obj":"RGBColor","blue":189,"grain":0,"red":173}}, {}, function () {})

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4074561 has been verified fixed in staging and closed.
