### ISSUE TITLE
Moving an overlapping layer with Select tool and modifiers results in marquee select error.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2974]
create two overlapping text layers:
<img width="182" alt="screen shot 2015-10-15 at 1 51 33 pm" src="https://cloud.githubusercontent.com/assets/8442631/10527210/172e82f8-7344-11e5-855c-d10b25555c0c.png">

Hold down Shift + click and drag

Result:
`Transfer from superselect.marqueeSelect to layers.select failed: Error: Select with modifier requires a single layer`

**Comment by chadrolfs** [comment]
<img width="1031" alt="screen shot 2015-10-15 at 1 48 37 pm" src="https://cloud.githubusercontent.com/assets/8442631/10527230/36aa09f4-7344-11e5-93ee-e3691d5757b4.png">

**Comment by iwehrman** [comment]
I think you can repro with just shift + marquee select.

**Comment by chadrolfs** [comment]
Yep, amended steps above
