### ISSUE TITLE
After missing font is synced, text layer needs to be double clicked to reset the font

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2976]
After missing font is synced, select superselect tool and click on the text layer in layers panel. Observe the bounding box is not fit to the text bound. Rotate the text layer on canvas. 
RESULT: The font shown is Myriad Pro Regular while typeface field says otherwise.

To reset the font after font is synced, you need to double click on the layer in the layers panel, or click on the text layer on canvas to go into editing mode. This step should not be required.

**Comment by iwehrman** [comment]
@ktaki I think this might be fixed. Can you verify?

**Comment by ktaki** [comment]
The issues with the bounding boxes still exist. Fonts shown in the properties panel and on canvas indicated correct fonts, but the bounding boxes shown are still that of Myriad Pro Regular.

![screen shot 2016-01-06 at 8 35 30 pm](https://cloud.githubusercontent.com/assets/2029597/12162431/db2f302c-b4b6-11e5-9ded-7bd44bd93816.png)

![screen shot 2016-01-06 at 8 36 44 pm](https://cloud.githubusercontent.com/assets/2029597/12162434/dfd489ba-b4b6-11e5-90d3-55b6e10dcbc9.png)

Sometimes the text is shown clipped.

![screen shot 2016-01-06 at 8 48 00 pm](https://cloud.githubusercontent.com/assets/2029597/12162443/f782b686-b4b6-11e5-8578-e0f218733f2d.png)

**Comment by iwehrman** [comment]
This seems like a core Photoshop issue to me; Design Space doesn't have any control over those particular bounding boxes. I think this needs a JIRA issue.

**Comment by iwehrman** [comment]
Though conceivably there is a hack workaround that we could do in the browser, like deselecting and reselecting the layers...

**Comment by ktaki** [comment]
Retested this issue. It appears that the bounding box issue happens with certain test files. Yes, it also happens with standard Ps. Recreated those files from scratch will show no issues. I assume the text layers in the original files may have been corrupted. I will talk to a type expert in the Core team. In the meantime, I think we can close this issue in our side safely. I will keep an eye on the functionality anyway.
