### ISSUE TITLE
Hitting delete key deletes all paths in edit mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2977]
create a mask with multiple paths
hit a to enter anchor point edit mode
select an anchor point and hit delete

Result: entire mask is deleted
Expect: user should be able to delete specific paths or points

**Comment by mcilroyc** [comment]
This looks to me like it works as expected now.  back to @chadrolfs

**Comment by ktaki** [comment]
Looks good to me also.

**Comment by chadrolfs** [comment]
almost.  Here are two cases where it fails
https://www.dropbox.com/s/m786bwdsmshqt95/Mask-marqueeAnchors.mov?dl=0
https://www.dropbox.com/s/pmvxb8egzzyinqq/Mask-inverted.mov?dl=0

**Comment by pineapplespatula** [comment]
The inverted case we may not be able to do anything about, the path tools draw xor paths without modifier keys after the first path. and when you remove the first path drawn it can appear like a subtraction. we may be able to make them default to add, but i'm not sure. ( a workaround is holding down shift before drawing a path)

**Comment by pineapplespatula** [comment]
also i cannot reproduce the first video can you provide more steps?

**Comment by chadrolfs** [comment]
Yeah, CNR first case now.  Once you click outside the masks, it now selects all instead of deselecting.

**Comment by chadrolfs** [comment]
Closing this, created #3044 for that specific case.
