### ISSUE TITLE
Space no longer works to pan with Select tool.

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2984]
new doc
Select tool
zoom out and hit Space + drag to pan

Result: marquee select.

Workaround: use a different tool.

**Comment by chadrolfs** [comment]
00b81dbf1af41b2c2061ed2adfe2c8481018b6aa is the first bad commit
commit 00b81dbf1af41b2c2061ed2adfe2c8481018b6aa
Author: Ian Wehrman <wehrman@adobe.com>
Date:   Thu Oct 15 09:48:20 2015 -0700

    Remove arrow keydown policies for superselect/vectorselect, and set the default keyboard mode to FOCUS_PROPAGATE.

**Comment by iwehrman** [comment]
@jsbache may also have inadvertently broken this with his scrubby zoom changes last night.

**Comment by iwehrman** [comment]
May or may not be addressed with branch `iwehrman/issue-2984`. I can't repro on my current build and can't get the most recent one at the moment.
