### ISSUE TITLE
Policy issue: keys fall through to classic PS

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#2986]
(using pgdev.780 mac or 761 win and master @ 965e872)
cmd/ctrl + n
t for Type tool
click on canvas and type
hit Enter to commit
hit f, or s

Result: you switch to a full screen mode or now have the clone stamp tool.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4075279

**Comment by iwehrman** [comment]
AFAICT, this does not have to do with editing type. Typing `f` with just the select tool takes us into full screen. This is definitely related to the switch from keyboard propagation mode of NEVER to FOCUS.

**Comment by iwehrman** [comment]
Typing `y` takes you into the history brush. The key event flood gates are open. This is a major issue.

**Comment by jsbache** [comment]
This is not a core problem (as far as I can see). Javascript sets keyboard propagation *mode* to 3 (focus) and this means that the "f" key is sent to PS when the canvas (or any other non HTML UI) has keyboard focus. I don't see this problem in perforce HTML, so I assume that this is related to a recent HTML change

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4075279 Closed/Withdrawn/NotThisProduct
