### ISSUE TITLE
vector mask: could be trapped by pen tool while in mask mode

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#2988]
1. create REC
2. enter vector mask mode
3. use select tool to make some selections (and nothing is selected)
4. switch to pen tool and start drawing, and you will probably stuck in pen tool mode

https://www.dropbox.com/s/e7ap2lvz3c8b78k/vector-mask-2.mov?dl=0

**Comment by iwehrman** [comment]
FBNC 2 @chadrolfs

**Comment by chadrolfs** [comment]
CNR from step 1 to step 2 bc you can't enter mask mode when a shape layer is targeted.

**Comment by pineapplespatula** [comment]
@chadrolfs  @shaoshing  i believe meant draw a rectangular marquee selection with the vector superselect tool
