### ISSUE TITLE
UI elements become unresponsive after working with vector mask mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#2996]
1. Open an image doc
2. Select superselect tool
3. Enter vector mask mode
4. Select rectangle tool
5. Select superselect tool
6. Select rectangle tool
7. Click on ellipse tool
RESULT: Cursor becomes a Cross when mouse down. Unable to select ellipse tool. At this point, you cannot select any UI elements including tool icons on toolbar, document names and icons on the doc bar, or those on the panels. Clicking them changes the cursor from black arrow to the cross icon (for vector mask drawing on canvas). This will not be recovered even after exiting vector mask mode by pressing 'm'.

On Windows, the cursor does not change to a cross, but the behavior is the same.

**Comment by pineapplespatula** [comment]
@ktaki  i'm not seeing this happen in the branch jecohen/vectorMaskPolicies3. Can you verify that?

**Comment by ktaki** [comment]
@pineapplespatula You are right. It does not happen with jecohen/vectorMaskPolicies3. Good!

**Comment by ktaki** [comment]
Verified the fix.
