### ISSUE TITLE
SDL: DE-DE: Arrange menu: several shortcuts are not easily accessible on a German keyboard

### ISSUE THREAD

**Issue by fzhu1978** [adobe-photoshop/spaces-design#3013]
Watson bug:
https://watsonexp.corp.adobe.com/#bug=4075062

Problem: Arrange menu: several shortcuts are not easily accessible on a German keyboard

Method:
1. Check the strings under Arrange menu on Design Space Preview.

Result:
The following shortcuts are not easily accessible on a German keyboard:
/ (requires pressing Shift+7 on a German keyboard)
[ (requires pressing Alt Gr + 8 on a German keyboard)
] (requires pressing Alt Gr + 9 on a German keyboard)

Expected:
Please choose directly accessible keys instead on a German keyboard, e.g.
.
<
#

Workaround:

**Comment by fzhu1978** [comment]
I almost forgot why I remove shortcuts file from ALF.  Seems I should introduce shortcut files in to keep on the latest version with en_US, and can localized the shortcuts.

**Comment by fzhu1978** [comment]
Last time translator translated a shortcut to localized character.  Can I imported these file to ALF for customization purpose?  That means we will not send out this file to translate, just aim at changing some keyboards shortcut for some languages.

**Comment by iwehrman** [comment]
@fzhu1978 Yes! As long as all the changes to the shortcuts files are chosen carefully and intentionally, this is perfectly fine. If you'd like to chat with our designer @placegraphichere about this, you can reach him at `sewalker at adobe.com`.

**Comment by placegraphichere** [comment]
German for:
Move target layer down up— WIN: Ctrl + # or ä, MAC: Command + # or ä
Move layer to bottom or upward— WIN: Ctrl + Shift + # or ä, MAC: Command + Shift + # or ä
Fixed transparency for target layer, or last applied lock on / off— WIN: ß, MAC: ß

German here:
https://helpx.adobe.com/de/photoshop/using/default-keyboard-shortcuts.html

English here:
https://helpx.adobe.com/photoshop/using/default-keyboard-shortcuts.html

**Comment by fzhu1978** [comment]
Thanks Seth!

Our linguist QE suggested changes like yours, I will fix it in ALF.

**Comment by iwehrman** [comment]
Fixed by #3025. Over to @ktaki to verify.

**Comment by ktaki** [comment]
Confirmed that the changes have been made. Some of the changes are working with English keybboard, but others are not. They need to be verified by i18n team.

**Comment by ktaki** [comment]
The fix has been verified by i18n team. The bug https://watsonexp.corp.adobe.com/#bug=4075062 has been closed as fixed.
