### ISSUE TITLE
Sampling from a layer with one effect to a layer with multiple effects of the same type only replaces the 1st one

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3016]
Create layer A with a drop shadow and 2 strokes
Create layer B with one stroke
Target layer A
select the Sampler tool
mouse over layer B, hit Space, and click on FX icon

Result: drop shadow is removed, the top stroke is replaced with the sampled stroke, and the 2nd stroke remains.

Expect: FX from layer B replace FX on layer A

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
:moneybag:
