### ISSUE TITLE
Artboard name disappears when clicked, just once after switched from Standard Ps

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3018]
Hi DPI only. A minor issue with forcing artboard name appear. When mouse-down on the name for dragging artboard, the name disappears. Subsequent mouse-up will show the title. This seems happens only once when switched from standard Ps and artboard documents are already open at that time.

Open an artboard doc.
Uncheck View > Show > Artboard names
Switch to DS
Click on the artboard name for drag.
The name disappears.
Releasing mouse button shows the name.
No disappearing of names happens after this.

**Comment by iwehrman** [comment]
I can't repro with pgdev.806. Maybe @jsbache and/or the recent mainline integration fixed it? Back to @ktaki to verify one way or another.

**Comment by ktaki** [comment]
I still can repro with pgdev.806 and master this morning. It sometimes gets into a state you cannot drag and move artboard, but this is intermittent. Disappearing the name on mouse down is fairly consistent. This does not happen when I tested only with pgdev.806, not with current master.

**Comment by ktaki** [comment]
https://watsonexp.corp.adobe.com/#bug=4077018

**Comment by ktaki** [comment]
This issue has been fixed in Ps 16.1 GM.
