### ISSUE TITLE
Copy/Paste text on canvas in Type edit mode fails

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3020]
create a type layer
(in edit mode) copy some of the on-canvas text (cmd + c), paste (cmd + v)

Result: paste fails
`Transfer from policy.suspendAllPolicies to policy.suspendPolicies failed: Error: Policies are already suspended`

**Comment by chadrolfs** [comment]
![screen shot 2015-10-19 at 1 46 15 pm](https://cloud.githubusercontent.com/assets/8442631/10590910/3d072db4-7668-11e5-95ba-93df789103f5.png)

**Comment by iwehrman** [comment]
This will be addressed by #2965.
