### ISSUE TITLE
Transform > Rotate 180/Right/Left on an empty layer results in error

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3022]
cmd/ctrl + n (by default empty layer is selected)
Layer > Transform > Rotate 180/Right/Left

Result:  `Transfer from transform.rotateLayersInCurrentDocument to transform.rotate failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -1 Photoshop message: error: -1 message: Could not complete the command because the initial bounding rectangle is empty.`

**Comment by chadrolfs** [comment]
Same thing happens on an empty group

**Comment by mcilroyc** [comment]
fbnc2 @chadrolfs
