### ISSUE TITLE
Shouldn't be able to edit mask when not in mask mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3029]
Open a test file and target a pixel layer
m to enter mask mode
r for Rect tool and drag out a rect mask
m to exit mask mode
v for Select tool
m to enter mask mode, m to exit mask mode
p for pen tool

Result: now you are able to see the mask anchor points and can edit with the pen tool (add/delete points).

**Comment by iwehrman** [comment]
FBNC to @chadrolfs
