### ISSUE TITLE
Vector masks: Path operation icons are dimmed

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3031]
The path operation icons (unite, subtract, etc.) are dimmed in vector masks editing mode.

In vector masks editing mode,
Create several ellipse paths that overlaps each other.
Select two paths.
RESULT: Path operation icons are dimmed and not selectable.

**Comment by ktaki** [comment]
If you create a shape layer, then those icons are enabled. Coming back to vector mask editing mode does not disable those icons and they work as expected. So, I think just matter of enabling it in the vector mask mode.

**Comment by shaoshing** [comment]
@ktaki can you verify?

**Comment by ktaki** [comment]
Verified the fix. Thanks!!
