### ISSUE TITLE
Copying Effects then Undo does not always update canvas

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3034]
- create two rects
- add multiple effects to one rect
- select the other rect and use the sampler to copy the effects
- CMD+Z to undo
- Result: Often the effects are not deleted from canvas, but nothing is in panel
- *Interestingly, if you save and reopen the doc, the effects will still be there.*

Example:
https://www.dropbox.com/s/93wd0bq4iv5ph80/undo-not-removing-canvas-effects.mov?dl=0

dev806

**Comment by placegraphichere** [comment]
Continuing to undo will finally get you results, but it seems incorrect that one action does not equal one undo step.

**Comment by chadrolfs** [comment]
Looks like there are multiple history states here.  If you do Update Document after undo, you'll see all the styles re-populate

**Comment by mcilroyc** [comment]
FBNC to @chadrolfs for validation
