### ISSUE TITLE
Revert should exit mask mode

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3040]
open a saved doc,
target a pixel layer, hit m to enter mask mode
r for Rect tool and drag out a rect mask
hit F12 or File > Revert
drag out another rect

Result: F12/Revert does not exit Mask Mode and rects are now created as paths instead of shapes

**Comment by chadrolfs** [comment]
Review all menu commands to make sure their safe or not and disable accordingly.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
