### ISSUE TITLE
copy/paste appearance between two text layers with different opacity will flash the number

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3049]
https://cloud.githubusercontent.com/assets/118264/10621526/34bf23ea-7736-11e5-8d10-37ed838fb837.gif

**Comment by chadrolfs** [comment]
Only if there's time and fix is low risk.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
no longer flashes, but doesn't copy the correct value.  see #3100
