### ISSUE TITLE
copy/paste appearance from Rect w/radius to Ellipse flashes Radius on paste

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3050]

**Comment by chadrolfs** [comment]
![paste-radiusflash](https://cloud.githubusercontent.com/assets/8442631/10624093/2d2ec3e2-774a-11e5-8c19-9034bb2959bd.gif)

**Comment by chadrolfs** [comment]
Only if there's time and fix is low risk.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Looks fixed on Win but not on Mac (10.10.5, haven't tried 10.11.1 yet).  pgdev.826 with master @ 35bf347

**Comment by chadrolfs** [comment]
![paste-radiusflash2](https://cloud.githubusercontent.com/assets/8442631/10680165/11ff6e58-78d2-11e5-95a0-6b76a07f81ae.gif)

**Comment by shaoshing** [comment]
Hmm, that's weird, beucase the fix is produced on MAC. Let me double check.

**Comment by chadrolfs** [comment]
restested this morning with latest jenkins build cotaining the updated compiled js and it looks fixed.

**Comment by chadrolfs** [comment]
yesterday was nuts, i might have been on a branch other than master.  I trust myself more this morning.  :stuck_out_tongue_winking_eye:
