### ISSUE TITLE
Search > Recent Documents icon is clipped at the bottom

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3056]
<img width="407" alt="screen shot 2015-10-21 at 9 19 23 am" src="https://cloud.githubusercontent.com/assets/8442631/10642920/04404218-77d5-11e5-83e9-dfc08c46120f.png">

**Comment by iwehrman** [comment]
@placegraphichere and/or @designedbyscience: can you take a look at this?

**Comment by chadrolfs** [comment]
haven't checked any other icons but they may be clipped too

**Comment by placegraphichere** [comment]
I'm not seeing this with dev812. But I am seeing other search issues i'll file. @chadrolfs can you double check or ping me with details?

**Comment by placegraphichere** [comment]
Here's what I see on dev 812 for standard and retina:

![screen shot 2015-10-21 at 2 11 09 pm](https://cloud.githubusercontent.com/assets/3229167/10647388/ab7afd70-77fd-11e5-8ecb-ad7ba0e5154b.png)
<img width="563" alt="screen shot 2015-10-21 at 2 11 34 pm" src="https://cloud.githubusercontent.com/assets/3229167/10647387/ab7ad106-77fd-11e5-8f63-5b2c1e3160f1.png">

**Comment by placegraphichere** [comment]
also tried when there are no recent files in the list, as your screen shot showed. 
![screen shot 2015-10-21 at 2 15 41 pm](https://cloud.githubusercontent.com/assets/3229167/10647491/50fcc6ca-77fe-11e5-8b9d-bdf050390ae3.png)

**Comment by chadrolfs** [comment]
Some sort of caching issue?  Clipping was corrected once I resized/moved the app window.  Tried to restart with fresh prefs.  CNR now.
