### ISSUE TITLE
mergeDeep call in resetBounds is slow, possibly unnecessary

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3057]
Here: https://github.com/adobe-photoshop/spaces-design/blob/e9b0ef739a3b864ebd8b9873701c27271c3a15de/src/js/models/layerstructure.js#L1092

In Vermillion, changing a font results in a call to `layers.resetBounds`, and it _seems_ like it's spending ~300ms inside this `mergeDeep` call.

**Comment by shaoshing** [comment]
@iwehrman confirmed the test result in the PR, so issue closed.
