### ISSUE TITLE
Can't navigate search results with keyboard

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3065]
1. Open Vermilion
2. Cmd-F to search
3. Type "re"
4. Arrow down a few times.

Result:
![img](https://slack-imgs.com/?url=http%3A%2F%2Ff.cl.ly%2Fitems%2F0c2F023m11002G3M3J2t%2FScreen%2520Recording%25202015-10-21%2520at%252002.05%2520PM.gif&width=300&height=250)

**Comment by placegraphichere** [comment]
her's my repro too
https://www.dropbox.com/s/x6i8q9qjzlkugib/app-search-typing-arrow-funkiness.mov?dl=0

**Comment by DivyaPrabhakar** [comment]
@iwehrman the PR addressing this was merged, back to you even though it was already with you.
