### ISSUE TITLE
Keyboard Arrow Keys Don't Seem to Nudge Shape Points

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3075]
- Create Shape
- Double click into it
- select one point
- use arrow keys to nudge
- result: nothing

- Expected: nudging should work

**Comment by iwehrman** [comment]
Is this a modal state @pineapplespatula / @mcilroyc? We may have suspended policies, which removed our arrow key policies. This could be an easy fix...

**Comment by chadrolfs** [comment]
Verified this is fixed.
