### ISSUE TITLE
French Intro needs some repositioning of image and sentences

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3076]
In French intro screens, images and sentences have been placed too high. Need to center them vertically.

Example:

![screen shot 2015-10-21 at 4 17 15 pm](https://cloud.githubusercontent.com/assets/2029597/10652943/734400e8-780f-11e5-933f-df91e18515a2.png)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Looks good now!
