### ISSUE TITLE
Error deleting next to last layer with Pen tool

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3078]
cmd/ctrl + n
r for Rect tool, drag out a shape
p for Pen tool, draw a closed shape
hit delete

Result: `Transfer from tools.select to layers.deleteSelected failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Delete” is not currently available.`

**Comment by chadrolfs** [comment]
related to #3011

**Comment by chadrolfs** [comment]
![pendelete-error](https://cloud.githubusercontent.com/assets/8442631/10653278/c96358c2-7812-11e5-9d4b-615491233056.gif)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
bouncing.  follow the steps above and after the last step, hit delete again.
Result: `Menu command not available: 106`

**Comment by iwehrman** [comment]
That is a debug-only warning message. Is the behavior incorrect?

**Comment by iwehrman** [comment]
Alternatively: try verifying on a compiled build.

**Comment by chadrolfs** [comment]
yep, we're good on compiled and nothing bad happens in debug, just the console error.
