### ISSUE TITLE
Sampling LLSO (Library Linked Smart Object) has one extra history state "Relink to Library Graphic"

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3084]
Watson bug: https://watsonexp.corp.adobe.com/#bug=4077984
Video: https://www.dropbox.com/s/w7456wh35dlbf4p/sampling-graphic.mov?dl=0

This cause:

1. take two undo to restore to the original SO
2. target layer does not reset to the correct bound (beucase the relink happens after the "resetLayer")

**Comment by mcilroyc** [comment]
@shaoshing the bounds issue (part 2 in your description) seems to me to be unrelated to the history states.  That is, after I sample the graphic, immediately when I switch to SS tool I see that the bounds are incorrect. 
http://cl.ly/212E0320253I

can you confirm this?

**Comment by iwehrman** [comment]
Should we call this FBNC? Or leave it open because we only checked in a superhack? Either way, handing it off to @chadrolfs for testing.

**Comment by chadrolfs** [comment]
this is fixed but it uncovered or resulted in a secondary issue #3108

**Comment by iwehrman** [comment]
For posterity, @jsbache has suggested that perhaps we can use `_spaces.ps.processQueuedCommands` instead of the delay hack we previously used to work around the issue.
