### ISSUE TITLE
Swap-panels modifier click doesn't work on Windows

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3088]
I tried Ctrl, Win and Alt, but none of them do the right thing.

**Comment by iwehrman** [comment]
Note that, even with a JS patch, this is still unreliable on Win due to [Watson 4078041](https://watsonexp.corp.adobe.com/#bug=4078041).

**Comment by mcilroyc** [comment]
The engineer has reported this as being partially solved by 3091

**Comment by iwehrman** [comment]
The @jfitz-adobe has reported that this is fixed by CL 1049772. Over to @ktaki to verify.

**Comment by ktaki** [comment]
Ctrl key works now on Windows. Cmd key for Mac.
