### ISSUE TITLE
Can't navigate to all search results on Windows

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3089]
1. Ctrl-F to open the search UI
2. Type `re`
3. Arrow key down a few times.

For me, it stops going down on the 7th entry, "Test Reset Failure".

**Comment by iwehrman** [comment]
Selecting deeper results works with the mouse though.

**Comment by chadrolfs** [comment]
CNR.  Fixed or still an issue?

**Comment by iwehrman** [comment]
I'm not aware that this was ever fixed.

**Comment by chadrolfs** [comment]
#3068 didn't resolve this?  re-open if you can still repro.
