### ISSUE TITLE
Copy/Paste text Appearance doesn't paste the correct Opacity

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3100]
![copy-paste-typeappearnce](https://cloud.githubusercontent.com/assets/8442631/10699114/6fd14da2-7969-11e5-980c-b9fef771b76e.gif)

**Comment by chadrolfs** [comment]
related to #3092 which fixed #3049 (related)

**Comment by chadrolfs** [comment]
Notice, the leading did not paste correctly either.

**Comment by chadrolfs** [comment]
After I moved the layers and repeated the copy/paste, the opacity pasted correctly, but not the leading (Letterspacing)

**Comment by chadrolfs** [comment]
also related to #2755

**Comment by iwehrman** [comment]
Marked Fix-in-progress. If that's now the case @shaoshing, lemme know.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
