### ISSUE TITLE
Smart Guides should use visible px of masked layer

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3106]
Right now masked layers use the smart guide of the full size of the layer. We should use smart guides on the edge of the mask instead. (might be a core issue)

![screen shot 2015-10-23 at 3 37 07 pm](https://cloud.githubusercontent.com/assets/3229167/10704378/07a9c550-799c-11e5-8fea-83a5268276ae.png)

**Comment by iwehrman** [comment]
Definitely a core issue.

**Comment by iwehrman** [comment]
Over to @chadrolfs to file at his leisure, since this is clearly M4.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4079322
