### ISSUE TITLE
Layer highlighting is not working correctly

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3110]
Select tool selected
open any saved document (try our fav: Vermillion)
click anywhere outside the artboards to deselect anything that is selected
mouse over canvas objects
Result: nothing is highlighted (note if you choose Edit > Deselect, you'll get top level highlighting)

Hold down cmd/ctrl and mouse over layers
Result: if nothing is selected on canvas, you'll get no scrim highlighting
if you do have something selected on canvas, only smart guides will show on mouse over with cmd/ctrl key down (no blue highlighting)

**Comment by iwehrman** [comment]
I'm concerned that this is a core regression. If I create a single shape inside a single group inside an artboard and then hitTest the artboard _not_ in the group/shape bounds, the group is one of the returned hit layers. That doesn't seem right. Can you repro, @jsbache?

**Comment by jsbache** [comment]
@iwehrman: easy to repro.
This looks like an old bug. Layer sections are being included in the search result without looking at their "bounds". I can repro with the oldest 16.1 build that I could find (09/17)

**Comment by jsbache** [comment]
Here is the watson:
https://watsonexp.corp.adobe.com/#bug=4078748
Not for 16.1 (sorry). I am removing the M3 milestone.

**Comment by shaoshing** [comment]
This seems not working again with the latest master and dev 886. The first bad commit is 16fa189c3dadae1737649de366fb4137f4a41f07, but I may be wrong because I don't see anything suspicious in the commit.

**Comment by volfied** [comment]
@chadrolfs I know we sent this to Jesper, but can you re-confirm this bug exists. I see highlighting work correctly with and without cmd modifier.

**Comment by chadrolfs** [comment]
with master @ 59efbdf using pgdev build 933, I'm seeing highlighting working correctly.

**Comment by chadrolfs** [comment]
Fixed in latest mainline build with HTML update, m.337

**Comment by chadrolfs** [comment]
Won't go into 16.1.1 or 16.1.2 but will for M4
