### ISSUE TITLE
Sampling layer behind a masked group shows incorrect overlay

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3111]
This one is kind of hard to describe, but the video shows it pretty clearly. 

Trying to sample a layer behind a layer with a large px area but is masked will show the overlay for the large pixel layer, but it will sample correctly. This is just showing the wrong overlay hinting. It works correctly in the end.

![mask-sampler-hittest](https://cloud.githubusercontent.com/assets/3229167/10705445/892ced8a-79a3-11e5-9a4e-919f9cd58639.gif)

**Comment by iwehrman** [comment]
FBNC to @placegraphichere and/or @chadrolfs.

**Comment by chadrolfs** [comment]
Looks good to me, closing this puppy.
