### ISSUE TITLE
Text for suffix in Export panel appears too low on Surface Pro 3

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3112]
<img width="255" alt="screen shot 2015-10-23 at 2 48 29 pm" src="https://cloud.githubusercontent.com/assets/2029597/10705884/5ec064f8-7996-11e5-80d9-bde01674e94f.png">

Is this easy to fix? If yes, then M3. If not M4.

**Comment by iwehrman** [comment]
I can repro his. @placegraphichere: does anything look weird to you in the CSS here? If you have a small, suggested fix, I will test.

**Comment by iwehrman** [comment]
This `input` needs `font-size: 1.4rem`, but I'm not sure where to put it.

**Comment by ktaki** [comment]
Verified the fix.
