### ISSUE TITLE
Recent history changes break the opacity slider in the color picker

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3115]
Open any color picker, drag the opacity handle and start sliding: receiving errors related to history state id unmatch. 

<img width="1028" alt="screen shot 2015-10-23 at 5 24 06 pm" src="https://cloud.githubusercontent.com/assets/118264/10707673/e6d3f4d6-79aa-11e5-89c2-d0612d67a648.png">

As far as I know, the first related commit is from PR #3052, so I assign to @mcilroyc to take a look.

**Comment by iwehrman** [comment]
@mcilroyc @shaoshing: I'm not sure if this is actually FBNC based on @mcilroyc's comments in #3116. Assigning back to @shaoshing to work it out with @mcilroyc.

**Comment by mcilroyc** [comment]
Note: I believe @iwehrman's #3119 further addresses this issue.  The concerns I mentioned in #3116 (invalidating the history cache) seem to be fixed with 3119
