### ISSUE TITLE
Undo does not reset color picker sliders

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3117]
1. Open a color picker.
2. Drag either slider.
3. Cmd-z to undo. 

The color change is reversed on canvas and in the swatch in the main panel UI, but the color picker sliders do not update.

Noted in #3116

**Comment by iwehrman** [comment]
It works correctly if you just click on a slider to change the color.

**Comment by iwehrman** [comment]
CC @designedbyscience in case he has any ideas. I don't think this is related to incorrect history states, just incorrect state dynamics inside `ColorInput`.

**Comment by mcilroyc** [comment]
FBNC - assigning to @chadrolfs for independent review.
