### ISSUE TITLE
Swap fails on doc resolutions > 72

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3121]
create a new default photoshop file (res: 300) with a transparent background
drag several images onto canvas
select two
click Swap icon

Result: instead of swap, they move farther apart.

**Comment by chadrolfs** [comment]
![swap-fail](https://cloud.githubusercontent.com/assets/8442631/10718785/ba56dade-7b37-11e5-9672-a3e172d97b1b.gif)

**Comment by iwehrman** [comment]
Can you try `git bisect`ing this?

**Comment by iwehrman** [comment]
This may have had something to do with @volfied's changes to make bounds relative to their containing artboard, or with @DivyaPrabhakar's reference point changes.

**Comment by iwehrman** [comment]
I'm suspicious of 7691b2f50edc816fcb94f50f10f45ce26ac2d4ba

**Comment by iwehrman** [comment]
It's bad at least as far back as a1114370798a77b0daaacc0ee6357c9ce334de95.

**Comment by iwehrman** [comment]
I think this bug has to do with document resolution and not artboards vs non-artboards. It works correctly on 72dpi resolution documents (the default for artboard documents) but not 300dpi resolution documents (the default for non-artboard documents).

**Comment by chadrolfs** [comment]
Yes, it's a resolution bug, not specific to artboards.  Amending title.
