### ISSUE TITLE
Unable to commit text with Esc or Enter or continue to type after Paste

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3126]
create a type layer
(in edit mode) copy some of the on-canvas text (cmd + c), paste (cmd + v)
hit Enter or Esc

Result: Nothing

Workaround: select a different tool or switch focus away from app

**Comment by chadrolfs** [comment]
related to fix for #3020

**Comment by chadrolfs** [comment]
it’s actually worse than just Esc/Enter not committing the text
you can’t continue typing as well unless you hit a tool shortcut key

**Comment by iwehrman** [comment]
The fact that something changes when you hit a tool shortcut key means that, somehow, keyboard focus has gone back to CEF even while we're in a tool modal state. This is not how `FOCUS_PROPAGATE` mode is supposed to work. I suspect that this is at least partially a core issue.

**Comment by tiburbage** [comment]
I'll got a core bug to sync with this. John will need to investigate. I'm assuming this is a regression, so meanwhile, it will be useful to try to determine when this regression occurred. If you explicitly re-acquire focus after doing a paste, does that improve the outcome?

**Comment by tiburbage** [comment]
https://watsonexp.corp.adobe.com/#bug=4079392

**Comment by iwehrman** [comment]
FBNC to @chadrolfs. @tiburbage: the Watson bug can be closed. There are no new focus issues here; that was a bad early guess from me.

**Comment by jsbache** [comment]
Watson bug closed. I will remove the ps core tags
