### ISSUE TITLE
Place fails for 2nd asset when modifier is used

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3130]
cmd/ctrl + n
drag a cc library asset onto canvas (don't commit)
drag a 2nd asset onto canvas hold down opt/alt

Result: only 1st asset is placed.  nudge AB will force update the layers panel but will result in 
`Action layers.resetIndex failed: Error: Too many layers in layer index`

**Comment by chadrolfs** [comment]
![place-error](https://cloud.githubusercontent.com/assets/8442631/10741013/b5b8cf5e-7be2-11e5-970d-4ab8254e60de.gif)

**Comment by chadrolfs** [comment]
there is a secondary intermittent issue where you end up with two children with the same key
to try to repro that follow these steps:
cmd/ctrl + n
drag a cc library asset onto canvas (don't commit)
click once in the Lib panel (places 1st asset) then drag a 2nd asset onto canvas hold down opt/alt
select them both
Result: swap is greyed out

![screen shot 2015-10-26 at 1 13 32 pm](https://cloud.githubusercontent.com/assets/8442631/10741183/a5eb9a10-7be3-11e5-90f3-8c7b5ad9c513.png)

**Comment by iwehrman** [comment]
As of #3140, this is "fixed" by simply preventing the drag from libraries while in a tool modal state. If you think we'd like to file a bug about providing a somewhat better UX for this, go for it!

FBNC to @chadrolfs.
