### ISSUE TITLE
Mixed states don't show correctly 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3131]
create two rects with different fill colors
select them both

Result:
![screen shot 2015-10-26 at 1 36 10 pm](https://cloud.githubusercontent.com/assets/8442631/10741714/67b93d44-7be6-11e5-9b15-75c9123e7fd0.png)

Expected:
![screen shot 2015-10-26 at 1 36 32 pm](https://cloud.githubusercontent.com/assets/8442631/10741723/6ebd37a8-7be6-11e5-804e-ca9e4c37c4c2.png)

**Comment by chadrolfs** [comment]
81520b749623955e59eca0551574d4b207bdd7fb is the first bad commit
commit 81520b749623955e59eca0551574d4b207bdd7fb
Author: Ian Wehrman <wehrman@adobe.com>
Date:   Sun Oct 25 09:22:28 2015 -0700

    Upon receiving a timetravel event from the history store, re-parse the color props in order to reset the color picker sliders.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
