### ISSUE TITLE
Select overlay doesn't highlight siblings on hover

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3132]
![img](https://s3.amazonaws.com/f.cl.ly/items/1n1y1M0z2h0N2O470V0z/Screen%20Recording%202015-10-26%20at%2001.52%20PM.gif)

**Comment by chadrolfs** [comment]
related to #3110

**Comment by volfied** [comment]
The hitTest order of layers have changed. Fix for this will be in SuperSelectOverlay.jsx updateMouseOverHighlights function. We need to filter out non-superselectable layers similar to what we do in superselect.click

**Comment by iwehrman** [comment]
FBNC to @chadrolfs. Is there any way that we can sneak this into M3?

**Comment by chadrolfs** [comment]
Probably not in the least.
