### ISSUE TITLE
Numbers are not correctly localized

### ISSUE THREAD

**Issue by fzhu1978** [adobe-photoshop/spaces-design#3136]
Waston Bug:
https://watsonexp.corp.adobe.com/#bug=4078212

Problem: The numbers are not correctly localized on Design Space (Preview).

Method:
1. Install PS 20151022.m.268 build on DEU OS.
2 Switch to Design Space (Preview) work space.
3. New a doc and add the shape value.
4. Change the value of the shape properties, check the display of the numbers.

Result: The comma in the numbers display as dot. It is not localized. And input "," instead of "dot", it is un-accept.

Expected: The comma should be display well.

Note:
1. This issue occur on both Win and Mac on DEU and FRA OS.

**Comment by fzhu1978** [comment]
@iwehrman 
Can you evaluate if we can fix for 16.1.2?

**Comment by volfied** [comment]
@iwehrman you said this is partially addressed by #3627, can you comment on what's left / update the bug.

**Comment by iwehrman** [comment]
Still missing: respecting the system preferences for the decimal separator when it differs from the locale default, and possibly also correctly formatting percents.

**Comment by ktaki** [comment]
Also missing is a manual number input support. Currently fields do not accept numbers with comma as a decimal separator.

**Comment by iwehrman** [comment]
After #3692, the only thing missing that I know of is % formatting. (In some locales, a space precedes the %.) We should probably just file a different bug for that, though. Over to @ktaki to verify.

**Comment by ktaki** [comment]
New implementation is if the decimal separator is set to other than a period in the system prefs, it is set to use a comma. Windows offers an apostrophe as a choice, and standard Ps honors the selection.
According to wikipedia, however, it is only used in Spanish handwriting. The current implementation is straightforward, works well, and serves the purpose. 

Note for inputting numbers: 
If the decimal separator is a period, numerics with a comma as a decimal separator will be rejected.
If the decimal separator is a comma, both a period and a comma are accepted in numerical input, but the numerics are displayed with a comma as the decimal separator once accepted.

Closing this as fixed. Will address a space preceding % separately.

**Comment by ktaki** [comment]
Apparently, a space preceding % is shown in standard Ps in French and German. DS does not have the space. So, this is non-issue for DS.
