### ISSUE TITLE
Headlights data do not show "Spaces-" categories

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3142]
With the latest mac build pgDev.847, categories prefixed by "Spaces-" are shown as below.

![screen shot 2015-10-26 at 3 53 16 pm](https://cloud.githubusercontent.com/assets/2029597/10744840/fcb7e39c-7bf9-11e5-8614-f295b7ed2053.png)

However, this is not shown when current master branch is used.

![screen shot 2015-10-26 at 3 54 53 pm](https://cloud.githubusercontent.com/assets/2029597/10744842/03e1fe0a-7bfa-11e5-96b6-4fcc23e069d1.png)

**Comment by iwehrman** [comment]
I believe this is as designed. We disable headlights logging in debug mode:

https://github.com/adobe-photoshop/spaces-design/blob/08ed56ecd8a3aa2d2f118df93528d81199a8af14/src/js/util/headlights.js#L46-L50
