### ISSUE TITLE
X/Y transform inputs are broken when multiple layers are selected

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3144]
![img](https://s3.amazonaws.com/f.cl.ly/items/2r1C320f343O1O2i2L3f/Screen%20Recording%202015-10-26%20at%2007.05%20PM.gif)

**Comment by iwehrman** [comment]
Probably a BRC candidate.

**Comment by iwehrman** [comment]
This is actually the same as #3019, (for which there is open PR #3047), but it's worse than that bug states. #3047 is correct that it's the lock-dance routine that is the problem. But, the bigger problem is that this is also the selection-dance routine, which means that this breaks even on _unlocked_ multiply-selected layers.

**Comment by chadrolfs** [comment]
added Watson for BRC.  We will need to submit a formal request as specified in Steve's RCS email.  This bug is currently set to Staging.  Once we submit the request, we should assign it to Mainline.

https://watsonexp.corp.adobe.com//#bug=4079938
