### ISSUE TITLE
Dragging assets onto canvas sometimes results in two children with the same key; unable to swap

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3145]
cmd/ctrl + n (or cmd/ctrl + alt/opt + n and set Resolution to >72)
drag one asset from CC Lib onto canvas (repeat 2x)
select both images

Result: swap is dimmed and console outputs
Warning: flattenChildren(...): Encountered two children with the same key, `.$3283=15`. Child keys must be unique; when two children share a key, only the first child will be used.

**Comment by chadrolfs** [comment]
this is an intermittent bug, not always reproducible but seems easier for me to repro on docs with resolution >72

**Comment by chadrolfs** [comment]
<img width="1044" alt="screen shot 2015-10-27 at 8 45 38 am" src="https://cloud.githubusercontent.com/assets/8442631/10763654/0c423c66-7c88-11e5-8ef7-fa3bbb4e2c2d.png">

**Comment by shaoshing** [comment]
I found that if you expand a graphic that is a embedded SO, you will end up adding the layer twice and trigger the error (also #3146)

Reproduce: drag out "Embedded" from "Test - OK" with ALT key pressed

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
