### ISSUE TITLE
Swap enabled for single selected CC Library asset

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3146]
drag a CC Lib asset onto canvas (hit Enter to place)
Result: Swap menu cmd and transform panel icon is enabled

Expect: Swap should only be enabled when only 2 valid objects are selected

**Comment by chadrolfs** [comment]
drag out and select a shape, result: swap is greyed out.

**Comment by chadrolfs** [comment]
Currently, I can only repro on resolution >72.

Workaround: drag LLSO onto canvas, hit Swap icon, all is set right with the world (apparently).

**Comment by shaoshing** [comment]
@chadrolfs I think this is fixed by #3150, can you verify on that branch?

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
