### ISSUE TITLE
Alt/Opt + drag artboard to duplicate after zoom out shifts overlay highlight/bounds

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3149]
cmd/ctrl + n
draw a couple rects
zoom out a few times (cmd/ctrl + -)
with Select tool click + drag on AB title with Alt/Opt key down to duplicate
marquee select

Result: overlay highlight/bounds is shifted.

**Comment by chadrolfs** [comment]
![highlight-afterzoom](https://cloud.githubusercontent.com/assets/8442631/10772171/ed52339a-7cb1-11e5-8b26-8834fd7f5184.gif)

**Comment by volfied** [comment]
Can't repro currently.

**Comment by chadrolfs** [comment]
blocked due to highlighting being broken

**Comment by volfied** [comment]
@chadrolfs Tried couple times and I can't repro this. If you can, can you add more precise steps?

**Comment by chadrolfs** [comment]
Odd, I can repro on 2 different machines

**Comment by chadrolfs** [comment]
close all open doc, reset DS, then start from the top.  There aren't really any additional steps to what's above.

**Comment by mcilroyc** [comment]
please validate, @chadrolfs

**Comment by chadrolfs** [comment]
validated
