### ISSUE TITLE
Multiple selection: setting W also sets Y to a standard 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3151]
cmd/ctrl + n
draw out several rects of different sizes (both W & H)
select them all with Select tool (W/H/X/Y are all mixed values so fields show --)
enter a value into W

Result: Y value also gets set, making the shapes all the same size

**Comment by chadrolfs** [comment]
![setx-fixesy](https://cloud.githubusercontent.com/assets/8442631/10775573/df46d282-7cc6-11e5-9b81-220f5feb76fc.gif)

**Comment by chadrolfs** [comment]
wondering if this will be addressed by #3047 since it deals with Transformation fields.

**Comment by chadrolfs** [comment]
This broke sometime after the Sprint 33 build ( 20f8742f7188333db70ddac6688838d118723917 )

**Comment by mcilroyc** [comment]
chad, it seems broken to me on the commit you referenced (20f8742)

**Comment by mcilroyc** [comment]
by bisecting starting with 32.1 sprint release, I found:
0da3c2f81799372c8696d801be21e64bad508c3f is the first bad commit

**Comment by mcilroyc** [comment]
stealing this for now - but @shaoshing (original assignee) let me know if you want it back, or whatnot

**Comment by chadrolfs** [comment]
Thanks Cory.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
