### ISSUE TITLE
Entering negative transform value for LLSO (and other layers, i.e. Type) results in badness

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3153]
cmd/ctrl + n
drag a library asset onto canvas
click in Transform field (W) and enter a negative number (-50), Enter

Result: all fields are now blank.  If you click on Layer 1 you'll error
`Action transform.setSize failed: Error: Photoshop returned an error when playing command number: 2 Photoshop code: -1 Photoshop message: error: -1 message: Could not complete the command because the initial bounding rectangle is empty.`

**Comment by chadrolfs** [comment]
![screen shot 2015-10-28 at 9 53 42 am](https://cloud.githubusercontent.com/assets/8442631/10796137/0d195872-7d5a-11e5-8395-331aa7921baa.png)

**Comment by chadrolfs** [comment]
![screen shot 2015-10-28 at 9 57 37 am](https://cloud.githubusercontent.com/assets/8442631/10796156/1f1dcb5c-7d5a-11e5-83a2-2a818897d8a8.png)

**Comment by shaoshing** [comment]
This is probably a core issue. The valid range for size is 0.1 ~ 32000 in DS. However, if we set the width / height to 0.1 for some graphics (for example, `Test - OK` > `Climber`), they will turn into invisble with null w/h/x/y.

**Comment by shaoshing** [comment]
Watson: https://watsonexp.corp.adobe.com/#bug=4080692

**Comment by ktaki** [comment]
This issue still exists, but console does not show any errors now. See the #3526.

**Comment by ktaki** [comment]
Opened a bug in JIRA. https://jira.corp.adobe.com/browse/PS-884

**Comment by chadrolfs** [comment]
I'm still able to hit this:

![negxformvalues](https://cloud.githubusercontent.com/assets/8442631/13188538/e35614a6-d706-11e5-9e8d-ea20c3b4b3f2.gif)

**Comment by chadrolfs** [comment]
using pgdev.1081 w/master @ 58fc655e7f74cf28b2550a5c3f87d4060b585a5e

**Comment by iwehrman** [comment]
Isn't this the different bug that has to do with proportional locking? See #3725.

**Comment by chadrolfs** [comment]
Oh right, my bad.  As written, this is fixed.
