### ISSUE TITLE
Marquee select doesn't work dragging from masked out area

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3158]
Open CannoSelectLayers.psb
click and drag in empty space to marquee select

Result: no marquee

Workaround: click+drag from outside masked layer bounds or shift+click on layers or shift+drag

**Comment by volfied** [comment]
@chadrolfs Is this fixed alongside all other highlighting/marquee fixes?

**Comment by chadrolfs** [comment]
no, this is still an issue with current resources, pgdev.921 master @ dd265a7

**Comment by volfied** [comment]
After #3474 is merged, please consider that #3475 has been created to keep track of marquee select issues on vector masked layers with polygon masks.

**Comment by mcilroyc** [comment]
Addressed (partially?) by 3474.  passing to @chadrolfs for review.
