### ISSUE TITLE
Entering mask mode, hitting Delete, then switching tools results in error

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3161]
cmd/ctrl + n
create a layer you can mask so either drag in a LLSO or
create a rect shape, then cmd/ctrl + g to create a group
hit v for Select tool
hit m to enter Mask Mode
hit Delete key
hit r for Rect tool

Result: Switching tool kicks you out of Mask Mode and console spits -
 `Action tools.select failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “<unknown>” is not currently available.`

**Comment by chadrolfs** [comment]
![screen shot 2015-10-28 at 4 03 38 pm](https://cloud.githubusercontent.com/assets/8442631/10805725/4403baac-7d8d-11e5-9cb9-acfa786526d1.png)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
