### ISSUE TITLE
Resizing multiple artboards via Transform fields can have unexpected results

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3164]
open explore-mt-hood.psd
select ~~all 3~~ an artboards
click in H field and Shift+up arrow a few times
click in W field and Shift+up arrow a few times

Result: artboards jump extremely left

Note: reference point is bottom left

**Comment by chadrolfs** [comment]
![ab-jump-jump](https://cloud.githubusercontent.com/assets/8442631/10806637/4521d782-7d94-11e5-963c-a849fc9facff.gif)

**Comment by chadrolfs** [comment]
can repro with just one AB selected (don't need to select all 3)

**Comment by iwehrman** [comment]
I think standard PS explicitly removed support for on-canvas resizing of multiple artboards at once. We should probably just enforce that same constraint in our transform panel as well.

**Comment by volfied** [comment]
I can't repro this today.

**Comment by chadrolfs** [comment]
make sure the ref point is bottom right.

**Comment by iwehrman** [comment]
Disable the resize of multiple artboards to downgrade this to workflow.

**Comment by ktaki** [comment]
I think the original jumping issue was fixed, but the canvas is not expanded until artboard is moved.

![screen shot 2016-02-18 at 3 12 00 pm](https://cloud.githubusercontent.com/assets/2029597/13161368/141fee5a-d652-11e5-8c5a-eca95cf38bc8.png)

**Comment by ktaki** [comment]
I opened a new issue #3726 for the above.

**Comment by ktaki** [comment]
@chadrolfs: I think the original problem was fixed. Do you see any issues with resizing multiple ABs?

**Comment by chadrolfs** [comment]
Yep, verified this is fixed.  Thanks for logging the other issue.
