### ISSUE TITLE
A library sticks every time coming back to DS

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3168]
DS started with Library A selected. Select Library B. Switch to standard Ps, and switch back to DS. Library A is selected. I expect Library B is selected. This behavior seems started happening recently.

**Comment by chadrolfs** [comment]
related to if not a dupe of #2360

**Comment by ktaki** [comment]
Yes, it might be related, but here, the issue is more towards within DS. The stickiness to a particular lib happens when quitting Ps in DS mode and starting Ps in DS mode.

**Comment by volfied** [comment]
FNBC to Taki

**Comment by ktaki** [comment]
Verified the fix.
