### ISSUE TITLE
Color of shape resets to default

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3169]
In Standard Ps, create a new doc, and draw a rectangle. Change the color. With the shape layer selected, switch to DS. RESULT: The color of the rectangle is reset to default (gray).

**Comment by pineapplespatula** [comment]
We are setting the default of shapes intentionally. assigning to @placegraphichere for discussion

**Comment by iwehrman** [comment]
I don't think @ktaki means that the default is changing. I think he means that the color of the existing layer is changing.

**Comment by ktaki** [comment]
Sorry for the confuse on the title. Yes, color will reset.

**Comment by volfied** [comment]
Adding to STR: You need to leave rect tool selected.

**Comment by volfied** [comment]
Gets reset because tools.resetShapeDefaults gets called before document is initialized, which skips the selection dance and forces the selected layer's colors.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.

**Comment by chadrolfs** [comment]
https://watsonexp.corp.adobe.com/#bug=4087965
