### ISSUE TITLE
Search: clear field icon (x) is not shown when you select a category

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3187]
cmd/ctrl + f
arrow down to display datalist, click on Open Documents

Result: Open Docs category icon is shown in search field but (x) icon to clear field is not

alternately, if you type "Open" then click on Open Documents category, the icon shows in field as in steps above but now the (x) icon shows

**Comment by chadrolfs** [comment]
![search-x](https://cloud.githubusercontent.com/assets/8442631/10918194/4a5dc484-8219-11e5-8fa3-2ab5af1c3e6c.gif)

**Comment by DivyaPrabhakar** [comment]
@chadrolfs I am not able to repro this. I am using Mac build 936 and on master, here is what I see: 

![](https://www.dropbox.com/s/p5kkonpj2w86i4g/xsearchbar.gif?raw=1)

**Comment by chadrolfs** [comment]
Instead of first hitting any alpha-numeric keys (letter "o") follow the step in the bug.  cmd/ctrl + f, then down arrow, click on Open Docs

**Comment by chadrolfs** [comment]
I can still repro on pgdev.936 and master @ d44c3f9

**Comment by DivyaPrabhakar** [comment]
@chadrolfs got it now, thanks.
