### ISSUE TITLE
Opening/Closing Folders shows changed file status without ability to save

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3191]
- Create new file with some folder/artboards
- Save the file
- Open/close the AB or folder a few times using the layers panel
- Get into a state where the file has the asterisk, but the file menu does not allow a save. 
- Exiting Ps will prompt a file-has-changed save tho

- expected: saving file menu and CMD+S should be in sync with the folder changes

![screen shot 2015-11-03 at 8 12 46 pm](https://cloud.githubusercontent.com/assets/3229167/10927716/b14b6f9a-8267-11e5-916c-2e03f3f4bb18.png)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
