### ISSUE TITLE
Unable to align children within artboard

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3197]
cmd/ctrl + n
draw some shapes and group them (within AB)
(in layers panel) select the group and the artboard layer (cmd/ctrl + click)

Result: align icons/cmds are disabled  (in classic PS, the are not)

**Comment by volfied** [comment]
FBNC to @chadrolfs

**Comment by chadrolfs** [comment]
fix for this may have caused/exposed this bug #3468
