### ISSUE TITLE
Entering DS with a shape selected over-writes Fill and Stroke settings

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3210]
Start in standard PS
hit U for Rect shape tool, set a specific color for fill and stroke (also change stroke size)
draw out a shape
switch to DS

Result: Shape is set to DS defaults and over-writes previous settings from standard PS

**Comment by chadrolfs** [comment]
I thought this was already written up.  Apologies if this is a dupe.

**Comment by ktaki** [comment]
@chadrolfs  I just closed #3169. Can you double check with the latest master?

**Comment by chadrolfs** [comment]
ah, that explains it. ran into this finishing up RC sweep.  Verified this is fixed on current master - Closing as dupe
