### ISSUE TITLE
Export SVG `path` data on artboards often adds unnecessary `transform`

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3211]
- Create a non-standard shape by editing a rect or adding points so it will no longer be a `rect`, rather a `path`
- Create a new artboard
- Copy and drag the shape to the new artboard 
- Export the artboard using Crema or Ds using SVG
- Result: The shape `path` in the SVG  will have additional `transform=translate()` data on it for no real reason.

- Expected: no additional transform data

Notes: 
- if this is attempted with simple shapes like a `rect`, the transform will not be applied.
- I believe this is a regression since I've been using SVG for icon creation for some time with previous PS builds

![screen shot 2015-11-05 at 5 01 33 pm](https://cloud.githubusercontent.com/assets/3229167/10984421/ec000da8-83de-11e5-9b6e-007f0846cd3c.png)

Example files:
https://www.dropbox.com/s/c2twmxo2oidbeyp/Untitled.psd?dl=0

Exported Artboard: 
https://www.dropbox.com/s/osbgr09es56xpqy/Artboard%202.svg?dl=0

**Comment by iwehrman** [comment]
I believe this is a generator-core (actually an SVG OMG) bug, so we may want to move it there. CC @mcilroyc @tomwmcrae.

**Comment by placegraphichere** [comment]
logged this issue with svg omg folks on corp #413

**Comment by dirkschulze** [comment]
https://git.corp.adobe.com/WebPA/svgObjectModelGenerator/issues/413

This is indeed coming from svgOMG. Just to give a bit of context: The art is somewhere on the document and we trim the output to the art bounds. For that we need to shift the position of shapes. This is fairly simple for rectangles. It gets more complicated for arbitrary shapes with arbitrary transforms. It is definitely a planned enhancement to avoid applying a transform in those cases. However, you will probably notice that simply removing the transform gives a wrong visual result. Unless we do not apply the transform to the path the transform attribute will be required.
