### ISSUE TITLE
2nd resize of expanded CC Lib asset fails

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3212]
cmd/ctrl + n
load CC Lib: Test - OK to accidentally nuke
alt/opt + drag asset onto canvas (GearSale)
Resize it with Shift key to constrain, move and resize again

Result: 2nd attempt fails

**Comment by chadrolfs** [comment]
![cc-lib-2nd-resizefail](https://cloud.githubusercontent.com/assets/8442631/10984951/285c9454-83d2-11e5-8ad0-9b2629bb936c.gif)

**Comment by chadrolfs** [comment]
![screen shot 2015-11-05 at 3 34 28 pm](https://cloud.githubusercontent.com/assets/8442631/10985051/cca20986-83d2-11e5-9469-3f79d647d6bf.png)

**Comment by chadrolfs** [comment]
![screen shot 2015-11-05 at 3 36 12 pm](https://cloud.githubusercontent.com/assets/8442631/10985082/098e32c0-83d3-11e5-8adb-7dad63fd560a.png)

**Comment by volfied** [comment]
As the last screenshot shows, this is related to the bounds not updating correctly. Make sure to keep Help > Show Policy Frames enabled to see whether bounds are correctly updating as you resize the expanded layers.

**Comment by volfied** [comment]
FBNC to @chadrolfs
