### ISSUE TITLE
missing file error loading master: ico-layer-search.svg and ico-libraries-cc.svg 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3218]
load current master
result: `GET file:///Users/crolfs/playground-repos/spaces-design/img/ico-layer-search.svg net::ERR_FILE_NOT_FOUND`
`GET file:///Users/crolfs/playground-repos/spaces-design/img/ico-libraries-cc.svg net::ERR_FILE_NOT_FOUND`

**Comment by iwehrman** [comment]
I think this is somehow related to #3214. It seems like our LESS files have `url`s that are relative to the current file, but that they're interpreted different in debug and compiled mode :(
