### ISSUE TITLE
Select: Leaf layer highlighting doesn't work with modifier key

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3224]
new doc, create a bunch of shapes and nest them in groups
deselect (nothing selected)
mouse over the shapes with Select tool (result top level group highlights)
hold down cmd/ctrl and mouse over shapes

Result: no highlighting at all

**Comment by iwehrman** [comment]
Looks good, works good.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
YAY!  A bug fix to verify.

**Comment by chadrolfs** [comment]
Here is a case where it doesn't work, where a selection bounding box includes unselected layers that you want to add to the selection (holding Cmd/Ctrl + Shift).  

![select-overlap](https://cloud.githubusercontent.com/assets/8442631/11155783/a45bfcf4-89fc-11e5-955d-a25eaa77a387.gif)

**Comment by iwehrman** [comment]
FBNC 2 @chadrolfs again :notes:

**Comment by chadrolfs** [comment]
2nd case was originally #3195 but now 'tis fixed, yay!
