### ISSUE TITLE
Placing smart object should skip the transform modal state

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3246]
There's already a standard PS preference for this:
![image](https://cloud.githubusercontent.com/assets/1075154/11156416/a6b446ce-8a00-11e5-9b36-aa4751a3484b.png)

**Comment by iwehrman** [comment]
As of #3598, we now skip the transform mode by default when placing. I am wary that this will cause some bugs, mainly because we've had to put in so many hacks and workarounds to deal with placing objects already. FBNC to @ktaki, but testing from @chadrolfs would be great too!

**Comment by ktaki** [comment]
Looks good to me. Turn it over to @chadrolfs.

**Comment by chadrolfs** [comment]
Still sometimes gets stuck on LLSO, but that's tracked here #3575. Secondarily also relates to #3102.  Otherwise, this looks good to me as well.
