### ISSUE TITLE
On-canvas highlighting broken

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3251]
create a new doc, select the artboard
Result: adders do not show on-canvas

create some rects and mouse over
result: no blue highlighting

**Comment by chadrolfs** [comment]
Show Policy Frames doesn't work either

**Comment by volfied** [comment]
Something changed and we no longer get OS.externalMouseMove events, I'm looking at it.

**Comment by volfied** [comment]
https://github.com/adobe-photoshop/spaces-design/issues/3278 is a dupe of this.

**Comment by volfied** [comment]
https://jira.corp.adobe.com/browse/PS-306

**Comment by chadrolfs** [comment]
related to #3312

**Comment by shaoshing** [comment]
Fixed by #3320
