### ISSUE TITLE
Changing type box size creates a secondary visual change to the type

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3252]
Resizing a text-box will allow live editing, but then when the mouse is released, the type will resize one additional time. 

Expected: Type should remain in place after resizing.

Note: this also occurs when editing text, but this is a more pronounced way to see it. Standard Ps does not have this secondary resize.

Screen cap: https://www.dropbox.com/s/zjgt0ol7mereniy/text-editing-jump.mov?dl=0

**Comment by ktaki** [comment]
This issue has been reported in watson as https://watsonexp.corp.adobe.com/#bug=4049956.

**Comment by chadrolfs** [comment]
Not our bug.  Closing
