### ISSUE TITLE
Opening Illustrator file (Import PDF) results in error and no doc ID

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3253]
Open an Illustrator file
Import PDF dialog: accept defaults and click OK

result: new doc is open/created but UI still shows no doc state (no layers or doc title).  console error: 
`Uncaught Error: Document opened with no ID`

![screen shot 2015-11-16 at 2 11 42 pm](https://cloud.githubusercontent.com/assets/8442631/11196534/6c71bfa0-8c6c-11e5-8454-fbc8ba03170b.png)

Shipped in 16.1

**Comment by chadrolfs** [comment]
Also, attempting to open these via MRU fails and results in
`Action documents.open failed: TypeError: Cannot set property 'selection' of undefined`

**Comment by volfied** [comment]
There is one bug in our adapter side, where lib/document.js `openDocument` was not constructing the descriptor correctly, showing the above error. But there is still a problem opening these files, so I will have to look at PS sources to figure out what's going on. But it's mainly a core problem.

**Comment by volfied** [comment]
So, this has two fixes.

One is in playground-dev, CL 1054573, and adds the document ID to all open PDF/AI descriptors.
Other is in spaces-adapter, https://github.com/adobe-photoshop/spaces-adapter/pull/170, which will fix the open recent showing Open dialog problem.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs?
