### ISSUE TITLE
Color Picker Opacity field accepts out of range values sending indicator outside 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3254]
draw a shape, click on color picker, click in Opacity field, Shift + up/down arrow

Result: field accepts values greater than 100 and less than 0 sending indicator outside color picker border

![colorpicker-opacity](https://cloud.githubusercontent.com/assets/8442631/11197391/f67035e2-8c71-11e5-812c-60f85740e5bf.gif)

**Comment by placegraphichere** [comment]
![spinal_tap_-_up_to_eleven](https://cloud.githubusercontent.com/assets/3229167/11198940/a55cd97c-8c8e-11e5-8eb1-fc1fe050632e.jpg)

**Comment by chadrolfs** [comment]
hah yaaaasssss!
