### ISSUE TITLE
Error opening Search dialog

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3256]
With the Pg-Dev Mac build #886, clicking on search icon produces errors.

Transfer from search.toggleSearchBar to dialog.openDialog failed: Error: Translation not found for: menu.WINDOW.OPEN_DOCUMENT

![screen shot 2015-11-17 at 10 40 30 am](https://cloud.githubusercontent.com/assets/2029597/11221182/8d793cf8-8d18-11e5-9b26-db23bf70507f.png)

**Comment by iwehrman** [comment]
After the fix for this in #3261, there are now a bunch of string keys that just map N -> N and I can't figure out why. This seems like useless cruft. Back to @pineapplespatula to clean it up.

**Comment by volfied** [comment]
Back to @iwehrman to close
