### ISSUE TITLE
Errors on closing a doc while in text editing mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3258]
Tested with pg-dev Mac build 886.

Create a text layer. While in text editing mode, Cmd-W to close the doc. Click on Do not save.

Action layers.resetLayers failed: Error: unknown exception type

![screen shot 2015-11-17 at 11 04 25 am](https://cloud.githubusercontent.com/assets/2029597/11221784/c23bd27c-8d1b-11e5-8a87-f5958e55c58e.png)
![screen shot 2015-11-17 at 11 04 41 am](https://cloud.githubusercontent.com/assets/2029597/11221787/ca45ad80-8d1b-11e5-8f51-c8ebfa87d311.png)

**Comment by mcilroyc** [comment]
fixed by ref'd PR.  back to @ktaki

**Comment by ktaki** [comment]
Verified the fix.
