### ISSUE TITLE
Opening a LLSO has incorrect coordinates and highlight location

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3259]
new doc
drag a LLSO onto canvas (note it auto-commits)
hit Enter (opens LLSO)

Result: artboard adders and highlighting coordinates are off

**Comment by chadrolfs** [comment]
![openllso-badcoords](https://cloud.githubusercontent.com/assets/8442631/11222175/cd7d7814-8d1d-11e5-8c6c-1f1d6b3a6cbc.gif)

**Comment by shaoshing** [comment]
Might related to #3251 because I also see this in regular document. Will check again once #3251 is resolved.

**Comment by shaoshing** [comment]
![screen shot 2015-11-30 at 3 13 09 pm](https://cloud.githubusercontent.com/assets/118264/11487559/e8bc45ae-9774-11e5-8f58-5080df7be8f0.png)

**Comment by shaoshing** [comment]
Fixed by #3320
