### ISSUE TITLE
Errors on entering vector mask mode with superselect tool selected

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3260]
Tested with pg-dev Mac 688 build.

Open a new dox. Select super select tool. Click on the vector mask mode icon.

Transfer from tools.changeVectorMaskMode to tools.select failed: Error: Translation not found for: strings.TOOLS.superselectVector

![screen shot 2015-11-17 at 11 25 30 am](https://cloud.githubusercontent.com/assets/2029597/11222271/6a40ba80-8d1e-11e5-87de-239d4f0171f5.png)
![screen shot 2015-11-17 at 11 25 53 am](https://cloud.githubusercontent.com/assets/2029597/11222281/74d93ddc-8d1e-11e5-895e-814aed3679e5.png)

**Comment by pineapplespatula** [comment]
this is fixed with #3257

**Comment by ktaki** [comment]
Verified the fix.
