### ISSUE TITLE
Error on adding layer styles from libraries

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3264]
Create a shape layer. Click on a layer style from a CC library.

Action libraries.applyLayerStyle failed: Error: value conversion failed

![screen shot 2015-11-17 at 3 10 07 pm](https://cloud.githubusercontent.com/assets/2029597/11227836/660ff038-8d3d-11e5-8a9b-6378b37523a5.png)

**Comment by volfied** [comment]
Shoud be fixed with #3294

**Comment by ktaki** [comment]
Verified the fix.
