### ISSUE TITLE
Errors on Next Document and Previous Document

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3268]
Open two docs. Execute Window->Next Document and Window->Previous Document

Action documents.selectNextDocument failed: TypeError: Cannot read property 'get' of undefined
Action documents.selectPreviousDocument failed: TypeError: Cannot read property 'get' of undefined

![screen shot 2015-11-18 at 11 20 17 am](https://cloud.githubusercontent.com/assets/2029597/11251635/07f91ac4-8de7-11e5-8b0f-e595155af706.png)
![screen shot 2015-11-18 at 11 20 59 am](https://cloud.githubusercontent.com/assets/2029597/11251641/0c45b290-8de7-11e5-87fb-6f41967be56c.png)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
