### ISSUE TITLE
Selecting a layer group may result in collapsing the group.

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3271]
This occurs on some layers.

![select-layer](https://cloud.githubusercontent.com/assets/118264/11253313/92883898-8def-11e5-8378-9c0862b0f7c4.gif)

Reproduce
1. open `VermilionArtboards.psd`
2. expand art board `Desktop Large` while holding OPT key
3. scroll to `Fashion` group (it should be expanded)
4. select the group, and it is selected but also collapsed

**Comment by shaoshing** [comment]
JIRA: https://jira.corp.adobe.com/browse/PS-439

**Comment by shaoshing** [comment]
These groups appears to be expanded, but switching to classic shows that they are actually collapsed.

**Comment by mcilroyc** [comment]
to @chadrolfs - note the required build of mac dev >= 932
