### ISSUE TITLE
Open search dialog throws "Translation not found" error

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3272]
We don't seems to have the translation key `menu.FILE.OPEN_RECENT.19`, the maximum number is 16. 

![screen shot 2015-11-18 at 12 32 38 pm](https://cloud.githubusercontent.com/assets/118264/11253459/84a5f5fc-8df0-11e5-8315-dcbf2f323a38.png)

**Comment by DivyaPrabhakar** [comment]
I was just about to create the same issue.

**Comment by placegraphichere** [comment]
Same

**Comment by shaoshing** [comment]
Duplicate with #3256
