### ISSUE TITLE
Error on Clear Guides

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3276]
Create a new doc, add a guide, and run View->Clear Guides.

Action guides.clearGuides failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -1 Photoshop message: error: -1 message: Could not complete the Clear All Guides command because of a program error.

![screen shot 2015-11-18 at 3 01 35 pm](https://cloud.githubusercontent.com/assets/2029597/11257297/85ddc4c6-8e05-11e5-9cfd-cfdfb6adf92b.png)

**Comment by mcilroyc** [comment]
related(?): I get an error when *creating* the first guide on a new document.  Almost certainly related to #3274   - I'll investigate further.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
