### ISSUE TITLE
Blue regions for guide creation still available after Show Guides is turned off

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3277]
The blue regions for creating guides still be shown after Show Guides is turned off in the View menu until layer selection is changed on canvas or in the Layers panel. It should be turned off immediately after the command is executed. This also happens when Show Guides is turned on. The blue regions are not available till a layer is selected, or layer selection is changed.

**Comment by volfied** [comment]
I can't repro this, the overlays get cleared out correctly. Please confirm.

**Comment by ktaki** [comment]
CNR with current master. Closing.
