### ISSUE TITLE
focus lost after setting color via color picker

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3281]
new doc
drag out 2 rect shapes
click on Fill color and click to set color
press Shift + Tab

Result: focus switches to other rect shape

**Comment by chadrolfs** [comment]
![colorpicker-lostfocus](https://cloud.githubusercontent.com/assets/8442631/11258518/9772834e-8e0e-11e5-9435-657f5288dbde.gif)

**Comment by chadrolfs** [comment]
happens on 16.1 GM (r.301)

**Comment by iwehrman** [comment]
Sliders eventually need to be made focusable.

**Comment by iwehrman** [comment]
Or, on mouse up, refocus whatever was focused before.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
