### ISSUE TITLE
Expanding/collapsing layers is slow

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3284]
Especially expanding, and especially when option-clicking to expand all descendants. It's very easy to make this take > 1s.

**Comment by shaoshing** [comment]
Shall we delete this as it seems duplicate with the JIRA tasks?

**Comment by iwehrman** [comment]
I'd like to keep these performance bugs open even though there are overlapping JIRA stories. It's OK with me if everyone else wants to ignore performance bugs like this, but I find it useful though to track them in Github.

**Comment by iwehrman** [comment]
Over to @chadrolfs to evaluate.

**Comment by chadrolfs** [comment]
Testing Vermillion on both Mac and Win, it takes less <1 sec to expand all groups within any of the artboards.  @iwehrman reopen if you still want to keep this open.
