### ISSUE TITLE
Scrubby mixin is handling all window mousemove events

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3286]
The Scrubby mixin is intercepting ALL window mousemove events because it is registering itself on the window at component mount time. Instead, it should only register this handler when you mousedown on the input's label and unregister the handler on mouseup.

**Comment by volfied** [comment]
Grabbing from Jeffrey as I'm wiring up all the scrubbies.

**Comment by mcilroyc** [comment]
satisfied @iwehrman ?
