### ISSUE TITLE
history.revertCurrentDocument is slow

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3289]
This is a "request for investigation". When I load Design Space with a dirty copy of Vermilion, `documents.beforeStartup` takes 1.3s. However, if I then ~~undo/~~revert, there is a history cache miss and `history.revertCurrentDocument` is called, and this takes 6.3s. Why is this so much slower than `documents.beforeStartup`? It feels like I should know this off the top of my head but I don't. Obviously we're loading less state in the former than the latter, and so it seems like we should probably port that optimization (whatever it is) to the latter as well.

Also: there are probably other instances where this optimization has yet to be ported over, and it would be good to take a look at all of them!

CC @mcilroyc

**Comment by iwehrman** [comment]
I now see that this only happens for `history.revertCurrentDocument` and not for `edit.undo`. And, after examining the transfer log, I see that we aren't spending any more time in the former in JavaScript than the latter. I guess Photoshop's revert command is just really slow! So, probably we should just close this, unless anyone thinks it would be worthwhile to log a JIRA but for this, or just seal with it as FOL.

**Comment by mcilroyc** [comment]
An observation: revert does not simply step back to the last-saved history state, but in fact creates a *new* history state based on the last saved document.  That doesn't really explain *why* it is slow, but is an indication that it is "different"
