### ISSUE TITLE
Linespacing and Letterspacing in tooltips

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3296]
These words are used in the tooltips for leading and tracking in the appearance panel for text layers. These should be corrected to "Line Spacing" and "Letter Spacing"

**Comment by ktaki** [comment]
Verified the fix.

**Comment by chadrolfs** [comment]
not seeing this fixed on current master.  did it just re-break?

**Comment by placegraphichere** [comment]
Should be seeing something like this:

![screen shot 2015-11-25 at 1 01 55 pm](https://cloud.githubusercontent.com/assets/3229167/11406782/c2954de8-9374-11e5-92f3-33e929c422ed.png)
![screen shot 2015-11-25 at 1 01 49 pm](https://cloud.githubusercontent.com/assets/3229167/11406781/c2948250-9374-11e5-9698-5b987129d556.png)

**Comment by chadrolfs** [comment]
doh, i was loading the webpack repo instead of design-space
