### ISSUE TITLE
Undo re-order of uninitialized layers failed

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3307]
When you re-order an uninitialized layer and hit undo, the LayerPanel is not updated until you click on the item to trigger an update. Please see video for repro steps:

https://www.dropbox.com/s/p7qbxxv4td99fzy/layer-reorder-undo.mov?dl=0

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify.
