### ISSUE TITLE
Deleting vector mask fails

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3309]
Open an image doc. Enter vector mask mode. 
Select Ellipse tool and draw an ellipse mask path. 
With Select tool, double-click inside the ellipse
Click on a path handle and move it to expand or reduce the masked area. 
With the direction lines still visible, press 'm' to exit vector mask mode. (Note that the direction lines do not disappear after exiting the vector mask mode. This might be the root cause.) 
Press 'm' to re-enter vector mask mode. 
With the mask selected, hit delete key to delete the mask. 

The error below happens. After this error, DS is in a state that all panels do not update themselves unless they are forced to be redrawn. Add a layer, for example. It does not shown in Layers panel until the Layers panel is collapsed and expanded. Need to reset DS to recover from the state.

Action mask.handleDeleteVectorMask failed: TypeError: Cannot read property 'transfer' of undefined

![screen shot 2015-11-25 at 1 38 48 pm](https://cloud.githubusercontent.com/assets/2029597/11410134/e825f5c6-9379-11e5-89d7-dcdd49564703.png)

**Comment by ktaki** [comment]
This is said to be fixed in PR #3304. To be verified when merged.

**Comment by volfied** [comment]
@pineapplespatula, since #3304 is a bigger PR and will be in the cycle for a while, can you make a separate PR for fixing this issue? It's your single `.bind(this)` line in actions/mask.js as the stack trace shows.

We'd like to get this in before end of week so it's fixed in the next push to Perforce.

**Comment by ktaki** [comment]
This issue appeared to be fixed.
