### ISSUE TITLE
Cannot create new layers

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3318]
With the latest pg-Dev Mac build #906 and master branch (#3315, feec60e), new layers cannot be created with shape tools, pen tool, or type tool. The pg-Dev Mac build #906 itself does not have the issue.

**Comment by ktaki** [comment]
This does not happen with the Mac build #903. Could this be a Core issue caused by tristam's submissions?

**Comment by iwehrman** [comment]
Is there a warning/error/stack trace in the console?

**Comment by ktaki** [comment]
No errors are shown in the console.

**Comment by iwehrman** [comment]
Seems to work again in pgdev 908.

**Comment by ktaki** [comment]
Well, not with my machine. So, you cannot reproduce this? I will try with other machine.

**Comment by chadrolfs** [comment]
yeah, i can repro this bug with pgdev.910 with master @ feec60e

**Comment by ktaki** [comment]
@chadrolfs: Good to hear you can repro. Windows seems working fine. Have you tried on Win?

**Comment by chadrolfs** [comment]
start with Select tool, reset DS, hit r to switch to Rect tool, try to draw a shape.

if you reset DS and you already have a shape tool active, you can create shapes.

**Comment by ktaki** [comment]
Thanks for clarifying the steps. Windows has the same issue.

**Comment by volfied** [comment]
Can repro on Mac with Chad's steps.

**Comment by volfied** [comment]
We have a foreign PROP_TO_BROWSER leftMouseDown policy whenever we start with superselect tool, it doesn't go away, and breaks things. This is the cause, I'm working on it now.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
