### ISSUE TITLE
Datalist: wrong position when the dropdown list is above the input

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3325]
Dropdown list should update its position to bottom align with the input below, when its height changed.

![datalist-dropdown](https://cloud.githubusercontent.com/assets/118264/11511022/784d73d6-981b-11e5-87bf-f9984d0a9672.gif)

**Comment by mcilroyc** [comment]
@ktaki could you please eyeball this?  Fixed with recent PR.

**Comment by mcilroyc** [comment]
Note that the position issue is only visible (prior to this PR) after entering some filtering text on datalists that appear *above* the input.

**Comment by ktaki** [comment]
It looks good now.
<img width="99" alt="screen shot 2015-12-09 at 4 31 26 pm" src="https://cloud.githubusercontent.com/assets/2029597/11703263/5cb32d78-9e92-11e5-9f50-696ac39c1798.png">
