### ISSUE TITLE
StoreWatchMixin broken after controller reset

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3338]
After the controller resets due to an error, React components that registered for changes via the `StoreWatchMixin` no longer receive change events. To test:

1.` Help > Test Action Failure`
2. Zoom in or out and observe that the `Zoom` component in the toolbar does not change.

**Comment by volfied** [comment]
This only happens with UI store, as far as I can tell.. hmmm

**Comment by iwehrman** [comment]
Fixed by #3343.
