### ISSUE TITLE
entering and exiting vector mask mode rapidly causes a transfer error

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#3340]
Method
create file with pixel layer
Press M a number of times very rapidly 

transfer fails because of modal state
<img width="491" alt="screen shot 2015-12-02 at 3 18 53 pm" src="https://cloud.githubusercontent.com/assets/1008531/11547359/11e33db8-9908-11e5-8c95-bce7e6b8dd86.png">

**Comment by ktaki** [comment]
This is no longer reproducible.
