### ISSUE TITLE
Cannot undo transforming object placed with Place Linked and Place Embedded

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3342]
Create a new doc. Place a file using Place Linked or Place Embedded command under File menu. Without committing it (by hitting enter key,) do resize, move, and rotate the placed object. Do Cmd-z a few times. These actions cannot undo. Undo actions are queued however. Hitting enter key will execute the undo actions. As a result, placed object is gone and subsequent undo will produce errors.

![screen shot 2015-12-02 at 3 49 27 pm](https://cloud.githubusercontent.com/assets/2029597/11547907/6c93f7a8-990c-11e5-9201-1136dc111000.png)

**Comment by mcilroyc** [comment]
@ktaki I think the essential character of this issue has changed.  Placing (linked or embedded) now auto-commits, right?

After placing, If you explicitly enter a modal transformation state (by resizing the placed layer, for instance) then Undo does behave "weirdly".  To wit: It uses the standard "undo" command, similar to text editing, only allowing toggling back/forth between current and previous state.  That may be its own issue.  But, I can't seem to produce an error like the one you described above.

**Comment by ktaki** [comment]
@mcilroyc You are right. No error like the above can be reproduced. Undo seems to work reasonably. If I find some oddity on undo, I will open a separate issue. Closing this one.
