### ISSUE TITLE
Faded letters shown on the New Folder button

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3344]
A dialog for selecting a location for saving exported assets on Mac has "New Folder" button that shows faded letters behind "New Folder".

Select a layer with export asset defined. Click on export icon in the Export panel.

<img width="127" alt="screen shot 2015-12-02 at 3 17 10 pm" src="https://cloud.githubusercontent.com/assets/2029597/11549792/086009f4-991e-11e5-8aab-f98f1db5ef58.png">

**Comment by iwehrman** [comment]
Dupe of #3059.
