### ISSUE TITLE
D3 + guides error when resizing window

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3351]
With guides enabled, if I resize the window to be fairly small I get these warnings:
![image](https://cloud.githubusercontent.com/assets/1075154/11572680/5caf68ee-99b7-11e5-8ead-ab33b3797066.png)

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify.

**Comment by chadrolfs** [comment]
I'm still running into these but maybe only when Show Policy Frames is enabled (?).  I'm also seeing incomplete updates on resize. 

![resize-policyunupdate](https://cloud.githubusercontent.com/assets/8442631/11671784/81e50504-9dbf-11e5-93f7-a782393583df.gif)

**Comment by chadrolfs** [comment]
![screen shot 2015-12-08 at 3 24 07 pm](https://cloud.githubusercontent.com/assets/8442631/11671809/a9d7a53a-9dbf-11e5-8d2e-a9533844cac1.png)

**Comment by iwehrman** [comment]
Back to @chadrolfs to verify again!

**Comment by chadrolfs** [comment]
working fantastically!
