### ISSUE TITLE
Artboards get clipped outside original area after transform

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3357]
I do not know how to describe this, but please follow the steps to reproduce. Feel free to change the title.
 
New AB doc
Add a rectangle
Set W to 300
tab
Set H to 300
tab
Set X to 0
Hit return
Cmd-z
V to select superselect tool
Cmd-A
Grab the artboard title to move artboard

![screen shot 2015-12-03 at 4 02 40 pm](https://cloud.githubusercontent.com/assets/2029597/11578115/5c1c5688-99d7-11e5-9990-d096fff2d382.png)

**Comment by volfied** [comment]
Happens on Core as well (as in, you can switch to core, and it stays that way. We should let the artboards team know of this issue.

**Comment by ktaki** [comment]
Yes, it stays that way when switched to standard Ps, but I cannot make it happen in standard Ps. Note that this does not happen with 16.1 GM DS. I can contact cjb.

**Comment by ktaki** [comment]
Verified the fix.
