### ISSUE TITLE
Off-topic question

### ISSUE THREAD

**Issue by cameronmcefee** [adobe-photoshop/spaces-design#3360]
I just stumbled across this project today when digging through the core Photoshop files. Looking at this repo, I'm curious how the tech of the project all works together. Disclosure: I'm the developer of [GuideGuide‌](http://guideguide.me).

For years I've been vexed by ActionDescriptors and whatnot. There have been a few recent Photoshop releases that include awesome upgrades to the guide system that have been beyond my grasp due to lack of documentation. As I was digging through this repo and https://github.com/adobe-photoshop/spaces-adapter, I see a lot of API interactions with guides that I've not seen before in Photoshop. Are the APIs you are working with something that are exposed to vanilla Photoshop, or are they something unique to Spaces?

Put in another way, if I were to spend the effort to reverse engineer how you're doing things like getting and setting artboard specific guides or rendering previews of guides, could I use them in regular Photoshop, or are they unique to the Spaces ecosystem?

I realize this may be on the edge of appropriate and is definitely not related to this repo, so feel free to close and ignore, however you could theoretically dramatically improve my life if there's something here I can learn from your expertise.

**Comment by volfied** [comment]
Hi @cameronmcefee. Spaces works by Photoshop exposing us a `_spaces` object in the global space that allows us to play ActionDescriptors. With `spaces-adapter`, we try to simplify/centralize all our ActionDescriptor code so it acts as both a library and a documentation.

We do not render any of the guides ourselves, and use Photoshop canvas to render them. We also pass the mouse events to Photoshop so the moving of guides is completely controlled by Photoshop as well. The passing of mouse events is something very specific to Spaces, you can see how we calculate what areas to install guide mouse policies in this file: https://github.com/adobe-photoshop/spaces-design/blob/master/src/js/actions/guides.js#L105

At the end of the day, we use only three action descriptors related to guides, `insert`, `remove` and `clear`

**Comment by iwehrman** [comment]
Hi @cameronmcefee! First of all, GuideGuide is very cool. Thanks for building it for Photoshop! 

    Put in another way, if I were to spend the effort to reverse engineer how you're doing things
    like getting and setting artboard specific guides or rendering previews of guides, could I use
    them in regular Photoshop, or are they unique to the Spaces ecosystem?

There isn't currently a way to directly make use of the JSON action descriptor format we use in spaces-adapter repo in standard Photoshop CEP panels. But I do think that all of the action descriptors we can be played in CEP with the ExtendScript `ActionDescriptor`-style syntax. Unfortunately we don't currently have a good, automatic way to convert from one to the other. If you squint, you may be able to do the mapping manually, but it will probably be painful. We've talked about adding support for JSON-style action descriptors to CEP, which would allow easy reuse of the objects in spaces-adapter, but I don't know when (or if) that will actually happen. 

So, yes, I do think you can reverse engineer what you find in spaces-adapter for your projects. Also, if there's a particular thing you're trying to accomplish from CEP with action descriptors but can't quite crack, just send me an email and I'll try to help you find the answer!

**Comment by cameronmcefee** [comment]
@iwehrman Thanks for the explanation! What you describe is what I was figuring/hoping would be the case. While I'm not super sharp with `ActionDescriptor`-style, knowing that there is parity is a handy start.

Thanks for your offer to help. I'll do my best not to abuse your offer. You can expect an email from me soon!

**Comment by jsbache** [comment]
Hi @iwehrman and @cameronmcefee some details.
Designspace use a json serialization for action descriptors, action references, and action lists. We have support for going between that serialization and the ExtendScript support. The following shows how to do so:
function desc2json(descToConvert)
{
    var desc = new ActionDescriptor();
    desc.putObject(S("object"), S("object"), descToConvert );
    var resultDesc = executeAction( S("convertJSONdescriptor"), desc, DialogModes.NO );
    return resultDesc.getString(S("json"));
}

function json2desc(jsonSrc)
{
    var desc = new ActionDescriptor();
    desc.putString(S("json"), jsonSrc );
    var resultDesc = executeAction( S("convertJSONdescriptor"), desc, DialogModes.NO );
    return resultDesc.getObjectValue(S("object"));
}
Designspace use a few action system extensions (such as mult-get and extended references). That support is not yet exposed to the Extendscript environment.
