### ISSUE TITLE
Add grunt task fast-debug

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3363]
Where `fast-debug` just starts the two watchers, doesn't bother to recompile the external dependencies, and doesn't recreate/recopy the build directory. In other words, `grunt fast-debug` would save time in some cases by assuming everything is already set up correctly, except that possibly your JavaScript and LESS files need to be recompiled.

This might be impossible, but who knows.

**Comment by volfied** [comment]
So, there is no way for webpack to skip compiling files when it's first run. Tracked here: https://github.com/webpack/webpack/issues/250

Given that #3366 was just fixed, and how little time the dictionary merging takes (especially in debug when it's only English), I'm suggesting this is never fix at this point. @iwehrman
