### ISSUE TITLE
Layers Panel: CMD+SHIFT+] should scroll panel 

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3375]
When moving layers with CMD+] or any of those variations, the layers panel should scroll to follow if necessary. If the layer/s are within the view in any way, then we should not scroll. It should only scroll when the selected layer is moved out of viewable range.

Ps standard does this.

**Comment by iwehrman** [comment]
I'm surprised this doesn't already work. We should be scrolling to the new selection whenever it's out of view...

**Comment by iwehrman** [comment]
Can you take a look at this in the context of your improved `LayerFace` scroll-to-selection implementation?

**Comment by iwehrman** [comment]
We might just need an action (besides selection) like `layers.exposeLayer`.

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify.
