### ISSUE TITLE
Text Layer Editing: CMD+A should select all of the text 

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3377]
- create text layer
- begin editing the text
- CMD+A does nothing

- Expected: CMD+A should select all of the text

**Comment by placegraphichere** [comment]
Looks like it actually defaults to marquee select, which we don't have in Ds. Upgrading the priority a bit because of that.

**Comment by iwehrman** [comment]
I can't reproduce this.

**Comment by placegraphichere** [comment]
I think I had my steps wrong, closing
