### ISSUE TITLE
Vector mask HUD is very slow to come up

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#3378]
It takes almost 850 ms for the vector mask hud to come up after entering vector mask mode. 
<img width="189" alt="screen shot 2015-12-07 at 1 15 18 pm" src="https://cloud.githubusercontent.com/assets/1008531/11639954/cfb742be-9ce4-11e5-962e-7ebc1919c5f8.png">
<img width="342" alt="screen shot 2015-12-07 at 1 15 41 pm" src="https://cloud.githubusercontent.com/assets/1008531/11639953/cfb61d26-9ce4-11e5-905b-71f7c0044eb6.png">

**Comment by pineapplespatula** [comment]
I'm no longer seeing this issue. I wonder if one of the recent performance fixes cleared this up

**Comment by pineapplespatula** [comment]
@iwehrman are you seeing a delay on your system?

**Comment by iwehrman** [comment]
On a large group I see it take ~400ms on a 4Ghz Core i7. It should always take <= 100ms, so yes, I still see a problem.

**Comment by pineapplespatula** [comment]
@ktaki  I think this issue is resolved, unless you think that the document open case is a blocker.

**Comment by ktaki** [comment]
Here are some data points.
Doc: Vermilion_Site.psd "Desktop Large" selected.
After the document was completely loaded, entered vector mask mode 4 times.

MacBook Pro 2.3 GHz Intel Core i7 (Mac OS X 10.11.2)
1. Finished action tools.changeVectorMaskMode in 499ms with RTT 500ms;
2. Finished action tools.changeVectorMaskMode in 323ms with RTT 324ms;
3. Finished action tools.changeVectorMaskMode in 344ms with RTT 344ms;
4. Finished action tools.changeVectorMaskMode in 338ms with RTT 338ms;
Without HUD shown (i.e., a shape tool was selected): ~100ms

Surface Pro 3 1.90 GHz Intel Core i5 (Windows 10)
1. Finished action tools.changeVectorMaskMode in 1452ms with RTT 1452ms;
2. Finished action tools.changeVectorMaskMode in 533ms with RTT 533ms;
3. Finished action tools.changeVectorMaskMode in 540ms with RTT 540ms;
4. Finished action tools.changeVectorMaskMode in 527ms with RTT 527ms;
Without HUD shown (i.e., a shape tool was selected): ~350m

With the exception of the first attempt on SP3, I did not much stress on the speed, but if the target is said to be less, (note: <=100ms target is too high based on the numbers above), this needs to be looked at further. For the first attempt on SP3, it took nearly 1.5 sec and HUD was not shown. This may be another bug and will be investigated separately.

**Comment by pineapplespatula** [comment]
I think that the baseline for "Without HUD shown" is incorrect.
What it should be a comparison of is entering mask mode with the super select tool on a layer with an existing vector mask 
when I do that test I get numbers on Mac in the range of

Finished action tools.changeVectorMaskMode in 276ms with RTT 277ms; 2/1

making the HUD take < 100 ms

**Comment by ktaki** [comment]
OK. I got it and confirmed the differences are <100 ms as you claimed. Tested on Mac and Windows. Closing.
