### ISSUE TITLE
Menu commands are broken in search

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3382]
![image](https://cloud.githubusercontent.com/assets/1075154/11641760/d9f4bcfc-9cee-11e5-8030-6b31534d881f.png)

CC @DivyaPrabhakar

**Comment by mcilroyc** [comment]
looks fixed to me, but leaving with @iwehrman as one final check... and to make sure he didn't have some other concern with the underlying PR.
