### ISSUE TITLE
Lost spinner on Export

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3384]
A spinner is no longer shown while exporting assets. This is the case for both quick export from Export panel and exporting from Export dialog.

**Comment by mcilroyc** [comment]
@designedbyscience update here if think your work fixes this issue.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
The spinner does not show up in the Export panel on Mac. It's there for Export dialog on Mac and both Export panel and Export dialog on Windows.

<img width="289" alt="screen shot 2015-12-09 at 4 07 39 pm" src="https://cloud.githubusercontent.com/assets/2029597/11702925/99002310-9e8f-11e5-86f5-d3936c77f147.png">

**Comment by ktaki** [comment]
Sorry, wrong statement in the previous comment. The spinner does NOT shown in the Export panel on Mac and Windows. It is shown in Export dialog on Mac and Windows. Mac and Windows versions are consistent.

**Comment by mcilroyc** [comment]
Export panel fixed by second PR.  back to @ktaki again.  @designedbyscience is sorry : )

**Comment by ktaki** [comment]
Verified the fix.
