### ISSUE TITLE
Application Frame setting not reset returning to standard PS

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3396]
launch in standard PS, uncheck Window > Application Frame
enter DS, return to standard PS
Result: Application Frame is now checked.
Expect: previous user specified setting to be honored

https://twitter.com/robedhapa/status/674352563630817280

**Comment by ktaki** [comment]
https://jira.corp.adobe.com/browse/PS-881

**Comment by ktaki** [comment]
It turned out that this issue has been reported a couple of times in the past in Watson, and withdrawn as AsDesigned. See https://watsonexp.corp.adobe.com/#bug=3948755.
