### ISSUE TITLE
Promise warnings during startup (again)

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#3398]
During startup, it seems like we're getting the Promise related warnings again.  still?
![screenshot](http://cl.ly/image/3c2e3D2M0z3c/Image%202015-12-08%20at%206.30.51%20PM.png)

**Comment by mcilroyc** [comment]
only happens when npm linked to spaces-adapter.  @volfied

**Comment by iwehrman** [comment]
Pretty sure we need to `Promise.config` in spaces-adapter in the same way that we do in spaces-design.

**Comment by iwehrman** [comment]
FBNC to @mcilroyc.

**Comment by mcilroyc** [comment]
booya
