### ISSUE TITLE
Library Asset subtitles can push buttons out of view

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#3404]
![untitled-1___66_7___rectangle_1__rgb_8____](https://cloud.githubusercontent.com/assets/22372/11697096/fed5f408-9e85-11e5-80dd-de36871f5eae.png)

**Comment by iwehrman** [comment]
@placegraphichere: is this still FIP?

**Comment by shaoshing** [comment]
This is fixed by #3583. Over to @designedbyscience to verify.

**Comment by iwehrman** [comment]
This looks fixed to me!
