### ISSUE TITLE
Scrubbing position needs performance improvement (finesse) 

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3424]
Performance should mirror standard PS:
small drag mouse movements should increment/decrement by 1 value
Shift + drag should increment/decrement by 10

**Comment by chadrolfs** [comment]
Should be in parity with standard PS functionality.  See scrubbing X and Y of an object in Free Transform mode.

**Comment by iwehrman** [comment]
dupe of #3426
