### ISSUE TITLE
Turbo and slow-mo scrub

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#3426]
If you scrub on a an inch on screen it should scrub about an inch on canvas. regardless of the resolution of the document.

**Comment by volfied** [comment]
I disagree with this. Right now, based on zoom level, I move my mouse by 1 pixel, and my layer changes width by 3 pixels. There is no fine tuning possible and as a user I would find it aggravating if I had to switch methods to get last few pixels right.

**Comment by volfied** [comment]
Dropping this on @placegraphichere's plate for his input.

**Comment by placegraphichere** [comment]
Are we talking about scrubbing the dimension inputs? Sliders? Or what?

![screen shot 2015-12-12 at 3 57 10 pm](https://cloud.githubusercontent.com/assets/3229167/11764113/08679868-a0e9-11e5-991e-bde940f8e75e.png)
If we're talking about dimension inputs, we should try and maintain consistent speed. I'd find it quite jarring if I scrubbed an input and found that at one zoom level it went a certain speed, and at another it went faster. You begin muscle memory on how far to move something for an expected result. Constantly changing the feel of that doesn't allow that comfort level.

The important thing about scrubbers is the ability to change the value from single digit changes all the way to large changes, and feel the ability to get that without difficult small mouse moves.

An amazingly weird way a 3D app called Blender does this is to allow screen looping of your mouse. So dragging your mouse will literally loop around the screen as you scrub in one direction. Its weird, but quite nice so you never run out of room for large changes.

They also have a nice SHIFT+drag that will slow the increment down to 1/10th speed. I think we could look to things like SHIFT+DRAG to increment slowly, while just DRAG does a more fixed 1unit increment  for some nice improvements in the future.

**Comment by pineapplespatula** [comment]
When i was playing with scrubbing i found it very nice to have the distance my mouse moved match the distance that the pixels moved. So When you were zoomed in it would move fare fewer pixels, but the same amount of "inches",
Which allows you to scrub to the degree that you can actually see the change, I think that modifiers may be key here. with the current set up allowing for gross modifications and SHIFT+drag could do 1/10th speed
and a third modifier to lock it to  1 mouse pixel moved = 1 canvas pixel change . instead of the current set up of 1 mouse pixel moved = 1 "screen" pixel moved

**Comment by iwehrman** [comment]
Hold shift for turbo scrub. Hold option for slow-mo scrub.
