### ISSUE TITLE
grunt debug - webpack  does not incorporate new JSON changes while running

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#3429]
When you switch between branches with different localization files you get errors on launch

![image](https://cloud.githubusercontent.com/assets/1008531/11752757/174e1968-9ff6-11e5-8412-a23b4d17a395.png)

the current workaround is killing a rerunning grunt debug.

**Comment by iwehrman** [comment]
Fixed by #3501.
