### ISSUE TITLE
Marquee does not work on Default Photoshop Size doc (Background)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3434]
alt+cmd/ctrl + n and select Default Photoshop Size
select the rect tool and drag out several shapes
switch to select tool and try to marquee select

Result: no marquee

works with default artboard

Workaround: switch back to Rect tool and then back to Select, click and move a shape, then marquee is back

**Comment by volfied** [comment]
@chadrolfs Can you repro this, I can't repro it, and I made changes to marquee code recently.

**Comment by chadrolfs** [comment]
Yeah, I think those recent changes to Mr. Quee fixed this.
