### ISSUE TITLE
Remove use of React isMounted 

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3438]
`isMounted` in React components is going to be deprecated soon:

https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html

I haven't found any uses of `isMounted` in our code base that seem egregious (i.e., that result in memory leaks due to failing to unregister listeners from unmounted components), but I guess we won't have a choice in the future.

**Comment by volfied** [comment]
For most D3 components, this can be done by keeping a flag, which is the suggested way. 

For Select.jsx we can probably cancel the listener callback if we unmount.

And for `AssetPreviewImage` flag seems like the easier solution. Or we'll have to Promisify entire `_updateRenditionPath`and cancel that promise on `componentWillUnmount`

**Comment by iwehrman** [comment]
Fixed by #3445.
