### ISSUE TITLE
Clipped layer effect swatch + incorrect color picker position

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3440]
![image](https://cloud.githubusercontent.com/assets/1075154/11904125/dfc59354-a572-11e5-97cc-b41c69d44525.png)

To repro, reduce window height so that the second effect needs slightly more space than is available in the effects panel.

**Comment by iwehrman** [comment]
Related #3550.

**Comment by volfied** [comment]
I'm closing this as clipping no longer occurs (unless the swatch is at the bottom and it's the Export panel divider that clips it). Other issue is being tracked in #3550

**Comment by iwehrman** [comment]
Over to @chadrolfs for testing + verification.
