### ISSUE TITLE
Radius shows for rotated shapes in some cases

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#3444]
Create a rectangle
Rotate it
See that radius control is still showing, even though it shouldn't. It's a no-op if you change it.

It shouldn't show for shapes we can't set radius on.

**Comment by iwehrman** [comment]
@DivyaPrabhakar is this still fix in progress? If not, I suggest kicking it over to @volfied, who may have some spare cycles in the short term.

**Comment by DivyaPrabhakar** [comment]
I will give it to @volfied because of the new developments with Stock search, I probably won't get to this faster than he will.

**Comment by volfied** [comment]
Problem is, we only reset bounds, but we need to reset the radii of the layer as well, so we can see that 
`descriptor.keyOriginType[0].keyShapeInvalidated` is true and set radii to null.

**Comment by iwehrman** [comment]
Over to @ktaki to verify.

**Comment by ktaki** [comment]
Verified the fix.
