### ISSUE TITLE
Rotate input not reset when switching layers

### ISSUE THREAD

**Issue by mcilroyc** [adobe-photoshop/spaces-design#3446]
This is probably a regression introduced by the recent scrubby PR.  I am working on a fix, so assigning to myself.  cc @volfied 

1. rotate a layer by inputing a number into the input
1. select a different layer
1. note that the rotate input retains the previous value

**Comment by mcilroyc** [comment]
FBNC to @ktaki  (thanks for noticing this one)

**Comment by ktaki** [comment]
Verified the fix.
