### ISSUE TITLE
Document activation is slow

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3458]
There are at least two problems:

1. ~~We currently don't start updating the UI until after Photoshop finishes changing the document and updating the canvas. Usually, we should be able to perform these operations in parallel.~~ Fixed by #3459.
2. For documents that are already initialized, we shouldn't need to change more than one or two CSS classes because each document's panel structure is maintained separately in the DOM. I suspect it takes longer than this because our `shouldComponentUpdate` functions aren't sharp enough to limit re-rendering to the top-most components.

**Comment by iwehrman** [comment]
We currently spend ~180ms out of a total of ~360ms (in Flat_Style.psd) doing CSS style recalculation and layout. I think we should be able to restructure the CSS to avoid this.
![image](https://cloud.githubusercontent.com/assets/1075154/12128635/602ff446-b3b3-11e5-826c-cc778c92056c.png)

**Comment by iwehrman** [comment]
Unsurprisingly, it seems that almost all of the style recalculation and layout is caused by the layers panel. Here's what document switching looks like when the layers panel is collapsed:
![image](https://cloud.githubusercontent.com/assets/1075154/12129368/05188398-b3b8-11e5-9e96-4b28b151add0.png)

**Comment by iwehrman** [comment]
Also, as guessed by @designedbyscience, we pay the same exorbitant layout cost when expanding the layers panel:
![image](https://cloud.githubusercontent.com/assets/1075154/12129588/6491ac54-b3b9-11e5-9d36-ab31f99ee49e.png)

**Comment by iwehrman** [comment]
Kicking this to @shaoshing since he's working on a PR for it now.

**Comment by iwehrman** [comment]
@chadrolfs to use judgment about whether or not the problem is solved.

**Comment by chadrolfs** [comment]
seems pretty zippy to me (at least on Mac).  Windows isn't bad but a tad slower than Mac.
