### ISSUE TITLE
Mixed selection including an Artboard does not indicate other layers

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3466]
new doc with 2 artboards
draw some shapes in 2nd artboard
select 1st artboard and a shape from with 2nd artboard
attempt to resize 1st artboard (selected)

Result: artboard and shape move, shape is not indicated in selection

**Comment by chadrolfs** [comment]
![mixed-ab-plus](https://cloud.githubusercontent.com/assets/8442631/12131779/782ac96a-b3ca-11e5-9de9-294166da4c80.gif)

**Comment by iwehrman** [comment]
Over to @chadrolfs to file a JIRA issue. This bug can be closed if it repros in standard PS as well.

**Comment by chadrolfs** [comment]
https://jira.corp.adobe.com/browse/PS-1030
