### ISSUE TITLE
Add even spacing align (distribute space) like Illustrator

### ISSUE THREAD

**Issue by jardicc** [adobe-photoshop/spaces-design#3481]
http://feedback.photoshop.com/photoshop_family/topics/even_spacing_align_like_illustrator

Spacing out objects evenly no matter the object's width. IE: putting 20px between each differently shaped nav item.

**Comment by chadrolfs** [comment]
Moving this to [Wishlist](https://github.com/adobe-photoshop/spaces-design/wiki/Wishlist) and closing as not a bug/defect.
