### ISSUE TITLE
React is in development mode in compiled builds

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3486]
Even in compiled builds, the `Download the React DevTools for a better development experience` message appears in the console, which implies that React is running in development mode, doing things like gathering runtime statistics, checking propTypes, etc., that it should only be doing in debug builds. Among other places, there is discussion of this in facebook/react#3877. This is a regression from the recent require-webpack conversion.

**Comment by volfied** [comment]
Thank you @iwehrman for catching and fixing this.
