### ISSUE TITLE
Can't drag artboards

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3493]
On master at 6c4ff31c5fa0a57c2fc50a3270825a0c327b4ad0 with pgdev.Mac 965, it isn't possible to drag artboards on canvas by their title:
![img](https://s3.amazonaws.com/f.cl.ly/items/0O0T1Y1G3c3P10303R0R/Screen%20Recording%202016-01-11%20at%2011.49%20AM.gif?v=82ff0533)
As shown in the gif, dragging other objects seems to work.

**Comment by volfied** [comment]
Will be fixed by #3490

**Comment by iwehrman** [comment]
Fixed by #3490.
