### ISSUE TITLE
Libraries asset icon misalignment

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3507]
1. The three asset icons are spaced too loosely.
2. The Character Styles subtitle pushes the icons off the panel edge.

![img](https://s3.amazonaws.com/f.cl.ly/items/0B3O0A052o3p2Q1Y272C/Screen%20Recording%202016-01-12%20at%2003.11%20PM.gif?v=9a38e9a2)

**Comment by iwehrman** [comment]
Also, the title should clip, not wrap, when selected for consistency with the editing mode:
![img](https://s3.amazonaws.com/f.cl.ly/items/3a19440k0f441w1j0C2m/Screen%20Recording%202016-01-19%20at%2010.30%20AM.gif?v=cfdeb679)

**Comment by designedbyscience** [comment]
Fixed by #3583
