### ISSUE TITLE
Opening multiple .PSDs results in errors

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3510]
double-click empty area of workspace to invoke open dialog
multi-select several pre-saved .PSD docs

Result: `Transfer from type.initFontList to layers.resetLayers failed: Error: Could not amend history, document not properly initialized: 2073`

several `Failed to deregister dialog`

`Uncaught TypeError: Cannot read property 'call' of undefined`

**Comment by chadrolfs** [comment]
![open-mult](https://cloud.githubusercontent.com/assets/8442631/12281273/8fbc6b2c-b949-11e5-8940-e431109ed15e.gif)

**Comment by chadrolfs** [comment]
Note: if I open up each file one by one, I get no errors.

**Comment by chadrolfs** [comment]
On Windows, I get 
![ice_screenshot_20160112-164444](https://cloud.githubusercontent.com/assets/8442631/12281463/37a6b1c0-b94b-11e5-8367-ded108e8bf0d.png)

**Comment by DivyaPrabhakar** [comment]
@chadrolfs I just merged @volfied's PR addressing this issue.

**Comment by chadrolfs** [comment]
Yusssss!  Fixed.  Seeing these warnings but that's ok  `[History] Could not amend history, document history not found`
