### ISSUE TITLE
Radius text input slightly out of alignment

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3512]
In #3509 @DivyaPrabhakar showed off her alignment fix for the `BlendMode` component's  `TextInput`. She showed too much though, and I can see a similar, minor grid alignment issue with the `Radius` component's `NumberInput`:

![img](https://camo.githubusercontent.com/7468a166410a574460de88741d8d75ce891102af/68747470733a2f2f7777772e64726f70626f782e636f6d2f732f306f673978787a7367307078316d752f6775696465732d73616d652d706f736974696f6e2e6769663f7261773d31)

![image](https://cloud.githubusercontent.com/assets/1075154/12283638/132b4e70-b95d-11e5-828b-bc90f8a1f57d.png)

**Comment by DivyaPrabhakar** [comment]
@iwehrman ![](https://31.media.tumblr.com/a4bbfa577497665658098c49d6197da8/tumblr_inline_n6aan62zxa1r0ql8k.gif)

**Comment by iwehrman** [comment]
Fixed by #3513.
