### ISSUE TITLE
Panning, zooming via trackpad doesn't work if cursor is in guide zone

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3516]
open existing or create a new doc
position cursor over guide zone
use trackpad to zoom (2 finger pinch/expand) or pan (2 finger swipe)

Result: pan/zoom doesn't work

**Comment by iwehrman** [comment]
Related to #3270.

**Comment by volfied** [comment]
@iwehrman This is not related to 3270, it's about the edge zones for creating guides.

I'm not sure how we can fix this, same issue happens with superselect highlight edges / sampler HUD as well. If cursor is over a non transparent HTML area, all mouse events come to us.

**Comment by iwehrman** [comment]
Certainly this is exacerbated by #3270? If the guide zones are misaligned w.r.t. the guide, then these gestures will fail even when your cursor is NOT over a guide.

**Comment by volfied** [comment]
The bug is for when gestures are failing while the mouse is over the canvas edges for creating guides.

**Comment by iwehrman** [comment]
OK, comment retracted given that by "guide zone" we're talking about the canvas edges from whence new guides come.

**Comment by volfied** [comment]
At this point, this is a core bug. Photoshop does not get scroll/zoom events when the cursor is over a non-transparent HTML area, and it's not under our control.

**Comment by chadrolfs** [comment]
https://jira.corp.adobe.com/browse/PS-908

**Comment by iwehrman** [comment]
Killed by @jsbache
