### ISSUE TITLE
Search UI loses focus when re-focusing app

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3519]
1. Open the search UI. The search UI has focus.
2. Cmd-tab to another application.
3. Cmd-tb back to Design Space.

Result: sometimes, but not always, the search UI has lost focus.

The search UI should always have focus while the search UI is open.

**Comment by iwehrman** [comment]
Strangely, it seems to lose focus _every other time_.

**Comment by volfied** [comment]
@chadrolfs can you verify the fix?

**Comment by chadrolfs** [comment]
works great on both Mac and Win!
