### ISSUE TITLE
Guide zone flash on creation of new guide

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3520]
move mouse to guide zone (blue hover)
mouse down (no blue hover) + drag (blue hover) then once you leave the zone (no blue hover)

Expect: either it should remain blue hover until exiting the zone or remain no blue hover while drag out of zone.

**Comment by chadrolfs** [comment]
![guidezone-blink](https://cloud.githubusercontent.com/assets/8442631/12307253/ff424364-b9f2-11e5-919c-c601783d2833.gif)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
