### ISSUE TITLE
Error thrown on some search terms in Search Bar

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#3524]
String matching in the Search Bar is only successful if the user inputted string matches the first word of a filter category or datalist option. For example, typing in "Open" while result in the successful autocomplete suggestion and selection of "Open Documents" from the datalist:
![](https://www.dropbox.com/s/tyf9fsuy4025cje/open.gif?raw=1)

Whereas typing "Documents" will still bring up the correct datalist but no autocomplete after a point even though the strings match:
![](https://www.dropbox.com/s/9rc7vmq40gd3kji/docuemnt.gif?raw=1)

and upon selection will result in this error: 
![](https://www.dropbox.com/s/se2o2wvs5509o25/c462d4da-b9dd-11e5-9178-f79bdf70d8a0.png?raw=1)

This error can be reproduced with typing the second word of any filter category:
- Open search, type "documents", choose "Recent Documents"
- Open search, type "library", choose "My Library" 
etc. 

An obvious place of one place we run into this error is in datalist.jsx, lines 556-568, where we only match against the 0th index of the string, not if the string includes the search term at all. Because it does not match, the autocomplete returns as undefined and then nothing gets stored as the state of the datalist state properites like lastHighlightedID. Later in the code, we use the value of lastHighlightedID to make decisions about executing datalist options on click. Because it is undefined, we get the error that you see later when we are trying to split id that is undefined.

We need to decide how we want to:
1.) Handle autocomplete in the search bar -- i.e. if you type "Documents" should the autocomplete result in "Open Documents" and move the user's cursor? 

2.)  Based on how we handle this case, we then need to change the logic in searchbar.jsx, lines 418-420.

**Comment by DivyaPrabhakar** [comment]
Waiting on an opinion from @placegraphichere about what to do for autocomplete in the problem cases listed above.

**Comment by volfied** [comment]
FBNC to @ktaki

**Comment by ktaki** [comment]
Will test after #3607 is fixed.

**Comment by ktaki** [comment]
Retested with the fix to #3607. The following case will cause the same error.

Select one of the entries found in "Limited search to..." list which are composed of more than a word. Then type the first word and miss-type the second. 

Examples:
Type "Smart objct" to the search dialog, and hit return.
Type "Recent dom" and hit return.

**Comment by DivyaPrabhakar** [comment]
@ktaki I have updated the PR #3479 with the fix to this issue since the PR #3606 was merged but did not fully solve the problem. You can test that branch for all search functionalities now, including the fix to this issue.

**Comment by ktaki** [comment]
@DivyaPrabhakar If you type "Re". "Recent Documents" is highlighted. Then hit return. It will show the following "warning". Has this been a known issue?

Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the TextInput component.

![screen shot 2016-02-12 at 3 51 22 pm](https://cloud.githubusercontent.com/assets/2029597/13023734/8982e2bc-d1a0-11e5-98cc-632a631fc66c.png)

**Comment by iwehrman** [comment]
I can confirm that the above problem is still happening and, more importantly, the dialog closes immediately when it happens instead of filtering by recent documents.

**Comment by chadrolfs** [comment]
I'm not seeing it.  I type "re", it highlights "Recent Documents", I hit enter, it sets Filter to Recent Documents (icon) and dialog remains open.

**Comment by DivyaPrabhakar** [comment]
This is solved by #3479 so closing this.

**Comment by iwehrman** [comment]
@ktaki: can you verify this? I saw it recently, but it's entirely possible that that was user error on my part (using an old branch, e.g.).

**Comment by ktaki** [comment]
Verified the fix. No errors.
