### ISSUE TITLE
Setting W or H values to zero for text layers will make the fields to be blank and not editable

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3526]
Create a box text layer. In the property panel, set Width (or Height) to 0 (zero).
RESULT: "0.1" flashes and leaves the fields, W, H, X, and Y to be blank.Those fields become unaccessible. Only undo will recover the layer contents.
EXPECTED: The minimum value 0.1 should be intact.

Note that this happens with point text layers also, but changing W and H values should be disabled for point text layers. See #2289.

**Comment by chadrolfs** [comment]
related to #3153 ?

**Comment by ktaki** [comment]
OK. Closing as a dupe of #3153.
