### ISSUE TITLE
Radius shows for non-rect shapes

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3530]
create a shape with either the pen or ellipse tool

Result: Radius field and slider appear in Appearance panel 

this is a regression based on 16.1.2 functionality

**Comment by iwehrman** [comment]
Is this a dupe of #3444?

**Comment by chadrolfs** [comment]
root cause for both bugs maybe the same, but in testing 16.1.2, this bug does **not** occur but 3444 **does**.  In current jenkins/master both bugs occur.  

Another distinction is that in this bug, the controls show but are inactive (you can't enter a Radius or move the slider).  In 3444 after you rotate the rect, the controls are still active but don't do anything.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
