### ISSUE TITLE
Search and Export document header buttons are broken

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3532]
![img](https://s3.amazonaws.com/f.cl.ly/items/1g421J3t2z1x0P3w3j0C/Screen%20Recording%202016-01-14%20at%2011.24%20AM.gif?v=ff77c5d1)

**Comment by pineapplespatula** [comment]
@DivyaPrabhakar  and I couldn't repro this. do you have any other steps?

**Comment by iwehrman** [comment]
CC @chadrolfs: I think you saw this too, can you help?

**Comment by DivyaPrabhakar** [comment]
@chadrolfs @pineapplespatula @iwehrman This was my fault -- I needed to update my bluebird version. Now I see the issue. Off to fix it!

**Comment by iwehrman** [comment]
Hmm... do you think this is somehow related to the updated version of Bluebird?

**Comment by DivyaPrabhakar** [comment]
@iwehrman What is happening is that upon initialization, in dialog.jsx we add an event listener to handle a window click if the parent component passes in a prop called dismissOnWindowClick. Therefore when we click on any of the document header icons, part of the `_handleWindowClick` function is to call the `toggle` dialog function.

**Comment by iwehrman** [comment]
You said earlier that you couldn't see the problem before you upgrade your version of bluebird, though. Is it true that this works correctly with an older version of bluebird and not with the latest version?

**Comment by DivyaPrabhakar** [comment]
@iwehrman -- Yes that is true.

**Comment by DivyaPrabhakar** [comment]
Update on research for this issue: 

When any dialog is launched, the `render` function within `dialog.jsx` is executed with some amount of the set of dialog ids. During a cycle, the `render` function checks each of the dialog ids for whether they are open or closed and then renders it as such. 

When a button in the document header is clicked, the `render` function within `dialog.jsx` is being called in three separate render cycles as explained above: 

First cycle -- some dialog ids are processed and the search bar opens
Second cycle -- some dialog ids are processed and the SVG for the search bar appears
Third cycle -- some dialog ids are processed and the dialog prompted via the document header closes

When the same dialog is prompted via the menu or keyboard shortcut, the third cycle does not occur. Something in particular is happening with the `documentheader` component. The subset of dialog ids that are being processed in the third cycle are: 

- `first-launch__dialog`
- `keyboard-shortcut__dialog`
- `search-bar__dialog`
- `exports-panel__dialog`
- `dialog-export-popover`
- `dialog-libraries`

None of the parent components for the dialog are re-rendering in between cycles. The `documentheader` component is rendering again but this does not contain the `dialog` component, therefore it is not the reason for the re-rendering of the `dialog`. Neither the `Search` or `SearchBar` is re-rendering before the third cycle. When I put a breakpoint in the `didComponentUpdate` function within `dialog.jsx` that calls to close the dialog when it is prompted via the menu or keyboard shortcut versus the document header. The stack traces are exactly the same. Therefore, I am still trying to figure out why these ids in particular are firing the third cycle and what correlation it has to the document header.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
