### ISSUE TITLE
Guide policy areas not updated on displayChanged

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3533]
After dragging the window from a non-retina to a retina display:
![image](https://cloud.githubusercontent.com/assets/1075154/12335437/19f4a4ec-bab4-11e5-83bb-c86388498767.png)

**Comment by iwehrman** [comment]
Note that they ALSO don't update when the window is resized, which as an even bigger problem.

**Comment by chadrolfs** [comment]
I swear I wrote this up a while back.  Maybe it was a comment in a PR?  Think it might have been @volfied PR?

**Comment by chadrolfs** [comment]
found it https://github.com/adobe-photoshop/spaces-design/issues/3351#issuecomment-163054277

**Comment by iwehrman** [comment]
Fixed by #3535.
