### ISSUE TITLE
Scrubbing X/Y values results in layer jumping if layers exist outside AB (auto-canvas calculation)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3536]
new doc, create shapes inside and outside the artboard
select a shape inside the artboard and scrub X or Y

Result: layer jumps to outside the artboard

**Comment by chadrolfs** [comment]
![coord-jump](https://cloud.githubusercontent.com/assets/8442631/12338518/d315b622-bac4-11e5-8676-a37ebacefc07.gif)

**Comment by chadrolfs** [comment]
this can subsequently end up in disconnecting the layer from it's position on canvas and where it displays on canvas
![layer-position](https://cloud.githubusercontent.com/assets/8442631/12339639/e8154096-baca-11e5-81b2-f34e49d3da39.gif)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
