### ISSUE TITLE
Using Shift modifier to marquee select layers results in errors

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3538]
cmd/ctrl + n
select rect tool and drag out a shape
hit v for select tool, hold down Shift and marquee select the shape

Result: `Transfer from superselect.marqueeSelect to layers.select failed: Error: Layers.select is passed an invalid modifier`
and then a slew of subsequent errors

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
