### ISSUE TITLE
Cancel quit results in errors and bad state when resuming work

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3541]
cmd/ctrl + n
drag out a guide to dirty the doc
(repeat steps so you have 2 dirty doc)
cmd/ctrl + q
at first prompt to save, click Cancel
then click on Artboard title and try to move it

Result: `Transfer from superselect.click to layers.select failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25922`
lots of other subsequent errors and bad state - can't continue

**Comment by volfied** [comment]
Correction to this bug: It doesn't happen if you click cancel at first prompt, but happens if you don't save first, and cancel second. Seems like PS gathers all the don't saves at first instead of closing documents one by one.

**Comment by volfied** [comment]
Ah, should be a simple fix, PS is in modal state, and sends us a close event later on, but we never handle the close event.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
