### ISSUE TITLE
Automatically turn off "Add copy to to copied layers and groups"

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3543]
We should not add "copy" to all duplicated layers. Its annoying. Either maintain the setting a user has or just turn it off by default in Ds. 

Received through user feedback

![screen shot 2016-01-14 at 7 55 40 pm](https://cloud.githubusercontent.com/assets/3229167/12343428/21ee97d0-baf9-11e5-87b6-46675abb7ce9.png)

Lemme know if this should go in JIRA

**Comment by iwehrman** [comment]
This doesn't have to happen in the current sprint @volfied but if you can find a simple flag to pass to our action descriptor, this would be nice.

**Comment by volfied** [comment]
I can fix this in a simple way by exposing that option to the UAppElement property, since it's globally available in Photoshop. Then we can set it ourselves on startup to the value we like.

**Comment by volfied** [comment]
I will work with Jesper on making sure this property is bounced back to existing value in Classic.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Personally, I didn't see a problem with the way it was before this change - DS would honor whatever the standard PS pref was so if you didn't want 'copy' added, just turn the pref off, enter DS and work away. The old way, you had the option either way - this way, we're forcing the user to user to work with it off.   

Other than forcing it off by default with no other option to turn it back on, the only other workflow problem with this is with Export.  You can have 5 artboards or layers with the same titled/name (e.g. Artboard 1), but only 1 will get exported.

**Comment by volfied** [comment]
@chadrolfs that is an important point. @mcilroyc is this going to break export, as in is export reliant on layers having different names?

**Comment by iwehrman** [comment]
Also, @placegraphichere, can you jump in here and argue for not exposing this pref (via standard PS) in Design Space?

**Comment by volfied** [comment]
By the way, I think that export code should gracefully handle multiple layers with the same name, maybe dropping down to parent names to show shortest unique path in the exported file name. After all, this option of appending "copy" is something the user can achieve themselves by renaming layers, as well.

**Comment by mcilroyc** [comment]
I agree that export should be better about multiple layers with the same name, so it is irrelevant to this conversation.

**Comment by chadrolfs** [comment]
I think that issue can be tracked via #2274
