### ISSUE TITLE
Marquee select causes unrecoverable error

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3547]
Open new doc. Add a shape. Select superselect tool. Marquee select the shape layer on canvas.

![screen shot 2016-01-18 at 11 08 21 am](https://cloud.githubusercontent.com/assets/2029597/12400344/47741d9e-bdd4-11e5-845c-3b3835588beb.png)

![screen shot 2016-01-18 at 11 10 59 am](https://cloud.githubusercontent.com/assets/2029597/12400347/4b49bfaa-bdd4-11e5-8132-e664ee95751b.png)

![screen shot 2016-01-18 at 11 11 12 am](https://cloud.githubusercontent.com/assets/2029597/12400351/540c12f0-bdd4-11e5-92c7-4d078bd88372.png)

**Comment by chadrolfs** [comment]
this was just fixed and looks broken again. but this is without Shift key, see related #3538

**Comment by mcilroyc** [comment]
New PR merged

**Comment by ktaki** [comment]
Verified the fix.
