### ISSUE TITLE
Color Picker offset (if not enough bottom space) is now at top and scrolling explodes the Color Picker controls

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3550]
new doc, drag out a shape, apply some effects, resize app window so there is lack of space at bottom
click on color picker of one of the top effects (so that there is an effect below it)

Bug 1: color picker opens at the top of the Properties panel, it should be just above the color picker swatch you click on.

next step: scroll down the effects panel and mouse over an attribute field

Bug 2: the color picker controls spread out (explode)

**Comment by chadrolfs** [comment]
![color-picker-offsetscroll](https://cloud.githubusercontent.com/assets/8442631/12401898/55be9640-bdde-11e5-8cfb-d58a46178675.gif)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
