### ISSUE TITLE
Descenders are clipped a little in Layer names on Retina

### ISSUE THREAD

**Issue by designedbyscience** [adobe-photoshop/spaces-design#3558]
So close.

<img width="72" alt="vermilionartboards_psd___16_7___image__rgb_8____" src="https://cloud.githubusercontent.com/assets/22372/12427085/26024f28-beab-11e5-9611-784a217c8f3b.png">

**Comment by iwehrman** [comment]
CC @shaoshing: maybe this was a real issue? See discussion in #3553.

**Comment by iwehrman** [comment]
@designedbyscience: can you confirm that if you restart `grunt debug` that this still happens?

**Comment by designedbyscience** [comment]
Yes, double-checked. Looks good on non-Retina.

**Comment by shaoshing** [comment]
Looking at it now.

**Comment by iwehrman** [comment]
I still can't repro, but I do see the problem in the Libraries panel:
![image](https://cloud.githubusercontent.com/assets/1075154/12430460/98cce506-bea4-11e5-8f74-77d9b14b62fd.png)

**Comment by shaoshing** [comment]
Confirmed the issue in small screen resolution (seeing this in 15-inch mbp)

**Comment by iwehrman** [comment]
(Note that we don't mark a bug as FBNC until the fix is merged into main.)

**Comment by designedbyscience** [comment]
@shaoshing fixed it real good.
