### ISSUE TITLE
Layer Panel Layer elements are incorrect size 

### ISSUE THREAD

**Issue by pineapplespatula** [adobe-photoshop/spaces-design#3559]
On a Retina Machine 
<img width="352" alt="screen shot 2016-01-19 at 10 33 06 am" src="https://cloud.githubusercontent.com/assets/1008531/12428332/d98003aa-be98-11e5-85c8-de6c8f4f7bb2.png">

It seems like the css for layers-group is somehow calculating a smaller dimension 

<img width="297" alt="screen shot 2016-01-19 at 10 40 44 am" src="https://cloud.githubusercontent.com/assets/1008531/12428367/1b16ff4e-be99-11e5-9c2b-d4140f88892f.png">
<img width="350" alt="screen shot 2016-01-19 at 10 41 00 am" src="https://cloud.githubusercontent.com/assets/1008531/12428376/2304c312-be99-11e5-8f04-9622f1ecb99d.png">

**Comment by iwehrman** [comment]
I'm seeing this on @ktaki's 10tkfonts.psd file:
![image](https://cloud.githubusercontent.com/assets/1075154/12432103/1a4f30c6-beae-11e5-834d-16e49b0622d4.png)

**Comment by iwehrman** [comment]
I think it only happens if the top layer is not a group.

**Comment by volfied** [comment]
@pineapplespatula Please confirm the fix.

**Comment by pineapplespatula** [comment]
Fixed!
