### ISSUE TITLE
Libraries Panel style issues due to change in the TextInput component

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3560]
Asset title got clipped
<img width="264" alt="screen shot 2016-01-19 at 11 01 04 am" src="https://cloud.githubusercontent.com/assets/118264/12428866/fef6596a-be9b-11e5-9d44-5dc0106c3687.png">

<img width="282" alt="screen shot 2016-01-19 at 11 01 22 am" src="https://cloud.githubusercontent.com/assets/118264/12428867/fefb2c2e-be9b-11e5-8a52-d33e0016c433.png">

<img width="290" alt="screen shot 2016-01-19 at 11 05 04 am" src="https://cloud.githubusercontent.com/assets/118264/12428995/bf4a4c4e-be9c-11e5-87dd-4c420b0789cd.png">

Long title overflow
<img width="290" alt="screen shot 2016-01-19 at 11 06 43 am" src="https://cloud.githubusercontent.com/assets/118264/12429000/c285a02a-be9c-11e5-8d75-9b95ad5b0626.png">

Secondarly title got pushed down when editing title
<img width="285" alt="screen shot 2016-01-19 at 11 08 05 am" src="https://cloud.githubusercontent.com/assets/118264/12429032/ef083590-be9c-11e5-8343-bdb5cada8351.png">

Button spacing changed when editing title
<img width="284" alt="screen shot 2016-01-19 at 11 09 29 am" src="https://cloud.githubusercontent.com/assets/118264/12429080/24f4bfb6-be9d-11e5-81ec-7fb878f5fc12.png">

**Comment by DivyaPrabhakar** [comment]
I have checked and this PR solves the issues brought up in #3507.
The issues brought up in that issue that are now solved are: 

1. The asset icons are too loosely spaced. 
2. Character style icons are pushed off. 
3. Title should clip, not wrap


Before: 
![](https://www.dropbox.com/s/wll517nskretoik/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f3042334f30413035326f337032513159323732432f53637265656e2532305265636f7264696e67253230323031362d30312d3132253230617425323030332e3131253230504d2e6769663f763d39613338.gif?raw=1)

After: 
![](https://www.dropbox.com/s/nrm1fdb6xutd537/Screenshot%202016-01-20%2022.44.03.png?raw=1)
![](https://www.dropbox.com/s/zdgevhqubw17v73/Screenshot%202016-01-20%2022.44.46.png?raw=1)


Before: 
![](https://www.dropbox.com/s/81j99xr04yvuyan/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f336131393434306b306634343177316a3043326d2f53637265656e2532305265636f7264696e67253230323031362d30312d3139253230617425323031302e3330253230414d2e6769663f763d63666465.gif?raw=1)

After: 
![](https://www.dropbox.com/s/qscl5zvruw91ft3/Screenshot%202016-01-20%2023.20.58.png?raw=1)

**Comment by shaoshing** [comment]
Thanks for the update @DivyaPrabhakar

**Comment by designedbyscience** [comment]
Fixed by #3583
