### ISSUE TITLE
Panel column toggle breaks opening 2nd doc

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3566]
Open a saved doc
collapse one of the panel columns (Properties or Layers & Libraries)
Open a 2nd document 
try to expand the column you closed so that both panels are open

Result: you're stuck in toggle mode

**Comment by iwehrman** [comment]
Hmm, I can't repro. I opened Vermilion via search, collapsed the properties panel (so only layers was showing) then opened Flat_Style via search, and re-opened the properties panel without issue. Any idea how your steps might be different?

**Comment by chadrolfs** [comment]
hmmm, i didn't open via search.  Opened via no doc state and clicking on Vermillions in Recent Docs column, collapse props column, then cmd+o and dclick on Flat_style

**Comment by iwehrman** [comment]
OK, I can repro with those exact steps (weirdly). I suspect the adapter is failing to send us a `adaperFlagsChanged` event, but I'll check it out.

**Comment by iwehrman** [comment]
Even simpler repro steps:

1. Open any file with cmd-O.
2. Click either icon in the icon bar.

Result: behaves like a cmd-click instead of a regular click.

**Comment by iwehrman** [comment]
Tracking: https://jira.corp.adobe.com/browse/PS-1003
CC @jsbache @jfitz-adobe

**Comment by iwehrman** [comment]
Kicking out of the milestone because we're blocked anyway.
