### ISSUE TITLE
Scrubbing to zero boundary results in layer flicker

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3570]
select a layer on canvas
scrub W or H to zero (0)

Result: layer flashes

**Comment by chadrolfs** [comment]
related to #3153

**Comment by chadrolfs** [comment]
https://www.dropbox.com/s/8ytai89cmlip2e1/scrub-flicker.mov?dl=0

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
