### ISSUE TITLE
Dragging LLSO onto canvas sometimes gets stuck, Enter doesn't place

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3575]
new doc, start dragging library assets onto canvas.

Result: most auto-commit on drop but occasionally, you get stuck where it doesn't place (Enter, Esc, Return don't commit).  You have to right-click > Place.

**Comment by chadrolfs** [comment]
![place-fail](https://cloud.githubusercontent.com/assets/8442631/12459686/dae20406-bf64-11e5-937e-83cf6055ceec.gif)

**Comment by ktaki** [comment]
@chadrolfs Do you still see this happening?

**Comment by chadrolfs** [comment]
I don't. CNR.  I'll re-open if I run into this again but looks resolved.
