### ISSUE TITLE
Shortcut to undo fails when reordering layer groups

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3581]
create 3 shape layers 
select one at a time (in the layers panel) and cmd + g so that each shape is in their own group
collapse all 3 groups
drag the middle group above the top group (reorder the stacking order of the groups)
cmd + z

Result: nothing
workaround: use the menu command

**Comment by iwehrman** [comment]
So it works completely correctly if you choose `Edit > Undo`?

**Comment by chadrolfs** [comment]
yup

**Comment by chadrolfs** [comment]
seems to work fine on windows

**Comment by chadrolfs** [comment]
Here's another case where it fails:
create two shapes, select them both, click on one of the combine icons (e.g. Unite), cmd+z - doesn't work.

**Comment by volfied** [comment]
Seems like selecting the layers in the panel is the cause of this, we're probably stopping propagation.

**Comment by volfied** [comment]
This is due to fact that we call acquireFocus on mousedown for LayerFace's TextInput, but never call releaseFocus. Not sure how to fix it, but I'm leaving this note here so the next dev doesn't have to triage it.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
