### ISSUE TITLE
Closing a doc in the vector mask mode will not exit the mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3584]
Open a AB doc. Select superselect tool. Select the AB. Hit M. Close the doc. (Note that you are still in the mode). Change the tool to a shape tool.

![screen shot 2016-01-20 at 3 45 26 pm](https://cloud.githubusercontent.com/assets/2029597/12467056/59e1ad42-bf8d-11e5-873e-77c3e8161596.png)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
