### ISSUE TITLE
Layers panel icons flash when they swap 

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3599]
Layer icons like the artboard and group icons that have different states will often flash blank before the other state is loaded. It looks odd. We should see if we can avoid this.

![icon-flash-when-selecting](https://cloud.githubusercontent.com/assets/3229167/12499948/61bb4928-c074-11e5-9f07-76890f9e8468.gif)

**Comment by iwehrman** [comment]
Related to or a duplicate of #2020?

**Comment by iwehrman** [comment]
Please verify and close, @placegraphichere.

**Comment by placegraphichere** [comment]
This feels so much better, thanks for getting this done @shaoshing!
