### ISSUE TITLE
Cannot open .MOV filetype with Jenkins builds

### ISSUE THREAD

**Issue by placegraphichere** [adobe-photoshop/spaces-design#3600]
When using our Jenkins builds I cannot open `.mov` files. I receive this error: 

![screen shot 2016-01-21 at 7 24 08 pm](https://cloud.githubusercontent.com/assets/3229167/12499985/b1052c74-c074-11e5-875a-464cba54f440.png)

This does not happen in release builds (thor). Probably a core issue, but figured I'd say it out loud somewhere.

**Comment by chadrolfs** [comment]
Our jenkins builds have always been this way.  Like Crema, DynamicLink is most likely a separate STI and isn't included in our normal PS build.  I'm pretty sure you need to run an actual PS intaller to get this as well as Crema and other STIs bundled in the PS installer.

**Comment by placegraphichere** [comment]
well, it isn't a bug for github then, thanks @chadrolfs
