### ISSUE TITLE
Enabling Guides or Smart Guides in DS after turning off Extras in standard PS fails/errors

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3604]
open Vermillion in standard PS
View > (uncheck) Extras (or hit cmd+ h)
Enter DS
View > Show Guides

Result: `Action documents.toggleGuidesVisibility failed: Error: Photoshop returned an error when playing command number: 1 Photoshop code: -25920 Photoshop message: error: -25920 message: The command “Set” is not currently available.`

**Comment by chadrolfs** [comment]
relates to #3480

**Comment by volfied** [comment]
If extras are hidden, trying to show guides in PS fails by NotAvailable error. This will require core work, or us to turn on extras at all times (which will also require core work as there doesn't seem to be a setter for extrasVisible flag)

**Comment by chadrolfs** [comment]
https://jira.corp.adobe.com/browse/PS-1212

**Comment by chadrolfs** [comment]
Also related to a crasher PS-1032

**Comment by iwehrman** [comment]
Kicking this out of the sprint milestone because it's blocked on core work.

**Comment by chadrolfs** [comment]
In the current build, this puts you into an unrecoverable state. 
Turn off Extras in standard PS,
enter DS, try to enable Smart Guides and Guides
You end up in an unrecoverable state and can't return to standard PS. You have to force quit and risk losing unsaved work.

**Comment by chadrolfs** [comment]
try this:
start in PS standard, create a new doc (iphone 6 template)
 View > (uncheck) Extras
enter DS
View > Show Guides
View > Show Smart Guides
Result: you're now in unresponsive state

**Comment by ktaki** [comment]
That happens only when the sampler tool was selected when the Show Guilds command was executed. For other tools, the error seems not to affect on the state. Also, you need to turn off Extras explicitly in standard Ps and switch to Ps. This might be a rare case. When Ps is non-open doc state, opening a doc or creating a new doc will turn on Extras automatically. This is the case in the DS mode also.

**Comment by chadrolfs** [comment]
Hmmm, doesn't seem isolated to sampler tool for me.  I get into a bad state with default Select tool.

**Comment by ktaki** [comment]
Have you tested with the current master? I see the bad behavior with the current pg-dev build as is, but not with the master.

**Comment by chadrolfs** [comment]
Yes, I ran 'grunt compile' and replaced the www/src in the pgdev.1185 build but I also replaced the info.plist file as well.

**Comment by ktaki** [comment]
OK. I can repro with compiled sources. Interesting thing is that unless those two commands ran consecutively, things seems fine, but once they do, tons of errors are generated, and it is fatal.

**Comment by chadrolfs** [comment]
Yep, glad you can repro.  It is definitely a corner case but because there is the potential for users to lose work, it should be fixed.

**Comment by ktaki** [comment]
Agreed.

**Comment by chadrolfs** [comment]
using pgdev.1258 on mac and master @ 5c94d744

Enabling one, enables both

(with existing doc open) Turn off Extras in standard PS, enter DS, View > Show Guides
Result: both Show Guides and Show Smart Guides are now enabled
