### ISSUE TITLE
Exporting with multiple layers the same name only saves one

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3609]
cmd/ctrl + n 
hold Opt/Alt, click and drag on the artboard title (x4)
You now have 4 artboards named the same
Cmd/Ctrl + E or File > Export
Click Export

Result: only one file is exported.

**Comment by chadrolfs** [comment]
relates to #2274 and #3543

**Comment by mcilroyc** [comment]
Any hot ideas on how to resolve file naming conflicts?  Suffix with a number?  `LayerOne.png`, `LayerOne.1.png` ... etc.  @placegraphichere ?

**Comment by mcilroyc** [comment]
example: ![ss](http://cl.ly/2M1s2i223k01/Image%202016-02-23%20at%204.33.23%20PM.png)

**Comment by chadrolfs** [comment]
Ideas (not necessarily hot):
file #.ext
file(#).ext
file.#.ext
file-#.ext
file copy #.ext (this is what Mac OS does when you dupe a file)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Blocked by windows bug 3743
