### ISSUE TITLE
Tab should autocomplete current match in search

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3610]
Currently `<Enter>` applies the currently selected filter, but `<Tab>` does nothing. `<Tab>` should also apply the currently selected filter, if there is one.

**Comment by DivyaPrabhakar** [comment]
This is also solved in PR #3479 now

**Comment by DivyaPrabhakar** [comment]
FBNC @iwehrman

**Comment by iwehrman** [comment]
It does seem like tab does the same thing as enter, which is technically what this bug was about. But, I also notice that tab/enter does not work correctly with filters. For example, if I type "op<tab>" then instead of filtering by open documents (the selected option), it just closes. Would you like me to open a different bug for this, @DivyaPrabhakar?

**Comment by DivyaPrabhakar** [comment]
@iwehrman I read this issue to mean "Tab" should autocomplete the suggestion, and then you have the option of pressing "Enter" or not. For example, if I type "op", the autofill suggestion may be "Open Documents". If I press "Tab" then "Open Documents" changes from the suggestion to my enter search query. Then I can press enter on that option or continue using the arrow keys to navigate the datalist. 

1.) Do you think that "Tab" should select the option for you completely? Therefore "Tab" would be equivalent to "Enter"? 

2.) I am definitely not seeing the problem where the search dialog just closes after you press "Tab" on a filter.

**Comment by iwehrman** [comment]
After discussing with @DivyaPrabhakar, I think this issue can be considered fixed, though she may decide to change the behavior of tab later to auto-select the current filter.
