### ISSUE TITLE
Datalists colors are inconsistent (selections hard to read on some themes)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3628]
compare search, cc libraries and blend modes datalists (effect and appearance).

blend modes is lighter and highlight is harder to read.

**Comment by chadrolfs** [comment]
<img width="184" alt="screen shot 2016-01-27 at 3 48 51 pm" src="https://cloud.githubusercontent.com/assets/8442631/12632602/faf80ac0-c50d-11e5-9257-0b44ce5d9476.png">
<img width="190" alt="screen shot 2016-01-27 at 3 49 14 pm" src="https://cloud.githubusercontent.com/assets/8442631/12632601/faf77c54-c50d-11e5-8df7-863e02604139.png">

**Comment by chadrolfs** [comment]
related to #3345

**Comment by iwehrman** [comment]
Might need some input from @placegraphichere here first.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
yeppers
