### ISSUE TITLE
CC Libraries auto-vaccuum is on by default (it should be off)

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3631]
open Vermillion
notice progress bar: waiting for libraries, converting colors
check your libraries after progress dialogs finish

Result: you now have a new library called VermillionArtboards

**Comment by iwehrman** [comment]
I'm pretty sure we need a JIRA bug for this.

**Comment by chadrolfs** [comment]
https://jira.corp.adobe.com/browse/PS-1127
