### ISSUE TITLE
Drag and drop a photo from browser causes an error

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3635]
Action layers.addLayers failed: base element not found

Open Adobe Stock site in a browser. Drag and drop a photo onto a canvas.

![screen shot 2016-01-28 at 2 03 32 pm](https://cloud.githubusercontent.com/assets/2029597/12660336/167bdac8-c5c8-11e5-945c-6e57044bcf66.png)

**Comment by iwehrman** [comment]
Probably happens for all images from browsers?

**Comment by ktaki** [comment]
Yes, that is the case. Dragging any image from browsers on to canvas does.

**Comment by iwehrman** [comment]
Hmm, I can't repro on Mac pgdev.1054 at 86ccaf629190b7baccbdaf1d663a22f9c55500a9. Did you observe this on Mac or Win?

**Comment by ktaki** [comment]
I tried with the Mac pgdev 1060 at 86ccaf6. It is and has been easy to repro for me. @chadrolfs Can you try it? Just drag any image from a browser to a canvas.

**Comment by chadrolfs** [comment]
yep, piece of :cake:, I can repro very easily

**Comment by iwehrman** [comment]
I still can't repro, I guess it's a timing issue. Maybe some other engineer can try to repro? @DivyaPrabhakar?

**Comment by iwehrman** [comment]
@volfied can you repro this?

**Comment by volfied** [comment]
I can repro, given that `base element is not found` error is coming from PS, I'll take a look.

**Comment by volfied** [comment]
Trick is to open a new document.

**Comment by volfied** [comment]
I believe the problem is dragging an image to canvas acts as a paste operation, and we get the "drag" event before Photoshop had the time to update it's own document. 

https://jira.corp.adobe.com/browse/PS-1370

**Comment by iwehrman** [comment]
Kicking this out of the milestone because we're blocked, but adding the Ship Blocker label.

**Comment by iwehrman** [comment]
Over to @ktaki to verify.

**Comment by ktaki** [comment]
No, it did not fix the issue. Do we want to double the value? It seems to me, this will not result in any bad state afterwards. What would happen if we leave it as is?

**Comment by iwehrman** [comment]
Back to @shaoshing. Maybe the timeout wasn't long enough?

**Comment by iwehrman** [comment]
In theory the UI should reset itself after the unhandled error. I prefer not to rely on that though...

**Comment by shaoshing** [comment]
@iwehrman @ktaki It turns out that the error has nothing to do with time delay. I've explains the actual cause in my PR #3797, and it only happens when dropping image from browser to an empty artboard.

Here's how to reproduce the bug:
1 create a new document
2 drag any image from browser to the art board
3 error `base element not found`

Same operation works if the artboard is not empty:
1 create a new document
2 draw a rectangular on the artboard
3 drag any image from browser to the art board

**Comment by iwehrman** [comment]
OK, let's try it again! FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
