### ISSUE TITLE
Inner Shadow should be listed above Color Overlay

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3636]
In Effects panel, the order should be

Stroke
Inner Shadow
Color Overlay
Drop Shadow

![screen shot 2016-01-28 at 3 57 22 pm](https://cloud.githubusercontent.com/assets/2029597/12662877/2fd8c96c-c5d8-11e5-9190-be565bed3b29.png)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
