### ISSUE TITLE
Cannot add effects

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3650]
Open new doc, add a shape, click '+' in the Effects panel, and choose an effect (e.g., Stroke).

Uncaught TypeError: Cannot read property 'addEffect' of undefined

![screen shot 2016-02-01 at 4 58 19 pm](https://cloud.githubusercontent.com/assets/2029597/12736453/5f067876-c905-11e5-8d90-382e21119940.png)

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
