### ISSUE TITLE
Reloading DS with multiple docs open results in incorrect bounds until all layers are initialized

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3655]
Open/create multiple docs and select top artboard
reset DS
cmd + ` to cycle through open docs (notice bounds and adders)

Result: they are incorrect until you cycle through the docs a 2nd time (once all layers are initialized)

**Comment by chadrolfs** [comment]
![reset-boundsoff](https://cloud.githubusercontent.com/assets/8442631/12766798/4d2b6cb4-c9ba-11e5-8257-73bf43fd50af.gif)

**Comment by shaoshing** [comment]
Removing the performance tag as this is caused by action execution order, rather than performance.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
