### ISSUE TITLE
Font change should be undo-able by just one Cmd/Ctrl-z

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3667]
Font faces previewed, i.e., not committed, should not be added to the history.

**Comment by ktaki** [comment]
@iwehrman This works, but mouse hovering over the font data list, each font produces a history re-initialization warning such as:

[History] Re-initializing history because photoshop thinks the current state is 3 of 4, while our model says 4 of 5
[History] Initializing history with 4 states

Can this be simply ignored? Just checking.

**Comment by iwehrman** [comment]
Let's ask @mcilroyc.

**Comment by mcilroyc** [comment]
That's undesirable.  It means we are nuking history, which will prevent fast undo/redo.

**Comment by iwehrman** [comment]
@mcilroyc Is there a standard way to address issues like this? Or is this a "new adventure every time" thing?

**Comment by mcilroyc** [comment]
At a quick glance, it seems that you're not providing the `coalesce` flag to the store event... which results in different history treatment between DS and PS ... which gets things out of sync.

https://github.com/adobe-photoshop/spaces-design/pull/3787/files#diff-66fb006bb46f8f716c009f317aded016R158

and then line 121

**Comment by iwehrman** [comment]
Derp, on it, thanks.

**Comment by mcilroyc** [comment]
with the merge of #3796, the "Re-initializing history" issue from @ktaki's most recent report seems to be fixed

**Comment by ktaki** [comment]
Verified the fix. No more history warnings.
