### ISSUE TITLE
Keyboard input doesn't work in PS native modal dialogs (Save, New...)

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3681]
I used to be able to press cmd-D to dismiss the Photoshop native close-dirty file modal dialog without saving, or to press enter to save, but that doesn't seem possible at the moment. This is almost certainly a core bug, and probably due to @jfitz-adobe's recent changes. I'm logging it here for now because I'm too lazy to get on the VPN to file it in JIRA.

**Comment by chadrolfs** [comment]
you shouldn't even need the Cmd, simply pressing D should work, but yes, it is broken.  Same on Windows (hitting N fails to Not Save).  Esc also fails to Cancel

https://jira.corp.adobe.com/browse/PS-1277

**Comment by chadrolfs** [comment]
This isn't just keyboard shortcuts for native dialogs.  It's key strokes in general.  You can't name files you save, you can specify dimensions or name for new files you create.  This is a serious Blocking issue.
