### ISSUE TITLE
Undoing rotation always reverts to 0, instead of the previous value

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3689]
Reproduce:

1. create and select a new layer
2. Set rotation to 10
3. Set rotation to 20
4. undo
5. layer on the canvas is reverted to 10 degree, while the input is set to 0 incorrectly.

![undo-rotation](https://cloud.githubusercontent.com/assets/118264/12904762/6689727a-ce86-11e5-9b41-03d86eebe7de.gif)

**Comment by chadrolfs** [comment]
This has been the implementation from the beginning.  Note too, that if you enter a rotation value, then deselect the shape and then reselect it, it will be reset to 0.

**Comment by iwehrman** [comment]
@chadrolfs see if this is a dupe? Or consider closing.

**Comment by chadrolfs** [comment]
#1313, #2359
Design Limitation
