### ISSUE TITLE
Hitting Cmd/Ctrl+Period in text editing mode causes an error

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3693]
Press Cmd/Ctrl+period to cancel text editing mode will produce:
Uncaught TypeError: this.flux.actions.tool.type.handleTypeModalStateCanceled is not a function

![screen shot 2016-02-09 at 3 04 48 pm](https://cloud.githubusercontent.com/assets/2029597/12933790/dbf8b170-cf3e-11e5-9739-9ab033361033.png)

**Comment by ktaki** [comment]
Note that the result is the same by hitting Esc key if Esc key is set to cancel the text editing.

**Comment by chadrolfs** [comment]
I wonder if this is related to the native dialogs bugs #3681

**Comment by shaoshing** [comment]
This is fixed by #3719. Back to Taki to verify.

**Comment by ktaki** [comment]
Verified the fix.
