### ISSUE TITLE
Panel bounds do not include icon bar bounds (off-set guide highlight)

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3703]
![image](https://cloud.githubusercontent.com/assets/1075154/12994713/61727aae-d0d7-11e5-8520-740d3d8675b6.png)

**Comment by iwehrman** [comment]
I think this broke in #3696 and is caused by the fact that the `panelSet` ref now includes the `IconBar`.

**Comment by shaoshing** [comment]
I verified this is fixed by #3708, but over to @chadrolfs to double check.
