### ISSUE TITLE
Guide policy frame is not cleared when creating a new doc

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3722]
(Debug > Show Policy Frames)
cmd/ctrl + n
drag out some guides
cmd/ctrl + n

Result: guide policy frames still shown from previous doc guides

**Comment by chadrolfs** [comment]
![guidepolicyframenotcleared](https://cloud.githubusercontent.com/assets/8442631/13154750/5ab6189e-d62f-11e5-9f1c-24674a2e2bdf.gif)

**Comment by pineapplespatula** [comment]
@chadrolfs  can you regress this?

**Comment by volfied** [comment]
This was fixed by #3738
