### ISSUE TITLE
Mac only: Cmd-n and then Cmd-minus does not work

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3731]
Open new file and then Cmd-- to zoom out. This does nothing. Cmd-+ and then Cmd-- works. After any action, zooming out works fine, just not the first time after Cmd-n. Mac only.

**Comment by iwehrman** [comment]
Works for me. Can you post your console logs? Could this be related to #3464?

**Comment by ktaki** [comment]
Cmd-n and Cmd-minus four times. The "View" on the menu bar flashes, but nothing happens on canvas.

![screen shot 2016-02-19 at 2 36 24 pm](https://cloud.githubusercontent.com/assets/2029597/13191098/457a0688-d716-11e5-890c-ecedc71e0017.png)

**Comment by chadrolfs** [comment]
Works for me.  What buid are you using (1081)?

**Comment by ktaki** [comment]
After restarting Ps, it is working now. I think I did something else to get into the state. I will close this for now.
