### ISSUE TITLE
Keyboard shortcut dialog difficult to read on lighter color stops

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#3739]
![](https://www.dropbox.com/s/eou0hi5em6j6uma/Screenshot%202016-02-22%2012.48.44.png?raw=1)
![](https://www.dropbox.com/s/qfff90iv7b6e42l/Screenshot%202016-02-22%2012.49.30.png?raw=1)

**Comment by iwehrman** [comment]
Over to @chadrolfs to verify.

**Comment by chadrolfs** [comment]
Looks great
