### ISSUE TITLE
Arrow keys focus on canvas rather than search dialog in the vector mask mode

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3740]
Windows only.
Open an image file and hit M.
In the vector mask mode, add a mask. 
While is the mask is selected, open the search bar.
Type "vector".
Use down arrow key to select "Super Select Vector".

RESULT: The mask on canvas moves downward.

EXPECTED: Traverses the items in the search dialog.

**Comment by iwehrman** [comment]
Just end mask mode when opening search.

**Comment by iwehrman** [comment]
FBNC to @ktaki.

**Comment by ktaki** [comment]
Verified the fix.
