### ISSUE TITLE
GIFs need to be redone  for lighter color stops in the DS Introduction dialog

### ISSUE THREAD

**Issue by DivyaPrabhakar** [adobe-photoshop/spaces-design#3745]
Example: some of the lines in the GIFs are very light and not crisp

![](https://www.dropbox.com/s/6akyiif2jp8rsk0/Screenshot%202016-02-23%2013.47.15.png?raw=1)
![](https://www.dropbox.com/s/8pnzmczhpiy73pm/Screenshot%202016-02-23%2013.47.31.png?raw=1)
![](https://www.dropbox.com/s/6gf74bwnphu923g/Screenshot%202016-02-23%2013.47.35.png?raw=1)

**Comment by iwehrman** [comment]
Alternatively, we could force the intro dialog to always be medium gray.

@placegraphichere: how painful would it be to recreate these gifs?

**Comment by iwehrman** [comment]
Over to @ktaki to verify.

**Comment by ktaki** [comment]
@DivyaPrabhakar: With the change, Keyboard Shortcuts had a negative effect. Could this be an easy fix? Affected "Original" and "Light"

<img width="776" alt="screen shot 2016-03-08 at 4 34 27 pm" src="https://cloud.githubusercontent.com/assets/2029597/13621348/d76269a8-e54b-11e5-817c-de00e432ec6f.png">

**Comment by DivyaPrabhakar** [comment]
@ktaki Definitely an easy fix, will do that asap. Thanks for catching this.

**Comment by iwehrman** [comment]
Back to @ktaki to verify.

**Comment by ktaki** [comment]
Verified the fix.
