### ISSUE TITLE
Selected layer not shown in the layers panel when drilling down

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3746]
Tested with Vermillion document. When drilling down layers by clicking on canvas, sometimes the layers panel does not scroll to shown the selected layer. 

Open Vermillion doc.
Click any part of the document on canvas to drilling down to a leaf layer.
Observe if the selected layer is shown in the layers panel.

RESULT: Sometimes the layers panel fails to show the layer selected.

**Comment by iwehrman** [comment]
CC @shaoshing

**Comment by iwehrman** [comment]
Back to @ktaki to verify.

**Comment by ktaki** [comment]
Verified the fix.
