### ISSUE TITLE
Initial coordinates of an object moved out of an artboard are incorrect

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3748]
create a shape within an AB (note the X,Y coords)
move shape either to a 2nd AB or outside the current AB

Result: coordinates are incorrect  (changing them via X,Y have unexpected results)

**Comment by chadrolfs** [comment]
![ab-coords2](https://cloud.githubusercontent.com/assets/8442631/13271846/a7c6e020-da4c-11e5-9f8e-df6aca937ba7.gif)

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.

**Comment by chadrolfs** [comment]
Coordinates for layers outside an AB are still really confusing but we have a JIRA card for that work.  Closing this as drags between ABs now result in correct coords
