### ISSUE TITLE
Creating a circle mask in a newly created group fails

### ISSUE THREAD

**Issue by volfied** [adobe-photoshop/spaces-design#3754]
1 - Create a rectangle
2 - Create another rectangle
3 - Select both rectangles
4 - Cmd+G to create group
5 - Press M for mask mode HUD
6 - Click the circle button

Result:

![](https://s3.amazonaws.com/f.cl.ly/items/3z0h180w0f2T0H3k3V0N/Image%202016-02-24%20at%203.50.08%20PM.png?v=3f101f93)

Note: This is not related to #3753, or my changes from #3744, this bug happens before that PR.

**Comment by pineapplespatula** [comment]
is this still happening in master, I think it should have been fixed with the #3753 fix

**Comment by chadrolfs** [comment]
Nope,looks fixed to me.  Closing
