### ISSUE TITLE
Opacity/Alpha/Rotation/Radius inputs are misaligned

### ISSUE THREAD

**Issue by shaoshing** [adobe-photoshop/spaces-design#3756]
<img width="458" alt="screen shot 2016-02-24 at 3 59 15 pm" src="https://cloud.githubusercontent.com/assets/118264/13305420/f3dbf3e2-db0f-11e5-8a6b-95925d1b561e.png">
<img width="461" alt="screen shot 2016-02-24 at 3 59 21 pm" src="https://cloud.githubusercontent.com/assets/118264/13305421/f3ee3b60-db0f-11e5-935d-e07d9a661a8b.png">

**Comment by shaoshing** [comment]
@DivyaPrabhakar I found another alignment issue with the alpha input in the color picker. Feel like they are similar issues, so I am posting it here as well. Thanks for looking into it.

<img width="565" alt="screen shot 2016-02-24 at 4 05 40 pm" src="https://cloud.githubusercontent.com/assets/118264/13305538/a55731b8-db10-11e5-979c-a96b3ad7cb8b.png">

**Comment by shaoshing** [comment]
Rotation input:

<img width="626" alt="screen shot 2016-02-24 at 4 08 58 pm" src="https://cloud.githubusercontent.com/assets/118264/13305579/0c6fa9ac-db11-11e5-9a0f-e2f9ff03ec3f.png">

**Comment by shaoshing** [comment]
Radisu input:
<img width="622" alt="screen shot 2016-02-24 at 4 11 47 pm" src="https://cloud.githubusercontent.com/assets/118264/13305635/7e07588a-db11-11e5-863a-900a74a50db9.png">

**Comment by DivyaPrabhakar** [comment]
Fixed with #3662
