### ISSUE TITLE
Search hitting Enter with partially typed filter has unexpected results, doesn't auto-complete text

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3757]
(have MRU populated, no doc open)
cmd/ctrl + f
type "rec" (hints "rec"ent Documents, and Recent Documents filter is highlighted blue)
hit Enter

Results: top most doc in MRU is opened
Expect: auto-complete filter for Recent Documents to be applied and search dialog remains open

Note: if you do this with Adobe Stock, it just opens the generic stock URL

**Comment by chadrolfs** [comment]
![search-autocomplete](https://cloud.githubusercontent.com/assets/8442631/13330616/73470312-dbae-11e5-8702-628bda62abe0.gif)

**Comment by ktaki** [comment]
This is more likely caused by doble-keydown event fix by @jfitz-adobe. He is working on another fix now.

**Comment by chadrolfs** [comment]
Oh, right!

**Comment by chadrolfs** [comment]
self-assigned so I can use this as another test case to validate his fix.

**Comment by chadrolfs** [comment]
change backed out so this is no longer happening.
