### ISSUE TITLE
Default export asset is created for the first artboard only

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3759]
Artboards added later to a doc do not have the default 1x export assets.

**Comment by iwehrman** [comment]
CC @placegraphichere @mcilroyc

**Comment by iwehrman** [comment]
It seems easy enough to just let all artboards have a default 1x export?

**Comment by mcilroyc** [comment]
I think this already works.  http://cl.ly/0s3z162B0s06

artboards DO have to be non-empty for them to show up in the export modal...

**Comment by ktaki** [comment]
Yes. Verified. Thanks.
