### ISSUE TITLE
Weird hover styling for search input

### ISSUE THREAD

**Issue by iwehrman** [adobe-photoshop/spaces-design#3763]
![img](https://s3.amazonaws.com/f.cl.ly/items/0O0R0X2u3Z0c1x1x0W1l/Screen%20Recording%202016-02-29%20at%2011.08%20AM.gif?v=814ecfe1)

**Comment by mcilroyc** [comment]
Fixed by PR.  still to @iwehrman ?

**Comment by chadrolfs** [comment]
I'll take it

**Comment by chadrolfs** [comment]
verified the fix
