### ISSUE TITLE
Zoom commands don't center/work correctly

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3803]
Fit to Window and Zoom Out zooms out and down to the left

**Comment by chadrolfs** [comment]
This is a mainline issue with new artboards changes
PS-1950

**Comment by ktaki** [comment]
This is a Core issue. Removing Ship Blocker.

**Comment by ktaki** [comment]
This issue has been fixed in core. (PS-1950)
