### ISSUE TITLE
Artboard swapping is broken

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3804]
![ab-swap](https://cloud.githubusercontent.com/assets/8442631/14002170/63eb8898-f107-11e5-8b18-05ad46eda641.gif)

**Comment by chadrolfs** [comment]
![ds-swaptheplank](https://cloud.githubusercontent.com/assets/8442631/14691213/dce29e86-0704-11e6-8e27-9d76bfe9643b.gif)

**Comment by mcilroyc** [comment]
FBNC 2 @chadrolfs

**Comment by chadrolfs** [comment]
This is now on par with 16.1.2.  Thanks @mcilroyc
