### ISSUE TITLE
Text editing commits when the text color is changed

### ISSUE THREAD

**Issue by ktaki** [adobe-photoshop/spaces-design#3807]
Create a text layer. While in the text editing mode, select a part of a string. Open the color picker and change the color.

RESULT: Text editing ends and the entire text color changes

EXPECTED: Text editing continues and the color of the selected text changes

**Comment by mcilroyc** [comment]
@ktaki back to you. see also the note in the PR about opacity

**Comment by ktaki** [comment]
Verified the fix.
