### ISSUE TITLE
Export failing at scales other than 1x

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3821]
create or open doc 
click on (+) in Export panel and set Scale != 1
click the panel export icon and destination, click OK

Result: nothing exported
`Export Failed for asset 0 of layerID 5, documentID 230, with error:  Failed to export components: Error generating component: Cannot read property 'bottom' of undefinedError: Failed to export components: Error generating component: Cannot read property 'bottom' of undefined`

**Comment by chadrolfs** [comment]
![screen shot 2016-04-29 at 8 45 10 am](https://cloud.githubusercontent.com/assets/8442631/14921486/5f5ce5fe-0de7-11e6-8590-939edf5c649b.png)

**Comment by mcilroyc** [comment]
fixed by generator plugin change, present in `generator` jenkins builds as of mac 280
