### ISSUE TITLE
EPV: Adding a 2nd asset to a Library shifts UI up

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3824]
![ds-add-assetuishift](https://cloud.githubusercontent.com/assets/8442631/15087558/bc43ddba-139e-11e6-8ac5-09875467fba3.gif)

**Comment by iwehrman** [comment]
Can you take a look at this, @DivyaPrabhakar?

**Comment by chadrolfs** [comment]
Doesn't have to be an artboard (like gif), can be effects or other assets

**Comment by DivyaPrabhakar** [comment]
Sure, will do.

**Comment by chadrolfs** [comment]
Repro'd on mac. not Win specific.  (tip from Divya: for mac repro, make the app frame smaller, then do repro steps)

**Comment by chadrolfs** [comment]
I was able to repro in 16.1.2, adding EPV to title.  Based on that we may want to defer this.

**Comment by iwehrman** [comment]
FBNC to @chadrolfs.
