### ISSUE TITLE
Rotation icon is in wrong location

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3825]
Wrong:
![wrong](https://cloud.githubusercontent.com/assets/8442631/15156783/817e6090-169d-11e6-873e-71cbb722490e.png)
Correct:
![correct](https://cloud.githubusercontent.com/assets/8442631/15156799/8e8fb5fe-169d-11e6-887f-5a4066398791.png)

**Comment by iwehrman** [comment]
FBNC 2 @chadrolfs.
