### ISSUE TITLE
Libraries panel has bottom border

### ISSUE THREAD

**Issue by chadrolfs** [adobe-photoshop/spaces-design#3826]
![screen shot 2016-05-10 at 11 19 52 am](https://cloud.githubusercontent.com/assets/8442631/15157788/fc467098-16a1-11e6-8a34-2543d27de901.png)

It doesn't in 15.1.2:
![screen shot 2016-05-10 at 11 19 22 am](https://cloud.githubusercontent.com/assets/8442631/15157794/04332fbc-16a2-11e6-993d-03d773c5430e.png)

**Comment by chadrolfs** [comment]
possibly related to #3824

**Comment by iwehrman** [comment]
Terminated with extreme prejudice by @DivyaPrabhakar. Over to @chadrolfs to verify.
